### ISSUE TITLE
White border around image/shiny integration

### ISSUE THREAD

**Issue by ciflikli** [kassambara/ggpubr#10]
Hello, thanks for the great package. I'm trying to use ggpubr inside a Shiny app but so far not able to get rid of the white border surrounding the image to blend in with the rest. Here's a screenshot:

<img width="1153" alt="ggpubr" src="https://user-images.githubusercontent.com/24681395/27788943-690564fc-5fe2-11e7-981c-8bea52579d1f.png">

I have tried adding

    bgcolor("#ecf0f5") +
    theme(legend.background = element_rect("#ecf0f5"),
    panel.background = element_rect("#ecf0f5"),
    plot.background = element_rect("#ecf0f5"),
    plot.margin = unit(x = c(0, 0, 0, 0), units = "mm"))

but still have the faint lines shown in the image. I thought setting the margins to 0 would solve it, but it only got rid of the part in the middle (top of the legend). Any ideas to either get rid of it or changing its color? Cheers.

**Comment by kassambara** [comment]
Hi,

This is not reproducible on my computer, but I would suggest to specify the argument `color`  for  `plot.background` as follow: `plot.background = element_rect(fill = "#ecf0f5", color = "#ecf0f5")`.

Complete code:  

```r
bgcolor("#ecf0f5") +
theme(legend.background = element_rect("#ecf0f5"),
panel.background = element_rect("#ecf0f5"),
plot.background = element_rect(fill = "#ecf0f5", color = "#ecf0f5"),
plot.margin = unit(x = c(0, 0, 0, 0), units = "mm"))
```

Hope it works!  Please let me know...

**Comment by ciflikli** [comment]
Ah, I feel stupid now. That does the trick. Thanks!
