### ISSUE TITLE
Unable to add bars to grouped boxplot

### ISSUE THREAD

**Issue by sbaross** [kassambara/ggpubr#100]
I have created a grouped boxplot using ggpubr and have run t-tests on each group but I am unable to figure out how to add bars as in this image.

![](http://www.sthda.com/english/sthda-upload/figures/ggpubr/010-add-p-values-to-ggplots-pairwise-comparisons-bar-location-1.png)

If I run compare_means I get this table with the required p-values:
```
> compare_means(value~type, data=dataset, group.by="gene")
# A tibble: 3 x 9
  gene  .y.   group1  group2     p p.adj p.format p.signif method  
  <fct> <chr> <chr>   <chr>  <dbl> <dbl> <chr>    <chr>    <chr>   
1 gene1 value control gene   0.962     1 0.96     ns       Wilcoxon
2 gene2 value control gene   0.997     1 1.00     ns       Wilcoxon
3 gene3 value control gene   0.366     1 0.37     ns       Wilcoxon
```

And I have created my boxplot with this code:
`ggboxplot (dataset, x="gene", y="value", color="type") + stat_compare_means(aes(group=type), label="p.signif")`

To generate this plot:
![image](https://user-images.githubusercontent.com/41447413/42960240-2af5b2b6-8b83-11e8-8ac4-0c0df88432d0.png).

However, all the documentation I can find for adding bars uses  a variable containing the values of "group 1" and "group 2" from the tibble.  When I try this I get an error message as below:

```
> mycomparisons <- list(c("control", "gene"))
> ggboxplot (dataset, x="gene", y="value", color="type") + stat_compare_means(comparisons=mycomparisons, aes(group=type), label="p.signif")
Warning message:
Computation failed in `stat_signif()`:
missing value where TRUE/FALSE needed 
```

The same happens with multiple versions I've tried. Any help would be greatly appreciated!

**Comment by kassambara** [comment]
To add bars between two groups, the groups should be present on x-axis, not only in the legends.

For example:

```r
library(ggpubr)
df <- ToothGrowth

ggboxplot(df, x = "supp", y = "len",  color = "supp", ggtheme = theme_bw())+
  facet_wrap(~dose) + 
  stat_compare_means(comparisons = list(c("OJ", "VC")))
```

![grouped-box-plot-with-p-value](https://user-images.githubusercontent.com/3313355/43103556-cdbd74f4-8ece-11e8-96cd-f29952cb7108.png)
