### ISSUE TITLE
Please add Tukey post-hoc test to stat_compare_means()

### ISSUE THREAD

**Issue by BlueCeramicRipples** [kassambara/ggpubr#102]
Hi,

I am using stat_compare_means() to carry out  an anova. I need to also carry out the post-hoc Tukey test and would like to add p value comparisons to the figure, as is possible with the Kruskal-Wallis test. 

So currently Kruskal-Wallis, followed by the post-hoc Dunn test can be implemented as: 

my_comparisons <- list( c("0.5","1"),c("1","2"),c("0.5","2"))
df <- ToothGrowth
ggbarplot(data=df,"dose","len", add = c("mean_se")) +
  stat_compare_means(comparisons = my_comparisons)

I am picturing the code for anova followed by Tukey test looking something like this:

my_comparisons <- list( c("0.5","1"),c("1","2"),c("0.5","2"))
df <- ToothGrowth
ggbarplot(data=df,"dose","len", add = c("mean_se")) +
  stat_compare_means(method="anova", comparisons = my_comparisons)

Best wishes

**Comment by kassambara** [comment]
Hi,

for pairwise-comparison between groups, you need to specify method = "t.test" (Instead of anova)  or method = "wilcox.test"

```r
my_comparisons <- list( c("0.5","1"),c("1","2"),c("0.5","2"))
df <- ToothGrowth
ggbarplot(data=df,"dose","len", add = c("mean_se")) +
    stat_compare_means(method="t.test", comparisons = my_comparisons)
```

**Comment by BlueCeramicRipples** [comment]
Thanks for the help!

**Comment by sakuramaezono** [comment]
Hi. I have the same request. T-test and post-hoc tukey would give out varying results (close but not the same level).

**Comment by kassambara** [comment]
You can try this:

```r

# Data preparation
df <- ToothGrowth
df$dose <- as.factor(df$dose)

# Tukey HSD
library(rstatix)  # https://github.com/kassambara/rstatix
stat.test <- aov(len ~ dose, data = df) %>%
  tukey_hsd()
```

<pre>
# A tibble: 3 x 8
   term group1 group2 comparison estimate  conf.low conf.high   p.adj
  <chr>  <chr>  <chr>      <chr>    <dbl>     <dbl>     <dbl>   <dbl>
1  dose    0.5      1      1-0.5    9.130  5.901805 12.358195 2.0e-08
2  dose    0.5      2      2-0.5   15.495 12.266805 18.723195 1.1e-11
3  dose      1      2        2-1    6.365  3.136805  9.593195 4.2e-05
</pre>


```r
# Visualize
library(ggpubr)
ggboxplot(df, x = "dose", y = "len") +
  stat_pvalue_manual(
    stat.test, label = "p.adj", 
    y.position = c(29, 35, 39)
      )
```

![rplot37](https://user-images.githubusercontent.com/3313355/43925932-0df094ea-9c29-11e8-9cd8-a6aa4eba6b7d.png)

**Comment by sakuramaezono** [comment]
I found a way around it but this is a simpler way to it. Thank you!

**Comment by EmilioEm** [comment]
Thank you kassambara for a nice explanation. I have a similar problem, but with stat_compare_means. How could I include a Tukey test in this function, instead of a t.test, wilcox, kruskal anova?

I tried your code with stat.test. However, I get the following error:
Warning messages:
1: Computation failed in `stat_compare_means()`:
Non-supported method specified. Allowed methods are one of: t.test, t.test, t.test, wilcox.test, wilcox.test, wilcox.test, anova, anova, kruskal.test, kruskal.test

**Comment by kassambara** [comment]
It works on my computer!

**Comment by Cumol** [comment]
Is there a way to do the same thing with the outputs of glht like so:

```
stat.test <- aov(len ~ dose, data = df) %>%
  summary(glht(., linfct=mcp(dose="Dunnett")))
```

**Comment by 18853857973** [comment]
> It works on my computer!

why you don't add mrot test means??? thank you!

**Comment by Rhodnius** [comment]
Hi guys,

Just a silly question, was Dunn's test finally implemented? @BlueCeramicRipples structured an answer, but I guess this way applied only ANOVA.

Any suggestions in this regard?

Best wished and be safe!

**Comment by kassambara** [comment]
Please consider the following blog for adding kruskal-wallis p-value and [Dunn Test pairwise comparisons p-values onto a ggplot](https://www.datanovia.com/en/lessons/kruskal-wallis-test-in-r/)

**Comment by felixradtke** [comment]
As a follow up on the question from @Rhodnius : Which test is performed when doing pairwise comparisons + global p value as stated in your docs?

"p + stat_compare_means(comparisons = my_comparisons)+ # Add pairwise comparisons p-value
  stat_compare_means(label.y = 50)                   # Add global p-value"

My plan is to implement Kruskal-Wallis + Dunn's for a faceted plot, **each facet containing 3 groups**. Is it automatically the case that Dunn's is used for the pairwise comparisons if you chose Kruskal?

**Comment by birdbio2222** [comment]
hi all,

Is there a way to make the significance bar locations automatic? 
When making lots of graphs it can be tedious to go through each variable

**Comment by phancanhtrinh** [comment]
> ```r
> stat.test <- aov(len ~ dose, data = df) %>%
>   tukey_hsd()
> ```

@kassambara Could you please tell me how we could use ANOVA-Post Hoc Test for grouped data?
I want to get something similar to this picture but people always just show t.test.
![image](https://user-images.githubusercontent.com/61386728/226168271-0890deda-07ea-4968-82a9-c985f11c19c7.png)
