### ISSUE TITLE
Fit points to an exponential model

### ISSUE THREAD

**Issue by iferres** [kassambara/ggpubr#103]
Hi, I was wondering if it is possible to fit a log or exponential model curve to a ggscatter plot.
I can do the following:

ggscatter(data, x = x, y = y, color = my_groups) + 
                geom_smooth(method = "lm", formula = y ~ log(x))

...which will add a curve fitted for all the data points. What I want is to plot different curves according to the data$my_groups column.
Is it any way to achieve that more easily in ggpubr?

Thanks!

**Comment by iferres** [comment]
Ok, sorry. I just could. For the record:

ggscatter(data, x = x, y = y, color = my_groups) +
geom_smooth(method = "lm", formula = y ~ log(x), mapping = aes(color = my_groups))

**Comment by kassambara** [comment]
so we can close this issue...

**Comment by fgvieira** [comment]
Following up on this thread, is it possible to show the equation of a fitted log model curve?

I've been trying with `stat_regline_equation` by setting `formula = y ~ log(x)` but it just shows a linear model equation.
