### ISSUE TITLE
Possible to use stat_pvalue_manual() with dodged bar chart?

### ISSUE THREAD

**Issue by emcnerny** [kassambara/ggpubr#104]
Is there any way to define the group names (columns 'group1' and 'group2' in the df) so that the new stat_pvalue_manual function can map the comparisons to specific bars on a dodged bar chart with grouping factors for both x and color?

**Comment by kassambara** [comment]
Please, try this:

```r

library(rstatix)  # https://github.com/kassambara/rstatix
stat.test <- ToothGrowth %>%
  group_by(dose) %>%
  t_test(len ~ supp) %>%
  adjust_pvalue() %>%
  add_significance("p.adj")


library("ggpubr")
ggbarplot(ToothGrowth, x = "dose", y = "len", add = "mean_se",
          color = "supp", palette = "jco", 
          position = position_dodge(0.8)) +
  stat_pvalue_manual(stat.test, x= "dose", y.position = 30, label = "p = {p.adj}")
```

![rplot](https://user-images.githubusercontent.com/3313355/43866199-2e3ff32c-9b65-11e8-80b7-18193d88cc34.png)

**Comment by Adam-JJJJJ** [comment]
> Please, try this:
> 
> ```r
> library(rstatix)  # https://github.com/kassambara/rstatix
> stat.test <- ToothGrowth %>%
>   group_by(dose) %>%
>   t_test(len ~ supp) %>%
>   adjust_pvalue() %>%
>   add_significance("p.adj")
> 
> 
> library("ggpubr")
> ggbarplot(ToothGrowth, x = "dose", y = "len", add = "mean_se",
>           color = "supp", palette = "jco", 
>           position = position_dodge(0.8)) +
>   stat_pvalue_manual(stat.test, x= "dose", y.position = 30, label = "p = {p.adj}")
> ```
> 
> ![rplot](https://user-images.githubusercontent.com/3313355/43866199-2e3ff32c-9b65-11e8-80b7-18193d88cc34.png)

Hi，Doc, thanks your codes. May i ask that if i have three columns, how can i separate the two different t.test result?
![image](https://user-images.githubusercontent.com/45379515/58378633-a383f900-7fc9-11e9-9b82-bde2d3e37cd0.png)
I've tried position=position_dodge(0.9）in stat_pvalue_manual, but it did't seem to work.
Thank for ur time.

**Comment by kassambara** [comment]
fixed now, thanks!

Please install the latest dev version and try the R code below:

```r
df <- ToothGrowth
df$dose <- as.factor(df$dose)
# t - test
library(rstatix)  # https://github.com/kassambara/rstatix
stat.test <- df %>%
  group_by(supp) %>%
  t_test(len ~ dose, ref.group = "0.5") %>%
  adjust_pvalue() %>%
  add_significance("p.adj")
stat.test

# Plot
bp <- ggbarplot(df, x = "supp", y = "len",
                fill = "dose",
                add = "mean_sd", add.params = list(group = "dose"),
                position = position_dodge(0.8)) 
bp
# Add pvalue
bp + stat_pvalue_manual(
  stat.test, x = "supp", y.position = 33,
  ref.group = "0.5", label = "p.adj.signif",
  position = position_dodge(0.8)
)
```

![Rplot01](https://user-images.githubusercontent.com/3313355/58594591-57a5ae00-826e-11e9-8c35-1fe8aa13945c.png)
