### ISSUE TITLE
modify legend text of ggscatter() and label font of stat_cor()

### ISSUE THREAD

**Issue by zhan6073** [kassambara/ggpubr#111]
When I use the following code,
ggscatter(herita, x = 'sigma2', y = 'pre.mean', color = 'Group', add = "reg.line", conf.int = FALSE)+
    stat_cor(aes(color = Group, label = paste(..rr.label.., ..p.label.., sep = "~`,`~"))) +
    scale_color_discrete(name = 'Group',labels = c(expression(italic(h)^2),expression(italic(H)^2)))
I got the plot
![rplot](https://user-images.githubusercontent.com/34253682/45391670-7d5c2b80-b5e9-11e8-97ab-93ed994f72dc.png)
How do I removed the original legend and keep the revised? Also, I want to  revise italic label to 'R2' and 'P'  and modify their font size. I tried code,stat_cor(aes(color = Group,label = paste0(expression(R^2)," = ", ..r.., ", P = ", ..p..)))  and font(), but failed. It seems no parameters for these.

**Comment by xavierjob** [comment]
Did you/anyone figure this out? I have the same issue.

**Comment by zhan6073** [comment]
Use geom_point() instead of ggscatter() to address two legends issue.
For revising the labels, use 
stat_cor(aes(color = Group, label = paste(paste("R^2~`=`~", ..rr..),
                                                         paste("P~`=`~", ..p..),sep = '~`,`~')),
             size = 3, # geom_text size
             show.legend = F # remove 'a' in the legend.key
             )

**Comment by kassambara** [comment]
Fixed now, thanks!

``` r
library(ggpubr)
#> Le chargement a nécessité le package : ggplot2

# Reg line without confidence band
ggscatter(
  iris, x = 'Sepal.Length', y = 'Petal.Length', color = 'Species', 
  add = "reg.line", conf.int = FALSE
  )+
  stat_cor(aes(color = Species, label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), show.legend = FALSE) +
  scale_color_discrete(
    name = 'Species', 
    labels = c(expression(italic(h)^2), expression(italic(H)^2), expression(italic(HH)^2)) 
    ) 
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/Hr8yexF.png)

``` r

# Reg line with confidence band
ggscatter(
  iris, x = 'Sepal.Length', y = 'Petal.Length', color = 'Species', 
  add = "reg.line", conf.int = TRUE
)+
  stat_cor(aes(color = Species, label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), show.legend = FALSE) +
  # setting legend for color (point, line)
  scale_color_discrete(
    name = 'Species', 
    labels = c(expression(italic(h)^2), expression(italic(H)^2), expression(italic(HH)^2)) 
  ) +
  # setting legend for fill (confidence band)
  scale_fill_discrete(
    name = 'Species', 
    labels = c(expression(italic(h)^2), expression(italic(H)^2), expression(italic(HH)^2)) 
  ) 
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/v9q67z4.png)

<sup>Created on 2020-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
