### ISSUE TITLE
color aesthetic not working on some platforms

### ISSUE THREAD

**Issue by YazBraimah** [kassambara/ggpubr#112]
Greetings,

We found this strange behavior with `ggerrorplot` function. In some cases, this works fine (i.e., produces offset colored points)

`data<-ToothGrowth`
`ggerrorplot(data = data,x = "dose",y = "len",color = "supp")`

But in other cases it does not (i.e. fail to apply the "color" aesthetic). Any idea what's going on here? R 3.3.2 works, but >3.3.3 doesn't.

**Comment by AnnaMariaL** [comment]
Doesn't work in R 3.3.1. either. 
Best,

Anna

**Comment by kassambara** [comment]
This is not reproducible in my hand. It works in 3.3.2 and 3.5.0. Make sure you have the latest developmental version of ggpubr.

```r
library(ggpubr)
data<-ToothGrowth
ggerrorplot(data = data,x = "dose",y = "len",color = "supp")
```

![rplot](https://user-images.githubusercontent.com/3313355/47911753-9325f880-de96-11e8-8ce5-a3097884fba5.png)


```r
devtools::session_info()
```

<pre>
Session info ----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2018-11-02                  

Packages --------------------------------------------------------------------------------------------------
 package    * version    date       source                            
 assertthat   0.2.0      2017-04-11 cran (@0.2.0)                     
 backports    1.1.2      2017-12-13 cran (@1.1.2)                     
 base       * 3.5.0      2018-04-24 local                             
 bindr        0.1.1      2018-03-13 cran (@0.1.1)                     
 bindrcpp     0.2.2      2018-03-29 cran (@0.2.2)                     
 colorspace   1.3-2      2016-12-14 cran (@1.3-2)                     
 commonmark   1.6        2018-09-30 CRAN (R 3.5.0)                    
 compiler     3.5.0      2018-04-24 local                             
 cowplot      0.9.3      2018-07-15 cran (@0.9.3)                     
 crayon       1.3.4      2017-09-16 cran (@1.3.4)                     
 datasets   * 3.5.0      2018-04-24 local                             
 desc         1.2.0      2018-05-01 CRAN (R 3.5.0)                    
 devtools   * 1.13.5     2018-02-18 CRAN (R 3.5.0)                    
 digest       0.6.18     2018-10-10 cran (@0.6.18)                    
 dplyr        0.7.7      2018-10-16 cran (@0.7.7)                     
 ggplot2    * 3.1.0.9000 2018-11-02 Github (tidyverse/ggplot2@c268b34)
 ggpubr     * 0.1.8.999  <NA>       local                             
 ggrepel      0.8.0      2018-05-09 cran (@0.8.0)                     
 ggsci        2.9        2018-05-14 cran (@2.9)                       
 ggsignif     0.4.0      2017-08-03 cran (@0.4.0)                     
 glue         1.3.0      2018-07-17 cran (@1.3.0)                     
 graphics   * 3.5.0      2018-04-24 local                             
 grDevices  * 3.5.0      2018-04-24 local                             
 grid         3.5.0      2018-04-24 local                             
 gridExtra    2.3        2017-09-09 cran (@2.3)                       
 gtable       0.2.0      2016-02-26 cran (@0.2.0)                     
 labeling     0.3        2014-08-23 cran (@0.3)                       
 lazyeval     0.2.1      2017-10-29 cran (@0.2.1)                     
 magrittr   * 1.5        2014-11-22 cran (@1.5)                       
 memoise      1.1.0      2017-04-21 CRAN (R 3.5.0)                    
 methods    * 3.5.0      2018-04-24 local                             
 munsell      0.5.0      2018-06-12 cran (@0.5.0)                     
 pillar       1.2.3      2018-05-25 cran (@1.2.3)                     
 pkgconfig    2.0.2      2018-08-16 cran (@2.0.2)                     
 plyr         1.8.4      2016-06-08 cran (@1.8.4)                     
 polynom      1.3-9      2016-12-08 cran (@1.3-9)                     
 purrr        0.2.5      2018-05-29 cran (@0.2.5)                     
 R6           2.3.0      2018-10-04 cran (@2.3.0)                     
 Rcpp         0.12.19    2018-10-01 cran (@0.12.19)                   
 rlang        0.3.0.9000 2018-11-02 Github (tidyverse/rlang@eb17969)  
 roxygen2     6.1.0      2018-07-27 CRAN (R 3.5.0)                    
 rprojroot    1.3-2      2018-01-03 CRAN (R 3.5.0)                    
 rstudioapi   0.7        2017-09-07 CRAN (R 3.5.0)                    
 scales       1.0.0      2018-08-09 cran (@1.0.0)                     
 stats      * 3.5.0      2018-04-24 local                             
 stringi      1.2.4      2018-07-20 cran (@1.2.4)                     
 stringr      1.3.1      2018-05-10 cran (@1.3.1)                     
 tibble       1.4.2      2018-01-22 cran (@1.4.2)                     
 tidyr        0.8.2      2018-10-28 cran (@0.8.2)                     
 tidyselect   0.2.5      2018-10-11 cran (@0.2.5)                     
 tools        3.5.0      2018-04-24 local                             
 utils      * 3.5.0      2018-04-24 local                             
 withr        2.1.2      2018-03-15 CRAN (R 3.5.0)                    
 xml2         1.2.0      2018-01-24 CRAN (R 3.5.0)                    

</pre>
