### ISSUE TITLE
Creating a specific publication table format

### ISSUE THREAD

**Issue by sdhutchins** [kassambara/ggpubr#113]
How would I be able to create a table like the one below which is a more typical publication kind of table?

![image](https://user-images.githubusercontent.com/20976111/45703763-d6244a80-bb3a-11e8-9c32-874b4170b010.png)

I'm looking through the code regarding [ggtexttable](http://www.sthda.com/english/rpkgs/ggpubr/reference/ggtexttable.html) but I don't see (yet) a way to make this happen.

**Comment by kassambara** [comment]
This is now possible, thanks

``` r
suppressPackageStartupMessages(library("ggpubr"))
# Column names border only
ggtexttable(head(iris), rows = NULL, theme = ttheme("blank")) %>%
  tab_add_hline(at.row = 2, row.side = "top", linewidth = 2)
```

![](https://i.imgur.com/GAnGV0v.png)

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
