### ISSUE TITLE
Changing the number of significant digits shown with stat_cor

### ISSUE THREAD

**Issue by raedevan6** [kassambara/ggpubr#114]
Hello, forgive me if this an easy fix. I'm trying to change the number of digits shown on the plot for both R2 and pvals. Below is my code, I would like to only show 3 sig digits.

ggplot(pxsam, aes(x=cbi, y=value, color=phy)) + geom_point() + 
  geom_smooth(method = "lm") + theme_pubr() +
  ggpubr::stat_cor(
    aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~"))) 

![image](https://user-images.githubusercontent.com/10078749/45933415-80401000-bf49-11e8-95d2-a3719979021a.png)

**Comment by icer182** [comment]
Hi @raedevan6. Did you ever get this figured out? I am trying to do the same thing, mostly for the r^2 values though. I've been pouring through ggpubr and ggplot2 blogs but have not found a simple solution yet. Please let me know what was recommended to you.

**Comment by kassambara** [comment]
Related issue: https://github.com/kassambara/ggpubr/issues/186

**Comment by kassambara** [comment]
New arguments `digits` added.  

Applying different digits for each regression line  on the same plot is not supported by `stat_cor`.  

I don't know how to achieve this automatically in ggplot context.  I would suggest the following (manual) solution:

``` r
library(ggpubr)
library(dplyr)

df <- mtcars
paste("italic(R)^2", ..rr.., sep = "~`=`~")
#> Error in paste("italic(R)^2", ..rr.., sep = "~`=`~"): objet '..rr..' introuvable
df$cyl <- as.factor(df$cyl)

# Prepare data for each group
grp1.df <- df %>% filter(cyl == "4")
grp2.df <- df %>% filter(cyl == "6")
grp3.df <- df %>% filter(cyl == "8")

# Plot
ggplot(df, aes(wt, mpg, color = cyl)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor(label.x = 3, label.y = 34, digits = 3, data = grp1.df)+
  stat_cor(label.x = 3, label.y = 32, digits = 2, data = grp2.df) +
  stat_cor(label.x = 3, label.y = 30, digits = 1, data = grp3.df)
```

![](https://i.imgur.com/Pprbg68.png)

<sup>Created on 2020-02-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by icer182** [comment]
Hi @kassambara. Thanks for implementing the digits variable to stat_cor. I was just curious if there was a method to keep trailing 0s? I specified digits = 2, but it deletes my trailing 0. Thank you.

**Comment by kassambara** [comment]
Hi,

for advanced p-value formatting, I would suggest the function `scales::pvalue()` using the option `accuracy`.  Use accuracy = 0.01 to show 2 decimal places of precision.

``` r
library(ggpubr)
#> Le chargement a nécessité le package : ggplot2
# Custom formatting fucntion
format_pval <- function(pval){
  pval <- scales::pvalue(pval, accuracy= 0.001, add_p = TRUE)
  gsub(pattern = "(=|<)", replacement = " \\1 ", x = pval)
}
# Display formatted p-value
ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line") +
  stat_cor(
    aes(label = paste(..rr.label.., format_pval(..p..), sep = "*`,`~")),
    label.x = 3
  )
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/HuVzymR.png)

<sup>Created on 2020-05-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by icer182** [comment]
Hi @kassambara. Thanks for the explanation. However, I am looking to keep a trailing 0 in the R^2 value. Is there a current method of doing this? Sorry for the confusion.

**Comment by kassambara** [comment]
With the latest dev version, you can now specify the argument `p.accuracy` and `r.accuracy`:

``` r
suppressPackageStartupMessages(library(ggpubr))
# Default plot
sp <- ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line")
sp + stat_cor(label.x = 3)
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/5hSqJm5.png)

``` r
# Specify the number of decimal places of precision for 
# the p-value and the correlation coefficient r
sp + stat_cor(label.x = 3, p.accuracy = 0.001, r.accuracy = 0.01)
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/VjDvFyW.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by lauralogozzo** [comment]
Hi @kassambara -- thanks for your earlier responses. I know this is an old thread, but I was wondering if this issue has been resolved. I am still unable to keep the trailing 0s on displayed R2 values. For example, if I use r.accuracy = 0.01 on an R2 value of 0.901, it only displays 0.9 when I need it to display 0.90. All of my attempts to manually format it do not work as I am using facet_wrap and there are multiple R2 values being input. Thank you!

**Comment by Stiltstiltstilts** [comment]
Hi @kassambara. The above suggestion to including trailing zeros for the correlation coefficient by setting r.accuracy isn't working for me. I have tried both the current CRAN version of ggpubr and the dev version. 

```
... +
stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
           label.x = .5, label.y = .05, geom = "label",
           label.padding = unit(0.1, "lines"), r.accuracy = 0.01) +
...
```

The R2 always shows as 0.6 in the plot rather than 0.60. From what I can gather, ..rr.label.. is correctly as "0.60" but when it gets passed into the R expression format, that removes the trailing zero. Do you see any way around that?

Thanks
