### ISSUE TITLE
Adjusted p-value for multiple testing - stat_compare_means()

### ISSUE THREAD

**Issue by jglopes** [kassambara/ggpubr#119]
Hello,

When performing pairwise comparisons using stat_compare_means(), how can I guarantee that the argument  (label="p.signif") adds the symbols of statistical significance corresponding to those of the adjusted p-value, which is corrected for multiple testing?
It seems that when using the label argument, stat_compare_means () is only able to "capture" the normal p-values. 

Thank you.

**Comment by kassambara** [comment]
Using the rstatix and ggpubr packages should fix this issue.  Many examples are provided in the following blog posts:

- [How to Add P-Values onto Basic GGPLOTS](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-basic-ggplots/)
- [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/)
- [How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)
