### ISSUE TITLE
Specifying 'fill' argument other than 'x' variable leads to stat computation failure

### ISSUE THREAD

**Issue by lorenzofanchi** [kassambara/ggpubr#121]
Any ideas why the following code fails?

Example:

    library(data.table)
    library(ggpubr)
    
    dt = data.table(timepoint = c('pre', 'post') %>% sapply(rep, 100) %>% c,
                    subtype = c('A', 'B') %>% sapply(rep, 50) %>% c(. ,.),
                    score = c(runif(100, 0, 1), runif(50, 10, 20), runif(50, 0, 1)))

Now the following plot code works as expected (note: fill commented out):

    ggplot(data = dt,
       mapping = aes(x = factor(timepoint, levels = c('pre', 'post')),
                     y = score
                     # fill = factor(subtype)
                     )) +
      geom_boxplot() +
      scale_fill_manual(values = c('red', 'blue')) +
      stat_compare_means(label.y = 25) +
      stat_compare_means(comparisons = list(c('pre', 'post')),
                         label = 'p.signif',
                         label.x = 1.25,
                         label.y = 22) +
      facet_wrap(~subtype)

![plot_zoom_png 3](https://user-images.githubusercontent.com/770285/47218104-fb5edf80-d3aa-11e8-94ee-a68d0221d598.png)

Adding a fill to the boxplot, results in the following:

    ggplot(data = dt,
       mapping = aes(x = factor(timepoint, levels = c('pre', 'post')),
                     y = score,
                     fill = factor(subtype)
                     )) +
      geom_boxplot() +
      scale_fill_manual(values = c('red', 'blue')) +
      stat_compare_means(label.y = 25) +
      stat_compare_means(comparisons = list(c('pre', 'post')),
                         label = 'p.signif',
                         label.x = 1.25,
                         label.y = 22) +
      facet_wrap(~subtype)`

> Warning messages:
1: Unknown or uninitialised column: 'p'. 
2: Computation failed in `stat_compare_means()`:
argument "x" is missing, with no default 
3: Unknown or uninitialised column: 'p'. 
4: Computation failed in `stat_compare_means()`:
argument "x" is missing, with no default 

![plot_zoom_png 2](https://user-images.githubusercontent.com/770285/47218110-00bc2a00-d3ab-11e8-863a-ff230c0a2025.png)

As can be seen from the last plot, the text labels are not plotted anymore in both cases and the bracket is only plotted on the left facet..

I know the fills don't add any info this way. Let's just say I'm making these plots "for a friend".... ;)

**Comment by lorenzofanchi** [comment]
By specifying:

   aes(x = factor(timepoint, levels = c('pre', 'post')),
                            y = score),
                        inherit.aes = F

in the stat_compare_means(), I can get both text labels to plot, but the bracket and 'ns' are still missing in the right facet...

![plot_zoom_png 4](https://user-images.githubusercontent.com/770285/47218415-f8b0ba00-d3ab-11e8-9609-6a1061cf427a.png)

**Comment by kassambara** [comment]
Hi,

Please specify the fill aesthetic in the geom_boxplot() function instead of the global ggplot():


```r

# Load required packages
library(data.table)
library(ggpubr)
# Prepare some data
dt = data.table(timepoint = c('pre', 'post') %>% sapply(rep, 100) %>% c,
                subtype = c('A', 'B') %>% sapply(rep, 50) %>% c(. ,.),
                score = c(runif(100, 0, 1), runif(50, 10, 20), runif(50, 0, 1)))

# Box plot with p-value: fill specified in geom_boxplot()
ggplot(data = dt,
   mapping = aes(x = factor(timepoint, levels = c('pre', 'post')),
                 y = score)) +
  geom_boxplot(aes(fill = factor(subtype))) +
  scale_fill_manual(values = c('red', 'blue')) +
  stat_compare_means(label.y = 25) +
  stat_compare_means(comparisons = list(c('pre', 'post')),
                     label = 'p.signif',
                     label.x = 1.25,
                     label.y = 22) +
  facet_wrap(~subtype)
```

![rplot](https://user-images.githubusercontent.com/3313355/47408859-38d3bc00-d761-11e8-8c73-40508856ca16.png)

**Comment by BenAbabaei** [comment]
You code only works when 'facets' are defined. This does not work:

```
library(data.table)
library(ggpubr)
# Prepare some data
dt = data.table(timepoint = c('pre', 'post') %>% sapply(rep, 100) %>% c,
                subtype = c('A', 'B') %>% sapply(rep, 50) %>% c(. ,.),
                score = c(runif(100, 0, 1), runif(50, 10, 20), runif(50, 0, 1)))

# Box plot with p-value: fill specified in geom_boxplot()
ggplot(data = dt,
       mapping = aes(x = factor(timepoint, levels = c('pre', 'post')),
                     y = score)) +
    geom_boxplot(aes(fill = factor(subtype))) +
    scale_fill_manual(values = c('red', 'blue')) +
    stat_compare_means(label.y = 25) +
    stat_compare_means(comparisons = list(c('A', 'B')),
                       label = 'p.signif',
                       label.x = 1.25,
                       label.y = 22)
```
