### ISSUE TITLE
ggqqplot confidence interval

### ISSUE THREAD

**Issue by vsluydts** [kassambara/ggpubr#123]
Dear Kassambara, 

It seems there is a little bug in specifying the CI in the qqplot function.
It seems the .95 is dragged along the ggqqplot_core function as well?

best regards,
Vincent

library(ggpubr)
p1<-ggqqplot(res, conf.int.level = 0.75)
p2<-ggqqplot(res,conf.int.level = 0.99)
multiplot(p1,p2)

![afbeelding](https://user-images.githubusercontent.com/11047465/47292483-673d8400-d607-11e8-82ad-12299c32fd0a.png)

**Comment by kassambara** [comment]
fixed now thanks
