### ISSUE TITLE
ggarrange 

### ISSUE THREAD

**Issue by Gian77** [kassambara/ggpubr#124]
Hello,

is there a way to prevent a legend to be displayed in only one of the plots in a ggarrange() code?

For example:

`library("ggpubr")`
`ggarrange(p1, p2,`
 `         labels = c("A", "B"),`
  `        widths = c(1, 1),`
   `       align = "none", `
`          ncol = 2, nrow = 1)`

And I want to display just the legend of p1.

Thank you!

G.

**Comment by kassambara** [comment]
Please try the option `common.legend = TRUE` in ggarrange().

**Comment by Gian77** [comment]
Maybe I wasn't clear enough, if I have two plots with different legends and I want to display only one legend. Is there a way to do it in ggarrange() ?
Thanks,

Gian
