### ISSUE TITLE
compare_means with option "comparisons"

### ISSUE THREAD

**Issue by adomingues** [kassambara/ggpubr#126]
I wonder if there is an alternative or similar option in `compare_means` similar to that of `stat_compare_means(comparisons = my_comparisons)`. This would add some flexibility to the calculation of p-values before replacing manually in the plot. 

---

The problem I am trying to solve: programatically add `p-values` __and__ number of observations to the x-axis of a plot. The first part is easy thanks to `ggpubr`:

```R
library("data.table")
library("ggpubr")

a = rnorm(mean=1, 10)
b = rnorm(mean=1.5, 7)
c = rnorm(mean=1.25, 15)

data = rbindlist(list(
  data.frame(facet=1, group="A", value=a),
  data.frame(facet=2, group="A", value=a),
  data.frame(facet=1, group="B", value=b),
  data.frame(facet=2, group="B", value=b),
  data.frame(facet=1, group="C", value=c),
  data.frame(facet=2, group="C", value=c)
))

my_comparisons <- list(c("A", "B"), c("B", "C"))
ggplot(data, aes(x = group, y = value, color = group)) +
	geom_point() +
	facet_wrap(~facet) +
	stat_compare_means(comparisons = my_comparisons, method = "t.test") 
```

![gihub_question plot1](https://user-images.githubusercontent.com/2607577/47712786-f286cd00-dc38-11e8-97e0-12b4bc51a1bf.png)

But then once the N is calculated the comparisons in "my_comparisons" are no longer valid because the factors are different (which makes total sense):

```R
data[ , N := .N , by = c("group", "facet")]
data[, label := factor(paste0(group, "\n(n=", N, ")")), ]

ggplot(data, aes(x = label, y = value, color = label)) +
	geom_point() +
	facet_wrap(~facet) +
	stat_compare_means(comparisons = my_comparisons, method = "t.test") 
```

![gihub_question plot2](https://user-images.githubusercontent.com/2607577/47712872-2c57d380-dc39-11e8-9ad7-11a2b8ee7e50.png)

If the comparisons would be only against a control groups, this could be solved with some grep magig to look it up in the new labels. However, my comparisons are more elaborate. 
 
Ideally I would calculate manually with `compare_means`, or extract the p-values from the first plot, and add it to second which has the right labels but not p-values. Is there a solution for this? 

Cheers.

**Comment by kassambara** [comment]
Hi,

I would suggest to use the function `scale_x_discrete()` [in ggplot2] to customize axis tick labels.

The code looks like this:

```r
library(ggplot2)
library(ggpubr)

data <- ToothGrowth
data$dose <- as.factor(data$dose)
my_comparisons <- list(c("0.5", "1"), c("1", "2"))

ggplot(data, aes(x = dose, y = len, color = dose)) +
  geom_point() +
  facet_wrap(~supp) +
  stat_compare_means(comparisons = my_comparisons, method = "t.test") +
  scale_x_discrete(
    breaks=c("0.5","1","2"),
    labels=c("D0.5\n(n=10)", "D1\n(n=10)", "D2\n(n=10)")
  )
```
![rplot50](https://user-images.githubusercontent.com/3313355/47898344-c310d400-de75-11e8-8cd7-c29c956489a6.png)
