### ISSUE TITLE
How to change the font (ex. italics) for an entire specific column (Just rows not header) in ggtexttable

### ISSUE THREAD

**Issue by ricschwarz** [kassambara/ggpubr#129]
Hi I am learning how to include tables in figures using ggtexttable.
How can I change the font (ex. italics) for an entire specific column (Just rows not header).
I tried inside theme() but I can't specify all rows from a single column. Using tbody.style I can change the entire column but not specific rows or columns. Using table_cell_font(...) it is possible but just one cell at time, not handy when you have many columns or lines. Is there a way to do this? thanks for the support. Cheers Rick

**Comment by kassambara** [comment]
This feature is now possible.

``` r
# Table cells background and font for column 3, 
# Spaning from row 2 to the last row in the data
suppressPackageStartupMessages(library("ggpubr"))
df <- head(iris)
ggtexttable(df, rows = NULL, theme = ttheme("classic")) %>%
  table_cell_bg(row = 2:(nrow(df)+1), column = 3, fill = "darkblue") %>%
  table_cell_font(row = 2:(nrow(df) +1), column = 3, face = "italic", color = "white")
```

![](https://i.imgur.com/B6zglhH.png)

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by ricschwarz** [comment]
Thank you!!!

Em seg., 8 de jun. de 2020 às 21:10, Alboukadel KASSAMBARA <
notifications@github.com> escreveu:
