### ISSUE TITLE
can background_image() be used to fill patterns in bars?

### ISSUE THREAD

**Issue by ginolhac** [kassambara/ggpubr#13]
Hi,

thanks for a nice package!

I posted this a long time ago on [stackoverflow](https://stackoverflow.com/questions/31342379/geom-bar-color-gradient-and-cross-hatches-using-gridsvg-transparency-issue). Looking at the `background_image()` function, I was wondering is this could be used for mapping bar sections instead of the plot background.

**Comment by kassambara** [comment]
Hi, `background_image()` doesn't support a such functionality.  

If you want to contribute to ggpubr with this option, you're very welcome, because I do not have programming window to do it. Otherwise, we can close the issue.

**Comment by ginolhac** [comment]
Ok no worries
