### ISSUE TITLE
add.params change the size of point and bars simultaneously

### ISSUE THREAD

**Issue by Pang-Junling** [kassambara/ggpubr#130]
Hi， when I use ggbarplot and add points and errorbars, using this parameters: add=c("point","mean_se"),add.params=list(size=4), the size of the dots and the bars change simultaneously. What should I do if I only want to change the size of the dots?

**Comment by kassambara** [comment]
I would suggest this:

```r
library(ggpubr)
ggbarplot(ToothGrowth, x = "dose", y = "len", 
          add = "mean_se", add.params = list(size = 3))+
  geom_point(size = 1)
```

![rplot51](https://user-images.githubusercontent.com/3313355/47912339-91f5cb00-de98-11e8-96a0-3317ba99f0a3.png)

**Comment by Pang-Junling** [comment]
It works! Thank you for your suggestion.
