### ISSUE TITLE
Looping within ggboxplot

### ISSUE THREAD

**Issue by skoturan** [kassambara/ggpubr#132]
Hi,
I am using **ggpubr** (thank you for this amazing package- it's really useful for my work) to do some boxplots for genes expressed in two groups. My dataframe looks like this:
Pat_ID  Group  Gene 1   Gene2 ...... etc.
P13       NST     9.001     6.455
p14       NST     9.060     6.730
p13       TCR     10.137    6.416
p14       TCR     9.519      5.671

I can plot individual genes or a group of them by name:
```
# AAMP
ggboxplot(cd8_v1, x = "Group", y = "AAMP",
          title = "AAMP", ylab = "Log2 counts",
          color = "Dataset", palette = "jco")
```

OR
```
`ggboxplot(cd8_v1, x = "Group",
          y = c("IL2", "CTSW", "FADS2", "B2M", "IL17A", "TNF"),
          combine = TRUE,
          color = "Dataset", palette = "jco",
          ylab = "Log2 counts", 
          add = "jitter",                         
          add.params = list(size = 0.1, jitter = 0.2),  
          label = "Patient.ID",               
          label.select = list(top.up = 2, top.down = 2),
          font.label = list(size = 9, face = "italic"), 
          repel = TRUE  
)`
```

I have 755 genes like this- I would like to generate boxplots comparing the two groups per gene into a PDF file- I tried to add a loop, but it didn't work- PDF doesn't open, I also don't see any plots being generated on the R plot window. 

```
`Genelist=colnames(cd8_v1[,-(1:2)])   #to exclude the first two columns

pdf(file = "Test.pdf",width = 10,height = 10)
par(mfrow(3,2))
for (g in Genelist) {
  print(g)
  ggboxplot(cd8_v1, x = "Group",
            y=g,
            color = "Group", palette = "npg",
            ylab = "Log2 counts", 
            add = "jitter",                              # Add jittered points
            add.params = list(size = 0.1, jitter = 0.2)  # Point size and the amount of jittering
  )
}
dev.off()`
```

I've been hunting for a solution on the internet- I would really appreciate it if you could take a look at it! 
Any suggestions on how to get this working?
Thank you very much!

**Comment by skoturan** [comment]
Hi, thank you for getting back to me- I tried it with concatenating all the gene names- and it seems to run the loop without any issues! 

I tried this as you suggested:

```
my_data <- iris
my_gene_list <- c("Sepal.Length", "Petal.Width")    **_#here I have around 700 genes, so i copied it from a txt file- it works, but i have to see if there is a more efficient way..._**

# Create a list of ggplot
my_plot_list = list()
for(i in 1:length(my_gene_list)){
  p <- ggboxplot(my_data, x = "Species", y = my_gene_list[i])
  my_plot_list[[i]] <- p
}

# Export into pdf: display multiple plots on the same page
ggexport(
  plotlist = my_plot_list, filename = "plot.pdf", 
  ncol = 2, nrow = 3
)

```
I have to figure out an easier way to concatenate the gene names without having to list every name by copy/paste. I will play around with it a bit- for now it works!

Thank you so much! 👍

**Comment by kassambara** [comment]
Your gene list can be obtained as you did before: `Genelist=colnames(cd8_v1[,-(1:2)])`; so you don't need to do copy/paste for concatenating gene names.
