### ISSUE TITLE
compute p-value by gene (t-test) on qPCR data

### ISSUE THREAD

**Issue by lmanchon** [kassambara/ggpubr#134]
--Hi,

i work on table shaped as follow:
            group  gene normalized  calibrated relative_expression      error        lower        upper   color
1   H9_NT_LSB_D16 ASCL1  10.997000  3.55566692         -3.55566692 0.20989458  0.073528048 9.836083e-02 #42c7ce
2   H9_NT_LSB_D20 ASCL1  10.041000  2.59966692         -2.59966692 0.14456394  0.149246514 1.823645e-01 #42c7ce
3   H9_NT_LSB_D27 ASCL1   7.441333  0.00000000          0.00000000 0.06947961  0.952981682 1.049338e+00 #42c7ce
4  H9_Ri1_LSB_D16 ASCL1  14.511000  7.06966718         -7.06966718 0.21513200  0.006412936 8.641304e-03 #42c7ce
5  H9_Ri1_LSB_D20 ASCL1  13.145333  5.70400048         -5.70400048 0.10920400  0.017784886 2.069181e-02 #42c7ce
6  H9_Ri1_LSB_D27 ASCL1   3.259334 -4.18199920          4.18199920 9.34894129  0.027835270 1.183638e+04 #f67468
7  H9_Ri3_LSB_D16 ASCL1  14.167666  6.72633330         -6.72633330 0.34238223  0.007449114 1.197400e-02 #42c7ce
8  H9_Ri3_LSB_D20 ASCL1  12.073000  4.63166714         -4.63166714 0.03499479  0.039372662 4.132984e-02 #42c7ce
9  H9_Ri3_LSB_D27 ASCL1   8.715000  1.27366702         -1.27366702 0.10553967  0.384430129 4.449986e-01 #42c7ce
10  H9_NT_LSB_D16 FOXG1  15.478000  3.38800017         -3.38800017 0.21835466  0.082106780 1.111326e-01 #42c7ce
11  H9_NT_LSB_D20 FOXG1  11.442667 -0.64733282          0.64733282 0.13629949  1.425070539 1.721460e+00 #f67468
12  H9_NT_LSB_D27 FOXG1  12.090000  0.00000000          0.00000000 0.12898911  0.914471990 1.093527e+00 #42c7ce
13 H9_Ri1_LSB_D16 FOXG1  14.312666  2.22266643         -2.22266643 0.31353510  0.172396032 2.662528e-01 #42c7ce
14 H9_Ri1_LSB_D20 FOXG1  12.441000  0.35100047         -0.35100047 0.11337113  0.724786708 8.481378e-01 #42c7ce
15 H9_Ri1_LSB_D27 FOXG1   9.196000 -2.89399973          2.89399973 9.35114100  0.011381691 4.854614e+03 #f67468
16 H9_Ri3_LSB_D16 FOXG1  16.024333  3.93433349         -3.93433349 0.56043311  0.044354780 9.646167e-02 #42c7ce
17 H9_Ri3_LSB_D20 FOXG1  12.318333  0.22833284         -0.22833284 0.23950700  0.723046414 1.007775e+00 #42c7ce
18 H9_Ri3_LSB_D27 FOXG1  11.347667 -0.74233309          0.74233309 0.04958543  1.616358996 1.731375e+00 #f67468
19  H9_NT_LSB_D16 HOXB4  16.134666  1.04566605         -1.04566605 0.30914201  0.390986834 6.001837e-01 #42c7ce
20  H9_NT_LSB_D20 HOXB4  15.334667  0.24566618         -0.24566618 0.21284675  0.727735991 9.775081e-01 #42c7ce
21  H9_NT_LSB_D27 HOXB4  15.089000  0.00000000          0.00000000 0.07253994  0.950962304 1.051566e+00 #42c7ce
22 H9_Ri1_LSB_D16 HOXB4  15.789667  0.70066643         -0.70066643 0.23817304  0.521652340 7.257309e-01 #42c7ce
23 H9_Ri1_LSB_D20 HOXB4  15.530667  0.44166628         -0.44166628 0.12390913  0.675685870 8.023162e-01 #42c7ce
24 H9_Ri1_LSB_D27 HOXB4  10.275333 -4.81366730          4.81366730 9.34877326  0.043131749 1.833663e+04 #f67468
25 H9_Ri3_LSB_D16 HOXB4  16.060333  0.97133223         -0.97133223 0.41698356  0.382010503 6.809644e-01 #42c7ce
26 H9_Ri3_LSB_D20 HOXB4  15.033000 -0.05600008          0.05600008 0.13453065  0.947021725 1.141183e+00 #f67468
27 H9_Ri3_LSB_D27 HOXB4  15.536000  0.44699923         -0.44699923 0.30776057  0.592645051 9.079982e-01 #42c7ce
28  H9_NT_LSB_D16  PAX6   5.184999 -0.45766671          0.45766671 0.19210101  1.202107324 1.568916e+00 #f67468
29  H9_NT_LSB_D20  PAX6   4.704000 -0.93866634          0.93866634 0.09125535  1.799269121 2.041913e+00 #f67468
30  H9_NT_LSB_D27  PAX6   5.642666  0.00000000          0.00000000 0.07359626  0.950266280 1.052337e+00 #42c7ce
31 H9_Ri1_LSB_D16  PAX6   2.239000 -3.40366618          3.40366618 0.24029512  8.959207100 1.250091e+01 #f67468
32 H9_Ri1_LSB_D20  PAX6   3.418000 -2.22466659          2.22466659 0.03218695  4.570904404 4.779480e+00 #f67468
33 H9_Ri1_LSB_D27  PAX6  -2.332000 -7.97466659          7.97466659 9.34875971  0.385795143 1.640102e+05 #f67468
34 H9_Ri3_LSB_D16  PAX6   2.638333 -3.00433318          3.00433318 0.28261153  6.596595505 9.760430e+00 #f67468
35 H9_Ri3_LSB_D20  PAX6   4.272999 -1.36966674          1.36966674 0.05022576  2.495693865 2.675656e+00 #f67468
36 H9_Ri3_LSB_D27  PAX6   2.903334 -2.73933220          2.73933220 0.03814863  6.503352260 6.856540e+00 #f67468
37  H9_NT_LSB_D16   RFX  14.000000  3.42900054         -3.42900054 0.45305080  0.067824422 1.271013e-01 #42c7ce
38  H9_NT_LSB_D20   RFX   9.471334 -1.09966564          1.09966564 0.08118040  2.025790859 2.267097e+00 #f67468
39  H9_NT_LSB_D27   RFX  10.570999  0.00000000          0.00000000 0.07146385  0.951671882 1.050782e+00 #42c7ce
40 H9_Ri1_LSB_D16   RFX  12.638333  2.06733386         -2.06733386 0.44233702  0.175595664 3.242106e-01 #42c7ce
41 H9_Ri1_LSB_D20   RFX  12.339667  1.76866722         -1.76866722 0.22879153  0.250440752 3.439151e-01 #42c7ce
42 H9_Ri1_LSB_D27   RFX   5.362333 -5.20866648          5.20866648 9.34876427  0.056716103 2.411145e+04 #f67468
43 H9_Ri3_LSB_D16   RFX  11.253333  0.68233331         -0.68233331 0.27621934  0.514572888 7.546534e-01 #42c7ce
44 H9_Ri3_LSB_D20   RFX  11.055000  0.48400084         -0.48400084 0.20540179  0.620110561 8.243912e-01 #42c7ce
45 H9_Ri3_LSB_D27   RFX   8.489000 -2.08199946          2.08199946 0.03430261  4.134454085 4.335812e+00 #f67468

i want to compute p-value on each gene based on his qPCR relative-expression, i don't know how to order my data to run compare_means.

When i run this command:
 compare_means(gene ~ relative_expression, data = result, ref.group = "0", method = "t.test")
it returns this error:
Error in t.test.default(xi, xj, paired = paired, alternative = alternative,  : 
  not enough 'x' observations

thank you for your help.
L.M.

**Comment by kassambara** [comment]
Hi,

Your data is not readable.  kindly upload a file containing your data.

**Comment by lmanchon** [comment]
--Sorry,
i upload my file here:
[results.txt](https://github.com/kassambara/ggpubr/files/2579756/results.txt)
thank you--

**Comment by kassambara** [comment]
Do you want to do pairwise comparisons between genes?

**Comment by lmanchon** [comment]
yes pairwise comparison

**Comment by kassambara** [comment]
You can do something like this:

``` r
# Data
library(tibble)
qpcr_data <- tibble::tribble(
            ~group,   ~gene, ~relative_expression,
   "H9_NT_LSB_D16", "ASCL1",   0.0850428099406276,
   "H9_NT_LSB_D20", "ASCL1",    0.164976573544034,
   "H9_NT_LSB_D27", "ASCL1",                    1,
  "H9_Ri1_LSB_D16", "ASCL1",  0.00744420148864075,
  "H9_Ri1_LSB_D20", "ASCL1",   0.0191833637229854,
  "H9_Ri1_LSB_D27", "ASCL1",     18.1512777357052,
  "H9_Ri3_LSB_D16", "ASCL1",  0.00944434657620244,
  "H9_Ri3_LSB_D20", "ASCL1",   0.0403393839880304,
  "H9_Ri3_LSB_D27", "ASCL1",    0.413607135448519,
   "H9_NT_LSB_D16", "FOXG1",    0.095523521291806,
   "H9_NT_LSB_D20", "FOXG1",     1.56626988233749,
   "H9_NT_LSB_D27", "FOXG1",                    1,
  "H9_Ri1_LSB_D16", "FOXG1",    0.214245019717008,
  "H9_Ri1_LSB_D20", "FOXG1",    0.784040198651729,
  "H9_Ri1_LSB_D27", "FOXG1",     7.43328400287002,
  "H9_Ri3_LSB_D16", "FOXG1",   0.0654105208843682,
  "H9_Ri3_LSB_D20", "FOXG1",    0.853620757269047,
  "H9_Ri3_LSB_D27", "FOXG1",     1.67287899407069,
   "H9_NT_LSB_D16", "HOXB4",    0.484421212644635,
   "H9_NT_LSB_D20", "HOXB4",    0.843426243080346,
   "H9_NT_LSB_D27", "HOXB4",                    1,
  "H9_Ri1_LSB_D16", "HOXB4",    0.615287919982095,
  "H9_Ri1_LSB_D20", "HOXB4",    0.736283726386726,
  "H9_Ri1_LSB_D27", "HOXB4",     28.1227797402091,
  "H9_Ri3_LSB_D16", "HOXB4",    0.510034863084201,
  "H9_Ri3_LSB_D20", "HOXB4",     1.03957949041986,
  "H9_Ri3_LSB_D27", "HOXB4",    0.733567065300311,
   "H9_NT_LSB_D16",  "PAX6",     1.37331893715346,
   "H9_NT_LSB_D20",  "PAX6",     1.91675552714952,
   "H9_NT_LSB_D27",  "PAX6",                    1,
  "H9_Ri1_LSB_D16",  "PAX6",     10.5829224916898,
  "H9_Ri1_LSB_D20",  "PAX6",     4.67402870189862,
  "H9_Ri1_LSB_D27",  "PAX6",     251.543934734049,
  "H9_Ri3_LSB_D16",  "PAX6",     8.02406435441965,
  "H9_Ri3_LSB_D20",  "PAX6",     2.58410866182804,
  "H9_Ri3_LSB_D27",  "PAX6",     6.67761168242255,
   "H9_NT_LSB_D16",   "RFX",   0.0928470230032253,
   "H9_NT_LSB_D20",   "RFX",     2.14305018776766,
   "H9_NT_LSB_D27",   "RFX",                    1,
  "H9_Ri1_LSB_D16",   "RFX",     0.23860003228108,
  "H9_Ri1_LSB_D20",   "RFX",    0.293479731740049,
  "H9_Ri1_LSB_D27",   "RFX",     36.9798246830472,
  "H9_Ri3_LSB_D16",   "RFX",    0.623156609394906,
  "H9_Ri3_LSB_D20",   "RFX",    0.714992075229158,
  "H9_Ri3_LSB_D27",   "RFX",      4.2339359947402,
   "H9_NT_LSB_D16",  "SOX1",     1.00509609440131,
   "H9_NT_LSB_D20",  "SOX1",     5.46542224783275,
   "H9_NT_LSB_D27",  "SOX1",                    1,
  "H9_Ri1_LSB_D16",  "SOX1",     1.27691830185423,
  "H9_Ri1_LSB_D20",  "SOX1",     1.19305898623718,
  "H9_Ri1_LSB_D27",  "SOX1",     210.012673254757,
  "H9_Ri3_LSB_D16",  "SOX1",     6.56289749490824,
  "H9_Ri3_LSB_D20",  "SOX1",     1.83231279801729,
  "H9_Ri3_LSB_D27",  "SOX1",     60.5196822026087,
   "H9_NT_LSB_D16",  "SOX2",    0.782412249945215,
   "H9_NT_LSB_D20",  "SOX2",     0.93670499922313,
   "H9_NT_LSB_D27",  "SOX2",                    1,
  "H9_Ri1_LSB_D16",  "SOX2",     1.43993166119035,
  "H9_Ri1_LSB_D20",  "SOX2",    0.829511177620706,
  "H9_Ri1_LSB_D27",  "SOX2",     107.958487525821,
  "H9_Ri3_LSB_D16",  "SOX2",     1.01865601942724,
  "H9_Ri3_LSB_D20",  "SOX2",     0.79959065341965,
  "H9_Ri3_LSB_D27",  "SOX2",     3.41448077278548,
   "H9_NT_LSB_D16", "TUBB3",     1.13314601288608,
   "H9_NT_LSB_D20", "TUBB3",    0.152512599374295,
   "H9_NT_LSB_D27", "TUBB3",                    1,
  "H9_Ri1_LSB_D16", "TUBB3",    0.721464326761447,
  "H9_Ri1_LSB_D20", "TUBB3",    0.146739865870025,
  "H9_Ri1_LSB_D27", "TUBB3",     27.8447403261715,
  "H9_Ri3_LSB_D16", "TUBB3",    0.396026083803494,
  "H9_Ri3_LSB_D20", "TUBB3",   0.0943391766530857,
  "H9_Ri3_LSB_D27", "TUBB3",    0.461797854867308,
   "H9_NT_LSB_D16",  "ZIC1",     1.31798463356003,
   "H9_NT_LSB_D20",  "ZIC1",    0.802922562778366,
   "H9_NT_LSB_D27",  "ZIC1",                    1,
  "H9_Ri1_LSB_D16",  "ZIC1",    0.041829552574958,
  "H9_Ri1_LSB_D20",  "ZIC1",    0.102592666730595,
  "H9_Ri1_LSB_D27",  "ZIC1",     1.24343715761413,
  "H9_Ri3_LSB_D16",  "ZIC1",    0.140275328519986,
  "H9_Ri3_LSB_D20",  "ZIC1",    0.353145176558724,
  "H9_Ri3_LSB_D27",  "ZIC1",    0.147079307084289
  )

# Statistical test
library(rstatix)

stat.test <- qpcr_data %>%
  t_test(relative_expression ~ gene)
stat.test
#> # A tibble: 36 x 10
#>    .y.        group1 group2    n1    n2 statistic    df     p p.adj p.adj.signif
#>  * <chr>      <chr>  <chr>  <int> <int>     <dbl> <dbl> <dbl> <dbl> <chr>       
#>  1 relative_… ASCL1  FOXG1      9     9     0.323 10.3  0.753     1 ns          
#>  2 relative_… ASCL1  HOXB4      9     9    -0.433 13.8  0.671     1 ns          
#>  3 relative_… ASCL1  PAX6       9     9    -1.08   8.08 0.31      1 ns          
#>  4 relative_… ASCL1  RFX        9     9    -0.657 11.7  0.524     1 ns          
#>  5 relative_… ASCL1  SOX1       9     9    -1.29   8.12 0.234     1 ns          
#>  6 relative_… ASCL1  SOX2       9     9    -0.908  8.45 0.389     1 ns          
#>  7 relative_… ASCL1  TUBB3      9     9    -0.369 13.8  0.718     1 ns          
#>  8 relative_… ASCL1  ZIC1       9     9     0.818  8.12 0.437     1 ns          
#>  9 relative_… FOXG1  HOXB4      9     9    -0.723  9.01 0.488     1 ns          
#> 10 relative_… FOXG1  PAX6       9     9    -1.11   8.01 0.299     1 ns          
#> # … with 26 more rows
```

<sup>Created on 2020-06-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by lmanchon** [comment]
ok, thank you.
