### ISSUE TITLE
p values not completely shown in stat_compare_means 

### ISSUE THREAD

**Issue by sbbmu** [kassambara/ggpubr#136]
Using the sample data, p values not shown completely after specifying the comparisons. ggpubr version=0.1.9

`library(ggpubr)
p <- ggboxplot(ToothGrowth, x = "supp", y = "len",
               color = "supp", palette = "jco",
               add = "jitter",
               facet.by = "dose", short.panel.labs = FALSE)

p + stat_compare_means(method = "t.test", label = "p.format", 
	comparisons=list(c("OJ","VC")))
`
![2](https://user-images.githubusercontent.com/4334177/48432572-9d16e980-e729-11e8-81b5-1491592e62e9.png)

It has to be very long to show them. This is not convenient for publications.
![3](https://user-images.githubusercontent.com/4334177/48432753-24645d00-e72a-11e8-9217-5d83cd52a743.png)

**Comment by kassambara** [comment]
Hi,

Did you tried to change the y axis limits in ggboxplot() (argument: ylim) or the p-value label y position (argument: label.y).

Example of R code: 

```r
p <- ggboxplot(ToothGrowth, x = "supp", y = "len",
               color = "supp", palette = "jco",
               add = "jitter",
               facet.by = "dose", short.panel.labs = FALSE,
               ylim = c(0, 40))

p + stat_compare_means(method = "t.test", label = "p.format",
                       comparisons=list(c("OJ","VC")),
                       label.y = 35)
```

![rplot](https://user-images.githubusercontent.com/3313355/48436564-44723b80-e77f-11e8-81ef-0469774aadc6.png)

**Comment by komalsrathi** [comment]
What if the y axis scales for all facets are different?

**Comment by yangkl0909** [comment]
The same problem bothers me.
Though changing the I can change y limit for 1 figrue, but I can't set up a y limit for facet with different y limit. Can ggpubr support p value vjust like ggsignif? Thanks.

**Comment by yangkl0909** [comment]
The same problem bothers me.
Though changing  I can change the y limit for it, but I can't set up a y limit for the facet with different y limit. Can ggpubr support p value vjust like ggsignif? Thanks.

**Comment by Youguang** [comment]
Yes, how does ggbarplot decide the y limit? It seems depends on the raw data range but not the bar+errorbar range.

<img width="587" alt="Screen Shot 2019-10-08 at 20 27 29" src="https://user-images.githubusercontent.com/7878120/66395752-cd830880-ea0a-11e9-825b-050a6c6311ae.png">

**Comment by fxpopp** [comment]
This problem is still unsolved, isn't it? Or did anybody come up with a solution? When setting label.y with multiple comparisons, all p values are displayed on top of each other. 

![image](https://user-images.githubusercontent.com/38974891/82722097-d1c31400-9cc3-11ea-9227-06d8cbf54449.png)

**Comment by kassambara** [comment]
Using the combination of the ggplot functions `scale_y_continuous()` and `expansion()` should solve this issue; see example of R codes at:  [GGPLOT Facet: How to Add Space Between Labels on the Top of the Chart and the Plot Border](https://www.datanovia.com/en/blog/ggplot-facet-how-to-add-space-between-labels-on-the-top-of-the-chart-and-the-plot-border/)

Let me know if it works, so that we can close the issue. If you still have the problem, please consider providing a reproducible R script with a demo data so that we can help efficiently

**Comment by fxpopp** [comment]
Hi,
thank you so much, your suggestion worked perfectly.
Best regards
Felix




Am So., 24. Mai 2020 um 14:18 Uhr schrieb Alboukadel KASSAMBARA <
notifications@github.com>:

**Comment by kassambara** [comment]
great, so we can close this issue
