### ISSUE TITLE
Problem with error bar attribution

### ISSUE THREAD

**Issue by sebastienmeurant** [kassambara/ggpubr#140]
I'm trying to plot graph of protein relative abundance during a timeline with 7 time points and 2 conditions per time point (Diff and Undiff) but when I plot only the mean the graph work properly but when I try to add the se (with: add="mean_se"), I obtain a se not based on each individual mean but on the mean of the mean of my two conditions for each time point.
To help you see clearer I join a picture of what I obtain.
I think maybe that the problem comes from a bad organization of my data but I cannot figure out what is the problem. I join the data file and a example of one code I'm using:

p<-ggline(data2, x='Day', y='eIF4G',add =c("mean_se","jitter"), color = "Diffcond",palette = c("grey30","grey"), xlim=c(0,24), legend='right', size=1.4, linetype = "solid", shape="Diffcond",point.size =2.2)+scale_shape_manual(values=c(18,15))+expand_limits(x=0,y=0)+scale_y_continuous(expand = c(0,0))+scale_x_continuous(expand = c(0, 0),breaks=seq(0,24, by = 4))+labs(title="eIF4G", x="Day of differentiation", y="Relative protein abundance (fold)")+theme(axis.line = element_line(colour = "dimgrey"), plot.title = element_text(hjust = 0.5),legend.text = element_text(size=15))

ggpar(p,font.main=c(18,"bold","black"), legend.title = "", font.x = c(15,"bold","black"), font.y = c(15,"bold","black"), font.tickslab= c(12,"plain","black"))

![eif4g](https://user-images.githubusercontent.com/45287899/48941890-9e13fc00-ef1d-11e8-900d-19669570b580.png)
[Quantif - Stat - WB.xlsx](https://github.com/kassambara/ggpubr/files/2610596/Quantif.-.Stat.-.WB.xlsx)

**Comment by kassambara** [comment]
It works with the latest developmental version of ggpubr as illustrated below:

![Rplot04](https://user-images.githubusercontent.com/3313355/58837725-b5fed200-865c-11e9-96b5-7a87e46278fe.png)
