### ISSUE TITLE
p.adj with stat_compare_means()

### ISSUE THREAD

**Issue by lapotok** [kassambara/ggpubr#143]
I recently discovered ggpubr for myself and I've been enjoying it a lot!
I count get stat_compare_means() to show t-test p-values adjusted for multiple comparison.
This is what I tried. I used a modified example from #65.

```r
library(ggpubr)

data("ToothGrowth")
head(ToothGrowth)

my_comparisons <- list( c("0.5", "1"), c("1", "2"), c("0.5", "2") )
ggboxplot(ToothGrowth, x = "dose", y = "len") +
  stat_compare_means(
    p.adjust.method = "bonferroni", 
    method='t.test',
    comparisons = my_comparisons, 
    label.y = c(29, 35, 40)
  )

compare_means(len~dose,comparisons = my_comparisons, p.adjust.method = "bonferroni", method='t.test',data = ToothGrowth)
```

These are attempts that I made to get it working (mentioned in earlier thread covering this issue).

```r
# label = 'p.adj' would be the best (but p.adj.format or p.adj.signif even better)

ggboxplot(ToothGrowth, "dose", "len") +
  stat_compare_means(
    p.adjust.method = "bonferroni", 
    method='t.test',
    label='p.adj',
    comparisons = my_comparisons
  )

# aes(label=..p.adj..) doesn't work either

ggboxplot(ToothGrowth, "dose", "len") +
  stat_compare_means(
    aes(label=..p.adj..),
    p.adjust.method = "bonferroni", 
    method='t.test',
    comparisons = my_comparisons
  )

ggboxplot(ToothGrowth, "dose", "len") +
  stat_compare_means(
    mapping = aes(label=..p.adj..),
    p.adjust.method = "bonferroni", 
    method='t.test',
    comparisons = my_comparisons
  )

ggboxplot(ToothGrowth, "dose", "len") +
  stat_compare_means(
    mapping=aes(label = format.pval(..p.adj.., digits = 1)),
    p.adjust.method = "bonferroni", 
    method='t.test',
    comparisons = my_comparisons
  )
```

The only solution I found that actually worked for me is [this one](https://github.com/kassambara/ggpubr/issues/65#issuecomment-407211245). But I thought it would be great if adjusted p-values could be displayed without having to get the test results precalculated and adjusted.

```r
library(rstatix)
pairwise.test = ToothGrowth %>% 
  t_test(len ~ dose) %>% 
  adjust_pvalue(method = 'bonferroni')

ggboxplot(ToothGrowth, x = "dose", y = "len")+
  stat_pvalue_manual(
    pairwise.test, label = "p.adj", 
    y.position = c(29, 35, 39)
  )
```

**Comment by WaasThissen** [comment]
This would also work, using only the ggpubr package:

my_comparisons <- list( c("0.5", "1"), c("1", "2"), c("0.5", "2"))
t_test_tooth <- compare_means(len ~ dose, comparisons = my_comparisons, p.adjust.method = "bonferroni", method='t.test', data = ToothGrowth)
t_test_tooth <- t_test_tooth %>% mutate(y.position = c(29, 35, 39))
ggboxplot(ToothGrowth, x = "dose" , y = "len") + stat_pvalue_manual(t_test_tooth, label = "p.adj") 

It is also an example in:
?stat_pvalue_manual

**Comment by ShixiangWang** [comment]
I have the same problem. The `label=..p.adj..` do nothing to show adjusted p-value.

**Comment by kassambara** [comment]
I recently developed a package, named [rstatix](https://github.com/kassambara/rstatix), which makes it possible to run basic stat tests separately (t-test, wilcoxon, anova, kruskal-wallis).

The output of the rstatix package are easily handled by the function stat_pvalue_manual() and others [in ggpubr package] to display p-values/adjusted p-values and test details on a plot.

so, the new workfow is now:

1. Compute easily statistical test using the rstatix package. The output is always a data frame and p-values are adjusted for multiple testing
2. Create plot and add (rstatix) test outputs using stat_pvalue_manual() [ggpubr]

See examples at:

-   [Comparing Means of Two Groups in R](https://www.datanovia.com/en/courses/comparing-means-of-two-groups-in-r/)
    -   [T-test in R](https://www.datanovia.com/en/lessons/t-test-in-r/)
    -   [Wilcoxon Test in R](https://www.datanovia.com/en/lessons/wilcoxon-test-in-r/)
    -   [Sign Test in R](https://www.datanovia.com/en/lessons/sign-test-in-r/)
-   [Comparing Multiple Means in R](https://www.datanovia.com/en/courses/comparing-multiple-means-in-r/)
    -   [ANOVA in R](https://www.datanovia.com/en/lessons/anova-in-r/)
    -   [Repeated Measures ANOVA in R](https://www.datanovia.com/en/lessons/repeated-measures-anova-in-r/)
    -   [Mixed ANOVA in R](https://www.datanovia.com/en/lessons/mixed-anova-in-r/)
    -   [ANCOVA in R](https://www.datanovia.com/en/lessons/ancova-in-r/)
    -   [One-Way MANOVA in R](https://www.datanovia.com/en/lessons/one-way-manova-in-r/)
    -   [Kruskal-Wallis Test in R](https://www.datanovia.com/en/lessons/kruskal-wallis-test-in-r/)
    -   [Friedman Test in R](https://www.datanovia.com/en/lessons/friedman-test-in-r/)

**Comment by dryjon** [comment]
Any thoughts how to extend this to work when you have broken the plot into several panels using facet.by (i.e. to calculate and label the stats for just sample subsets within each panel)?  Thanks

**Comment by kassambara** [comment]
@dryjon if understood well your issue, you want to create a facet plot and to show stats labels for some specific pairwise comparisons  in each panel.

**Comment by dryjon** [comment]
Yes, I'm currently using:

v = ggviolin(File, x="colA", y="colB", facet.by="colC")
v + stat_compare_means(method = "t.test", comparisons = list(c("classA","classB"),c("classB","classC"),c("classC","classD"))) + stat_compare_means(method = "anova")

And would like the plot to display the FDR p.adj on each facet for the t.test and anova results.

**Comment by negin1986** [comment]
I have the same issue. Any solutions for that?

**Comment by kassambara** [comment]
This new function might help to add adhusted p-values: https://rpkgs.datanovia.com/ggpubr/reference/geom_pwc.html

**Comment by nilsrudqvist** [comment]
> This new function might help to add adhusted p-values: https://rpkgs.datanovia.com/ggpubr/reference/geom_pwc.html

Hi Kassambara, this is great, thank you! I only wish it could handle paired data. Is that a possible fix?

Thanks,
Nils
