### ISSUE TITLE
ggarrange fails if eiter `ncol = 1` or `nrow = 1`

### ISSUE THREAD

**Issue by GegznaV** [kassambara/ggpubr#144]
In the example below `ggarrange` fails to create a single plot if eiter `ncol = 1` or `nrow = 1`:

```r
library(ggplot2)

fig_1 <- 
  ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_line()

ggpubr::ggarrange(fig_1, fig_1, ncol = 1)
ggpubr::ggarrange(fig_1, fig_1, nrow = 1)
```
I by specifying ` ncol = 1` I expected all plots on one page arranged in one column.  But the result is two separate plots and the output in the console:
```
$`1`

$`2`

attr(,"class")
[1] "list"      "ggarrange"
```

This should either be fixed (preferred), or a meaningful warning message should appear with explanations what happened, or, if the behavior I described is expected, more information should be included in the documentation.

In the situation:
```r
ggpubr::ggarrange(fig_1, fig_1, nrow = 0)
```

A meaningful error message that  `nrow` must be > 0 would also be preffered instead of `Error in 1:(rows * cols) : NA/NaN argument`.

**Comment by ashenkin** [comment]
+1, except that it's not just a matter of ncol/nrow = 1.  This happens when only ncol or only nrow is specified.  i.e., 
`ggpubr::ggarrange(fig_1, fig_1, fig_1, ncol = 2)`
fails as well.

**Comment by kassambara** [comment]
In the current version:

- If you want to arrange 2 , 3, ..., or n plots  by rows only, you need to specify `nrow = n`, where `n` is the number of plots
- Similarly, if you want to arrange 2 , 3, ..., or n plots  by columns only,  you need to specify `ncol = n`

In your example, the following R code should work:

```r
# Arrange two plots in two successive columns
ggpubr::ggarrange(fig_1, fig_1, ncol = 2)

# Arrange two plots in two successive rows
ggpubr::ggarrange(fig_1, fig_1, nrow = 2)
```

I will update ggarrange(), so that it can automatically guess the correct layout for  the options `ncol=1` and `nrow=1`

**Comment by kassambara** [comment]
fixed now thanks

**Comment by mielk132** [comment]
I had the same error as GegznaV ( running ‘4.1.3’ in Rstudio), but it worked when I supplied 1.5. It would not work when I set nrow =2 & ncol =1.

 ggarrange(p,p2, labels = c("A","B"),combine.legend = TRUE, legend = "right", ncol = 2, nrow= 1.5)
