### ISSUE TITLE
yticks.by not works with minus scale

### ISSUE THREAD

**Issue by biofisherman** [kassambara/ggpubr#146]
The y scale range of my dataset is (-3, 3). When I set the `yticks.by = 1`, only the positive scales were changed, but not the negative scales.
Now, I have to use the following code to make it work.`scale_y_continuous(breaks=c(-3,-2, -1,0, 1, 2, 3))`

Any suggestions?

Thanks!

**Comment by kassambara** [comment]
Should work now after the update in #258 
``` r
library(ggpubr)
# Data
set.seed(123)
x <- rnorm(100)
df <- data.frame(x = x, y = 2*x )

# Default plot
ggscatter(df, "x", "y")
```

![](https://i.imgur.com/q7DrMMa.png)

``` r

# Set ticks
# Use this
ggscatter(df, x = "x", y = "y", yticks.by = 1)
```

![](https://i.imgur.com/aSe3S9l.png)

``` r

# Or use this
ggscatter(df, x = "x", y = "y")+
  scale_y_continuous(breaks = get_breaks(by = 1))
```

![](https://i.imgur.com/I2Ag9HC.png)

<sup>Created on 2020-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
