### ISSUE TITLE
displaced error bars in stacked ggbarplot

### ISSUE THREAD

**Issue by strassf** [kassambara/ggpubr#147]
Hi, i've been having an issue with adding error bars & data points to a stacked ggbar plot. The error bars and data points are reflective of the original data values, not the stacked values. Please let me know if there is a workaround. 

#Tooth Growth example with Displaced Errorbars
ggbarplot(ToothGrowth, x = "dose", y = "len", 
          add = c("mean_se", "jitter"),
          color = "supp", palette = "jco",
          combine=TRUE)

![image](https://user-images.githubusercontent.com/46455723/50784916-17bd3a80-127d-11e9-9b83-39b6da43188a.png)

I also need to be able to compare the groups in the stacked bar against each other, i.e. OJ @ dose 0.5 to OJ @ dose 1. How do I configure my stat_compare_means command to do this?

**Comment by brentocarrigan** [comment]
Hi all,

Any updates for this question? A work-around using ggplot2 directly is described on [StackOverflow #58603380](https://stackoverflow.com/questions/58603380/how-to-organize-error-bars-to-relevant-bars-in-a-stacked-bar-plot-in-ggplot) calling a new data frame, but a solution inside ggbarplot would be fantastic

I appreciate interpreting error bars on stacked bar plots is fraught and ambiguous to interpret, and that side-by-side dodge position much clearer - but supervisors want what supervisors want :)

**Comment by kassambara** [comment]
Fixed now, thanks:

``` r
# 1. Load required R packages
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(rstatix))

# 2. Data preparation
df <- ToothGrowth
df$dose <- factor(df$dose)

# 3. Statistical tests
res.stats <- df %>%
  group_by(dose) %>%
  t_test(len ~ supp) %>%
  adjust_pvalue() %>%
  add_significance()
res.stats
#> # A tibble: 3 x 11
#>   dose  .y.   group1 group2    n1    n2 statistic    df       p   p.adj
#>   <fct> <chr> <chr>  <chr>  <int> <int>     <dbl> <dbl>   <dbl>   <dbl>
#> 1 0.5   len   OJ     VC        10    10    3.17    15.0 0.00636 0.0127 
#> 2 1     len   OJ     VC        10    10    4.03    15.4 0.00104 0.00312
#> 3 2     len   OJ     VC        10    10   -0.0461  14.0 0.964   0.964  
#> # … with 1 more variable: p.adj.signif <chr>

# 4. Create a stacked bar plot, add "mean_se" error bars
p <- ggbarplot(
  df,
  x = "dose", y = "len", add = "mean_se",
  color = "supp", palette = "jco"
)

# 5. Add p-values to the bar plot using ggpubr verbs
p + stat_pvalue_manual(
  res.stats,
  x = "dose", y.position = c(30, 45, 60),
  label = "p.adj.signif"
)
```

![](https://i.imgur.com/bm3Wb7y.png)

``` r

# or use ggplot2 verbs
p + geom_text(
  aes(x = dose, y = c(25, 42, 60), label = p.adj.signif),
  data = res.stats
)
```

![](https://i.imgur.com/SpTYa5u.png)

**Comment by brentocarrigan** [comment]
Fantastic! Thank you kassambara - super efficient, clean fix as always! I don't think I can close issue as am not original poster.

**Comment by dkagro1991** [comment]
I want to create A stalked bar plot using ggpubr using the given data and codes:
Input1= ("Year	Trt	Rep	AGR36	AGR69	CGR36	CGR69
Year:2015	N1	1	1.817	2.216	15.13561	18.45928
         Year:2015	N1	2	1.814	2.481666667	15.11062	20.67228333
         Year:2015	N1	3	1.816666667	2.892666667	15.13283333	24.09591333
         Year:2015	N1	4	1.785666667	2.235333333	14.87460333	18.62032667
         Year:2015	N2	1	2.040333333	2.623	16.99597667	21.84959
         Year:2015	N2	2	1.906	3.095	15.87698	25.78135
         Year:2015	N2	3	2.053333333	3.052666667	17.10426667	25.42871333
         Year:2015	N2	4	1.880666667	3.283	15.66595333	27.34739
         Year:2015	N3	1	2.695333333	2.933333333	22.45212667	24.43466667
         Year:2015	N3	2	2.250666667	4.006666667	18.74805333	33.37553333
         Year:2015	N3	3	2.132	2.931	17.75956	24.41523
         Year:2015	N3	4	2.613333333	3.067333333	21.76906667	25.55088667
         Year:2015	N4	1	1.746	2.234	14.54418	18.60922
         Year:2015	N4	2	1.846	2.659	15.37718	22.14947
         Year:2015	N4	3	2.040666667	2.461	16.99875333	20.50013
         Year:2015	N4	4	1.754666667	2.293666667	14.61637333	19.10624333
         Year:2015	N5	1	2.02	3.378333333	16.8266	28.14151667
         Year:2015	N5	2	1.922666667	3.145333333	16.01581333	26.20062667
         Year:2015	N5	3	1.789666667	2.258666667	14.90792333	18.81469333
         Year:2015	N5	4	1.747666667	3.537	14.55806333	29.46321
         Year:2015	N6	1	1.927	2.996333333	16.05191	24.95945667
         Year:2015	N6	2	2.321	3.720666667	19.33393	30.99315333
         Year:2015	N6	3	2.672333333	2.732666667	22.26053667	22.76311333
         Year:2015	N6	4	2.605666667	2.977333333	21.70520333	24.80118667
         Year:2015	N7	1	1.984666667	2.764666667	16.53227333	23.02967333
         Year:2015	N7	2	2.232999913	3.032333421	18.60088927	25.25933739
         Year:2015	N7	3	2.411	2.964333333	20.08363	24.69289667
         Year:2015	N7	4	1.918333333	3.849	15.97971667	32.06217
         Year:2015	N8	1	2.037	3.272	16.96821	27.25576
         Year:2015	N8	2	1.858	3.012	15.47714	25.08996
         Year:2015	N8	3	1.286	2.367	10.71238	19.71711
         Year:2015	N8	4	2.121666667	2.73	17.67348333	22.7409
         Year:2016	N1	1	1.919	2.441666667	15.98527	20.33908333
         Year:2016	N1	2	1.797	2.395333333	14.96901	19.95312667
         Year:2016	N1	3	1.756666667	3.018666667	14.63303333	25.14549333
         Year:2016	N1	4	1.683	2.194	14.01939	18.27602
         Year:2016	N2	1	2.070333333	2.861333333	17.24587667	23.83490667
         Year:2016	N2	2	1.950666667	2.895333333	16.24905333	24.11812667
         Year:2016	N2	3	2.025666667	3.052	16.87380333	25.42316
         Year:2016	N2	4	1.921666667	3.259	16.00748333	27.14747
         Year:2016	N3	1	2.657333333	3.341	22.13558667	27.83053
         Year:2016	N3	2	2.782333333	3.417333333	23.17683667	28.46638667
         Year:2016	N3	3	2.030333333	2.830666667	16.91267667	23.57945333
         Year:2016	N3	4	2.701	2.888	22.49933	24.05704
         Year:2016	N4	1	1.886333333	2.367333333	15.71315667	19.71988667
         Year:2016	N4	2	1.796666667	2.705	14.96623333	22.53265
         Year:2016	N4	3	1.892333333	2.673	15.76313667	22.26609
         Year:2016	N4	4	1.693333333	2.291	14.10546667	19.08403
         Year:2016	N5	1	2.095	2.533	17.45135	21.09989
         Year:2016	N5	2	1.918333333	2.664333333	15.97971667	22.19389667
         Year:2016	N5	3	1.817333333	3.587333333	15.13838667	29.88248667
         Year:2016	N5	4	1.955666667	3.110666667	16.29070333	25.91185333
         Year:2016	N6	1	2.407666667	2.944333333	20.05586333	24.52629667
         Year:2016	N6	2	2.405	3.661333333	20.03365	30.49890667
         Year:2016	N6	3	2.398333333	2.929	19.97811667	24.39857
         Year:2016	N6	4	2.564666667	3.084666667	21.36367333	25.69527333
         Year:2016	N7	1	2.270666667	2.798666667	18.91465333	23.31289333
         Year:2016	N7	2	2.006	2.933666667	16.70998	24.43744333
         Year:2016	N7	3	2.382	3.046333333	19.84206	25.37595667
         Year:2016	N7	4	2.065666667	3.701	17.20700333	30.82933
         Year:2016	N8	1	1.480666667	2.615	12.33395333	21.78295
         Year:2016	N8	2	1.984666667	2.785	16.53227333	23.19905
         Year:2016	N8	3	2.046333333	3.147333333	17.04595667	26.21728667
         Year:2016	N8	4	2.113666667	2.8	17.60684333	23.324
         ")
df = read.table(textConnection(Input1), header = TRUE)
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(rstatix))
Trt <- factor(df$Trt)
Year <- factor(df$Year)
a=ggbarplot(data1, x = "Trt", y = "AGR36",
            fill = "Year", palette = "grey",
            add = "mean_sd", add.params = list(group = "Year", size=0.8, width=5), 
            error.plot = "errorbar", label = FALSE,
            position = position_stack(0.5),
            font.x = c(12, "bold", "black"), 
            font.y = c(16, "bold", "black"),
            font.legend = c(12, "bold", "black"),
            font.xtickslab = c(12, "bold", "black"),
            font.ytickslab = c(12, "bold", "black"),
            xticks.by =NULL, yticks.by = 0.5,
            title = NULL, xlab = "Treatments",
            ylab = expression("kg grain kg" ^{-1}* "N uptake"), panel.labs = NULL,
            short.panel.labs = FALSE, show.line.label = FALSE,
            length = nrow(data), 
            font.label = list(size = 12, face = "bold", color ="black"), 
            label.select = list(top.up = 12, top.down = 4), repel = TRUE, 
            legend =NULL, legend.title =NULL)
print(a)
The result is:
![barplot6](https://user-images.githubusercontent.com/47247171/82433860-ae278000-9aaf-11ea-80fd-0c29f2ce2d5e.png)

I want all the errorbars at approriate places like:

![68747470733a2f2f692e696d6775722e636f6d2f537054596135752e706e67](https://user-images.githubusercontent.com/47247171/82434324-55a4b280-9ab0-11ea-8fa2-f382138048ad.png)

also i want year 2015 to be apper first in stack position.

please help

**Comment by kassambara** [comment]
Hi, you only need to install the latest version of ggpubr available on CRAN.

 To have year 2015 appearing first in stack position, please specify the option `position = position_stack(0.5, reverse = TRUE)`.

You will end up with the following plot:

![Rplot](https://user-images.githubusercontent.com/3313355/82437162-449b7780-9a97-11ea-83ea-85172aa1c955.png)

**Comment by dkagro1991** [comment]
Thanks, this is working now, but I am not able to increase the width of errorbar, they are too thin.

**Comment by kassambara** [comment]
Thank you for pointing this out. The argument `width`  is now supported see #278. Please install the latest dev version: `devtools::install_github("kassambara/ggpubr")`

**Comment by osei2021** [comment]
Pls how can add a single error bar  to represent all all the levels in a bar while keeping the color code for both year 2015 and 2016?. For examples, I do not want separate error bars for year 2015 and year 2016 but a single one for both.

**Comment by Agustin-5** [comment]
I'm still having the same issue of displaced errorbars when trying to stack positive and negative values together. Any suggestions? 
Thanks

> rec
   Block Treatment    Depth  lit.der_SOC       try
1     BI      IRRI   Litter 200.60140696     Added
2     BI       DRY   Litter 200.15854722     Added
3    BII      IRRI   Litter 200.36284589     Added
4    BII       DRY   Litter 201.07118712     Added
5   BIII      IRRI   Litter 200.83262608     Added
6   BIII       DRY   Litter 200.95313025     Added
7    BIV      IRRI   Litter 201.06384517     Added
8    BIV       DRY   Litter 199.79214004     Added
9     BI      IRRI   Litter 162.67223066  6 months
10    BI       DRY   Litter 145.30796715  6 months
11   BII      IRRI   Litter 165.94734970  6 months
12   BII       DRY   Litter 165.42415364  6 months
13  BIII      IRRI   Litter 166.56132628  6 months
14  BIII       DRY   Litter 175.03680007  6 months
15   BIV      IRRI   Litter 167.19386417  6 months
16   BIV       DRY   Litter 171.55939042  6 months
17    BI      IRRI   Litter 200.48335009     Added
18    BI       DRY   Litter 202.71174675     Added
19   BII      IRRI   Litter 201.07608174     Added
20   BII       DRY   Litter 200.49558665     Added
21  BIII      IRRI   Litter 198.76389057     Added
22  BIII       DRY   Litter 201.29995892     Added
23   BIV      IRRI   Litter 200.71456918     Added
24   BIV       DRY   Litter 201.75994984     Added
25    BI      IRRI   Litter  81.67314658 13 months
26    BI       DRY   Litter  69.87997411 13 months
27   BII      IRRI   Litter  57.66392059 13 months
28   BII       DRY   Litter  80.78068368 13 months
29  BIII      IRRI   Litter  79.46654447 13 months
30  BIII       DRY   Litter 119.43297578 13 months
31   BIV      IRRI   Litter  73.58404924 13 months
32   BIV       DRY   Litter  92.26087859 13 months
33    BI      IRRI   0-5 cm -16.61684020 13 months
34    BI      IRRI  5-10 cm  -0.85861080 13 months
35    BI      IRRI 10-20 cm  -0.26653591 13 months
36    BI      IRRI 20-40 cm   0.00000000 13 months
37    BI       DRY   0-5 cm -18.19397017 13 months
38    BI       DRY  5-10 cm  -1.60913363 13 months
39    BI       DRY 10-20 cm  -0.58920156 13 months
40    BI       DRY 20-40 cm   0.00000000 13 months
41   BII      IRRI   0-5 cm -21.84582760 13 months
42   BII      IRRI  5-10 cm  -1.53017507 13 months
43   BII      IRRI 10-20 cm  -0.43183087 13 months
44   BII      IRRI 20-40 cm  -0.57452145 13 months
45   BII       DRY   0-5 cm -14.69022133 13 months
46   BII       DRY  5-10 cm  -2.62928253 13 months
47   BII       DRY 10-20 cm  -0.97054075 13 months
48   BII       DRY 20-40 cm  -1.27804330 13 months
49  BIII      IRRI   0-5 cm -11.67742553 13 months
50  BIII      IRRI  5-10 cm  -1.98756823 13 months
51  BIII      IRRI 10-20 cm  -0.66220384 13 months
52  BIII      IRRI 20-40 cm   0.00000000 13 months
53  BIII       DRY   0-5 cm -12.02927203 13 months
54  BIII       DRY  5-10 cm  -1.65783250 13 months
55  BIII       DRY 10-20 cm  -0.94420555 13 months
56  BIII       DRY 20-40 cm  -0.98772403 13 months
57   BIV      IRRI   0-5 cm -11.29702920 13 months
58   BIV      IRRI  5-10 cm  -1.24230185 13 months
59   BIV      IRRI 10-20 cm  -0.67237858 13 months
60   BIV      IRRI 20-40 cm  -0.09959631 13 months
61   BIV       DRY   0-5 cm -12.88809810 13 months
62   BIV       DRY  5-10 cm  -1.66912975 13 months
63   BIV       DRY 10-20 cm  -0.75638382 13 months
64   BIV       DRY 20-40 cm  -0.85880038 13 months
65    BI      IRRI   0-5 cm  -8.76740676  6 months
66    BI      IRRI  5-10 cm  -0.63486176  6 months
67    BI      IRRI 10-20 cm  -0.17377915  6 months
68    BI      IRRI 20-40 cm  -0.11005066  6 months
69    BI       DRY   0-5 cm  -7.96025584  6 months
70    BI       DRY  5-10 cm  -0.90234972  6 months
71    BI       DRY 10-20 cm  -0.20623258  6 months
72    BI       DRY 20-40 cm   0.00000000  6 months
73   BII      IRRI   0-5 cm  -5.83373867  6 months
74   BII      IRRI  5-10 cm  -0.17048297  6 months
75   BII      IRRI 10-20 cm   0.00000000  6 months
76   BII      IRRI 20-40 cm   0.00000000  6 months
77   BII       DRY   0-5 cm  -8.53555872  6 months
78   BII       DRY  5-10 cm  -0.22213583  6 months
79   BII       DRY 10-20 cm  -0.67072101  6 months
80   BII       DRY 20-40 cm   0.00000000  6 months
81  BIII      IRRI   0-5 cm  -8.56494530  6 months
82  BIII      IRRI  5-10 cm  -0.16359151  6 months
83  BIII      IRRI 10-20 cm   0.00000000  6 months
84  BIII      IRRI 20-40 cm   0.00000000  6 months
85  BIII       DRY   0-5 cm  -9.29394800  6 months
86  BIII       DRY  5-10 cm  -0.34334168  6 months
87  BIII       DRY 10-20 cm   0.00000000  6 months
88  BIII       DRY 20-40 cm  -0.42264637  6 months
89   BIV      IRRI   0-5 cm  -7.67759931  6 months
90   BIV      IRRI  5-10 cm  -0.51149227  6 months
91   BIV      IRRI 10-20 cm   0.00000000  6 months
92   BIV      IRRI 20-40 cm   0.00000000  6 months
93   BIV       DRY   0-5 cm  -9.17671082  6 months
94   BIV       DRY  5-10 cm  -0.58256320  6 months
95   BIV       DRY 10-20 cm   0.00000000  6 months
96   BIV       DRY 20-40 cm   0.00000000  6 months

rec %>%
  ggbarplot(x = "Treatment", 
            y ="lit.der_SOC", 
            add="mean_se",
            fill= "Depth", 
            ylab=expression("Litter-derived C (g C " *m^-{2}*")"),
            xlab="",
            legend.title= "",
            facet.by = "try",
            title="(a)",
            palette = "aaas", alpha=.7) +
  geom_hline(yintercept = 0)+ 
  theme_pubr(legend="right")

![Rplot](https://user-images.githubusercontent.com/89936620/131723445-118f63be-a789-4788-9eab-84be6cbc1e97.png)
