### ISSUE TITLE
Getting rid of the original color scale after gradient_color layer

### ISSUE THREAD

**Issue by atakanekiz** [kassambara/ggpubr#148]
Hello,

Any ideas how I can get rid of the original blue color scale below? I tried removing the `legend` while creating the initial graph prior to `+ gradient_color()` function, but it gets rid of both color scales that way.

Thanks
Atakan

``` r
library(ggpubr)
#> Loading required package: ggplot2
#> Loading required package: magrittr

ggboxplot(iris, "Species", "Sepal.Length", color="Sepal.Width", add="jitter")
```

![](https://i.imgur.com/BxaUusS.png)

``` r


ggboxplot(iris, "Species", "Sepal.Length", color="Sepal.Width", add="jitter") + gradient_color(c("black", "red"))
```

![](https://i.imgur.com/6lZxRgx.png)

<sup>Created on 2019-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kassambara** [comment]
fixed now, thanks!
``` r
library(ggpubr)
ggboxplot(iris, "Species", "Sepal.Length", color="Sepal.Width", add="jitter") + 
  gradient_color(c("black", "red")) 
```

![](https://i.imgur.com/iRmUIgB.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
