### ISSUE TITLE
ggscatter label.sep not working?

### ISSUE THREAD

**Issue by sbbmu** [kassambara/ggpubr#150]
Want to print R and p values in two lines in ggscatter. Sample code generated one line, ignored `label.sep` argument.

```
ggscatter(mtcars, x = "wt", y = "mpg",
          shape = 21, size = 3, # Points color, shape and size
          add = "reg.line",  # Add regressin line
          cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
          cor.coeff.args = list(method = "pearson", label.x = 3, label.sep = "\n")
)
```
![image](https://user-images.githubusercontent.com/4334177/51407594-24f5e700-1b11-11e9-8158-5e5c77fb35a5.png)

**Comment by dchiu911** [comment]
Any follow-up here? Experiencing the same issue

**Comment by kassambara** [comment]
fixed now, thanks
