### ISSUE TITLE
Add an option to change the alpha in ggmaplot()

### ISSUE THREAD

**Issue by apcamargo** [kassambara/ggpubr#152]
Sometimes it is important to see the density of the points in a MA-plot. Usually, this is done by lowering the alpha of the points, which is not possible to do in `ggmaplot()` (in an easy way, at least). Adding an option to set point alpha in the `ggmaplot()` would be very useful.

**Comment by kassambara** [comment]
fixed now, thanks!

``` r
library(ggpubr)
data(diff_express)
# Default plot
ggmaplot(diff_express, main = expression("Group 1" %->% "Group 2"),
         fdr = 0.05, fc = 2, size = 0.4, 
         genenames = as.vector(diff_express$name),
         ggtheme = ggplot2::theme_minimal())
```

![](https://i.imgur.com/Ui7gwLZ.png)

``` r

# Use alpha = 0.5
ggmaplot(diff_express, main = expression("Group 1" %->% "Group 2"),
         fdr = 0.05, fc = 2, size = 0.4, 
         genenames = as.vector(diff_express$name),
         ggtheme = ggplot2::theme_minimal(),
         alpha = 0.5
         )
```

![](https://i.imgur.com/UxfVkmJ.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
