### ISSUE TITLE
ggarrange generates one extra page in Rnotebook when used with plotlist and common.legend = TRUE

### ISSUE THREAD

**Issue by ntthung** [kassambara/ggpubr#153]
**Example**

`lapply(unique(diamonds$cut), 
       function(cut) ggplot(diamonds[cut == cut,], aes(carat, price, colour = depth)) + 
           geom_point()) %>% 
    ggarrange(plotlist = ., common.legend = TRUE)`

When this code is run in Rnotebook, a blank page is created before the page of the actual plot. When this is exported to HTML, a big gap is present before the plot.

**Comment by xiaohk** [comment]
#158 might be related

**Comment by kassambara** [comment]
duplicates of #158; Obviously, we'll fix it

**Comment by Hungreeee** [comment]
This has not been fixed

**Comment by kassambara** [comment]
@Hungreeee  you are right but it's a duplicate of #158, which is still open
