### ISSUE TITLE
Autocompute y.position in stat_pvalue_manual

### ISSUE THREAD

**Issue by andreyto** [kassambara/ggpubr#154]
Right now `stat_pvalue_manual` needs a data frame that has `y.position` already set. The `y.position` is difficult to pre-compute properly for different main geoms and multiple comparisons when the plot is generated inside some automated report generator. On the other hand, `stat_compare_means` can already compute all positions automatically, and seems to be quite good at it. Would it be possible to make `y.position` optional in the input data frame for `stat_pvalue_manual`? Maybe it could call the implementation from `stat_compare_means` when `y.position` is not provided?

**Comment by kassambara** [comment]
P-values positions are automatically computed. Many examples are provided in the following blog posts:

- [How to Add P-Values onto Basic GGPLOTS](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-basic-ggplots/)
- [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/)
- [How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)

**Comment by jgarces02** [comment]
In my case (version 0.4.0) is not automatically computed... 😓

**Comment by adomingues** [comment]
@jgarces02 @andreyto if you are using `rstatix` to manually compute the p-values, then the solution seems to be adding `add_xy_position` to the pipe. See example in https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/

```R
stat.test <- stat.test %>% add_xy_position(x = "supp")
```

**Comment by jgarces02** [comment]
Thanks a lot, @adomingues.

**Comment by jgarces02** [comment]
I'm afraid there's a little bug in this function... if a columns is called `variable` (very normal when performing `melt()`, for example) `add_xy_position` brings an error because duplication problems... changing the name seems to fix this error. I've see this explanation [here](https://github.com/IndrajeetPatil/groupedstats/issues/24) and works well for me.

```
> data <- source("https://pastebin.com/raw/JzgNYvHR")$value

> (stats_tmp <- data %>% group_by(variable) %>% dunn_test(nums ~ value) %>%
    add_xy_position())
# Error: Names must be unique.
# x These names are duplicated:
#   * "variable" at locations 1 and 3.
# ℹ Use argument `names_repair` to specify repair strategy.
# Run `rlang::last_error()` to see where the error occurred.

> (stats_tmp <- data %>% mutate(variable2 = variable) %>% group_by(variable2) %>% dunn_test(nums ~ value) %>%
    add_xy_position())
# # A tibble: 7 x 14
#   variable2       .y.   group1 group2        n1    n2 statistic           p       p.adj p.adj.signif y.position groups      xmin  xmax
#   <fct>           <chr> <chr>  <chr>      <int> <int>     <dbl>       <dbl>       <dbl> <chr>             <dbl> <named li> <int> <int>
# 1 CRS_(Risk_grou… nums  BAJO   MEDIO          1    39     0.888     3.75e-1     3.75e-1 ns                 30.1 <chr [2]>      1     2
# 2 CRS_(Risk_grou… nums  BAJO   ALTO           1    10     2.17      2.98e-2     5.96e-2 ns                 34.8 <chr [2]>      1     6
# 3 CRS_(Risk_grou… nums  MEDIO  ALTO          39    10     3.89      9.92e-5     2.98e-4 ***                39.5 <chr [2]>      2     6
# 4 exitus          nums  0      1             45     5     2.45      1.45e-2     1.45e-2 *                  30.1 <chr [2]>      3     7
# 5 time_group      nums  <5     5-13          20    21     4.88      1.07e-6     2.14e-6 ****               30.1 <chr [2]>      4     5
# 6 time_group      nums  <5     >13/exitus    20     9     5.70      1.22e-8     3.67e-8 ****               34.8 <chr [2]>      4     8
# 7 time_group      nums  5-13   >13/exitus    21     9     1.91      5.57e-2     5.57e-2 ns                 39.5 <chr [2]>      5     8
```
Thanks for your attention.

**Comment by NeginValizadegan** [comment]
Hello all,

I am having issue with y.position even when I create a column manually, the graph shows all brackets on the same y location. I was not able to automatically calculate y.positions. I am using glm as shown below and I tried everything and it still doesn't work:

# Run the glm test
 glm_test <- glm(k_Bacteria ~ sample_Species, 
              data = comparison, 
              family = nbinom2, 
              maxit = 100)

# Run Tukey for pairwise comparison  
pairwise <- summary(glht(glm_test,linfct=mcp(sample_Species="Tukey")))

Create a significance table manually to input p value and all other values:
sig_table <- as.data.frame(matrix(ncol=3, nrow=6))
  colnames(sig_table) <- c("sigma", "t.stat", "p.val")
  sig_table$`t.stat` <- pairwise$test$tstat
  sig_table$`p.val` <- pairwise$test$pvalues
  sig_table$sigma <- pairwise$test$sigma
  sig_table$groups <- names(pairwise$test$pfunction())
  sig_table <- sig_table %>% separate(groups, c("group1","group2"), sep = " - ")
  sig_table <- sig_table %>%
      add_significance()

# Trying to add y either with x or including glm doesn't work
stat_test <-  sig_table %>% add_xy_position(x = "sample_Species")
 stat_test <-  sig_table  %>% add_xy_position(glm_test, k_Bacteria ~ sample_Species)

Error in add_y_position(., fun = fun, step.increase = step.increase, stack = stack,  : 
  data and formula arguments should be specified.


# Adding y.position manually
 stat_test$y.position <- c(0.2,0.5,0.7)

Result:
        sigma        t.stat         p.val                    group1       group2       p.val.signif    y.position
1 0.1907023 3.942625 0.0003731565  2.Macaque     1.Human          ***        0.2
2 0.2035256 4.023208 0.0002792872 3.Marmoset   1.Human         ***        0.5
3 0.2332643 1.492983 0.4393674788    4.Lemur      1.Human           ns        0.7

Graph shows that still y.position is not recognized.
<img width="431" alt="Screen Shot 2021-03-17 at 6 46 55 AM" src="https://user-images.githubusercontent.com/12476457/111462578-98451480-86ec-11eb-8ba1-1d58f94deeb5.png">

**Comment by nickdylla** [comment]
I was going insane trying to figure this out! Thanks!

**Comment by txemaheredia** [comment]
I want to report that this exact error also happens if your grouping variable is called `data`. As in the "data source" of the groups you want to compare.
