### ISSUE TITLE
stat_signif() missing value where TRUE/FALSE needed 

### ISSUE THREAD

**Issue by mariaasierra** [kassambara/ggpubr#155]
Hello, 
After reading all the issues related to adding p-value to ggboxplot,  I couldn't find any solution to my problem. I hope you can help me with this.

This is my data 
[dataexample.txt](https://github.com/kassambara/ggpubr/files/2846765/dataexample.txt)

phylum.aldex<-read.table("dataexample.txt") #my data
#### Perform the test
compare_means(Actinobacteria ~ Lichen,  data = phylum.aldex,  method = "wilcox.test")
### pairwise test afterwards
dunn.test(phylum.aldex$Actinobacteria,phylum.aldex$Lichen)

ggboxplot(phylum.aldex, x = "Lichen", y = "Actinobacteria", color = "Black", palette = "Set1", fill = "Lichen", legend = "none", size = 0.2, title = "Actinobacteria") +  rotate_x_text(angle = 45)+
  stat_compare_means(comparisons = list(c("Cladonia+", "Hypotrachyna")))+
  geom_hline(yintercept = mean(phylum.aldex$Actinobacteria), linetype = 3)+ 
  geom_jitter(position = "jitter", size=3, alpha=0.8,aes(colour = Lichen)) 

I want to be able to:
1. add p-values from Dunn.test 
2. add the arrows in each of the groups that are significantly different. (like the image)

Thanks you!!

Maria.

![rplot](https://user-images.githubusercontent.com/26929522/52504546-caebbd00-2bb6-11e9-99c5-ed75f52cde72.png)

**Comment by xiaorenwu1111** [comment]
Hello,
Have you solve this problems? I met same problems.Could you help me ?
This is my code：
library(ggpubr)
ggboxplot(
distance, x="Group", y="Distance",
add = "mean_se",
facet.by = "Method"
) +
stat_compare_means(
comparisons = list(c("A", "B"), c("B", "C"), c("C", "D")),
label = "p.signif"
)
This is my data structures:
Group Distance Method
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
A 0 Hamming distance
B 162 Hamming distance
B 151 Hamming distance
B 90 Hamming distance
B 150 Hamming distance
B 131 Hamming distance
B 107 Hamming distance
B 145 Hamming distance
B 87 Hamming distance
B 103 Hamming distance
B 96 Hamming distance
B 114 Hamming distance
B 102 Hamming distance
B 103 Hamming distance
B 91 Hamming distance
B 71 Hamming distance
B 77 Hamming distance
B 77 Hamming distance
B 67 Hamming distance
B 40 Hamming distance
C 179 Hamming distance
C 167 Hamming distance
C 109 Hamming distance
C 152 Hamming distance
C 152 Hamming distance
C 152 Hamming distance
C 152 Hamming distance
C 152 Hamming distance
C 152 Hamming distance
C 152 Hamming distance
C 129 Hamming distance
C 89 Hamming distance
C 86 Hamming distance
C 109 Hamming distance
C 86 Hamming distance
C 93 Hamming distance
C 89 Hamming distance
C 80 Hamming distance
C 55 Hamming distance
D 275 Hamming distance
D 250 Hamming distance
D 193 Hamming distance
D 241 Hamming distance
D 235 Hamming distance
D 186 Hamming distance
D 240 Hamming distance
D 174 Hamming distance
D 183 Hamming distance
D 193 Hamming distance
D 171 Hamming distance
D 182 Hamming distance
D 169 Hamming distance
D 159 Hamming distance
D 141 Hamming distance
D 131 Hamming distance
D 122 Hamming distance
D 111 Hamming distance
D 94 Hamming distance
I want to draw a picture like this:
![42407858-33b43f68-81c3-11e8-8668-67c916b007d3](https://user-images.githubusercontent.com/35647271/55275390-4b5dad00-5320-11e9-85fe-1e019ade4d53.png)


But I used above data and code can't get similar picture.
![Rplot03](https://user-images.githubusercontent.com/35647271/55275393-557fab80-5320-11e9-8278-7c1f011dd4d4.png)


And I got some warning messages:
Warning messages:
1: Computation failed in stat_signif():
missing value where TRUE/FALSE needed
2: Computation failed in stat_signif():
missing value where TRUE/FALSE needed
3: Computation failed in stat_signif():
missing value where TRUE/FALSE needed
Could you help me ? Thank you !

**Comment by kassambara** [comment]
@mariaasierra For adding the Dunn test, please consider the following blog post: [Kruskal-Wallis Test and Dunn Test Pairwise Comparison in R](https://www.datanovia.com/en/lessons/kruskal-wallis-test-in-r/)

@xiaorenwu1111: all group A values are 0; this might explain the error you have obtained
