### ISSUE TITLE
Problem with plotting significance values in a grouped plot

### ISSUE THREAD

**Issue by jaydoc** [kassambara/ggpubr#156]
I am having trouble with plotting sgnificance values when the plot is faceted by a variable and grouped by two other variables.

```{r,echo=FALSE
example.df <- data.frame(species=sample(c("primate","non-primate"),50,replace = TRUE),treated=sample(c("Yes","No"),50, replace = TRUE),gender=sample(c("male", "female"),50,replace = TRUE), var1=rnorm(50,100,5))
```
```{r,echo=FALSE
library(tidyverse)
library(ggpubr)

ggboxplot(example.df, x="species", y="var1", fill="treated")+
+     facet_wrap(~gender)+stat_compare_means(aes(x=species,y=var1,group=treated),label="p.format",label.y=c(120,120,120,120))

```
Image 1
![rplot-1](https://user-images.githubusercontent.com/7351352/52517678-49228080-2c04-11e9-8f4d-0c818f62b1c9.png)

While this plot does not show bars between each of the two groups, you can see my actual plot constructed using my own data.

Image 2
![rplot-2](https://user-images.githubusercontent.com/7351352/52517692-871fa480-2c04-11e9-9705-9ada37df6a85.png)

As you can see, the lines are not right.  I am comparing each of the sub-groups within each group in both plots. 

The p-values are being calculated, as shown by  

```
compare_means(var1~species,data=example.df,group.by=c("gender","treated"))
# A tibble: 4 x 10
  gender treated .y.   group1     group2     p p.adj p.format p.signif method 
  <fct>  <fct>   <chr> <chr>      <chr>  <dbl> <dbl> <chr>    <chr>    <chr>  
1 male   No      var1  non-prima~ prima~ 0.713     1 0.71     ns       Wilcox~
2 female Yes     var1  non-prima~ prima~ 0.315     1 0.32     ns       Wilcox~
3 female No      var1  non-prima~ prima~ 0.307     1 0.31     ns       Wilcox~
4 male   Yes     var1  non-prima~ prima~ 0.303     1 0.30     ns       Wilcox~
```
Is there a way to fix the lines? 

PS: Thank you for the amazing work you have done. Its become really easy for people like me with no real experience in R to work to create great looking plots.

**Comment by kassambara** [comment]
This issue is fixed in the following blog post:

- [How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)
- [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/)
