### ISSUE TITLE
change the commmon legend names

### ISSUE THREAD

**Issue by allan296** [kassambara/ggpubr#157]
Hi! how can I change de common legend title?  I want to change to the greek letter alpha, but I can't.
`plot1 <- ggplot(ale_fdif,
                       aes(x = factor(beta), 
                           y = CONECP,
                           group = alpha,
                           color = factor(alpha))) +
  geom_point(alpha = 0.3,
             shape = 19,
             position = "jitter") +
  labs(x = expression(beta),
       y = "Weighted conectance",
       caption = "",
       title = "E",
       colour= expression(alpha)
  ) +
  scale_color_viridis(discrete = TRUE, name="alpha")`

The another polts are the same. I've tried to change in each plot but doesn't work.

`t<-ggarrange(plot1,  plot2, plot3, plot4,   plot5  ncol=3, nrow=2, common.legend = TRUE, legend="bottom")`

![fig1](https://user-images.githubusercontent.com/38731217/52902983-8c31b480-31ff-11e9-951b-0b285a453bb0.png)
thanks in advance

**Comment by amgiraldi** [comment]
Hi, regarding to this post in some degree as well. Is it possible to change the size of the font for the legends? 

I am using the graphs for a presentation and the size of the legends is too small and can't be seen very well. 

Thanks!

**Comment by kassambara** [comment]
Hi,

You can customize legend as follow:

```r
library(ggpubr)
bxp <- ggboxplot(ToothGrowth, x = "dose", y = "len",
                 color = "dose", palette = "jco")
# Change legend title and appearnace in the first plot
plot1 <-  bxp + 
  labs(color = "Dose (mg)") +
  theme(legend.title = element_text(color = "blue", size = 10),
        legend.text = element_text(color = "red"))
  

ggarrange(plot1, bxp,  common.legend = TRUE)
```

![Rplot02](https://user-images.githubusercontent.com/3313355/58824651-dae34d00-863c-11e9-8faf-9eaf26d1e907.png)

**Comment by amgiraldi** [comment]
Thank you so much for your answer.

Antonio
