### ISSUE TITLE
ggarrange generates an extra figure in rpy2 magic cell of a python Jupyter notebook

### ISSUE THREAD

**Issue by xiaohk** [kassambara/ggpubr#158]
I am using `rpy2` to embed `ggplot` plots in my Python Jupyter notebook. I am also using the function `ggarrange()` from `ggpubr` to concatenate multiple plots.

If I add the argument `common.legend` in `ggarrange()`, this R magic cell will display two images (one empty image and one output figure). The cell only displays one figure if `common.legend` is not included.

Here is a [demo][1] of this error.

  [1]: https://gist.github.com/xiaohk/501cfde0e0eb432dcb2cbddcbebf7a57

**Comment by Dorpolo** [comment]
Hey, I'm following up here to check if you have find any solution for this issue ?
Thanks!

**Comment by xiaohk** [comment]
@Dorpolo Unfortunately, nope :(

**Comment by kassambara** [comment]
Similar discussions have been posted on stackoerflow [here](https://stackoverflow.com/questions/47580839/can-i-assume-that-it-is-always-possible-to-open-a-pdf-null-device-in-r) and [here](https://stackoverflow.com/questions/17012518/why-does-this-r-ggplot2-code-bring-up-a-blank-display-device).


It should be possible to fix the problem by opening a null pdf device.

```{r}
p <- ggboxplot(ToothGrowth, "dose", "len", color = "supp") 
pdf(NULL)
res <- ggarrange(p,p)
x <- dev.off()
res
```

Let me know if this solution works on your computer

**Comment by kassambara** [comment]
fixed now, thanks
