### ISSUE TITLE
Possible to align when using facets?

### ISSUE THREAD

**Issue by stanstrup** [kassambara/ggpubr#16]
Hi,

I was wondering if it is possible to align when you have used facets in the plots. 
See my work in progress plot. I hope the intention is clear.

When I try:
```r
ggarrange(p1, p2, heights = c(2, 0.7), ncol = 1, nrow = 2, align = "v")
```

I get:
```r
Warning messages:
1: Removed 29 rows containing missing values (geom_errorbar). 
2: In align_plots(plotlist = plots, align = align) :
  Graphs cannot be vertically aligned. Placing graphs unaligned.
```

![image](https://user-images.githubusercontent.com/4532682/28772776-81e39ed8-75e7-11e7-9239-e0813b127969.png)

**Comment by kassambara** [comment]
Hi,

Vertical alignment is possible even in faceted plots.

The problem is that your p1 has legends on the right but not p2. So you can't align them vertically, because p1 has an additional legend column.

My suggestion would be to put the legend of p1 on the top: 

```r
ggarrange(p1 + theme(legend.position = "top"), p2, 
    heights = c(2, 0.7), ncol = 1, nrow = 2, align = "v")
```

Hope it works.

**Comment by stanstrup** [comment]
Fantastic! Thanks! That worked perfectly.
