### ISSUE TITLE
stat_compare_means across multiple groups

### ISSUE THREAD

**Issue by audyavar** [kassambara/ggpubr#162]
Is it possible to do stat_compare_means on a stacked barplot between 2-factor levels of genes (x-axis) vs 2-factor levels on y-axis? I want to compare the 2 green bars between WT and MUT. 

![image](https://user-images.githubusercontent.com/2364625/53681938-4667f800-3ca5-11e9-81c8-0f3d2f3f49e6.png)

**Comment by bznes** [comment]
I have this same question.  I tried to follow the methods here but I couldn't get it to work:
https://github.com/kassambara/ggpubr/issues/48#issue-272641556

I want to overlay p-values for a subset of comparisons ONLY to the treated data to a base plot that looks like this:

`ggbarplot(d=d, x = "Group",y="response",color="Treatment",add = "mean_se",position = position_dodge(0.8))`
![baseplot](https://user-images.githubusercontent.com/48456383/54160072-32926380-4414-11e9-9fe1-dc0dcc80d176.jpeg)

When I add stat_compare_means for the treated plot I get this:
`  my_comparisons=list(c("C1","C2"),
                      c("A","C2"),
                      c("C2","B"),
                      c("C2","D"),
                      c("D","E"),
                      c("D","F"))
  d.treated <- d[d$Treatment == "treated",]
  ggbarplot(d=d, x = "Group",y="response",color="Treatment",add = "mean_se",position = position_dodge(0.8))+
    stat_compare_means(d.treated,comparisons=my_comparisons)`

![baseplot_statcompare](https://user-images.githubusercontent.com/48456383/54160201-8b61fc00-4414-11e9-9042-ae373f09072b.jpeg)

However, this is ignoring use of the treated group for stat_compare_means.  When I run as facet I see the p-values I actually want displayed on the plot.  

`  ggbarplot(d=d, x = "Group",y="response",color="Treatment",facet.by="Treatment",add = "mean_se",position = position_dodge(0.8))+
    stat_compare_means(comparisons=my_comparisons)`
![baseplot with facet](https://user-images.githubusercontent.com/48456383/54160458-2d81e400-4415-11e9-850a-3c8e2d775f7e.jpeg)

Is it possible to get the data from the right panel on my first image?  Per the above solution I updated all my packages and it still is not working.  Can I overlay two ggbarplots like geom_line and geom_point in ggplot?  I haven't been able to get that to work.

Thanks!
My first time posting so apologies if I'm not following protocol!

**Comment by kassambara** [comment]
Solutions are now provided in this blog post: [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/) 

You need to install the latest dev version of rstatix and ggpubr:

```r
devtools::install_github("kassambara/rstatix")
devtools::install_github("kassambara/ggpubr")
```
