### ISSUE TITLE
Panel.labs.background fill color by variable

### ISSUE THREAD

**Issue by audyavar** [kassambara/ggpubr#163]
Hi - Is it possible to add a functionality to add colors by a factor to the background color of the faceted panels? I am trying to make multiple plots that are color coded by a variable for easy visualization. But no matter what I change in strip.text.background in facet_wrap OR panels.labs.background in facet(), I cannot color code it by factor. I even tried just giving it a separate column of specific colors, but it still doesn't color code the panel background. 

a_table <-
  dsub %>% melt(., id.vars = 1:18) %>% 
  group_by(DCB,variable,value) %>% tally() %>% data.frame() 
p1 <- ggplot(asub, aes(x=value, y=n, fill=DCB)) +           
       geom_bar(position="fill", stat="identity") +
       scale_fill_manual(values=c('red',"darkgreen")) +
       labs(x='',y='Percentage') + 
       theme(axis.text = element_text(size=12, face='bold'), 
        axis.title=element_text(size=16, face='bold'), 
        legend.position='bottom', strip.text = element_text(size=10, face='bold')) 
p1 + facet_wrap( ~ variable, nrow=6, ncol=10) 
facet(p1, facet.by="variable", panel.labs.background = list(fill = asub$color))

**Comment by lixin4306ren** [comment]
have the same issue.

**Comment by kassambara** [comment]
ggpubr has no function to support that. Workaround is presented at  https://github.com/tidyverse/ggplot2/issues/2096
