### ISSUE TITLE
meet some questions with this packages

### ISSUE THREAD

**Issue by xiaorenwu1111** [kassambara/ggpubr#167]
Hello,
I met some questions when used this packages.Could you help me?
This is my code：

library(ggpubr)
ggboxplot(
  distance, x="Group", y="Distance",
  add = "mean_se",
  facet.by = "Method"
) +
  stat_compare_means(
    comparisons = list(c("A", "B"), c("B", "C"),  c("C", "D")),
    label = "p.signif"
  )

This is my data structures:
Group	Distance	Method
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
A 	0	Hamming distance
B 	162	Hamming distance
B 	151	Hamming distance
B 	90	Hamming distance
B 	150	Hamming distance
B 	131	Hamming distance
B 	107	Hamming distance
B 	145	Hamming distance
B 	87	Hamming distance
B 	103	Hamming distance
B 	96	Hamming distance
B 	114	Hamming distance
B 	102	Hamming distance
B 	103	Hamming distance
B 	91	Hamming distance
B 	71	Hamming distance
B 	77	Hamming distance
B 	77	Hamming distance
B 	67	Hamming distance
B 	40	Hamming distance
C 	179	Hamming distance
C 	167	Hamming distance
C 	109	Hamming distance
C 	152	Hamming distance
C 	152	Hamming distance
C 	152	Hamming distance
C 	152	Hamming distance
C 	152	Hamming distance
C 	152	Hamming distance
C 	152	Hamming distance
C 	129	Hamming distance
C 	89	Hamming distance
C 	86	Hamming distance
C 	109	Hamming distance
C 	86	Hamming distance
C 	93	Hamming distance
C 	89	Hamming distance
C 	80	Hamming distance
C 	55	Hamming distance
D 	275	Hamming distance
D 	250	Hamming distance
D 	193	Hamming distance
D 	241	Hamming distance
D 	235	Hamming distance
D 	186	Hamming distance
D 	240	Hamming distance
D 	174	Hamming distance
D 	183	Hamming distance
D 	193	Hamming distance
D 	171	Hamming distance
D 	182	Hamming distance
D 	169	Hamming distance
D 	159	Hamming distance
D 	141	Hamming distance
D 	131	Hamming distance
D 	122	Hamming distance
D 	111	Hamming distance
D 	94	Hamming distance

I want to draw a picture like this:
![42407858-33b43f68-81c3-11e8-8668-67c916b007d3](https://user-images.githubusercontent.com/35647271/55275287-02592900-531f-11e9-949f-fcf4a7897f6c.png)

But I used above data and code can't get similar picture.
![Rplot03](https://user-images.githubusercontent.com/35647271/55275279-dfc71000-531e-11e9-8b3e-6ac64ced61c3.png)

And I got some warning messages:
Warning messages:
1: Computation failed in `stat_signif()`:
missing value where TRUE/FALSE needed 
2: Computation failed in `stat_signif()`:
missing value where TRUE/FALSE needed 
3: Computation failed in `stat_signif()`:
missing value where TRUE/FALSE needed 

Could you help me ? Thank you !

**Comment by atakanekiz** [comment]
Try to see if the answer here helps. #65

**Comment by kassambara** [comment]
It works for me.  Please reinstall `ggsignif` package, then the latest dev version of ggpubr;

```r
library(ggpubr)
# Data
distance <- structure(list(Group = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 3L, 
3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
3L, 3L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 4L, 
4L, 4L, 4L, 4L, 4L), .Label = c("A", "B", "C", "D"), class = "factor"), 
    Distance = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 162L, 151L, 90L, 150L, 131L, 
    107L, 145L, 87L, 103L, 96L, 114L, 102L, 103L, 91L, 71L, 77L, 
    77L, 67L, 40L, 179L, 167L, 109L, 152L, 152L, 152L, 152L, 
    152L, 152L, 152L, 129L, 89L, 86L, 109L, 86L, 93L, 89L, 80L, 
    55L, 275L, 250L, 193L, 241L, 235L, 186L, 240L, 174L, 183L, 
    193L, 171L, 182L, 169L, 159L, 141L, 131L, 122L, 111L, 94L
    ), Method = structure(c(2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
    2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 
    2L, 2L, 2L, 2L, 2L, 2L, 2L), .Label = c("Euclidean distance", 
    "Hamming distance"), class = "factor")), .Names = c("Group", 
"Distance", "Method"), class = "data.frame", row.names = c(NA, 
-76L))

# Plot
ggboxplot(
  distance, x="Group", y="Distance",
  add = "mean_se",
  facet.by = "Method"
) +
  stat_compare_means(
    comparisons = list(c("A", "B"), c("B", "C"), c("C", "D")),
    label = "p.signif"
  )
```

![Rplot](https://user-images.githubusercontent.com/3313355/58616155-39b36a00-82bd-11e9-9149-a7f5668eda55.png)
