### ISSUE TITLE
How to add comparissons between treatments for heach gene expression in the same plot? ggboxplot

### ISSUE THREAD

**Issue by bioemprendiendo** [kassambara/ggpubr#169]
I want to add p-value and brackets for each gene (GATA3, PTEN, XBP1) but comparing BRCA to OV and BRCA to LUSC for each gene like this:

This is for one gene

`my_comparisons <- list(c("BRCA", "OV"), c("OV", "LUSC"))`
`ggboxplot(expr, x = "dataset", y = "GATA3",
          title = "GATA3", ylab = "Expression",
          color = "dataset", palette = "jco")+
  stat_compare_means(comparisons = my_comparisons)`

![image](https://user-images.githubusercontent.com/43187599/55508942-d20bd600-560f-11e9-8f0d-a293f8f2fbd4.png)

But i want to plot each group (Gene) in the same plot but adding p value for each treatment comparisson, something like:

GATA3 comparing BRCA to OV and BRCA to LUSC with their respecting p value
PTEN comparing BRCA to OV and BRCA to LUSC with their respecting p value
XBP1 comparing BRCA to OV and BRCA to LUSC with their respecting p value

`ggboxplot(expr, x = "dataset",
          y = c("GATA3", "PTEN", "XBP1"),
          merge = "flip",
          ylab = "Expression", 
          palette = "jco")`

![image](https://user-images.githubusercontent.com/43187599/55509035-02537480-5610-11e9-97a2-a0d8529c4e0f.png)

thank you

**Comment by llrs** [comment]
I have the same problem/wish. Maybe it can be solved by using nested lists? But they should only look at other variables used in aes?

**Comment by Adam-JJJJJ** [comment]
I have the same problem in the dodge barplot. I can calculate the significants respectively, and add the results by stat_pvalue_manual .However,the significant labels of two groups was stacked in the middle column and i had tried position=position_dodge(0.9) .It didn't seem to work.

**Comment by kassambara** [comment]
For each gene you want to perform pairwise comparisons against reference group.

Concerning dodged barplot see #104 

Possible solutions with box plots:  
  
```r
df <- ToothGrowth
df$dose <- as.factor(df$dose)
# t - test
library(rstatix)  # https://github.com/kassambara/rstatix
stat.test <- df %>%
  group_by(supp) %>%
  t_test(len ~ dose, ref.group = "0.5") %>%
  adjust_pvalue() %>%
  add_significance("p.adj")
stat.test


# Plot
bp <- ggboxplot(df, x = "supp", y = "len",
                fill = "dose") 
bp
# Add pvalue
bp + stat_pvalue_manual(
  stat.test, x = "supp", y.position = 35,
  label = "p.adj.signif",
  position = position_dodge(0.8)
)
```

![Rplot](https://user-images.githubusercontent.com/3313355/58777988-147e6e80-85d1-11e9-9e0f-37f82bd80061.png)
