### ISSUE TITLE
Remove outlier from ggstripchart

### ISSUE THREAD

**Issue by shathab** [kassambara/ggpubr#174]
Hello, 

Would it be possible to remove outliers from the "ggstripchart". I tried using outlier.shape=NA but I get the error message:
Warning: Ignoring unknown parameters: outlier.shape

Thank you for your help!

**Comment by kassambara** [comment]
I would suggest to use `ggboxplot()` as follow:  

```r
ggboxplot(PlantGrowth, x = "group", y = "weight", 
          outlier.shape = NA, add = "jitter")
````
