### ISSUE TITLE
Set different color in add.param: ggbarplot

### ISSUE THREAD

**Issue by tamacou** [kassambara/ggpubr#175]
Hi,
I would like to make barplot containing mean +/- se with jitter by ggbarplot.
```
ggbarplot(iris, x ="Species", y = "Petal.Length", add = c("mean_se","jitter"),
          color = "black", fill = "Species", palette = "npg",
          add.params = list(group = "Species"), legend = "none")
```
![Rplot](https://user-images.githubusercontent.com/43286916/56399718-c284c200-628a-11e9-98ea-fd976a4978c4.jpeg)

Then, I would like to change jitter point size and color without changing the error bar, but I cannot do it. Is there any good way?

**Comment by kassambara** [comment]
I would go as follow:

``` r
suppressPackageStartupMessages(library(ggpubr))
ggbarplot(iris, x ="Species", y = "Petal.Length", add = c("mean_se"),
          color = "black", fill = "Species", palette = "npg",
          add.params = list(group = "Species"), legend = "none")+
  geom_jitter(color = "darkgray", width = 0.2)
```

![](https://i.imgur.com/kUSNvNt.png)

<sup>Created on 2020-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by srj-io** [comment]
ggboxplot(
  data = subset(final_cibersortx_data, gene == "B.cells.naive"),
  x = "Subtype",
  y = "Cibersortx_Score",
  color = "Subtype",
  palette = subtype_colors,
  xlab = "Histological Subtypes",
  ylab = "B cells naive", add = "jitter", 
) + stat_compare_means(method = "kruskal.test", label.x = 3, label.y = 0.55)
[Rplot.pdf](https://github.com/kassambara/ggpubr/files/14094191/Rplot.pdf)

How to color the jitter for each subtype based on the location column.  In location column, I have 3 location for each subtypes.
