### ISSUE TITLE
Add vertical or horizontal line to a ggscatterhist

### ISSUE THREAD

**Issue by juliechevalier** [kassambara/ggpubr#176]
I'd like to add a vertical and an horizontal line to my ggscatterhist.  But the ggadd seems to not run properly with ggscatterhist, as I've tested it to add a point without any success.
So, is there a way to add such line to my plot where the code is :
```
ggscatterhist(
  dfScatter, x = "SpeIndex", y = "BindingSignal",
  color = colors, size = 1, alpha = 1,
  palette = c("blue", "grey"),
  margin.plot="boxplot"
  )
```
I'd want to add a vertical line at a specific point of my xaxis through all the plot.
Thanks in advance for your help
Julie

**Comment by wenbostar** [comment]
Does ggpubr support this function?

**Comment by wenbostar** [comment]
@juliechevalier, I updated ggscatterhist to support this function. You can find the version here: https://github.com/wenbostar/ggpubr/blob/master/R/ggscatterhist.R.

**Comment by juliechevalier** [comment]
Thanks ! It will be very helpful.

**Comment by kassambara** [comment]
The following enhancement required:

1. the output of `ggscatterhist()` should be a list of ggplots, containing the main scatter plot and the marginal plots, which can be customized by the end user using the standard ggplot verbs
2. writing a S3 printing method for an object of class ggscatterhist. The printing method should display the arranged final figure

```r
# returns a list of plots which can be modified
plots <- ggscaterhist()
# Display the arranged ggscatterhist
plots
 ```

**Comment by kassambara** [comment]
fixed now, thanks!

``` r
library(ggpubr)

# Add vertical and horizontal line to a ggscatterhist
plots <- ggscatterhist(iris, x = "Sepal.Length", y = "Sepal.Width", print = FALSE)
plots$sp <- plots$sp + 
  geom_hline(yintercept = 3, linetype = "dashed", color = "blue") +
  geom_vline(xintercept = 6, linetype = "dashed", color = "red")
plots
```

![](https://i.imgur.com/RA7eLYY.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by DanielIAvila** [comment]
This is not longer working.

**Comment by LuisEnriqueAngelesGonzalez** [comment]
It is now.

**Comment by DanielIAvila** [comment]
Now, it is not working. First, it is not possible to select `xxplot$sp`, `$sp`seems to not exist.
