### ISSUE TITLE
How to add a jitter to ggdotplot?

### ISSUE THREAD

**Issue by Adam-JJJJJ** [kassambara/ggpubr#178]
When i used the geom_dotplot  function in ggplot2, i can made the dot be jitter by position = "jitter". However, in ggdotplot, when i tried to use the parameter of add.params=list(position="jitter”), dot just separated from the error bar. May i ask that what's wrong with my codes? 
![image](https://user-images.githubusercontent.com/45379515/57934273-e838d180-78f1-11e9-9600-fed725e2ef72.png)
The picture below is what I want. THANKS.
![image](https://user-images.githubusercontent.com/45379515/57934583-9ba1c600-78f2-11e9-8e03-3e240c17b6c2.png)

`ggplot(a1, aes(x = Treatment, y = Value)) +geom_dotplot(binaxis = "y", stackdir = "centerwhole",stackratio=0.5,position = "jitter")`

 `ggdotplot(a1, x = "Treatment", y = "Value",
          fill = "Treatment",
          palette = c("#0AFAC8", "#CD0000", "#5A9AD5"),
          binwidth = 0.3,add.params = list(position = "jitter"),add = c("mean_se"))+
  stat_compare_means(comparisons = my_comparisons1,
                     paired = FALSE,method = "t.test",
                     method.args = list(var.equal=TRUE),label = "p.signif")+
  ylab("Relative expression level")+xlab("")`

**Comment by kassambara** [comment]
The argument `position` is now handled by `ggdotplot()`. Please install the latest developmental version and try this:

```r
library(ggpubr)
ggdotplot(ToothGrowth, x = "dose", y = "len", add = "mean_sd", 
          fill = "dose", position = position_jitter(0.1))
```
![Rplot](https://user-images.githubusercontent.com/3313355/58515125-2cef2300-81a4-11e9-8dbb-1958c07bc81e.png)

**Comment by Adam-JJJJJ** [comment]
> The argument `position` is now handled by `ggdotplot()`. Please install the latest developmental version and try this:
> 
> ```r
> library(ggpubr)
> ggdotplot(ToothGrowth, x = "dose", y = "len", add = "mean_sd", 
>           fill = "dose", position = position_jitter(0.1))
> ```
> 
> ![Rplot](https://user-images.githubusercontent.com/3313355/58515125-2cef2300-81a4-11e9-8dbb-1958c07bc81e.png)

Thank ur codes very much. But i still have another question ,please.
https://github.com/kassambara/ggpubr/issues/104#issuecomment-495976181
