### ISSUE TITLE
stat_compare_means and coord_flip()

### ISSUE THREAD

**Issue by Nasimst** [kassambara/ggpubr#179]
Hi,

I need to change the angle of stat_compare_means p-value label to be vertical and in harmony with my flipped boxplot. I tried lots of things, so I was wondering whether you can help me with it.

`p1 <- ggplot(a, aes(Diagnosis, Axis.1, fill=Diagnosis))
p11<-p1 + geom_boxplot() + stat_compare_means(method = "wilcox.test", p.adjust.method = "bonferroni",comparisons = my_comparisons)+ coord_flip()`

Thanks

**Comment by LuffyLuffy** [comment]
the p value and its line would not change correctly with coord_flip

**Comment by tcyle14** [comment]
I'm having this same issue. If I run the above code chunk with coord_flip = TRUE, I still have the asterisks above the bracket. I'm running on a mac, R version 3.6.3. 

suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(rstatix))

# Transform `dose` into factor variable
df <- ToothGrowth
df$dose <- as.factor(df$dose)
stat.test <- df %>% t_test(len ~ dose)
stat.test
#> # A tibble: 3 x 10
#>   .y.   group1 group2    n1    n2 statistic    df        p    p.adj p.adj.signif
#> * <chr> <chr>  <chr>  <int> <int>     <dbl> <dbl>    <dbl>    <dbl> <chr>       
#> 1 len   0.5    1         20    20     -6.48  38.0 1.27e- 7 2.54e- 7 ****        
#> 2 len   0.5    2         20    20    -11.8   36.9 4.40e-14 1.32e-13 ****        
#> 3 len   1      2         20    20     -4.90  37.1 1.91e- 5 1.91e- 5 ****
# Box plot
bxp <- ggboxplot(df, x = "dose", y = "len", fill = "dose", 
                 palette = c("#00AFBB", "#E7B800", "#FC4E07"))
# Add pvalues
stat.test <- stat.test %>% add_y_position()
bxp + stat_pvalue_manual(
  stat.test, label = "p.adj.signif", tip.length = 0.01,
  coord.flip = TRUE
) +
  coord_flip()


![image](https://user-images.githubusercontent.com/6620682/85626918-bee18d80-b63b-11ea-9617-5e9bfaae3a49.png)

**Comment by kassambara** [comment]
Provide your session infos please and make sure you have the latest dev version: devtools::install_github("kassambara/ggpubr")

**Comment by tcyle14** [comment]
That seemed to solve the problem. My bad. Thanks for your quick response!
