### ISSUE TITLE
Support text justification in ggtexttable

### ISSUE THREAD

**Issue by cj-wilson** [kassambara/ggpubr#18]
I would like to support text justification in ggtexttable such that I can align financial data better.  I noticed that tableGrob supports an "hjust" parameter (below) but I'm not able to find a way to pass that in to the ggtexttable function.  

https://cran.r-project.org/web/packages/gridExtra/vignettes/tableGrob.html

Great package!  If I knew were to plug this in I'd offer a PR.  Thank you.

**Comment by kassambara** [comment]
Support for text justification added now, thank you.

This has been added in the documentation of `ggtexttable()`:

```r
# Text justification
#::::::::::::::::::::::::::::::::::::::::::::::
# Default is "centre" for the body and header, and "right" for the row names. 
# Left justification: hjust=0, x=0.1
# Right justification: hjust=1, x=0.9

ggtexttable(head(iris), rows = NULL,
            theme = ttheme(
              colnames.style = colnames_style(color = "white", fill = "#8cc257"),
              tbody.style = tbody_style(color = "black", fill = c("#e8f3de", "#d3e8bb"), hjust=1, x=0.9)
            )
)
```

**Comment by kassambara** [comment]
can we close this issue?

**Comment by kurttaylor** [comment]
Is it possible to justify text in certain columns/rows?
