### ISSUE TITLE
Freezing upon encountering a plotting error

### ISSUE THREAD

**Issue by atakanekiz** [kassambara/ggpubr#180]
Hello,

Thanks for this great package. It makes plotting and making reports a breeze.

I have experienced an issue when I try to plot a big data frame and make a mistake in the code to generate the plot. I figure out why the code fails, and that's not the problem. However, while `ggpubr` is throwing an error explaining the mistake, it seems like it is still doing something in the background which freezes the RStudio session for some time.

I tried this with smaller data frames and it is not a problem then. But when you have hundreds of columns and thousands of rows it becomes a problem. Please see my reprex below. Any ideas how to prevent data processing when there is an error so it fails fast?

Best,
Atakan

``` r
library(ggpubr)
#> Loading required package: ggplot2
#> Loading required package: magrittr

set.seed(100)

dat_rows <- 25000
dat_cols <- 900
data_points <- dat_rows * dat_cols

test_dat <- data.frame(matrix(rnorm(data_points), 
                              nrow = dat_rows,
                              ncol = dat_cols))

test_dat$category <- sample(LETTERS, dat_rows, replace = T)


# This works
ggscatter(test_dat, x="X1", y="X2", color="category", legend="none")
```

![](https://i.imgur.com/4kU2ZrX.png)

``` r


## This fails and freezes the RStudio session for some time
# ggscatter(test_dat, x="X1", y="X2", color="category", legend="none", add="segment")
# > Error in match.arg(add) : 
# >  'arg' should be one of “none”, “reg.line”, “loess”
```

<sup>Created on 2019-05-24 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kassambara** [comment]
fixed now, thanks
