### ISSUE TITLE
Error bars not working for grouped barplots and faceted bar plots

### ISSUE THREAD

**Issue by gmguriarte** [kassambara/ggpubr#181]
Hello, I'm having some issues with error bars when plotting with ggbarplot using groups and/or facets. Any ideas? Thank you!

![image](https://user-images.githubusercontent.com/20975884/58345148-8ce47300-7e0c-11e9-8833-62ac359de23d.png)

![image](https://user-images.githubusercontent.com/20975884/58345200-a5ed2400-7e0c-11e9-9d3a-72c13c968885.png)

![image](https://user-images.githubusercontent.com/20975884/58345107-7211fe80-7e0c-11e9-86ca-d4a3d276571f.png)

```R
df <- read.csv("dataframe.csv", header=TRUE)
ggbarplot(df, x=x, y=y,merge=TRUE, add="mean_se", error.plot = "errorbar", ggtheme = theme_bw()) +
ggtitle("test") + labs(x="test", y="test") + 
scale_fill_jco() + 
facet_grid(x~y, scales="fixed") +
stat_compare_means(label = "p.signif", method = "t.test", ref.group = ".all.", label.y.npc = "top") +
theme(plot.title=element_text(size = 14, face = "bold", hjust = 0.5),
        axis.title.x = element_text(face="bold"),
        axis.title.y = element_text(face="bold"),
        axis.text.x = element_text(angle = 70, hjust = 1, colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10))
```

**Comment by kassambara** [comment]
Provide your session infos please with reproducible example if possible 

Thanks

**Comment by gmguriarte** [comment]
You should be able to reproduce everything with the below. The code I was using to degenerate the plots is in the original post at the bottom.

Here's an edited version of the df I'm using:

https://docs.google.com/spreadsheets/d/1ubQYrVoR6n5LyBh9v5UqHyGYcP5oOYgYlQHkcgHUhmA/edit?usp=sharing

Here's the session info: 

`R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                  LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8        LC_MONETARY=en_US.UTF-8      
 [6] LC_MESSAGES=en_US.UTF-8       LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8           LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
[11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] factoextra_1.0.5        FactoMineR_1.41         plotly_4.9.0            ggthemes_4.0.1          shinycustomloader_0.9.0 shinydashboard_0.7.1   
 [7] stringr_1.4.0           dplyr_0.7.6             ggpubr_0.2.999          magrittr_1.5            ggplot2_3.1.1           XLConnect_0.2-15       
[13] XLConnectJars_0.2-15    readxl_1.1.0            purrr_0.3.2             reshape2_1.4.3          shiny_1.3.1            

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5     rJava_0.9-9          lattice_0.20-38      colorspace_1.4-1     htmltools_0.3.6      viridisLite_0.3.0    rlang_0.3.4         
 [8] later_0.8.0          pillar_1.3.1         glue_1.3.1           withr_2.1.2          bindrcpp_0.2.2       bindr_0.1.1          plyr_1.8.4          
[15] munsell_0.5.0        gtable_0.3.0         cellranger_1.1.0     htmlwidgets_1.3      leaps_3.0            httpuv_1.5.1         Rcpp_1.0.1          
[22] xtable_1.8-3         flashClust_1.01-2    promises_1.0.1       scales_1.0.0         scatterplot3d_0.3-41 jsonlite_1.6         mime_0.6            
[29] digest_0.6.18        stringi_1.4.3        ggrepel_0.8.0        grid_3.4.4           tools_3.4.4          lazyeval_0.2.2       tibble_2.1.1        
[36] cluster_2.0.7-1      crayon_1.3.4         tidyr_0.8.3          pkgconfig_2.0.2      MASS_7.3-51.3        data.table_1.12.2    assertthat_0.2.1    
[43] httr_1.4.0           rstudioapi_0.10      R6_2.4.0             compiler_3.4.4      `

**Comment by kassambara** [comment]
Hi,

Specifying the `facet.by` argument in `ggbarplot()` should work: 

```r
library(ggpubr)
ggbarplot(ToothGrowth, x = "dose", y = "len", add = "mean_se", facet.by = c("supp", "dose") )
```

![Rplot](https://user-images.githubusercontent.com/3313355/58511853-f9a89600-819b-11e9-8660-57caf8332ae8.png)

**Comment by gmguriarte** [comment]
I see. Write now this code is working within the context of a Shiny app. This is a bit more muddy, but this is the actual implementation within Shiny

```R
      plot <- ggbarplot(df, x=input$xaxisBar, y = input$yaxisBar, fill=input$fillBar, merge=TRUE, add="mean_se", error.plot = "errorbar", alpha=0.3, ggtheme = theme_bw()) +
        ggtitle(input$titleBar) + labs(x=input$xlabelBar, y=input$ylabelBar) +           
        {if(!(input$colorBar)) scale_fill_grey()} +
        {if((input$colorBar)) scale_fill_jco()} +
        {if(input$statGroupBar) stat_compare_means(label.x = 1.3,  label.y.npc = "top")} +
        {if(input$statPairBar) stat_compare_means(label = "p.signif", method = "t.test", ref.group = ".all.", label.y.npc = "top")}  +
        {if(input$yFacetBarSelect) facet_grid(as.formula(paste(input$yfacetBar, "~", ".")), scales="fixed")} +
        {if(input$xFacetBarSelect) facet_grid(as.formula(paste("~", input$xfacetBar)), scales="fixed")} +
        {if(input$facetBar) facet_grid(as.formula(paste(input$yfacetBar, "~", input$xfacetBar)), scales="fixed")} +
        theme(plot.title=element_text(size = 14, face = "bold", hjust = 0.5),
              axis.title.x = element_text(face="bold"),
              axis.title.y = element_text(face="bold"),
              axis.text.x = element_text(angle = 70, hjust = 1, colour="black", size = 10),
              axis.text.y=element_text(colour="black", size = 10))
      
      plot
```

Faceting this way seems to work for ggboxplot

```R
        plot <- ggboxplot(df, x=input$xaxisBox, y = input$yaxisBox, fill=input$fillBox, alpha=0.3, add="jitter", ggtheme = theme_bw()) +
          ggtitle(input$titleBox) + labs(x=input$xaxisBox, y=input$yaxisBox) +
          {if(!(input$color)) scale_fill_grey()} +
          {if((input$color)) scale_fill_jco()} +
          {if(input$statGroupBox) stat_compare_means(label.x = 1.3,  label.y.npc = "top")} +
          {if(input$statPairBox) stat_compare_means(label = "p.signif", method = "t.test", ref.group = ".all.", label.y.npc = "top")}  +
          {if(input$jitter) geom_jitter()} +
          {if(input$yFacetBoxSelect) facet_grid(as.formula(paste(input$yfacetBox, "~", ".")), scales="fixed")} +
          {if(input$xFacetBoxSelect) facet_grid(as.formula(paste("~", input$xfacetBox)), scales="fixed")} +
          {if(input$facet) facet_grid(as.formula(paste(input$yfacetBox, "~", input$xfacetBox)), scales="fixed")} +
          theme(plot.title=element_text(size = 14, face = "bold", hjust = 0.5),
                axis.title.x = element_text(face="bold"),
                axis.title.y = element_text(face="bold"),
                axis.text.x = element_text(angle = 70, hjust = 1, colour="black", size = 10),
                axis.text.y=element_text(colour="black", size = 10))
```

**Comment by kassambara** [comment]
Error bars are computed by grouping variables inside ggbarplot().

In the current version, the only possibility to take into account the facet grouping variables, when computing error bars, is to specify the argument `facet.by`

The code below should work:

```r
facet.by <- NULL
if(input$yFacetBarSelect | input$xFacetBarSelect) 
  facet.by <- unique(c(input$yFacetBarSelect, input$xFacetBarSelect))
else if(input$facetBar) 
  facet.by <- unique(c(input$yfacetBar, input$xfacetBar))

plot <- ggbarplot(df, x=input$xaxisBar, y = input$yaxisBar, fill=input$fillBar, merge=TRUE, 
                  add="mean_se", error.plot = "errorbar", alpha=0.3, ggtheme = theme_bw(),
                  facet.by = facet.by
                  ) +
  ggtitle(input$titleBar) + labs(x=input$xlabelBar, y=input$ylabelBar) +           
  {if(!(input$colorBar)) scale_fill_grey()} +
  {if((input$colorBar)) scale_fill_jco()} +
  {if(input$statGroupBar) stat_compare_means(label.x = 1.3,  label.y.npc = "top")} +
  {if(input$statPairBar) stat_compare_means(label = "p.signif", method = "t.test", ref.group = ".all.", label.y.npc = "top")}  +
  theme(plot.title=element_text(size = 14, face = "bold", hjust = 0.5),
        axis.title.x = element_text(face="bold"),
        axis.title.y = element_text(face="bold"),
        axis.text.x = element_text(angle = 70, hjust = 1, colour="black", size = 10),
        axis.text.y=element_text(colour="black", size = 10))
```

**Comment by gmguriarte** [comment]
Works brilliantly, thank you so much!

**Comment by gmguriarte** [comment]
Thank you so much! It works well for faceting, unfortunately grouped plots still seems to not work.

![image](https://user-images.githubusercontent.com/20975884/58563566-41511100-81e0-11e9-9187-937c375220b9.png)

![image](https://user-images.githubusercontent.com/20975884/58563597-49a94c00-81e0-11e9-8ed0-4d3660087171.png)

![image](https://user-images.githubusercontent.com/20975884/58563616-50d05a00-81e0-11e9-8d27-49433976b194.png)

**Comment by kassambara** [comment]
Hi, 

You are using a grouping variable to change the fill color of your bar plots.  

Please specify this variable in the argument `add.params`,  as illustrated below, so that error bars are created by groups. Let me know if it works: 

```r
library(ggpubr)
df <- ToothGrowth
df$dose <- as.factor(df$dose)
bp <- ggbarplot(df, x = "supp", y = "len",
          fill = "dose",
          add = "mean_sd",  add.params = list(group = "dose"),
          position = position_dodge(0.8)) 
```

![Rplot](https://user-images.githubusercontent.com/3313355/58580229-e6093800-824c-11e9-8341-0b42720f94ac.png)
