### ISSUE TITLE
how to add pair wise p value in alpha diversity to show the significant differences

### ISSUE THREAD

**Issue by yogeshgupt** [kassambara/ggpubr#184]
Hi,

I do have three treatment condition and used below code with ggplot to add p-value, but it added one global pvalue, could you please suggest how I can add p value for pairwise comparisons.

plot_richness(mymensingh_all_NO_ARCHEA,x="Group",color="Group",measures=c("observed","Chao1","Shannon", "Simpson")) + theme(axis.text.y=element_text(angle=90,hjust=0.5))+theme(axis.text.x=element_text(angle=90,hjust=0.5)) +geom_boxplot()+stat_compare_means(method = "kruskal.test")

**Comment by kassambara** [comment]
Your example is not reproducible.

Documentation is available at: https://rpkgs.datanovia.com/ggpubr/reference/stat_compare_means.html f
