### ISSUE TITLE
Report p-values as <0.001 (or similar)

### ISSUE THREAD

**Issue by garthtarr** [kassambara/ggpubr#186]
It would be great to have an option to report small p-values at some arbitrary threshold, e.g. "p < 0.001" or "p < 0.0001" . Looks like some efforts along this path exist in `stat_cor()` but it is hardcoded and at machine level precision.

I'm thinking that instead of this:

```r
ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line") +
  stat_cor(
    aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")),
    label.x = 3
  )
```

You might be able to implement something like this:

```r
ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line") +
  stat_cor(
    aes(label = paste(..rr.label.., ..p.rounded.., sep = "~`,`~")),
    label.x = 3, accuracy = 0.001
  )
```

where `accuracy` defines how far the p-value rounding went, much like the `pvalue_format()` function from the **scales** package does.  I.e.

```r
p.vals = c(0.123, 0.015, 0.0015, 0.00015, 1e-10)
accuracy = 0.01
scales::pvalue(p.vals, accuracy = accuracy, add_p = TRUE)
# [1] "p=0.12" "p=0.02" "p<0.01" "p<0.01" "p<0.01"
accuracy = 0.001
scales::pvalue(p.vals, accuracy = accuracy, add_p = TRUE)
# [1] "p=0.123" "p=0.015" "p=0.002" "p<0.001" "p<0.001"
```

I note that you've used spaces around the `=` and `<` in the **ggpubr** package, so that could be added back in:

```r
p.vals = c(0.123, 0.015, 0.0015, 0.00015, 1e-10)
accuracy = 0.01
pfmt = scales::pvalue(p.vals, accuracy = accuracy, add_p = TRUE)
gsub(pattern = "(=|<)", replacement = " \\1 ", x = pfmt)
# [1] "p = 0.123" "p = 0.015" "p = 0.002" "p < 0.001" "p < 0.001"
```

**Comment by kassambara** [comment]
good idea and thank you for the well documented examples. I will implement this as soon as possible

**Comment by kassambara** [comment]
Hi,

With the current version, you can pass  any pvalue formatting function you want to `stat_cor()`.

For example:

```r
# Custom formatting fucntion
format_pval <- function(pval){
  pval <- scales::pvalue(pval, accuracy= 0.0001, add_p = TRUE)
  gsub(pattern = "(=|<)", replacement = " \\1 ", x = pval)
}
# Display formatted p-value
ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line") +
  stat_cor(
    aes(label = paste(..rr.label.., format_pval(..p..), sep = "~`,`~")),
    label.x = 3
  )
```

![Rplot13](https://user-images.githubusercontent.com/3313355/59939785-3729d780-9459-11e9-802b-2886c27472b7.png)

**Comment by garthtarr** [comment]
Thanks!

**Comment by cigan77** [comment]
Is it possible to avoid the space between the R2 value and comma?

**Comment by garthtarr** [comment]
You can use `*` in place of `~` to prevent a space being generated:

```
library(ggpubr)
# Custom formatting fucntion
format_pval <- function(pval){
  pval <- scales::pvalue(pval, accuracy= 0.0001, add_p = TRUE)
  gsub(pattern = "(=|<)", replacement = " \\1 ", x = pval)
}
# Display formatted p-value
ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line") +
  stat_cor(
    aes(label = paste(..rr.label.., "*`,`~", format_pval(..p..))),
    label.x = 3,
    label.sep = ", "
  )
```

**Comment by kassambara** [comment]
With the latest dev version, you can now specify the argument `p.accuracy` and `r.accuracy`:

``` r
suppressPackageStartupMessages(library(ggpubr))
# Default plot
sp <- ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line")
sp + stat_cor(label.x = 3)
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/5hSqJm5.png)

``` r
# Specify the number of decimal places of precision for 
# the p-value and the correlation coefficient r
sp + stat_cor(label.x = 3, p.accuracy = 0.001, r.accuracy = 0.01)
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/VjDvFyW.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by johannesjuliusm** [comment]
This is fantastic, but is it true that this functionality is not available for stat_compare_means()? It would be fantastic to be able to do the same p-value formatting throughout statistical tests and procedures in ggpubr.

**Comment by dchiu911** [comment]
Any updates on adding `p.accuracy` to `stat_compare_means()`?
