### ISSUE TITLE
Exclude p-values from stat_cor() function

### ISSUE THREAD

**Issue by EugenioGrant** [kassambara/ggpubr#188]
Not clear from the documentation but is it possible to show ONLY R values when using the stat_corr() function and exclude p-values.

**Comment by kassambara** [comment]
yes, it is possible:

```r
library(ggpubr)
ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line") +
  stat_cor(aes(label = ..r.label..),  label.x = 3)
```

![Rplot](https://user-images.githubusercontent.com/3313355/59486056-541e4380-8e78-11e9-9325-e9a3b64928c1.png)

**Comment by givison** [comment]
This doesn't seem to be working for me...

![image](https://user-images.githubusercontent.com/6775088/75219153-df164400-5750-11ea-98b3-b45eb3bcf158.png)

![image](https://user-images.githubusercontent.com/6775088/75219192-fb19e580-5750-11ea-840b-3d4babdcf1c9.png)

**Comment by givison** [comment]
Tried it again with a cleaner session, still having this issue 
![image](https://user-images.githubusercontent.com/6775088/75219343-5e0b7c80-5751-11ea-945f-ef4ed53b065c.png)

![image](https://user-images.githubusercontent.com/6775088/75219370-6ebbf280-5751-11ea-991a-d8e2873be73c.png)

**Comment by kassambara** [comment]
fixed now, thanks
