### ISSUE TITLE
Strange behaviour when faceting

### ISSUE THREAD

**Issue by stevedempseybis** [kassambara/ggpubr#192]
This code
```
library(tidyverse)
library(ggpubr)
mtcars %>% 
  gather(var,value) %>% 
  ggpubr::gghistogram('value',facet.by = 'var',scales='free_x',add='mean')
```
leads to this strange result:
![bad_graph](https://user-images.githubusercontent.com/17702163/60337987-734ec200-999c-11e9-87f3-ad0dbfabf48a.png)

It can be remedied by replacing `var` with`vari`. This leads to the expected outcome:
![graph](https://user-images.githubusercontent.com/17702163/60338047-adb85f00-999c-11e9-9611-47838a900896.png)

**Comment by kassambara** [comment]
gghistogram computes internally some descriptive statistics before adding the mean line. These descriptive stats include mean, iqr, sd, var, cv, median, se.

Using any of these key words as x variable, will give the same behavior when add = "mean" or add = "median". 

We'll  fix this

**Comment by kassambara** [comment]
fixed now thanks
