### ISSUE TITLE
Adding "p = ...." to comparison in stat_compare_means

### ISSUE THREAD

**Issue by nickhir** [kassambara/ggpubr#194]
This code doesnt add the simple "p = "
`data("ToothGrowth")
df <- ToothGrowth

p<-ggboxplot(df, x = "dose", y = "len", width = 0.8)
my_comp = list(c("0.5","1"),c("2","1"))
p+stat_compare_means(comparisons = my_comp, aes (labels = paste0 ("p =",..p.format..)))`

Am I using it wrong or is this just not supported?

**Comment by kassambara** [comment]
Using the rstatix and ggpubr packages should fix this issue.   Many examples are provided in the following blog posts:

- [How to Add P-Values onto Basic GGPLOTS](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-basic-ggplots/)
- [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/)
- [How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)
