### ISSUE TITLE
baseMean in ggmaplot is not real A

### ISSUE THREAD

**Issue by QiangShiPKU** [kassambara/ggpubr#198]
Hi, I noticed that the baseMean is` (R+G)/2` (thus `log2( (R+G)/2 )` rather than real A belows
[https://en.wikipedia.org/wiki/MA_plot](url)
![image](https://user-images.githubusercontent.com/40571792/62471477-585b4300-b7cf-11e9-9ee0-d9de927968fe.png)
![image](https://user-images.githubusercontent.com/40571792/62471541-745ee480-b7cf-11e9-9014-f2f32b68c116.png)

**Comment by kassambara** [comment]
ok, thanks. the `ggmaplot()` expect a column containing mean and log2foldchange for creating the plot. No computation is made inside the function.

**Comment by QiangShiPKU** [comment]
> ok, thanks. the `ggmaplot()` expect a column containing mean and log2foldchange for creating the plot. No computation is made inside the function.

The real A in MA plot is the mean of two log-scale values (log first, then mean), instead of log scale of the mean of two values (mean first, then log). However, if I am not mistaken, `ggmaplot()` uses the log scale of the baseMean column as X axis, that is not real A. If users supply only the mean of two values but not two original values, the real A cannot be calculated. So, I think this function should expect two original/log-scale columns to calculate their mean (real A).

**Comment by kassambara** [comment]
thank you @QiangShiPKU for the clarification, I can see now the problem.

Let's keep this issue open

**Comment by kassambara** [comment]
The design of this function was influenced by the DESeq2 pipeline (https://www.bioconductor.org/packages/devel/workflows/vignettes/rnaseqGene/inst/doc/rnaseqGene.html#ma-plot), were log2 fold change is plotted against the basemean in log scale..

Obviously, I think that an option should be available in `ggmaplot()`  to create a real MA-plot as you mentionned.

**Comment by QiangShiPKU** [comment]
Great

**Comment by kassambara** [comment]
I think that we should allow two possible formats for the input data:

1/
baseMean | log2FoldChange|padj

Here, we'll use log2(baseMean) as the x-axis variable (like in the current version of the function)

2/ 
baseMeanLog2 | log2FoldChange|padj

here, baseMeanLog2 is assumed to be the mean of logged values; so we'll use it as x-axis variable without any transformation

**Comment by QiangShiPKU** [comment]
That's a good idea

**Comment by kassambara** [comment]
fixed now, thanks
