### ISSUE TITLE
Please submit ggpubr to ggplot2-exts.org/gallery/

### ISSUE THREAD

**Issue by talgalili** [kassambara/ggpubr#2]
It seems that this is the official extension website for ggplot2:
http://www.ggplot2-exts.org/gallery/

I think ggpubr should be mentioned there.

**Comment by kassambara** [comment]
Thank you @talgalili for the link.

I Will look  into ggplot2-exts for submitting ggpubr.

**Comment by kassambara** [comment]
done https://exts.ggplot2.tidyverse.org/gallery/
