### ISSUE TITLE
substituted labels with ggbarplot

### ISSUE THREAD

**Issue by tdelhomme** [kassambara/ggpubr#20]
Hi,

First of all thanks for developing this amazing package!

Actually I am playing with ggbarplot, and unfortunately my bar labels does not correspond to the true size of the bar. Here is my dataframe:

```
> df
  cl   scl len ylabel_pos
1  0 chr13  56         56
2  0 chr17  96        152
3  1 chr13  34         34
4  1 chr17 166        200
```

and here my command:

```
ggbarplot(df, x = "cl", y = "len",
          fill = "scl", color = "scl",
          label = TRUE, lab.col = "white", lab.pos = "in")
```

![rplot](https://user-images.githubusercontent.com/13535602/28927237-5798b886-786a-11e7-9b2d-1db46097818c.png)

**Comment by kassambara** [comment]
Thank you for pointing this out. Fixed now, thanks.

**Comment by tdelhomme** [comment]
Thanks a lot! Will close the issue.
