### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by mnhuda** [kassambara/ggpubr#201]
When I was using your stat_pvalue_manual, I got the following error message. Also, it seems that the code does not work if I use a fill option. Anyway, thank you so much for developing this convenient tool. 
"Warning: Ignoring unknown aesthetics: xmin, xm ax, annotations, y_position"

Regards,
Nazmul

**Comment by kassambara** [comment]
This should work now. Consider installing the latest dev version of rstatix and ggpubr R packages.

The following blog posts might help to add p-values onto ggplots

- [How to Add P-Values onto Basic GGPLOTS](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-basic-ggplots/)
- [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/)
- [How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)
