### ISSUE TITLE
ggpie changes the default order of label

### ISSUE THREAD

**Issue by WortJohn** [kassambara/ggpubr#203]
Hello, @kassambara 
When I use ggpie to plot a pie, I find the label is wrong. The following is my data:
![data](https://user-images.githubusercontent.com/12823074/63068718-d42f5b00-bf46-11e9-96dc-efc60012ca53.png)
And my code:
> pielabels = paste(freq$GENE, paste(round(freq$FREQUENCY * 100, 2), "%", sep = ""), sep = "\n")
> p = ggpie(freq, "FREQUENCY", label = pielabels, lab.pos = "out", lab.font = "white", fill = "GENE", color = "white", palette = "jco")
The following is the result and the order of label is wrong:
[pie.pdf](https://github.com/kassambara/ggpubr/files/3504097/pie.pdf)
Next, i check the data of plot. The order is changed.
![da2](https://user-images.githubusercontent.com/12823074/63069117-4d7b7d80-bf48-11e9-94bc-299d03a41daa.png)
According to #116 , it is also not work.

**Comment by WortJohn** [comment]
Sorry, according to #166 not 116, it is also not work.

**Comment by kassambara** [comment]
Thank you for pointing this issue. This is fixed by adding the pilabels into the data frame as follow:

```r
freq <- data.frame(
  GENE = c("EGFR", "KRAS", "NTRK", "ALK", "RET", "BRAF", "ERBB2", "MET", "ROS1"),
  FREQUENCY = c(0.46, 0.26666667, 0.08, 0.04666667, 0.04666667, 0.0333333, 0.0333333, 0.0333333, 0.0133333)
)
freq$pielabels <- paste(freq$GENE, paste(round(freq$FREQUENCY * 100, 2), "%", sep = ""), sep = "\n")

ggpie(
  freq, "FREQUENCY", label = "pielabels", lab.pos = "out",
  lab.font = "white", fill = "GENE", color = "white", palette = "jco"
  )
```

![Rplot](https://user-images.githubusercontent.com/3313355/63080710-1013f180-bf42-11e9-9730-f7eff620d1ae.jpeg)


In the current version of `ggpie()`, the data is sorted internally. This sorting is not applied to labels when specified separately from the main input data. I'll update the function.

**Comment by kassambara** [comment]
Note also that, by default genes are ordered alphabetically in the plot. To keep the same order as in the table, modify the data as follow:

```r
freq$GENE <- factor(freq$GENE, levels = freq$GENE)
```

You will end up with the plot below:

![Rplot21](https://user-images.githubusercontent.com/3313355/63081422-dcd26200-bf43-11e9-8761-af45f6febdcc.jpeg)

**Comment by kassambara** [comment]
fixed now, thanks!

You can install the latest dev version and try it: `devtools::install_github("kassambara/ggpubr", dependencies = FALSE)`

**Comment by WortJohn** [comment]
Thanks for your solution very much. I get it and thank you again !

**Comment by vertesy** [comment]
The example of @kassambara works well, however when I try to do it on another df, I get the error:

```r
Error: Problem with `mutate()` column `.lab.ypos.`.
ℹ `.lab.ypos. = cumsum(.x) - 0.5 * .x - lab.adjust`.
x ‘cumsum’ not meaningful for factors
```

Since the code is embedded in a function its not reprex
```r
df <- qqqCovert.named.vec2tbl(namedVec = vec, thr = max.names)
  if (length(vec) > max.categories) df[['names']][length(df$'names')] <- p0('Sum of rest ', length(idx.remaining))
  
  pcX <- df$"value" / sum(df$"value")
  labs <- paste(100 * signif(pcX, pcdigits), "%", sep = "")
  
  # if (both_pc_and_value) df$'names' <- paste(df$'names', labs, sep = "\n")
  if (decr.order) df[['value']] <- as.factor(make.unique(as.character(df$'value')))
  
  nrCategories.DFcol1 <- length(unique(df[,1])); stopif( nrCategories.DFcol1 > max.categories)
  print(nrCategories.DFcol1)
  
  if (NamedSlices) labs <- paste(df$names, "\n", labs)
  if (custom.order != F) df$'names' <- factor(df$'names', levels = custom.order)
  
  (p <- ggpubr::ggpie(data = df
                    , x = "value"
                     , label = 'names'
                     # , label = labs
                     , fill = "names", color = "white"
                     , title = plotname
                     , palette = 'rainbow'
                     , caption = paste('max.categories:', max.categories, 'max.names:', max.names)
                     # , ...
                     ))
````

If comment out
` if (decr.order) df[['value']] <- as.factor(make.unique(as.character(df$'value')))`
The plot is made, but in the wrong order.

If I keep it, 

```r
Error: Problem with `mutate()` column `.lab.ypos.`.
ℹ `.lab.ypos. = cumsum(.x) - 0.5 * .x - lab.adjust`.
x ‘cumsum’ not meaningful for factors
```

**Comment by vertesy** [comment]
`as.factor(make.unique(as.character(df$'value')))` is sometimes necessary, but same error occurs if `as.factor(df$'value')`.
