### ISSUE TITLE
show significant p-val otherwise "ns"

### ISSUE THREAD

**Issue by jiayiliujiayi** [kassambara/ggpubr#204]
is there a way of showing p values when they are significant and show "ns" when not significant?  

Thank you!

**Comment by kassambara** [comment]
Install the latest dev version of ggpubr and rstatix packages, then try the following R code: 

```r
# Install required packages
devtools::install_github("kassambara/ggpubr")
devtools::install_github("kassambara/rstatix")

# Load required package
library(ggpubr)
library(rstatix)

# Data preparation
df <- PlantGrowth
df$group <- as.factor(df$group)
# Statistical tests
stat.test <- df %>% t_test(weight ~ group)
stat.test

# Add custom label column
# showing p values when they are significant and 
# show "ns" when not significant
stat.test$custom.label <- ifelse(
  stat.test$p.adj <= 0.05, stat.test$p.adj, "ns"
  )
stat.test

# Visualize
stat.test <- stat.test %>% add_xy_position(x = "group")
ggboxplot(df, x = "group", y = "weight") +
  stat_pvalue_manual(
    stat.test, label = "custom.label", 
    step.increase = 0.1, tip.length = 0
    )
```


![Rplot](https://user-images.githubusercontent.com/3313355/63214563-e6adbe00-c119-11e9-9ed4-4869621b8980.png)

**Comment by jiayiliujiayi** [comment]
Thanks! It works pretty well!  

Additional question for this issue: is there a way of sepecifying the comparisons under this scenario? e.g., my_comparions = list(c("ctrl", "trt1'), c("ctrl", "trt2'))

Thank you!

**Comment by kassambara** [comment]
just specify the options `comparisons`  when computing the statistical test:

```r
my_comparions = list(c("ctrl", "trt1"), c("ctrl", "trt2"))
stat.test <- PlantGrowth %>% t_test(weight ~ group, comparisons = my_comparions)
stat.test
````

**Comment by jiayiliujiayi** [comment]
Nice! Thanks!! 

And for those who want to apply the " **significant p values other wise 'ns'** " to **facets**, the scripts can be: 

```r
# initiate df with facet column
df <- PlantGrowth
df$facet <- c(1, 2)

#my_comparions = list(c("ctrl", "trt1"), c("ctrl", "trt2"))
stat.test <- df %>% group_by(facet) %>%
t_test(weight ~ group, comparisons = my_comparions) %>% 
  cbind(., y.position = c(6.3, 6.6) # y.position here should be a numeric vetor whose length is the same as "length(my_comparisons)" )


# Add custom label column
# showing p values when they are significant and 
# show "ns" when not significant
stat.test$custom.label <- ifelse(
  stat.test$p.adj <= 0.05, stat.test$p.adj, "ns"
  )
stat.test

# Visualize
ggboxplot(df, x = "group", y = "weight") +
  facet_wrap(.~facet) +
  stat_pvalue_manual(
    stat.test, label = "custom.label", 
    y.position = "y.position"
    )
```

Since I'm kind of a novice I'm sure this is not the best solutions to this when it comes to facets.  

@kassambara If you have better solutions, could you please let us know that?  Thanks!  :))

**Comment by kassambara** [comment]
This article might help:  [add-pvalues to faceted plots](https://github.com/kassambara/ggpubr/wiki/Adding-Adjusted-P-values-to-a-GGPlot)

**Comment by jiayiliujiayi** [comment]
> This article might help: [add-pvalues to faceted plots](https://github.com/kassambara/ggpubr/wiki/Adding-Adjusted-P-values-to-a-GGPlot)

Thanks! 

The scripts I posted are for showing "significant p values other wise 'ns' " to facets while specifying the comparison groups.

**Comment by tamburinif** [comment]
I'm trying to run this code exactly as above but I'm getting an error 

```
> stat.test <- stat.test %>% add_xy_position(x = "group")
Error: Strings must match column names. Unknown columns: max
Call `rlang::last_error()` to see a backtrace
```

Please fix?
Thank you

**Comment by kassambara** [comment]
make sure you have the latest dev version of ggpubr and rstatix. If it still fails, please open a new issue for providing a reproducible R code and your session info.
