### ISSUE TITLE
ggerrorplot median_iqr

### ISSUE THREAD

**Issue by davidlorenz** [kassambara/ggpubr#209]
Thanks so much for developing and maintaining this great package! An issue I noticed is that the "median_iqr" descriptive stat for errors plots the median +/- IQR, which seems unusual (many people might assume that the ymin/ymax values would correspond to the 25th/75th percentiles, as in a box plot). You might want to add the option to specify confidence intervals (as in Hmisc::smedian.hilow). Thanks again.

`ggerr <- ggerrorplot(ToothGrowth, x = "dose", y = "len", desc_stat="median_iqr") + ylim(0,40)
ggbox <- ggboxplot(ToothGrowth, x = "dose", y = "len") + ylim(0, 40)
gridExtra::grid.arrange(ggerr, ggbox, nrow=1)
ToothGrowth %>% dplyr::group_by(dose) %>% dplyr::summarise(IQR(len))`

![ggpubr_median_iqr](https://user-images.githubusercontent.com/10579349/64737541-2d919800-d4bb-11e9-809b-d00b2c0b0839.png)

**Comment by kassambara** [comment]
New errorbar functions added now, thanks

``` r
library(ggpubr)
# Error plot
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Use this
ggerr <- ggerrorplot(
  ToothGrowth, x = "dose", y = "len", 
  desc_stat="median_hilow", ci = 0.5
  ) + 
  ylim(0,40) 
# Or this
ggerr <- ggerrorplot(
  ToothGrowth, x = "dose", y = "len", 
  desc_stat="median_q1q3"
) + 
  ylim(0,40) 
# Box plot
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ggbox <- ggboxplot(ToothGrowth, x = "dose", y = "len") + 
  ylim(0, 40) 
gridExtra::grid.arrange(ggerr, ggbox, nrow=1) 
```

![](https://i.imgur.com/jCklb2H.png)

<sup>Created on 2020-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
