### ISSUE TITLE
Can not export images into pdf in a for loop

### ISSUE THREAD

**Issue by caturra** [kassambara/ggpubr#21]
Hi,

First of all thanks for developing this amazing package!
I am using the function "ggboxplot", it's OK to export the images into pdf files individually while the files are broken and cannot open when I use a "for" loop to export them in batch. Here is my dataframe:

> head(a)
        exp class cancer_type
1  9.096848   ACC         ACC
2 10.808414   ACC         ACC
3  9.029533   ACC         ACC
4  8.399695   ACC         ACC
5  3.248019   ACC         ACC
6  7.958241   ACC         ACC

And the code:
```
for(i in c("AMOTL2.txt","AXIN1.txt","AXIN2.txt"))
{
    pdf(paste(i,".pdf",sep=""))
    a = read.table(i,header=T,sep="\t",quote="")
    ggboxplot(a, x="cancer_type", y="exp", font.x=c(14,"bold"), 
        font.y=c(14,"bold"),fill = "cancer_type",legend="none",
        outlier.size = -1,xtickslab.rt =60,font.xtickslab=c(12),font.ytickslab=c(12))
    dev.off()
}

```

**Comment by kassambara** [comment]
Hi,

To save multiple ggplots using for loop, you need to call the function print()  as follow:

```r
 
library(ggplot2)
p <- ggplot(iris, aes(x = Species, y = Sepal.Length))
colors <- c("black", "red", "green")
 
for(color in colors){
 
   final.plot <- p + geom_boxplot(color = color)
 
  pdf(paste0(color, ".pdf"))
  print(final.plot)
  dev.off()
}
 
```
