### ISSUE TITLE
stat_compare_means change distance between bracket and label 

### ISSUE THREAD

**Issue by tamburinif** [kassambara/ggpubr#210]
This seems simple but I can't figure out how to accomplish this -- I'd like to adjust the vertical distance between the label and the bracket when using stat_compare_means (red arrows in attached example).
![README-ggpubr-box-plot-dot-plots-strip-charts-3](https://user-images.githubusercontent.com/5864265/65637498-237e9780-df99-11e9-8b6e-61385ef4c192.png)

Is this an option? Without this adjustment the label positioning does not look very nice when trying to show brackets for multiple comparisons. Thank you!

**Comment by LuisEnriqueAngelesGonzalez** [comment]
I am looking also for an answer, please help :(

**Comment by kassambara** [comment]
Fixed now, thanks!

New argument `vjust` added to move text up and down.

``` r
library(ggpubr)
#> Le chargement a nécessité le package : ggplot2

# Load data
data("ToothGrowth")
head(ToothGrowth)
#>    len supp dose
#> 1  4.2   VC  0.5
#> 2 11.5   VC  0.5
#> 3  7.3   VC  0.5
#> 4  5.8   VC  0.5
#> 5  6.4   VC  0.5
#> 6 10.0   VC  0.5

# Boxplot with p-values
p <- ggboxplot(ToothGrowth, x = "supp", y = "len",
               color = "supp", palette = "npg", add = "jitter")

my_comparisons <- list( c("0.5", "1"), c("1", "2"), c("0.5", "2") )
ggboxplot(
  ToothGrowth, x = "dose", y = "len",
  color = "dose", palette = "npg"
  )+
  stat_compare_means(
    comparisons = my_comparisons, 
    method = "t.test",
    label.y = c(29, 35, 40), 
    label = "p.signif",
    vjust = 0.5
    )
```

![](https://i.imgur.com/eKw27pl.png)

<sup>Created on 2020-04-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by tamburinif** [comment]
Works great, thank you!!
