### ISSUE TITLE
gghistogram: second y-axis for add_density

### ISSUE THREAD

**Issue by timwoelfle** [kassambara/ggpubr#212]
First of all, great package! I really love the dedication and thought put into this :)

Personally, I find the add_density parameter of gghistogram() a bit confusing: It doesn't seem to correlate with the y-axis "count" values and seems to extend the ylimit of the plot, seemingly inflating the numbers. This can be seen  in the official example plot (bottom of https://rpkgs.datanovia.com/ggpubr/reference/gghistogram.html):

![image](https://user-images.githubusercontent.com/1315644/66048101-e2e6c700-e520-11e9-8907-f33dac8d16e0.png)

Maybe an optional second y-axis on the right giving the density like ggdensity() does would be a solution? What do you think?

**Comment by kassambara** [comment]
Using a secondary y-axis for density is a good suggestion.

Specifying the argument y = "..density.." gives a better result.  I need to update the documentation as follow:

```r
library(ggpubr)
# Demo data
set.seed(1234)
wdata = data.frame(
  sex = factor(rep(c("F", "M"), each=200)),
  weight = c(rnorm(200, 55), rnorm(200, 58)))
# Plot
gghistogram(
  wdata, x = "weight", y = "..density.."
  add = "mean", rug = TRUE,
  fill = "sex", palette = c("#00AFBB", "#E7B800"),
  add_density = TRUE
  )
```

![Rplot](https://user-images.githubusercontent.com/3313355/66066659-391c3000-e54a-11e9-96cd-31c54265f051.png)

**Comment by kassambara** [comment]
This is now possible using the cowplot package, see this:  [Aligning Plots](https://wilkelab.org/cowplot/articles/aligning_plots.html).

Examples:

``` r
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(cowplot))

# Demo data
set.seed(1234)
wdata = data.frame(
  sex = factor(rep(c("F", "M"), each=200)),
  weight = c(rnorm(200, 55), rnorm(200, 58)))

# Plot
phist <- gghistogram(
  wdata, x = "weight", 
  add = "mean", rug = TRUE,
  fill = "sex", palette = c("#00AFBB", "#E7B800")
)
#> Warning: Using `bins = 30` by default. Pick better value with the argument
#> `bins`.

# Density plot
pdensity <- ggdensity(
  wdata, x = "weight", 
  color= "sex", palette = c("#00AFBB", "#E7B800"),
  alpha = 0, xlab = 
) +
  theme_half_open(11, rel_small = 1) +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05)),
    position = "right"
  )  +
  theme(
    axis.line.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks = element_blank(),
    axis.ticks.length = grid::unit(0, "pt")
  )

# Aligning histogram and density plots
aligned_plots <- align_plots(phist, pdensity, align="hv", axis="tblr")
ggdraw(aligned_plots[[1]]) + draw_plot(aligned_plots[[2]])
```

![](https://i.imgur.com/hm5CZqH.png)

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
