### ISSUE TITLE
ggarrange: common.legend=T creates annoying whitespace in R notebooks

### ISSUE THREAD

**Issue by timwoelfle** [kassambara/ggpubr#213]
Using common.legend=T in ggarrange() creates annoying whitespace in R notebooks, see example attached.

[common_legend.zip](https://github.com/kassambara/ggpubr/files/3681437/common_legend.zip)

**Comment by timwoelfle** [comment]
The workaround offered here (https://github.com/kassambara/ggpubr/issues/158) seems to work, but hopefully it can be made unnecessary in a future patch:

pdf(NULL)
res = ggarrange(bxp, dp, common.legend = TRUE)
x = dev.off()
res

**Comment by kassambara** [comment]
duplicate of #158, will be fixed, thanks
