### ISSUE TITLE
gghistogram not parsing the weight parameter

### ISSUE THREAD

**Issue by y1zhou** [kassambara/ggpubr#215]
In `ggplot2` you can plot a weighted histogram with `geom_histogram(aes(x = x, weight = y))`, but `gghistogram()` doesn't have a parameter for weights. Is this by design, or can we add that into the parameters?

Thanks!

**Comment by kassambara** [comment]
fixe now, thanks!

``` r
library(ggpubr)
# Standard histogram
gghistogram(iris, x = "Sepal.Length", bins = 30)
```

![](https://i.imgur.com/iCCBZOc.png)

``` r

# Weighted histogram
gghistogram(iris, x = "Sepal.Length", bins = 30, weight = "Petal.Length")
```

![](https://i.imgur.com/QxHBd6D.png)
