### ISSUE TITLE
Using expression for label text

### ISSUE THREAD

**Issue by pbt001** [kassambara/ggpubr#22]
It's seems not possible to write special characters as expression, e.g. subscripts or greek letters as labels:

`ylab = expression(alpha^{3}*hel ~ "\u223")`

This fails and gives :  

> Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments

Could this be fixed or is there a workaround? 

Thanks.

**Comment by kassambara** [comment]
Fixed now, thanks!

Please install the latest developmental version.

```r
devtools::install_github("kassambara/ggpubr")
```

**Comment by kassambara** [comment]
Can we close this issue?

**Comment by pbt001** [comment]
Yes, thank you. I got it on one machine running flawlessly now after the update. On another machine, however, ggpubr crashes with an error message related to a lazy package or similar. I don't know if this is related to the update or if something went wrong on that machine.
