### ISSUE TITLE
units regarding position of labels in ggarrange: labels.x , labels.y , hjust and vjust

### ISSUE THREAD

**Issue by LIVF** [kassambara/ggpubr#221]
It seems that the units of the parameters in ggarrange regarding labels positioning depend on the characters of the labels, which can be quite annoying if you try to align them.

This code shows the effect pretty well. Data is the same for all the series, so that is not the problem:
`ggarrange(F2_NO, F2_NO, F2_NO,F2_NO, F2_NO, F2_NO, F2_NO,
            ncol = 1, labels = c("AAAAAA","AAAAAI","AAAAII", "AAAIII","AAIIII","AIIIII","IIIII"),hjust=-2.3,vjust=0.5, 
            font.label = list(size = 10),
            common.legend = T, legend = "bottom")`
![image](https://user-images.githubusercontent.com/51472835/68429822-203d1500-01af-11ea-9acb-5482751c0244.png)
The distance should be the same for all the labels, but it seems that the units are affected by the characters  in the label.
There was no effect using hjust=0 and vjust=0 (labels were aligned) and the effect increases with the units used, so I guess the measurement units are related to the characters. 
‘ggpubr’ version 0.2.3
R version 3.6.1

**Comment by kassambara** [comment]
hi, you need to play with `hjust` and `vjust`. Can be a single value (applied to all labels) or a vector of values (one for each label).

``` r
library(ggpubr)
bxp <- ggboxplot(ToothGrowth, x = "dose", y = "len", color = "supp")
ggarrange(bxp, bxp, bxp, ncol = 2, nrow = 2,
          
          labels = c("AAA","AAAAAAAAAAII", "AAAAA"),
          hjust = c(-1, -0.15, -0.8), vjust = 1.5
          )
```

![](https://i.imgur.com/zVitIK5.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
