### ISSUE TITLE
ggarrange() fail when nrow/ncol/legend arguments change

### ISSUE THREAD

**Issue by bioXiaoheng** [kassambara/ggpubr#224]
I'm trying to merge two ggplots (roc curve + barplot) as one on top of another (so 2 rows, 1 column). Both plots can be plotted out independently. Both plots have disabled the legend (theme(legend.position="none")). I added ggtitle to the curve, and added margin to barplot. 

Here are the commands I tried:

`part <- ggarrange(roc, bar, nrow=2) `
I get:

> Error in plot_to_gtable(x):
>    Argument needs to be of class "ggplot", "gtable", "grob", "recordedplot", or <...>
> Calls: ggarrange ... <Anonymous> -> align_plots -> lapply -> FUN -> plot_to_gtable

if I add "ncol=1" or replace "nrow=2" to "ncol=1", class(part) would return "list ggarrange", and won't be plotted.

For
```
part <- ggarrange(roc, bar, nrow=2, legend="none")
cat('Part type:', class(part),'.\n')
ggsave("filename.png", plot=part, width=7, weight=8, units='in', dpi=500)
```

I get:

> Part type: gg ggplot ggarrange

And the figure being produced is side by side.

I also attempted to add "heights=c(1.5,1)" (or any other values). The figure produced still has them side by side, just the length changes according to the value. (e.g. "heights=c(2,1)" would produce longer side-by-side figure than height=c(1,1). )

I'm so confused....

**Comment by kassambara** [comment]
It works for me. To export an object of class ggarrange, please consider using `ggexport()` [ from ggpubr]. If it still fails, please consider providing a reproducible R script so that we can efficiently help.

``` r
library(ggpubr)
p1 <- ggline(ToothGrowth, x = "dose", y = "len", add = "mean_sd") +
  theme(plot.margin = unit(c(1,1,1,1), "cm"))

p2 <- ggbarplot(ToothGrowth, x = "dose", y = "len", add = "mean_sd") +
  ggtitle("Plot 2")

part <- ggarrange(p1, p2, nrow = 2)
part
```

![](https://i.imgur.com/RfXnbrd.png)

<sup>Created on 2020-05-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
