### ISSUE TITLE
Resize the multipanel plot in ggarrange()

### ISSUE THREAD

**Issue by e-clin** [kassambara/ggpubr#226]
I like the convenience of `ggarrange()` for combining multiple ggplot2 plots into a multiple plot when writing reports in R Markdown. However, I found some of my plots overly "squashed" and didn't seem to find in the documentation on how to adjust the size of the product plot. Do I need to use `ggexport()` to save it as a .png file of specified dimension and then use `knitr::include_graphics()` to insert it to my report? I understand that I could set `fig.height=` and `fig.width=` in the chunk options, but that seemed to reduce the plot resolution...

**Comment by yingji15** [comment]
Hi there, I ran into a similar issue: my plot is too tall on the y axis and too narrow on x axis. So my work-around is just set "width" to a larger number than "height" when plotting to pdf, example is like

`pdf("out.pdf",width=xx, height =xx) 
p1 <- ggplot(...)
p2 <- ggplot(...)
ggarange(p1,p2,...) `

**Comment by kassambara** [comment]
In Rmarkdown,  you can consider using `fig.height` and `fig.width` chunk option.

Note also that using the option `dev: "cairo_pdf"` in your Rmd yaml header might help to increase the resolution

<pre>
---
title: "Untitled"
output: 
  pdf_document:
    dev: "cairo_pdf"
---
</pre>
