### ISSUE TITLE
anova asumption check

### ISSUE THREAD

**Issue by fconstancias** [kassambara/ggpubr#227]
Hi,
Thanks for developping this amazing R package.

Is there any easy way to check for ANOVA asumptions i.e., mainly Homogeneity of variance and Model checking plots [fitted vs residuals], predicted vs observed, ...] out of the compare_means output? 
Any suggestions as an alternative to be able to generate those tests/plots (bartlett.test(), shaprio.test on the residuals() on using variables from a dataframe ?

**Comment by kassambara** [comment]
The following guide might help for checking ANOVA assumptions using the combination of ggpubr & rstatix: [ANOVA IN R](https://www.datanovia.com/en/lessons/anova-in-r/)
