### ISSUE TITLE
ggscatter cannot handle non-standard column names  | Error in FUN(X[[i]], ...) : object 'B' not found

### ISSUE THREAD

**Issue by tobsecret** [kassambara/ggpubr#229]
# Preface
I am an r-newbie, so I'm not sure whether this is an issue or expected behavior and whether this is a `ggpubr` or `ggplot2` issue.
# Expected behavior
Given a `data.frame` with column names that are non-valid variable names, ggscatter produces a plot given the appropriate x and y column names.
# Observed behavior
Despite being able to access those columns from the `data.frame` in the console, ggscatter chokes if given a data.frame with non-valid column names and the corresponding x and y column names.

# MCVE
Let's make two `data.frames`, one with `check.names = FALSE` (i.e. with non-valid variable name columns) and one with `check.names = TRUE`. We can access columns with data from each of these frames without a problem:
```
> library(ggpubr)
> data_names_not_checked = data.frame('A-A' = 1:10, 'B-B' = 11:20, check.names = FALSE)
> data_names_not_checked[,'A-A']
 [1]  1  2  3  4  5  6  7  8  9 10
> data_checked_names = data.frame('A-A' = 1:10, 'B-B' = 11:20, check.names = TRUE)
> data_checked_names[,'A.A']
 [1]  1  2  3  4  5  6  7  8  9 10
```
When we try to plot the columns using ggscatter, we get an error if we left check.names = TRUE:
```
> ggscatter(data_names_not_checked, x = 'A-A', y = 'B-B')
Error in FUN(X[[i]], ...) : object 'B' not found
> ggscatter(data_checked_names, x=make.names('A-A'), y=make.names('B-B'))
```
If we use the frame with the checked names and the appropriate corrected column names, the function succeeds.

**Comment by kassambara** [comment]
fixed now, thanks

**Comment by tobsecret** [comment]
Awesome, thanks!

**Comment by kassambara** [comment]
Supporting non standard column breaks many other ggplot2 functionality.  So, I think we should remove  support to non-standard column names.

**Comment by kassambara** [comment]
Now `ggpubr.parse_aes` global options is available. logical indicating whether to parse or not the aesthetics variables names. Default is `TRUE`. For example, if you want ggpubr to handle non-standard column names, like A-A, without parsing, then set this option to FALSE using `options(ggpubr.parse_aes = FALSE)`.

```r
# Data
 data("mtcars")
  df <- mtcars[, c("wt", "mpg")]
  colnames(df) <- c("A-A", "B-B")

# Plotting after inactivating parsing
  old_options <- options(ggpubr.parse_aes = FALSE)
  p <- ggscatter(df, x = "A-A", y = "B-B" )

# restore back old settings
  options(old_options)
```
