### ISSUE TITLE
Error in `[.data.frame`(data, , x) : undefined columns selected

### ISSUE THREAD

**Issue by perro001** [kassambara/ggpubr#23]
I believe that the `ggscatter()` function in `ggpubr` has a bug.  The problem that I ad was that every time I tried to  run  `ggscatter()` I keep having the Error in `[.data.frame`(data, , x) : undefined columns selected

My code was 
```
install.packages("ggpubr")
library("ggpubr")
my_data <- All_Data_Summer_17_
head(my_data, 6)
ggscatter(my_data, x = "band", y = "Disk", 
      add = "reg.line", conf.int = TRUE, 
      cor.coef = TRUE, cor.method = "pearson",
      xlab = "Band", ylab = "Disk (cm)")
```
if instead some elements of the code get rearrange (see new code)  the problem is solve. This might indicate that the order does matter. So maybe you guys can look at it. 
```
ggscatter(my_data, x = "band",
                   y = "Disk",
                   add = "reg.line", 
                   cor.coef = FALSE,
                   cor.method = "pearson",
                   conf.int = TRUE,
                   xlab = "Band",
                   ylab = "Disk (cm)")  
```

**Comment by kassambara** [comment]
Hi,

Post the head of your data, so that I can check it. Or, just post the output of `colnames(my_data)` Because the demo data set works:

```r
ggscatter(mtcars, x = "mpg", y = "wt")
```

**Comment by perro001** [comment]
Hello @kassambara thank you for your response.  I have fix the problem, I just thought that maybe I should make you aware that it could a bug. 
A question regarding the same function, is there a way to introduce the Correlation Coefficient, Coefficient of Determination and the regression equation on the same graph? 
The code that I have right now is  
`ggscatter(my_data, x="Blue", y="SD",add = "reg.line", cor.coef = TRUE,cor.coeff.args = list(method = "pearson", label.x.npc = "right", label.y.npc = "top"),cor.method = "pearson",conf.int = TRUE,xlab = "Blue Band",ylab = "Secchi Disk (cm)") `
![rplot](https://user-images.githubusercontent.com/30909984/29192698-fa44b1de-7de7-11e7-804c-276757dc037a.jpeg)

**Comment by kassambara** [comment]
Hi,

Adding the equation is not possible in the current version. The package `ggpmisc` might help you on that.

**Comment by kassambara** [comment]
```r
library(ggpubr)
ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line") +
  stat_cor(label.x = 3, label.y = 34) +
  stat_regline_equation(label.x = 3, label.y = 32)
```
![rplot41](https://user-images.githubusercontent.com/3313355/43993182-e3baf294-9d89-11e8-8023-2730b5283da4.png)
