### ISSUE TITLE
stat_compare_means formatting

### ISSUE THREAD

**Issue by retrogenomics** [kassambara/ggpubr#230]
Is there a way to format more carefully the p-values using angle, hjust, vjust, size, etc? I'm working with facet_wrap and even the size option which is documented does not seem to work.
Thank you in advance for your help, and thanks for developing this very useful package !

**Comment by kassambara** [comment]
The following blog posts might help to add p-values onto ggplots facets

- [How to Add P-Values onto Basic GGPLOTS](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-basic-ggplots/)
- [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/)
- [How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)
