### ISSUE TITLE
Extended reporting or compare_means stat_compare_means discrepancies

### ISSUE THREAD

**Issue by SarenT** [kassambara/ggpubr#231]
I am trying to implement a solution, where `stat_compare_means` adds the statistics information on the plot but at the same time I would like to report details in a text format. One can add a few details (stars, p value etc.) on the plot or report some statistics details in the figure legends. Therefore, it would be great to have more detailed output similar to `compare_means` or e.g. `wilcox.test` in text or data frame format from `stat_compare_means`.
One way could be of course using the method separately (e.g. running `wilcox.test` separately) and report it. Or using `compare_means` separately. However, the way `stat_compare_means` and `compare_means` are called differ in a way that it is hard to foresee that they will compute statistics identically. It is undesirable if `stat_compare_means` output on the plot differs from `compare_means` output. Also as a principle, it is not a good idea to compute same thing twice.
For instance `stat_compare_means` accepts mappings, comparisons (for pairwise), whereas `compare_means` accepts formula. It would be better, if both functions would accept both mappings and formula. Even better, if `stat_compare_means` would call `compare_means` with exact same parameters (formula/mappings etc.).
I wonder if there is any way to this cleanly? Or any way to get statistics details from `stat_compare_means` without having to compute it twice?

**Comment by kassambara** [comment]
I recently developed a package, named [rstatix](https://github.com/kassambara/rstatix), which makes it possible to run basic stat tests separately (t-test, wilcoxon, anova, kruskal-wallis).

The output of the rstatix package are easily handled by the function stat_pvalue_manual() and others [in ggpubr package] to display p-values and test details on a plot.

so, the new workfow is know:

1. Compute easily statistical test using the rstatix package. The output is always a data frame
2. Create plot and add (rstatix) test outputs using stat_pvalue_manual() [ggpubr]

See examples at:

-   [Comparing Means of Two Groups in R](https://www.datanovia.com/en/courses/comparing-means-of-two-groups-in-r/)
    -   [T-test in R](https://www.datanovia.com/en/lessons/t-test-in-r/)
    -   [Wilcoxon Test in R](https://www.datanovia.com/en/lessons/wilcoxon-test-in-r/)
    -   [Sign Test in R](https://www.datanovia.com/en/lessons/sign-test-in-r/)
-   [Comparing Multiple Means in R](https://www.datanovia.com/en/courses/comparing-multiple-means-in-r/)
    -   [ANOVA in R](https://www.datanovia.com/en/lessons/anova-in-r/)
    -   [Repeated Measures ANOVA in R](https://www.datanovia.com/en/lessons/repeated-measures-anova-in-r/)
    -   [Mixed ANOVA in R](https://www.datanovia.com/en/lessons/mixed-anova-in-r/)
    -   [ANCOVA in R](https://www.datanovia.com/en/lessons/ancova-in-r/)
    -   [One-Way MANOVA in R](https://www.datanovia.com/en/lessons/one-way-manova-in-r/)
    -   [Kruskal-Wallis Test in R](https://www.datanovia.com/en/lessons/kruskal-wallis-test-in-r/)
    -   [Friedman Test in R](https://www.datanovia.com/en/lessons/friedman-test-in-r/)
