### ISSUE TITLE
Fixing ggarrange labels when ggplots have margins

### ISSUE THREAD

**Issue by luizalmeida93** [kassambara/ggpubr#235]
Hello everyone,

This is a minor problem but I wanted to check if there is any fix. I am generating two plots in a letter-size PDF (landscape), but I want them to be closer to a square size. If I don't change the margins in the ggplot code I end up with plots too tall, occupying the entire page. However, if I add a margin the ggarrange add the label at the top of the page, and not close to the graph. Is there anyway to solve this?

This is my code:
`pdf(file="hist_p-values.pdf", paper="special", width=11, height=8.5, useDingbats = FALSE)
plot1<-ggplot(res.eb, aes(x=p.ord)) +
  theme(plot.margin = margin(5,0.5,5,0.5, "cm")) +
  geom_histogram(color="black", fill="white", breaks=seq(0, 1, by=0.05))

plot2<-ggplot(res.eb, aes(x=p.mod)) +
  theme(plot.margin = margin(5,0.5,5,0.5, "cm")) +
  geom_histogram(color="black", fill="white", breaks=seq(0, 1, by=0.05))
ggarrange(plot1,plot2, labels = c("A","B"), nrow = 1, ncol = 2)
dev.off()`

[hist_p-values.pdf](https://github.com/kassambara/ggpubr/files/4032919/hist_p-values.pdf)

Best,
Luiz

**Comment by kassambara** [comment]
Consider specifying the option `vjust` 

``` r
library(ggpubr)
#> Le chargement a nécessité le package : ggplot2
# Default plot
bxp <- ggboxplot(ToothGrowth, x = "dose", y = "len") +
  theme(plot.margin = margin(5,0.5,5,0.5, "cm")) 
ggarrange(bxp, bxp,  ncol = 2, nrow = 1,
          labels = c("A", "B")
          )
```

![](https://i.imgur.com/1dk01wy.png)

``` r

# Specify vjust
ggarrange(bxp, bxp,  ncol = 2, nrow = 1,
          labels = c("A", "B"), vjust = 15
)
```

![](https://i.imgur.com/NvrYCzD.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
