### ISSUE TITLE
Thickness of the shapes

### ISSUE THREAD

**Issue by bioguy2018** [kassambara/ggpubr#236]
Dear All,
I am using ggline() to draw some plots.Can someone please tell me how can I increase the thickness of the shapes in legend and in my plot?
This is done usually through geom_point(stroke = 1.5) in ggplot but in ggpubr this doesn't work

**Comment by kassambara** [comment]
fixed now, thanks!

``` r
library(ggpubr)
# Default plot
ggline(
  ToothGrowth, x = "dose", y = "len", add = "mean_sd",
  shape = 21, point.size = 5
  )
```

![](https://i.imgur.com/3oWjhjB.png)

``` r

# Use stroke
ggline(
  ToothGrowth, x = "dose", y = "len", add = "mean_sd",
  shape = 21, point.size = 5, stroke = 5
)
```

![](https://i.imgur.com/Ct78EfL.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
