### ISSUE TITLE
ggarange() is not suitable for ggboxplot object

### ISSUE THREAD

**Issue by luomei308** [kassambara/ggpubr#237]
draw_score_pvalue_merge<-function(all_score,signture_name){
  pdf(file.path(out_path,paste(signture_name,"merged.pdf",sep = '.')),height = 5,width = 4)
  plot_list<-list()
  for(i in 1:length(all_score)){
    name<-names(all_score)[i]
    x<-all_score[i]
    score_data<-as.data.frame(x)
    colnames(score_data)<-c("atg_signature","label")
    score_data$atg_signature<-as.numeric(score_data$atg_signature)
    p<-ggpubr::ggboxplot(score_data,x = "label",y = "atg_signature",
                         color = "label", palette = "jco",title = name,
                         add = "jitter",shape = "label")
    q<-p + ggpubr::stat_compare_means(method = "t.test")
    plot_list[i]<-q
  }
  ggarrange(plotlist = plot_list,nrow = 4,ncol = 5)
  dev.off()
}

############# problem ########
ggarrange(plotlist = plot_list,nrow = 4,ncol = 5) dose not work.
but plot_list including ggplot objects work.

**Comment by kassambara** [comment]
You need to use: print(ggarrange(...))

Example:

```r
library(ggpubr)
test_ggarrange <- function(){
  df <- ToothGrowth
  df$dose <- as.factor(df$dose)
  bxp <- ggboxplot(df, x = "dose", y = "len",
                   color = "dose", palette = "jco") +
    stat_compare_means()
  pdf("test.pdf")
  res <- ggarrange(plotlist = list(bxp, bxp))
  print(res)
  dev.off()
}
```
see also `?ggexport`  in the ggpubr R package

**Comment by luomei308** [comment]
OK! Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Alboukadel KASSAMBARA"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月13日(星期四) 凌晨4:35
收件人:&nbsp;"kassambara/ggpubr"<ggpubr@noreply.github.com&gt;;
抄送:&nbsp;"370042463"<370042463@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kassambara/ggpubr] ggarange() is not suitable for ggboxplot object (#237)




You need to use: print(ggarrange(...))
 
Example:
 library(ggpubr) test_ggarrange <- function(){   df <- ToothGrowth   df$dose <- as.factor(df$dose)   bxp <- ggboxplot(df, x = "dose", y = "len",                    color = "dose", palette = "jco") +     stat_compare_means()   pdf("test.pdf")   res <- ggarrange(plotlist = list(bxp, bxp))   print(res)   dev.off() }
 
see also ?ggexport  in the ggpubr R package
