### ISSUE TITLE
ggballoonplot legend balloon cuts

### ISSUE THREAD

**Issue by obruck** [kassambara/ggpubr#238]
Hi!

Is there any possibility to define the cut limits for the balloons in the legend?

For example in the first figure, the balloon cuts are c(0, 40, 80, 120, 160), but could these be c(0,50,100,150)?
https://rpkgs.datanovia.com/ggpubr/reference/ggballoonplot.html

**Comment by kassambara** [comment]
```r
ggballoonplot(data) + scale_size(breaks = c(0,50, 100, 150))
```
