### ISSUE TITLE
Add an option in stat_cor so the p-value is not given

### ISSUE THREAD

**Issue by rdstern** [kassambara/ggpubr#240]
Thank you for all the work in ggpubr.  We are using ggpubr in one (of many) front ends to R to make it easier for non-specialists.  It is called R-Instat and one area of application is the analysis of climatic data.  So, we often plot the data for trends - particularly temperature data.  Here is a (not very good) example with stat_cor and stat_regline_equation using data from Niger.
![image](https://user-images.githubusercontent.com/11226469/75322717-47594880-586b-11ea-9541-edcb59785df2.png)

I note that stat_cor gives the p-value automatically, while the default for the regression is just the line - i.e. no P-value.

In our software we are trying to promote good statistical practice.  I suggest it is not good practice to give the p-value automatically - it assumes random samples, etc.  Hence, I suggest a TRUE/FALSE option for the display of the P-value, with FALSE the default.  That would make it really easy to have the current display, but you would have to ask for it!  And the default for the 2 stats would be consistent (i.e. just the correlation, and just the equation).

**Comment by smouksassi** [comment]
I think this was a recent regression that is already fixed in dev version

**Comment by kassambara** [comment]
In stat_cor(), the results of cor.test() are displayed. Changing now the default will break many ggpubr users R codes/packages.

Suggestion fr hiding  p-values in `stat_cor()`: 

``` r
suppressPackageStartupMessages(library(ggpubr))
# Default plot
sp <- ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line")
sp + stat_cor(label.x = 3)
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/IZWlR2J.png)

``` r
# Show only r.label
sp + stat_cor(aes(label = ..r.label..), label.x = 3)
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/Kk4idhz.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
