### ISSUE TITLE
p.signif symbols in compare_means()

### ISSUE THREAD

**Issue by IsabelFE** [kassambara/ggpubr#241]
In compare_means() are p.signif symbols determined based on p value, or based on the value of p.adj? Thanks!

**Comment by csdaw** [comment]
They are based on the p-value. Here is the relevant section of `R/compare_means.R`.
```r
# Formatting and adjusting pvalues, and adding significance symbols
#:::::::::::::::::::::::::::::::::::::::::::::::::::::
symnum.args$x <- res$p
pvalue.signif <- do.call(stats::symnum, symnum.args) %>%
  as.character()
```

`res$p` is the value in the `p` column of the results table and `pvalue.signif` is the symbol in the `p.signif` column. Hope this helps.
