### ISSUE TITLE
stat_compare_means(): errors when plotting multiple comparisons

### ISSUE THREAD

**Issue by mattvan83** [kassambara/ggpubr#242]
Hi,

I noticed multiple anomalies when using `stat_compare_means()` with multiple post-hoc t-tests:

1) Referring to #143: The label=..p.adj.. doesn't show the adjusted p-value but the non-adjusted one. @kassambara proposes to use [rstatix](https://github.com/kassambara/rstatix) package, but this method needs to specify y position manually, and it is not practical. Isn't it possible to correct this in ggpubr?
2) When using `hide.ns = TRUE` the non significant p-values are still showed on the boxplot 
3) Using the formatting `aes(label = paste0(“p =”, ..p.format..))` doesn't work on the boxplot. p-value is always the only thing showed.

**Comment by kassambara** [comment]
Obviously, we'll rewrite the content of `stat_compare_means()` as soon as possible. Using the rstatix and ggpubr packages should fix this issue. p-values positions are automatically computed. Many examples are provided in the following blog posts:

- [How to Add P-Values onto Basic GGPLOTS](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-basic-ggplots/)
- [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/)
- [How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)
