### ISSUE TITLE
Auto-locate multiple statistical outputs on a plot

### ISSUE THREAD

**Issue by markbneal** [kassambara/ggpubr#247]
On a typical lineplot, you might want to apply both `stat_cor` and `stat_regline_equation`, as per example below, though unless you specify a 'label.y', the will plot in the same place. Would it be difficult to have the `geoms` repel, similar to how `ggrepel` works? Or some `dodge=up` option that moves one a little up, and the other a little down (`dodge=down`) from default position?

Extra kudos for options to shift to other plot corners is negative correlation (to avoid data), or auto expand the plot scales such that they don`t plot over data?

```
ggscatter(df, x = "x", y = "y", add = "reg.line") +
  stat_cor(label.y = 300) +
  stat_regline_equation(label.y = 280)
```

**Comment by markbneal** [comment]
I've thought about this some more - I think that we should ideally be able to include the equation, r2 and p value in one string. This means only one location needs to be specified, and then if there are multiple equation (eg because of group), then the location will auto increment in the background, and everything is still aligned.

See question and discussion [here](https://stackoverflow.com/q/61266084/4927395)

**Comment by aphalo** [comment]
@markbneal By now you must be aware that you can use `stat_poly_eq()` from 'ggpmisc'. Much of what you request here has been already implemented after the code from `stat_poly_eq()` was copied almost unchanged and without acknowledgement into 'ggpubr' some time back. The idea about automatically selecting the corner for the labels based on the sign of R from linear regression is good, although not so easily applicable to higher order polynomials or with grouping. You may want to raise an issue for 'ggpmisc' at https://github.com/aphalo/ggpmisc/issues .

**Comment by markbneal** [comment]
Yes, you are correct most of this has been solved. We could close this issue. 

You are also correct that auto location is a tricky problem. Finding Space on a plot canvas is non-trivial, particularly with groups or complex fits. My current default option is to expand the plot range to make sufficient room if and when required.
