### ISSUE TITLE
ggboxplot: How to add aes(size) when add = "jitter"

### ISSUE THREAD

**Issue by gd047** [kassambara/ggpubr#25]
![image](https://user-images.githubusercontent.com/3167917/29612734-6954f552-880b-11e7-8be9-ba3a3f52f203.png)

**Comment by kassambara** [comment]
Hi,

Do you want to change the size of jitter points?

I'm not sure to understand the question. But if the idea is to adjust the jitter points size according to a continuous variable, then you can do this:

```r
library("ggpubr")
ggboxplot(iris, x = "Species", y = "Petal.Length", 
         add = "jitter",
          add.params = list(size = "Petal.Length")) +
  scale_size(range = c(0.5, 2.5))
```

![rplot](https://user-images.githubusercontent.com/3313355/29623184-d836de6c-8825-11e7-9dca-e2f9d1b23f00.png)

**Comment by gd047** [comment]
Oh,  I should have read the documentation more carefully..
Thanks!
