### ISSUE TITLE
greek letters for text labels of ggscatter

### ISSUE THREAD

**Issue by mattocci27** [kassambara/ggpubr#250]
Is there any easy way to use greek letter for text labels? My tentative solution is not using `label` argument in `ggscatter` and add `geom_text` separately. 

So using something like this 
```
ggscatter(data = df, x = "x", y = "y", label = NULL) +
  geom_text(data = df, aes(x = x, y = y, label = label), parse = TRUE)
```
instead of this.
```
ggscatter(data = df, x = "x", y = "y", label = label)
```
Because some packages use ggscater and it would be great if we can use greek
letter directly.

**Comment by kassambara** [comment]
fixed now, thanks!
``` r
suppressPackageStartupMessages(library(ggpubr))
d <- data.frame(x=1:3,y=1:3, label = c("rho", "pi", "delta"))
ggscatter(d, "x", "y", label = "label", parse = TRUE)
```

![](https://i.imgur.com/FlR0q5i.png)

<sup>Created on 2020-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mattocci27** [comment]
Great!
