### ISSUE TITLE
Is it possible to generate Barplot and Boxplot  together for a single plot?

### ISSUE THREAD

**Issue by aayushraman** [kassambara/ggpubr#252]
Dear Alboukadel,

Thanks a lot for developing and maintaining this fantastic package. I was wondering if it possible to generate a plot having both the barplot and boxplot together? Something similar to this plot. 

![Example_fig](https://user-images.githubusercontent.com/4062603/78218563-ff41cd00-748b-11ea-84f8-1bff0053da77.png)

**Comment by kassambara** [comment]
The following R code might help. Other possibilities can be found at: [How to Create a Beautiful Plots in R with Summary Statistics Labels](https://www.datanovia.com/en/blog/how-to-create-a-beautiful-plots-in-r-with-summary-statistics-labels/)

``` r
library(ggpubr)
#> Le chargement a nécessité le package : ggplot2
#> Le chargement a nécessité le package : magrittr
df <- ToothGrowth
df$dose <- as.factor(df$dose)

# Create barplots showing median and interquartile range (iqr)
ggbarplot(
  df, x = "dose", y = "len",
  color = "supp",
  add = "median_iqr", 
  add.params = list(width = 0.3),
  position = position_dodge(0.8)
)
```

![](https://i.imgur.com/iPlg4C9.png)

``` r

# Combining bar plot, box plot and jittered points
ggbarplot(
  df, x = "dose", y = "len",
  color = "supp",
  add = c("median", "boxplot", "jitter"), 
  add.params = list(width = 0.3),
  position = position_dodge(0.8)
)
```

![](https://i.imgur.com/B8vtxej.png)

<sup>Created on 2020-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by aayushraman** [comment]
Hi @kassambara 

Thanks for the quick reply. I appreciate it. I was wondering if we can get something similar to the following figure, where I can plot both bar and boxplot/violin plot together. 

Thanks!

![example](https://user-images.githubusercontent.com/4062603/78843975-61da2200-79d2-11ea-8278-915c5b6be085.png)

**Comment by kassambara** [comment]
For this type of sophisticated plots - mixing bar plot, violin plot and box plot-, I think that it's better to go with the ggplot2 standard verbs.
