### ISSUE TITLE
ggboxplot wilcox.test error:  cannot compute exact p-value with ties

### ISSUE THREAD

**Issue by Akyanus** [kassambara/ggpubr#254]
Hi,

Thank you for your useful package. I always use it too much. I have a problem about ggboxplot. 

I tried these codes:

`MyData <- read_excel("excell/RawData.xlsx", sheet = "Log", na = "---")
grey_theme <- theme(axis.text.x = element_text(colour = "grey20", size = 10),                     
                    axis.text.y = element_text(colour = "grey20", size = 10),                     
                    legend.position="bottom")
ggboxplot(MyData, x = "BMI", y = "LEPTIN",
          color = "BMI", palette = "jco",
          add = "jitter",
          xlab ="Body Mass Index (BMI)",
          ylab = "Relative LEPTIN mRNA Expression",
          add.params = list(size = 1, jitter = 0.5),
          facet.by = "Sex", short.panel.labs = FALSE)+
  stat_compare_means(comparisons = list(c("BMI<25", "BMI>=25")), method= "wilcox.test", size = 3, label = "p.format")` 

and I had an error: 

Warning messages:
1: In wilcox.test.default(c(1L, 30L, 27L, 29L, 28L, 15L), c(24L, 11L,  :
  cannot compute exact p-value with ties
2: Computation failed in `stat_signif()`:
non-numeric argument to binary operator

I tried lots of ways, but I could not fix it. Can you help me?
![Rplot06](https://user-images.githubusercontent.com/40204216/78587757-17c43580-7846-11ea-8dfe-a7813f3ccd10.jpeg)

**Comment by kassambara** [comment]
Do you still have this issue? If yes, then 1) make sure the y axis variable (Leptin) is considered as numeric in R; 2) please provide a reproducible R script with a demo data so that I can help efficiently
