### ISSUE TITLE
stat_compare_means and pairwise.wilcox.test

### ISSUE THREAD

**Issue by Akyanus** [kassambara/ggpubr#256]
I want to ask a queastion about these. When I calculated p values by stat_compare_means and compare_means, I obtained these p values :

`stat_compare_means( comparisons = list(c("Normal", "Fazla Kilolu"),
                                         c("Fazla Kilolu", "Klas 1 Obezite"),
                                         c("Klas 1 Obezite", "Klas 2 Obezite")),
                      test = "wilcox.test", size = 2, p.adjust.method = "BH")`

.y. | group1 | group2 | p | p.adj | p.format | p.signif | method
<chr> | <chr> | <chr> | <dbl> | <dbl> | <chr> | <chr> | <chr>
FGF23 | Normal | Fazla Kilolu      | 0.462 | 1      | 0.46 | ns | Wilcoxon
FGF23 | Normal | Klas 1 Obezite | 0.847 | 1     | 0.85 | ns | Wilcoxon
FGF23 | Normal | Klas 2 Obezite | 0.596 | 1     | 0.60 | ns | Wilcoxon
FGF23 | Normal | Klas 3 Obezite | 0.231 | 0.92 | 0.23 | ns | Wilcoxon

bu when I used,

pairwise.wilcox.test(Df_FGF23$FGF23, Df_FGF23$BMIL ,
                                p.adjust.method = "BH")

 |   | Fazla kilolu | Klas 1 Obezite | Obezite | Klas 2 Obezite | Klas 3 Obezite
-- | -- | -- | -- | -- | -- | --
Klas 1 | Obezite | 0.81 |   | - |   | - | -
Klas 2 | Obezite | 0.66 |   | 0.66 |   | - | -
Klas 3 | Obezite | 0.66 |   | 0.66 |   | 0.66 | -
Normal |   | 0.66 |   | 0.85 |   | 0.75 | 0.66

When I change p.adjust.method ="BH" to p.adjust.method ="None" in pairwise.wilcox.test, that time I obtain first table. P values are not changing in stat_compare_means with p.adjust.method ="BH".

Why they are different? Can you tell me please?

**Comment by kassambara** [comment]
Same results are obtained using either the ggpubr package or the R base functions. See the script below and make sure you have the latest version of ggpubr

``` r
suppressPackageStartupMessages(library(ggpubr))

# Demo data
data("ToothGrowth")
df <- ToothGrowth
df$dose <- as.factor(df$dose)

# Holm p-value adjustment --------------------------
# Compare means using ggpubr
compare_means(
  len ~ dose, data = df, method = "wilcox.test",
  p.adjust.method = "holm"
  )
#> # A tibble: 3 x 8
#>   .y.   group1 group2            p      p.adj p.format p.signif method  
#>   <chr> <chr>  <chr>         <dbl>      <dbl> <chr>    <chr>    <chr>   
#> 1 len   0.5    1      0.00000702   0.000014   7.0e-06  ****     Wilcoxon
#> 2 len   0.5    2      0.0000000841 0.00000025 8.4e-08  ****     Wilcoxon
#> 3 len   1      2      0.000177     0.00018    0.00018  ***      Wilcoxon

# Compare means using pairwise.wilcox.test
pairwise.wilcox.test(df$len, df$dose, p.adjust.method = "holm")
#> 
#>  Pairwise comparisons using Wilcoxon rank sum test 
#> 
#> data:  df$len and df$dose 
#> 
#>   0.5     1      
#> 1 1.4e-05 -      
#> 2 2.5e-07 0.00018
#> 
#> P value adjustment method: holm

# BH p-value adjustment --------------------------
compare_means(
  len ~ dose, data = df, method = "wilcox.test",
  p.adjust.method = "holm"
)
#> # A tibble: 3 x 8
#>   .y.   group1 group2            p      p.adj p.format p.signif method  
#>   <chr> <chr>  <chr>         <dbl>      <dbl> <chr>    <chr>    <chr>   
#> 1 len   0.5    1      0.00000702   0.000014   7.0e-06  ****     Wilcoxon
#> 2 len   0.5    2      0.0000000841 0.00000025 8.4e-08  ****     Wilcoxon
#> 3 len   1      2      0.000177     0.00018    0.00018  ***      Wilcoxon

# Compare means using pairwise.wilcox.test
pairwise.wilcox.test(df$len, df$dose, p.adjust.method = "holm")
#> 
#>  Pairwise comparisons using Wilcoxon rank sum test 
#> 
#> data:  df$len and df$dose 
#> 
#>   0.5     1      
#> 1 1.4e-05 -      
#> 2 2.5e-07 0.00018
#> 
#> P value adjustment method: holm
```

<sup>Created on 2020-05-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
