### ISSUE TITLE
Bug report: gghistogram() cannot use the paramter "yticks.by"

### ISSUE THREAD

**Issue by Chitanda-Satou** [kassambara/ggpubr#258]
If we use the paramter "yticks.by" to adjust the distances between yticks, it will lead to an error:
![图片](https://user-images.githubusercontent.com/32410912/80080867-c70e4580-8584-11ea-8ce3-2b1078581297.png)

Removing "yticks.by" will work:
![图片](https://user-images.githubusercontent.com/32410912/80080916-d9887f00-8584-11ea-9f48-57ef3f19528f.png)

![图片](https://user-images.githubusercontent.com/32410912/80080995-f1600300-8584-11ea-9fd6-db140b7d6509.png)

sessionInfo() is:
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936    LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                               LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggpubr_0.2.5       magrittr_1.5       ngsrtools_0.2.13   RColorBrewer_1.1-2 corrplot_0.84      readxl_1.3.1       forcats_0.5.0      stringr_1.4.0     
 [9] dplyr_0.8.5        purrr_0.3.4        readr_1.3.1        tidyr_1.0.2        tibble_3.0.1       ggplot2_3.3.0      tidyverse_1.3.0   

loaded via a namespace (and not attached):
 

> [1] httr_1.4.1         jsonlite_1.6.1     splines_3.6.3      modelr_0.1.6       gtools_3.8.2       assertthat_0.2.1   TTR_0.23-6         xlsxjars_0.6.1    
>  [9] cellranger_1.1.0   pillar_1.4.3       backports_1.1.6    lattice_0.20-38    glue_1.4.0         digest_0.6.25      ggsignif_0.6.0     rvest_0.3.5       
> [17] colorspace_1.4-1   Matrix_1.2-18      pkgconfig_2.0.3    broom_0.5.6        haven_2.2.0        scales_1.1.0       gdata_2.18.0       generics_0.0.2    
> [25] farver_2.0.3       ellipsis_0.3.0     withr_2.1.2        ROCR_1.0-7         DMwR_0.4.1         cli_2.0.2          quantmod_0.4.17    survival_3.1-8    
> [33] crayon_1.3.4       fs_1.4.1           fansi_0.4.1        nlme_3.1-144       gplots_3.0.3       xts_0.12-0         xml2_1.3.1         class_7.3-15      
> [41] tools_3.6.3        data.table_1.12.8  hms_0.5.3          lifecycle_0.2.0    xlsx_0.6.3         munsell_0.5.0      reprex_0.3.0       maftools_2.2.10   
> [49] compiler_3.6.3     caTools_1.18.0     rlang_0.4.5        grid_3.6.3         rstudioapi_0.11    bitops_1.0-6       labeling_0.3       gtable_0.3.0      
> [57] abind_1.4-5        DBI_1.1.0          curl_4.3           R6_2.4.1           zoo_1.8-7          lubridate_1.7.8    KernSmooth_2.23-16 rJava_0.9-12      
> [65] stringi_1.4.6      Rcpp_1.0.4.6       vctrs_0.2.4        rpart_4.1-15       wordcloud_2.6      dbplyr_1.4.3       tidyselect_1.0.0

**Comment by kassambara** [comment]
Fixed now, thanks! 

The latest dev version can be installed using: `devtools::install_github("kassambara/ggpubr")`

``` r
library(ggpubr)
# Set y ticks step
# Use this
gghistogram(iris, x = "Sepal.Length", fill = "lightgray",
            yticks.by = 2)
```

![](https://i.imgur.com/YfnBekH.png)

``` r
# Or this
gghistogram(iris, x = "Sepal.Length", fill = "lightgray") +
  scale_y_continuous(breaks = get_breaks(by = 2, from = 0))
```

![](https://i.imgur.com/Ptwdg5z.png)

<sup>Created on 2020-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
