### ISSUE TITLE
New functions not in ggpubr e.g. get_summary_stats

### ISSUE THREAD

**Issue by sfeds** [kassambara/ggpubr#259]
Hi,

I'm checking out the plots with summary statistics, but it doesn't seem to recognize some of the necessary functions e.g. get_summary_stats or ggsummarystats.
I seem to have the latest versions:
```{r}
> packageVersion("ggpubr")
[1] ‘0.2.5’
> packageVersion("rstatix")
[1] ‘0.4.0’
```

Maybe not in yet? Thanks!

**Comment by sfd99** [comment]
I had the sane problem, unfortunately...

Also tried installing 
**ggpubr** and **rstatix** pkgs
from **GITHUB**.

No luck...
From CRAN, 
the older version of ggpubr installs.
But from GITHUB,
the new (latest ggpubr) does not even install...

Argh!. :-(

**SFd99
Ubuntu LINUX 18.04, 
latest versions of Rstudio and R (v3.6.3).**

**Comment by kassambara** [comment]
Hi, you need the latest  dev version  of rstatix and ggpubr from github.

CRAN release planned for next week.

**Comment by sfd99** [comment]
**Hi Kassambara,**
 thanks f/ the quick reply.

Watch this R flow:

> devtools::install_github("kassambara/ggpubr",force=TRUE)
Downloading GitHub repo kassambara/ggpubr@master
✓  checking for file ‘/tmp/RtmphD9MqJ/remotes1e6940867451/kassambara-ggpubr-0df7aee/DESCRIPTION’ (1.9s)
─  preparing ‘ggpubr’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘ggpubr_0.2.5.999.tar.gz’
   
Installing package into ‘/home/ray/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘ggpubr’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (ggpubr)
> **library(ggpubr)**
Error: package or namespace load failed for ‘ggpubr’:
 object ‘df_arrange’ is not exported by 'namespace:rstatix'


**SFd99
Ubuntu LINUX 18.04,
latest versions of Rstudio and R (v3.6.3).**

**Comment by kassambara** [comment]
The ggpubr dev version depends on the dev version of rstatix package:

Please try this: 

```r
 devtools::install_github("kassambara/rstatix", force=TRUE)
 devtools::install_github("kassambara/ggpubr", force=TRUE)
```

**Comment by sfd99** [comment]
ok - trying, just a minute...

**Comment by sfd99** [comment]
> devtools::install_github("kassambara/rstatix", force=TRUE)
OK -  rstatix 0.5.0.99 installed!

> devtools::install_github("kassambara/ggpubr", force=TRUE)
OK -  ggpubr 0.4.0.99 seems to have installed!...

BUT THEN...
>  library(rstatix)
Attaching package: ‘rstatix’

The following object is masked from ‘package:janitor’:

    make_clean_names

The following object is masked from ‘package:stats’:

    filter

> library(ggpubr)
Error: package or namespace load failed for ‘ggpubr’ in get(method, envir = home):
 lazy-load database '/home/ray/R/x86_64-pc-linux-gnu-library/3.6/ggpubr/R/ggpubr.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
>

**Comment by kassambara** [comment]
Is this error reproducible after restarting R ?

**Comment by sfd99** [comment]
Ok, Kassambara, will restart R and Rstudio
from scratch. 
pls wait a minute...

**Comment by sfd99** [comment]
Ok, closed Rstudio and R _completely_
and restarted Rstudio....

Then:
> library(rstatix)

Attaching package: ‘rstatix’

The following object is masked from ‘package:janitor’:

    make_clean_names

The following object is masked from ‘package:stats’:

    filter

> library(ggpubr)
> 

**_Yay!  (no error messages...)_**


# Basic plot
ggsummarystats(
  df, x = "dose", y = "len", 
  ggfunc = ggboxplot, add = "jitter"
  )

Beautiful, Kassambara plot comes up!.
So, restarting Rstudio solved the problem.

I wondered why that happened.
I had installed BOTH **dev** pkgs from GITHUB,
as prescribed.
Do you need to restart RSTUDIO after
installing from GITHUB always...?.

**Comment by kassambara** [comment]
Sometimes trying to re-install an previously loaded package might end up with an error. In this case restarting a clean session can help.

so, we can close this issue. CRAN release is planned next week

**Comment by sfd99** [comment]
Thank you Kassambara!.
You and your R blog 
are **absolutely great**.

last Q:
if I have the GITHUB pkgs installed,
will the Rstudio "Update Packages" mechanism
update the latest pkg version from CRAN?.
Or,
should I first delete "manually" the GIT dev version
and then re-install the pkg from CRAN?.

what do you suggest?

**Comment by sfeds** [comment]
Aha! We were just faster than CRAN :)
Thanks!

**Comment by sfeds** [comment]
Hi again,

Can it be that it needs R version 3.6.3?
I have tried all updates needed, but still get this:

```{r}
* installing *source* package 'ggpubr' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'ggpubr'
```

I can't change my R version (this is done for my institute by support personnel), so just wondering if there's a way to go around it? (If this is the issue at all).
Thanks!

**Comment by kassambara** [comment]
You don't need to delete manually the GIT version. Using  install.packages("ggpubr"), will automatically delete the already installed (GIT/CRAN) version and install the latest version on CRAN

**Comment by domestosi** [comment]
Hi Everyone,

I had the same problem, then I ran the following code (a bit extended that @kassambara wrote above):
install.packages("ggpubr", dependencies = TRUE)

It installed every package I needed to create a boxplot with summary statistics.

Hope it helps!
Alex
