### ISSUE TITLE
strange result from stat_compare_means()

### ISSUE THREAD

**Issue by Gian77** [kassambara/ggpubr#26]
Good morning,
I am using ggpubr to add significance to my ggbarplot but I am having contrasting results form stat_compare_means(method = "kruskal.test", ...) and the basic function kruskal.test() when used on the same set of data. 
Please see below for details:

> head(data.test)
> data.test$site <- as.factor(data.test$site)

> head(data.tmel.eur)
sampleID readNO_Tmel   abund_ecm  abund_whol continent            site   b management              site_b
1  EU_ITS_35B           0  0.00000000 0.000000000    Europe EA  inside cultivated  EA.inside
2 EU_ITS_35HB           0  0.00000000 0.000000000    Europe EA outside cultivated EA.outside
3  EU_ITS_42B         935 79.91452991 6.274746661    Europe EA  inside cultivated  EA.inside
4 EU_ITS_42HB           0  0.00000000 0.000000000    Europe EA outside cultivated EA.outside
5  EU_ITS_44B         688 40.16345593 2.988705474    Europe EA  inside cultivated  EA.inside
6 EU_ITS_44HB           1  0.09532888 0.004022688    Europe EA outside cultivated EA.outside

>my_comparisons <- list(c("EA.inside","EA.outside"),c("EB.inside","EB.outside"),c("EC.inside","EC.outside"),c("ED.inside","ED.outside"),
                       c("EE.inside","EE.outside"),c("EF.inside","EF.outside"),c("EG.inside","EG.outside"),c("EH.inside","EH.outside"), 
                       c("EI.inside","EI.outside"),c("EL.inside","EL.outside"),c("EM.inside","EM.outside"),c("EN.inside","EN.outside"), 
                       c("EP.inside","EP.outside"))

>ggbarplot(data.test, x = "site_b", y="readNO_Tmel", fill="b", add="mean_se", 
          position=position_dodge(0.8), legend="none") +
stat_compare_means(method = "kruskal.test", label.x.npc=0.1, label.y =15000) + 
stat_compare_means(method = "wilcox.test", comparisons = my_comparisons, label = "p.signif",label.y =13000) +
scale_fill_manual(values = brewer.pal(4, "Paired")[1:2]) +
labs(title="Europe", x="Site", y="Read number") +
theme(plot.title = element_text(hjust = 0.5, face="bold")) +
theme(axis.title = element_text(face="bold")) +  
scale_y_continuous(breaks = seq(0, 16000, 2000)) +
theme(axis.text.x = element_text(size=8)) +
theme(axis.text.y = element_text(size=8)) +
rotate_x_text(angle = 45)

[dist_across-site_EUR.pdf](https://github.com/kassambara/ggpubr/files/1249299/dist_across-site_EUR.pdf)

On the barplot graph I have Kruskal−Wallis, p < 2.2e−16 which is very close to zero and so a very significant test result, but when I am doing it by using the standard function I have

> data.test$site <- as.factor(data.test$site)
> kruskal.test(data.test$readNO_Tmel ~ data.test$site)

	Kruskal-Wallis rank sum test

data:  data.test$readNO_Tmel by data.test$site
Kruskal-Wallis chi-squared = 18.517, df = 12, p-value = 0.1009

That is a very different result from what reported by the stat_compare_means()
Can you please tell me where is my mistake?
Thanks,
G.

**Comment by kassambara** [comment]
Hi,

Please, make sure that, you have the latest ggpubr version.

With the latest version of ggpubr ( 0.1.5),  this problem is not reproducible on my computer.

- Create a barplot with p-value

```r
library(ggpubr)
myeloma <- read.delim("https://raw.githubusercontent.com/kassambara/data/master/myeloma.txt")
my_comparisons <- list(c("cyclin.d.1", "cyclin.d.2"),
                       c("hyperdiploid", "low.bone.disease"),
                       c("mmset", "proliferation")
                       )
ggbarplot(myeloma, x = "group", y = "TP53", add = "mean_se")+
  stat_compare_means(method = "kruskal.test", label.x.npc=0.1, label.y =2500)+
  stat_compare_means(method = "wilcox.test", comparisons = my_comparisons, label = "p.signif", label.y =2100)+
  rotate_x_text(45)
``` 
![rplot](https://user-images.githubusercontent.com/3313355/29676246-d1fb0db6-88f7-11e7-963e-f5f843b30e9b.png)


- Basic  kruskal.test

```r
kruskal.test(TP53 ~ group, data = myeloma)
```

```

	Kruskal-Wallis rank sum test

data:  TP53 by group
Kruskal-Wallis chi-squared = 35.133, df = 6, p-value = 4.062e-06
```

So, It works.

If you still have this problem, then send me the data with a reproducible R script and your devtools::session_info().

With regards,

**Comment by Gian77** [comment]
Hi Alboukadel,
I have updated my ggpubr but I have the same issue.
I can send you the dataset, can I have you email address?
Thank will be helpful,
Thanks,
G.

> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.143)           
 language en_CA:en                    
 collate  en_CA.UTF-8                 
 tz       America/Toronto             
 date     2017-08-24                  

Packages ---------------------------------------------------------------------------------------------------------------------
 package        * version   date       source                            
 ade4             1.7-6     2017-03-23 CRAN (R 3.4.0)                    
 ape              4.1       2017-02-14 CRAN (R 3.4.0)                    
 assertthat       0.2.0     2017-04-11 CRAN (R 3.4.0)                    
 base           * 3.4.1     2017-07-08 local                             
 bindr            0.1       2016-11-13 CRAN (R 3.4.0)                    
 bindrcpp       * 0.2       2017-06-17 cran (@0.2)                       
 Biobase        * 2.36.2    2017-06-14 Bioconductor                      
 BiocGenerics   * 0.22.0    2017-06-14 Bioconductor                      
 biomformat       1.4.0     2017-06-14 Bioconductor                      
 Biostrings       2.44.1    2017-06-15 Bioconductor                      
 bitops           1.0-6     2013-08-17 CRAN (R 3.4.0)                    
 caTools          1.17.1    2014-09-10 CRAN (R 3.4.0)                    
 cluster          2.0.6     2017-03-16 CRAN (R 3.4.0)                    
 codetools        0.2-15    2016-10-05 CRAN (R 3.3.1)                    
 colorspace       1.3-2     2016-12-14 CRAN (R 3.4.0)                    
 compiler         3.4.1     2017-07-08 local                             
 data.table       1.10.4    2017-02-01 CRAN (R 3.4.0)                    
 datasets       * 3.4.1     2017-07-08 local                             
 devtools       * 1.13.3    2017-08-02 CRAN (R 3.4.1)                    
 digest           0.6.12    2017-01-27 CRAN (R 3.4.0)                    
 dplyr            0.7.2     2017-07-20 cran (@0.7.2)                     
 foreach        * 1.4.3     2015-10-13 CRAN (R 3.4.0)                    
 futile.logger  * 1.4.3     2016-07-10 CRAN (R 3.4.0)                    
 futile.options   1.0.0     2010-04-06 CRAN (R 3.4.0)                    
 gdata            2.18.0    2017-06-06 CRAN (R 3.4.0)                    
 ggplot2        * 2.2.1     2016-12-30 CRAN (R 3.4.0)                    
 ggpubr         * 0.1.5.999 2017-08-24 Github (kassambara/ggpubr@6f13072)
 ggrepel        * 0.6.5     2016-11-24 CRAN (R 3.4.0)                    
 ggsignif       * 0.4.0     2017-08-03 cran (@0.4.0)                     
 glmnet         * 2.0-10    2017-05-06 CRAN (R 3.4.0)                    
 glue             1.1.1     2017-06-21 cran (@1.1.1)                     
 gplots           3.0.1     2016-03-30 CRAN (R 3.4.0)                    
 graphics       * 3.4.1     2017-07-08 local                             
 grDevices      * 3.4.1     2017-07-08 local                             
 grid           * 3.4.1     2017-07-08 local                             
 gtable           0.2.0     2016-02-26 CRAN (R 3.4.0)                    
 gtools           3.5.0     2015-05-29 CRAN (R 3.4.0)                    
 htmltools        0.3.6     2017-04-28 CRAN (R 3.4.0)                    
 htmlwidgets      0.8       2016-11-09 CRAN (R 3.4.0)                    
 httr             1.2.1     2016-07-03 CRAN (R 3.4.0)                    
 igraph           1.0.1     2015-06-26 CRAN (R 3.4.0)                    
 IRanges          2.10.2    2017-06-14 Bioconductor                      
 iterators        1.0.8     2015-10-13 CRAN (R 3.4.0)                    
 jsonlite         1.5       2017-06-01 CRAN (R 3.4.0)                    
 KernSmooth       2.23-15   2015-06-29 CRAN (R 3.4.0)                    
 lambda.r         1.1.9     2016-07-10 CRAN (R 3.4.0)                    
 lattice        * 0.20-35   2017-03-25 CRAN (R 3.4.0)                    
 lazyeval         0.2.0     2016-06-12 CRAN (R 3.4.0)                    
 limma          * 3.32.2    2017-06-14 Bioconductor                      
 magrittr       * 1.5       2014-11-22 CRAN (R 3.4.0)                    
 MASS             7.3-47    2017-04-21 CRAN (R 3.4.0)                    
 Matrix         * 1.2-11    2017-08-16 CRAN (R 3.4.1)                    
 matrixStats      0.52.2    2017-04-14 CRAN (R 3.4.0)                    
 memoise          1.1.0     2017-04-21 CRAN (R 3.4.0)                    
 metagenomeSeq  * 1.18.0    2017-06-14 Bioconductor                      
 methods        * 3.4.1     2017-07-08 local                             
 mgcv             1.8-18    2017-07-28 CRAN (R 3.4.1)                    
 multtest         2.32.0    2017-06-14 Bioconductor                      
 munsell          0.4.3     2016-02-13 CRAN (R 3.4.0)                    
 nlme             3.1-131   2017-02-06 CRAN (R 3.4.0)                    
 parallel       * 3.4.1     2017-07-08 local                             
 permute        * 0.9-4     2016-09-09 CRAN (R 3.4.0)                    
 phyloseq         1.20.0    2017-06-14 Bioconductor                      
 pkgconfig        2.0.1     2017-03-21 CRAN (R 3.4.0)                    
 plotly         * 4.7.0     2017-05-28 CRAN (R 3.4.1)                    
 plyr             1.8.4     2016-06-08 CRAN (R 3.4.0)                    
 purrr            0.2.3     2017-08-02 cran (@0.2.3)                     
 R6               2.2.2     2017-06-17 cran (@2.2.2)                     
 RColorBrewer   * 1.1-2     2014-12-07 CRAN (R 3.4.0)                    
 Rcpp             0.12.12   2017-07-15 cran (@0.12.12)                   
 reshape2       * 1.4.2     2016-10-22 CRAN (R 3.4.0)                    
 rhdf5            2.20.0    2017-06-14 Bioconductor                      
 rJava          * 0.9-8     2016-01-07 CRAN (R 3.2.3)                    
 rlang            0.1.2     2017-08-09 cran (@0.1.2)                     
 rstudioapi       0.6       2016-06-27 CRAN (R 3.4.1)                    
 S4Vectors        0.14.3    2017-06-14 Bioconductor                      
 scales           0.5.0     2017-08-24 cran (@0.5.0)                     
 splines          3.4.1     2017-07-08 local                             
 stats          * 3.4.1     2017-07-08 local                             
 stats4           3.4.1     2017-07-08 local                             
 stringi          1.1.5     2017-04-07 CRAN (R 3.4.0)                    
 stringr        * 1.2.0     2017-02-18 CRAN (R 3.4.0)                    
 survival         2.41-3    2017-04-04 CRAN (R 3.4.0)                    
 tibble           1.3.4     2017-08-22 cran (@1.3.4)                     
 tidyr          * 0.7.0     2017-08-16 cran (@0.7.0)                     
 tidyselect       0.1.1     2017-07-24 cran (@0.1.1)                     
 tools            3.4.1     2017-07-08 local                             
 utils          * 3.4.1     2017-07-08 local                             
 vegan          * 2.4-3     2017-04-07 CRAN (R 3.4.0)                    
 VennDiagram    * 1.6.17    2016-04-18 CRAN (R 3.4.0)                    
 venneuler      * 1.1-0     2011-08-10 CRAN (R 3.4.1)                    
 viridisLite      0.2.0     2017-03-24 CRAN (R 3.4.0)                    
 withr            2.0.0     2017-07-28 CRAN (R 3.4.1)                    
 XVector          0.16.0    2017-06-14 Bioconductor                      
 zlibbioc         1.22.0    2017-06-14 Bioconductor

**Comment by kassambara** [comment]
alboukadel.kassambara@gmail.com

Please send also a reproducible script with data, thanks.

**Comment by Gian77** [comment]
Never mind. I had it fixed :) It was my fault. I was using the a different variable for kruskal.test() 
You can close this issue ticket if you want. And thank you for the really useful package!
Gian

> kruskal.test(data.test$readNO_Tmel ~ data.test$site_b)

	Kruskal-Wallis rank sum test

>data:  data.test$readNO_Tmel by data.test$site_b
>Kruskal-Wallis chi-squared = 158.28, df = 25, p-value < 2.2e-16

**Comment by kassambara** [comment]
Ok!!
