### ISSUE TITLE
ggline "combine" and "merge" does not work as expected

### ISSUE THREAD

**Issue by jiehuang001** [kassambara/ggpubr#262]
Hi, there:

I was able to use **ggline** and **combine=T** to generate a nice plot. The R code is as below:
**ggline(dat, x="grp", y=c("phe1","phe2","phe3","phe4"), combine=T, add="mean_se", color="race", palette = "jco")**

And the plot is shown as below:
![111](https://user-images.githubusercontent.com/26947455/80425307-fb338e80-8915-11ea-8e5e-3a5f86df372b.png)

However, this plot does not look good, because my 4 phenotypes have very different values. Is there a way for each plot to have its own ylab based on its values so that each plot has a much better resolution?

I also tried the "**merge=T**" option, which is supposed to plot all my 4 phenotypes in a single panel. However, I got an error message saying that "_**More than one expression parsed**_". 

Can you please kindly let me know how to scale the Y-axis automatically for each plot, or how to merge the 4 plots into a single panel?

Thank you & best regards,
Jie

**Comment by kassambara** [comment]
Please consider using the option `scales = "free_y"`.

``` r
library(ggpubr)
ggline(
  iris, x = "Species", y = c("Sepal.Length", "Petal.Length"),
  combine = TRUE, add = "mean_se",
  scales = "free_y"
  ) +
  rotate_x_text(45)
```

![](https://i.imgur.com/hDgLc5J.png)

<sup>Created on 2020-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jiehuang001** [comment]
Thank you very much!

scales = "free_y" works great!

But I am still wondering why "merge=T" does not work as expected.

Best regards,
Jie

**Comment by kassambara** [comment]
Merge works as illustrated below:

``` r
library(ggpubr)
ggline(
  iris, x = "Species", y = c("Sepal.Length", "Petal.Length"),
  merge = TRUE, add = "mean_se",
  scales = "free_y"
) +
  rotate_x_text(45)
```


![](https://i.imgur.com/AxoeWQf.png)

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Please provide a reproducible R script

**Comment by jiehuang001** [comment]
Thanks again!

Please see my plot below. Besides "x=" and "y=", I also used "color=" to add another dimension to the plot. Therefore, when I use the "combine=T" option, each panel has multiple lines, not just one line as shown in your plots. 

![捕获](https://user-images.githubusercontent.com/26947455/81029443-8d5c0980-8eb7-11ea-90c0-8f536ff30d4b.JPG)

Now, if I change "combine=T" to "merge=T", I got the error message: More than one expression parsed; Run `rlang::last_error()` to see where the error occurred.

Best regadrs,
Jie
