### ISSUE TITLE
compare_means should also return F value, chi square, W value, etc.

### ISSUE THREAD

**Issue by seal20** [kassambara/ggpubr#263]
First let me thank you for your package and blog posts that are very clear.

It would be nice if compare_means would also return, for example in the case of ANOVA, nicely in a tibble the F value, degree of freedom and residuals, or in the case of the wilcox.test the W value, and so on for the different tests. 
It is very useful to get the p value formatted in a nice tibble to insert later on graphs but I also like to insert the surrounding stat, and these are required for in the manuscript. I understand that many people would not include them, and that is fine to not return them in stat_compare_means.

Thanks for your consideration, for the moment I will use my "manual" method.

**Comment by kassambara** [comment]
Please consider using the functions `anova_test()`, `t_test()` and `wilcox_test()` available in  my R package named `rstatix`.  

Many tutorials are available on Datanovia for comparing means and displaying p-values : [Comparing Means in R](https://www.datanovia.com/en/classes/comparing-means-in-r/)

In the near future, the function compare_means() will be rewritten and will depend to the above mentioned functions.


Some examples of rstatix usage:

``` r
library(rstatix)

# Load data
#:::::::::::::::::::::::::::::::::::::::
data("ToothGrowth")
df <- ToothGrowth


# Two-samples unpaired test
#:::::::::::::::::::::::::::::::::::::::::
df %>% t_test(len ~ supp, detailed = TRUE)
#> # A tibble: 1 x 15
#>   estimate estimate1 estimate2 .y.   group1 group2    n1    n2 statistic      p
#> *    <dbl>     <dbl>     <dbl> <chr> <chr>  <chr>  <int> <int>     <dbl>  <dbl>
#> 1     3.70      20.7      17.0 len   OJ     VC        30    30      1.92 0.0606
#> # … with 5 more variables: df <dbl>, conf.low <dbl>, conf.high <dbl>,
#> #   method <chr>, alternative <chr>

# Compare supp levels after grouping the data by "dose"
#::::::::::::::::::::::::::::::::::::::::
df %>%
  group_by(dose) %>%
  t_test(len ~ supp) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj")
#> # A tibble: 3 x 11
#>    dose .y.   group1 group2    n1    n2 statistic    df       p   p.adj
#> * <dbl> <chr> <chr>  <chr>  <int> <int>     <dbl> <dbl>   <dbl>   <dbl>
#> 1   0.5 len   OJ     VC        10    10    3.17    15.0 0.00636 0.0191 
#> 2   1   len   OJ     VC        10    10    4.03    15.4 0.00104 0.00312
#> 3   2   len   OJ     VC        10    10   -0.0461  14.0 0.964   1      
#> # … with 1 more variable: p.adj.signif <chr>


# One-way ANOVA test
#:::::::::::::::::::::::::::::::::::::::::
df %>% anova_test(len ~ dose)
#> ANOVA Table (type II tests)
#> 
#>   Effect DFn DFd       F        p p<.05   ges
#> 1   dose   1  58 105.065 1.23e-14     * 0.644

# Grouped One-way ANOVA test
#:::::::::::::::::::::::::::::::::::::::::
df %>%
  group_by(supp) %>%
  anova_test(len ~ dose)
#> # A tibble: 2 x 8
#>   supp  Effect   DFn   DFd     F        p `p<.05`   ges
#>   <fct> <chr>  <dbl> <dbl> <dbl>    <dbl> <chr>   <dbl>
#> 1 OJ    dose       1    28  36.0 1.82e- 6 *       0.563
#> 2 VC    dose       1    28 118.  1.51e-11 *       0.808
```

<sup>Created on 2020-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
