### ISSUE TITLE
How can I add p value (FDR) calculated elsewhere (RNA-seq experiment) to ggplot

### ISSUE THREAD

**Issue by AnnaCot** [kassambara/ggpubr#265]
could you please provide me with solution to add a p value which I will not calculate with compare_means?
I have 3 different groups  "low" "middle" "high" and FDR values of 7.78e-12 (low-high), 2.12e-5 (low-middle), 0.08 (middle-high)

Additionally, how can I add the text with p-value over the groups (like in case of Kruskal-Wallis), 
my over the groups p=8.4e-17

Thank you!

**Comment by atakanekiz** [comment]
You could probably use ggplot functionality to add annotation layers. There are good examples at @kassambara's [website](http://www.sthda.com/english/wiki/ggplot2-texts-add-text-annotations-to-a-graph-in-r-software)

**Comment by kassambara** [comment]
This blog post might help: 

[GGPUBR: How to Add P-Values Generated Elsewhere to a GGPLOT](https://www.datanovia.com/en/blog/ggpubr-how-to-add-p-values-generated-elsewhere-to-a-ggplot/)

**Comment by kassambara** [comment]
``` r
library(ggpubr)

# Data preparation
df <- ToothGrowth
df$dose <- factor(df$dose)

# p-values
stat.test <- tibble::tribble(
  ~group1, ~group2,   ~p.adj,
  "0.5",     "1", 2.54e-07,
  "0.5",     "2", 1.32e-13,
  "1",     "2", 1.91e-05
)
stat.test
#> # A tibble: 3 x 3
#>   group1 group2    p.adj
#>   <chr>  <chr>     <dbl>
#> 1 0.5    1      2.54e- 7
#> 2 0.5    2      1.32e-13
#> 3 1      2      1.91e- 5

# Box plots + p-values
ggboxplot(df, x = "dose", y = "len") +
  stat_pvalue_manual(
    stat.test, 
    y.position = 35, step.increase = 0.1,
    label = "p.adj"
  )
```

![](https://i.imgur.com/s2Wxy12.png)

<sup>Created on 2020-05-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
