### ISSUE TITLE
Suggested feature: change common.legend in ggarrange to suit plots that show subsets of some series

### ISSUE THREAD

**Issue by jmwhyte** [kassambara/ggpubr#268]
Suppose I have a grid of ggplots, two rows and two columns. 
The data has a number of series. Each plot in the grid may not plot all of these series if some
conditions are not satisfied.
Suppose I want to use ggarrange to do something like:
ggpubr::ggarrange(gg1, gg2, gg3, gg4, ncol=2, nrow=2, common.legend = TRUE)

In the case described, the colour scheme for the geom_point/geom_line commands used in each individual ggplot, e.g. as required with geom_point(aes(color=important.variable)), was not consistent across the four graphs.

I'd appreciate an extension that allowed consistent use of colours and a displayed common legend that can accommodate this, even if plots may contain only a subset of the entirety of series. I'd also appreciate it if this extension can accommodate a blank plot, as could happen
when we have say three plots to show in a 2x2 grid.

**Comment by kassambara** [comment]
Would it be possible to have a reproducible script using a built-in R demo data such as `ToothGrowth` , `iris`, etc?

Using the [reprex ](https://reprex.tidyverse.org/index.html) R package makes it easy to create and submit a reproducible R script into github.

**Comment by kassambara** [comment]
The primmary usage of the `common.legend` option is illustrated below.  The aim is to avoid unnecessary duplications of identical legends when combining multiple plots with the same legend scheme.


``` r
library(ggpubr)
# Create multiple box plots
sepal.bxp <- ggboxplot(iris, x = "Species", y = "Sepal.Length", color = "Species")
petal.bxp <- ggboxplot(iris, x = "Species", y = "Petal.Length", color = "Species")

# Arrange into one figure
ggarrange(sepal.bxp, petal.bxp)
```

![](https://i.imgur.com/P1rR4Nq.png)

``` r

# Use common legend to simplify the figure
ggarrange(sepal.bxp, petal.bxp, common.legend = TRUE)
```

![](https://i.imgur.com/FQqWVtn.png)

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Any other suggestions/options are welcome.

**Comment by jmwhyte** [comment]
As I misunderstood the intent of the ggarrange, I have amended the original comment so that it is now a feature request, not a note on a possible bug.

**Comment by kassambara** [comment]
It appears hard to guess  which plot is a subset and which one is the full dataset without the end user inputs. 

It seems that your issue can be fixed using the standard ggplot2 verbs as described below. If the suggested solution is Ok for you, then we can close the issue.

``` r
# Packages
library(ggpubr)
library(dplyr)

# Settings: group colors
my_grps <- levels(iris$Species)
my_grps
#> [1] "setosa"     "versicolor" "virginica"

my_colors <- get_palette(k = 3)
names(my_colors) <- my_grps
my_colors
#>      setosa  versicolor   virginica 
#> "#F8766DFF" "#00BA38FF" "#619CFFFF"

# Create plots
gg1 <- ggplot(iris, aes(x = Sepal.Length, y=Sepal.Width, group=Species)) +
  geom_line(aes(color = Species)) +
  geom_point(aes(color = Species)) + 
  ggtitle("all three Species")
gg1
```

![](https://i.imgur.com/QDSTPOm.png)

``` r

# removing setosa species
filtered.iris.no.setosa <- dplyr::filter(iris, Species != "setosa") %>%
  droplevels()
remaining_grps <- levels(filtered.iris.no.setosa$Species)
remaining_grps
#> [1] "versicolor" "virginica"
gg2 <- ggplot(filtered.iris.no.setosa, aes(x=Sepal.Length, y=Sepal.Width, group=Species)) + 
  geom_line(aes(color = Species)) + 
  geom_point(aes(color = Species)) + 
  ggtitle("no Setosa")
gg2
```

![](https://i.imgur.com/Qbwgw7Q.png)

``` r

# Make gg2 color consitent with gg1
gg2_consistent <- gg2 + scale_color_manual(values = my_colors[remaining_grps])
gg2_consistent
```

![](https://i.imgur.com/A5Qjpvm.png)

``` r

# Arrange gg1 and gg2_consitent into one figure
# the legend of the firt ggplot is used as the legend of the final figure
ggarrange(gg1, gg2_consistent, common.legend = TRUE)
```

![](https://i.imgur.com/fhFKHxr.png)

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jmwhyte** [comment]
This proposed approach is good, thanks, but is not (yet?) a completely
general solution.

For example, suppose I wish to use RColorBrewer so as to plot
graphs with a colour-blind friendly palette.
Then, I need to replace
scale_color_manual(values = my_colors[remaining_groups])
by first defining my palette:
my_colors <- brewer.pal(n = 3, name = "Paired")

but the obvious command to add to ggplot:
scale_color_brewer(palette = my_colors[remaining_groups])

throws a warning and does not give the desired result.
The command is expecting a name for a palette, not a vector of values, and doesn't
like the restriction we wish to impose.

A remedy to this issue would be very useful.


Jason Whyte
Research Fellow _ Mathematics of Biosecurity
CEBRA, School of BioSciences, and
Associate Investigator at ACEMS
School of Mathematics and Statistics
The University of Melbourne 3010
Victoria AUSTRALIA
________________________________

**Comment by kassambara** [comment]
The function `brewer.pal(n = 3, name = "Paired")` generates a vector of colors. 

To apply any vector of color palette to a ggplot, please consider using the function **`scale_color_manual()`** as I illustrated above.

**Comment by larturr** [comment]
> # the legend of the firt ggplot is used as the legend of the final figure
> ggarrange(gg1, gg2_consistent, common.legend = TRUE)
> Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)

Dear @kassambara,
Sorry for this comment in a closed issue but I think maybe you could help me.
I wonder how the **gg_arrange** could use a list of legend levels of all plots (not only the first one). 
Thanks in advance.

**Comment by ElmoreEcology** [comment]
This solution only works when you plot the subset or filtered plot second. If you plot the one with 2 species first, the common.legend=TRUE argument takes the legend from the first plot in the series. Thus, you're left with a legend with 2 species.
