### ISSUE TITLE
Lollipop ggdotplot not displaying financial year in order

### ISSUE THREAD

**Issue by genghiskhanofnz** [kassambara/ggpubr#269]
Hi Kassmbara
My data contains knee replacements n by separation financial year with the "-" as well as character vector from 2013 to 2020.
ggdotplot fails to display those years in order with the codes below.

separation_fin_year is factorised with levels ascending.

ggdotchart(knee_n, 
           x = 'separation_fin_year',
           y = 'n',
           add = 'segments',
           dot.size = 4,
           label = 'n')

Please advise what is going wrong.
Thanks.
[knee_n.txt](https://github.com/kassambara/ggpubr/files/4596888/knee_n.txt)

**Comment by kassambara** [comment]
The default is to sort data values in ascending order. To avoid this, you need to specify the option sorting = "none"

**Comment by genghiskhanofnz** [comment]
I am using ggpubr 0.3.0
No option to put 'none' under sorting.
Can you please add it and thanks?

**Comment by kassambara** [comment]
This option is available in the github dev version (https://github.com/kassambara/ggpubr/commit/e4e435f08613cf3dafb4c490fea647748af7d0eb), which can be installed using `devtools::install_github("kassambara/ggpubr")`
