### ISSUE TITLE
ref.group must be displayed first in plot

### ISSUE THREAD

**Issue by sehufnkjesktgna** [kassambara/ggpubr#27]
When annotating ggplot2, the ref.group must precede other groups for significance measures to display.

stat_compare_means(ref.group = "1", label = "p.signif") +

If the ref.group is the last group, none of the other groups display significance measures.

**Comment by kassambara** [comment]
Fixed now. Thank you for pointing this out.

**Comment by sehufnkjesktgna** [comment]
Thanks!!
