### ISSUE TITLE
round coefficients in stat_regline_equation

### ISSUE THREAD

**Issue by fred-oswald** [kassambara/ggpubr#273]
Hello - I'd like to round coefficients in stat_regline_equation...in particular, I have an intercept near-zero that reports out as 6 * 10^-18 in scientific notation...thank you for considering (and sorry if I missed the option to do this!)

...also would like to suppress the leading 0 in the R2 value...thanks again!

**Comment by fred-oswald** [comment]
I can round slopes and intercepts in the formula object...this works fine....

**Comment by kassambara** [comment]
thanks
