### ISSUE TITLE
Generating stacked barplot representing proportion.

### ISSUE THREAD

**Issue by singcell** [kassambara/ggpubr#274]
I wanted to use your package to generate stacked barplot representing proportion with flow between two groups. Would it be possible to generate something like below?
THank you 

![image](https://user-images.githubusercontent.com/61842606/82136214-d1f97600-97d0-11ea-82b5-19a5202d5831.png)

**Comment by kassambara** [comment]
Your contribution is welcome if you have the R code producing this type of plot

**Comment by kassambara** [comment]
closed because of lack of activity
