### ISSUE TITLE
[feature request]: "alternative" argument in stat_cor

### ISSUE THREAD

**Issue by vorpalvorpal** [kassambara/ggpubr#276]
The stat_cor() function uses the cor.test() function internally. It would be useful if stat_cor() was able to pass an argument to cor.test() to specify the alternative argument (alternative = c("two.sided", "less", "greater")).

This is a simple fix and I'm happy to put together a pull request if you are happy to include it.

**Comment by kassambara** [comment]
thank you for pointing this out! Yes, your pull request is welcome!

**Comment by kassambara** [comment]
fixed now, thanks
