### ISSUE TITLE
ggpie legend position not changing

### ISSUE THREAD

**Issue by MichaelPeibo** [kassambara/ggpubr#277]
Hi, I am using ggpie and I found legend position could not be changed. Here is code:
```
ggpie(
  df, "ratio", label = "pielabels", lab.pos = "in",legend='none',
  lab.font =  c(6, "bold", "black"), fill = "var1", color = "black"
) + theme(text=element_text(face='bold',size=20))

```
Anything wrong with my code?
Legend is locked in top. And I can change legend position in other plot function such as `ggbarplot`

**Comment by kassambara** [comment]
fixed now, thanks
