### ISSUE TITLE
Scale free and stat_compare_means

### ISSUE THREAD

**Issue by carolsigm** [kassambara/ggpubr#279]
Hi there, 

I having an issue using facet_grid and stat_compare_means.
For the data set I have, I must use scales free to have a nice figure (figure as an example), however it causes some sort of problem in the stat_compare_means that did not return the desirable p values. 
It is the code I'm using in this case: 
`data %>% 
  ggplot(aes(y=log1p(measurement)  , x=Compartiment))+
  geom_boxplot()+
  facet_grid(Sugars~Organ,  scales = "free")+
  #scale_y_continuous("")+
  theme_bw()+
  ggtitle("Using scales free")+
  theme(legend.position = "none",
        panel.grid.minor=element_blank(),
        panel.grid.major = element_blank())+ 
  stat_compare_means(method = "anova", label = "p.format")`

<img width="979" alt="Captura de Tela 2020-05-21 às 12 36 58" src="https://user-images.githubusercontent.com/65306726/82555888-93f9aa80-9b60-11ea-810a-f23c232739cd.png">

When I did not set the scales, I have all the p-values, however, the figure is not in the way I would like to present it. 

`data %>% 
  ggplot(aes(y=log1p(measurement)  , x=Compartiment))+
  geom_boxplot()+
  facet_grid(Sugars~Organ)+
  theme_bw()+
  ggtitle("Not using scales free")+
  theme(legend.position = "none",
        panel.grid.minor=element_blank(),
        panel.grid.major = element_blank())+ 
  stat_compare_means(method = "anova", label = "p.format")`

<img width="982" alt="Captura de Tela 2020-05-21 às 12 36 40" src="https://user-images.githubusercontent.com/65306726/82555893-965c0480-9b60-11ea-8237-d8ac940e4503.png">

Does anyone know how I can solve this problem? I tried to use mapping and group, but it also didn't work =/

Thanks!

**Comment by kassambara** [comment]
I can't  reproduce your issue. Would you please provide a r[eproducible script](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) using a demo data?

**Comment by kassambara** [comment]
Please consider the following blog post for adding p-values onto ggplot facet:

[How to Add P-values to GGPLOT Facets](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/)
