### ISSUE TITLE
Jitter points not aligned with bar

### ISSUE THREAD

**Issue by aherholt** [kassambara/ggpubr#282]
Hi,
when I have subgroups in my data and I want to have black data points, the jitter function does not draw the datapoints in alignment with the bar. Any suggestions how to solve this?
best,
Alex

ggbarplot(data, x = "cond", y = "FC", orientation = "vert",
          add = c("mean_sd", "jitter"),  
          color = "black", palette = c("#807F7F", "#BF504D", "#0E71B4"), fill = "supp",
          position = position_dodge(0.9),
          sort.by.groups = TRUE)

![test](https://user-images.githubusercontent.com/65899507/82808180-c0c3ff80-9e89-11ea-960b-36d5b3f400f4.png)

**Comment by aherholt** [comment]
PS: And thanks for this awesome R package!

**Comment by kassambara** [comment]
fixed now, thanks!

Please install the latest dev version.

Reproducible example:

``` r
# Change bars fill color by groups
# You need to change also point shapes by groups
library(ggpubr)
ggbarplot(
  ToothGrowth, x = "dose", y = "len", 
  add = c("mean_sd", "jitter"), 
  add.params = list(shape = "supp"),
  fill= "supp", palette = c("#807F7F", "#BF504D"),
  position = position_dodge(0.8)
)
```

![](https://i.imgur.com/fARZy7O.png)

<sup>Created on 2020-05-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
