### ISSUE TITLE
when specifying a theme in ggtexttable it no longer accepts any customisation

### ISSUE THREAD

**Issue by Erinaceida** [kassambara/ggpubr#283]
Hi, 

When creating a table using ggtexttable and specifying a theme, any further modifications to the table, such as size, colour are ignored. This wouldn't be an issue if there was an easy way to reproduce the themes by writing my own theme, however, I found it impossible to replicate the lines of the "minimal" theme. 
` ggtexttable(results, 
                     rows = NULL, 
                     theme = ttheme(padding = unit(c(4, 20), "mm"),
                       tbody.style = tbody_style(fill = "white",
                                                 size = 7, 
                                                 linecolor = "black"),
                       colnames.style = colnames_style(fill = "white",
                                                       size = 10, 
                                                       color = "red")))`
![image](https://user-images.githubusercontent.com/65918054/82835372-bde20280-9ebb-11ea-8eaa-f6acf7f4e848.png)

`ggtexttable(results, 
                     rows = NULL, 
                     theme = ttheme("minimal", padding = unit(c(4, 20), "mm"),
                       tbody.style = tbody_style(fill = "white",
                                                 size = 7, 
                                                 linecolor = "black"),
                       colnames.style = colnames_style(fill = "white",
                                                       size = 10, 
                                                       color = "red")))`

![image](https://user-images.githubusercontent.com/65918054/82835424-dd792b00-9ebb-11ea-9ee1-c200a2caa069.png)

Regards, 
Tom

**Comment by kassambara** [comment]
Bug fixed now, thanks!

``` r
suppressPackageStartupMessages(library("ggpubr"))

ggtexttable(
  head(iris), rows = NULL, 
  theme = ttheme("minimal", padding = unit(c(4, 4), "mm"), 
                 tbody.style = tbody_style(fill = "white", size = 7, linecolor = "black"), 
                 colnames.style = colnames_style(fill = "white", size = 10, color = "red")
                 )
  )
```

![](https://i.imgur.com/F4rBQQI.png)

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by Erinaceida** [comment]
Dear Alboukadel Kassambara,

Unfortunately, the bug has not been fixed yet. This code:

ggtexttable(
  head(iris), rows = NULL,
  theme = ttheme("minimal", padding = unit(c(4, 4), "mm"),
                 tbody.style = tbody_style(fill = "white", size = 7,
linecolor = "black"),
                 colnames.style = colnames_style(fill = "white", size
= 10, color = "red")
                 )
  )

[image: image.png]
Gives the same output as this:

ggtexttable(
  head(iris), rows = NULL,
  theme = ttheme("minimal")
)
[image: image.png]
Kind regards,
Wojciech

**Comment by kassambara** [comment]
Make sure you have installed the latest dev version on github: `devtools::install_github("kassambara/ggpubr")`
