### ISSUE TITLE
How to add p-value in three or more groups comparison with stat_compare_means(aes())

### ISSUE THREAD

**Issue by Sylarair** [kassambara/ggpubr#284]
Hi,

There is a problem that bothers me a lot. How could I add p-value in the following condition where I'd like to perform a test between every two groups in 3 groups (0.5, 1, 2) for each `supp` condition? Thanks!

```
library(ggplot2)
library(ggpubr)
data("ToothGrowth")

ToothGrowth$dose = as.character(as.vector(ToothGrowth$dose))
p <- ggboxplot(ToothGrowth, x = "supp", y = "len", color = "dose", palette = "jco", add = "jitter")
p + stat_compare_means(aes(group = dose), method = 'wilcox.test', label = 'p.signif', tip.length = 0, label.x.npc = seq(0.1, 0.6, 0.1))
```

<img width="436" alt="Screen Shot 2020-05-26 at 11 32 07 AM" src="https://user-images.githubusercontent.com/18133362/82857764-89665900-9f44-11ea-89f1-f7be09243f39.png">

**Comment by kassambara** [comment]
Does this blog post helps: [How to Add P-Values onto a Grouped GGPLOT using the GGPUBR R Package](https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/) ?

**Comment by Sylarair** [comment]
@kassambara  Thanks very much! It helps a lot.
