### ISSUE TITLE
Different faces for legend

### ISSUE THREAD

**Issue by smesteves** [kassambara/ggpubr#287]
Hi,

Is it possible to make guides with different fonts, regarding a factor? I'm trying to plot my multivariate data and, in addition to the colour code, I'd like to make some of the guides bold.
face_type$Face contains the facet for each strain

` ggboxplot(data = tp,
               x = "variable", 
                y = "value",
                add = "jitter",
                add.params = list(color = "CC"),
                palette = cc_lab_ev,
                legend = c("bottom"),
                legend.title = "Strains",
                font.legend = list(size = 8)) + 
       theme(strip.text.x = element_text(hjust = 0),
             strip.background = element_blank(),
             panel.border=element_blank(),
             axis.text.x = element_text(size=11, hjust = 1),
             axis.text.y = element_text( size=11),
             axis.title = element_text( size=12),
             legend.text = element_text(face = face_type$Face)) +
       guides(col = guide_legend(nrow = 2, override.aes = list(size=3))) +
       scale_y_continuous(limits = c(0,4), expand=c(0,0))+
       labs(x = "Day", y = expression(OD["750 nm"]~(AU)))`

![tmp](https://user-images.githubusercontent.com/49430305/83332640-a1b7da00-a29c-11ea-8288-970f7da75c1d.jpeg)

Thanks on advance,
Sara

**Comment by kassambara** [comment]
This is a general question about ggplot2 legend customization. ggpubr doesn't contain any helper function for specifying different font faces for each legend item.

Please consider asking on stackoverflow.
