### ISSUE TITLE
Namespace load failed / tibble

### ISSUE THREAD

**Issue by TheJHRW** [kassambara/ggpubr#289]
Trying to load ggpubr but the following error is returned, even though latest version of tibble is installed

Error: package or namespace load failed for ‘ggpubr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘tibble’ 2.1.2 is already loaded, but >= 2.1.3 is required

**Comment by kassambara** [comment]
This is related to your setup. Similar discussion can be found on [twitter](https://twitter.com/JorisMeys/status/1268095907062599682).

Please consider: 1) re-starting your R session; 2) Install the latest version of tibble 3) Re-install ggpubr:  devtools::install_github("kassambara/ggpubr", dependencies = TRUE); 4) Load ggpubr.

If it fails, please provide your R session info

**Comment by TheJHRW** [comment]
Thanks - and sorry about that. Restarted R, reinstalled tibble & ggpubr and everything's working again. Cheers.
