### ISSUE TITLE
Computation failed in `stat_cor()`: could not find function ".label_params" 

### ISSUE THREAD

**Issue by Br00ksie** [kassambara/ggpubr#290]
Unable to use newest stat_cor() with p.accuracy. The above warning message shows up

**Comment by kassambara** [comment]
Hi, please make sure you have installed the latest dev version: devtools::install_github("kassambara/ggpubr"). If it still fails, please provide the output of devtools::session_info()

**Comment by Br00ksie** [comment]
I have installed the latest version, and it still failed. My apologies if this is not proper formatting, I am very new to GitHub. Output of devtools::session_info() is below..

devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.0 (2020-04-24)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_CA.UTF-8                 
 ctype    en_CA.UTF-8                 
 tz       America/Toronto             
 date     2020-06-04                  

─ Packages ──────────────────────────────────────────────────────────────────────────────────
 ! package      * version    date       lib source        
   abind          1.4-5      2016-07-21 [1] CRAN (R 4.0.0)
   apaTables    * 2.0.5      2018-08-29 [1] CRAN (R 4.0.0)
   assertthat     0.2.1      2019-03-21 [1] CRAN (R 4.0.0)
 V backports      1.1.6      2020-05-13 [1] CRAN (R 4.0.0)
   boot           1.3-25     2020-04-26 [1] CRAN (R 4.0.0)
   broom          0.5.6      2020-04-20 [1] CRAN (R 4.0.0)
   callr          3.4.3      2020-03-28 [1] CRAN (R 4.0.0)
 V car          * 3.0-7      2020-05-21 [1] CRAN (R 4.0.0)
 V carData      * 3.0-3      2020-05-22 [1] CRAN (R 4.0.0)
   cellranger     1.1.0      2016-07-27 [1] CRAN (R 4.0.0)
   cli            2.0.2      2020-02-28 [1] CRAN (R 4.0.0)
   coda           0.19-3     2019-07-05 [1] CRAN (R 4.0.0)
   codetools      0.2-16     2018-12-24 [1] CRAN (R 4.0.0)
   colorspace     1.4-1      2019-03-18 [1] CRAN (R 4.0.0)
   crayon         1.3.4      2017-09-16 [1] CRAN (R 4.0.0)
   curl           4.3        2019-12-02 [1] CRAN (R 4.0.0)
   data.table   * 1.12.8     2019-12-09 [1] CRAN (R 4.0.0)
   desc           1.2.0      2018-05-01 [1] CRAN (R 4.0.0)
   devtools     * 2.3.0      2020-04-10 [1] CRAN (R 4.0.0)
   digest         0.6.25     2020-02-23 [1] CRAN (R 4.0.0)
 V dplyr          0.8.5      2020-05-29 [1] CRAN (R 4.0.0)
 V ellipsis       0.3.0      2020-05-15 [1] CRAN (R 4.0.0)
 V emmeans      * 1.4.6      2020-05-25 [1] CRAN (R 4.0.0)
   estimability   1.3        2018-02-11 [1] CRAN (R 4.0.0)
   fansi          0.4.1      2020-01-08 [1] CRAN (R 4.0.0)
   farver         2.0.3      2020-01-16 [1] CRAN (R 4.0.0)
   forcats      * 0.5.0      2020-03-01 [1] CRAN (R 4.0.0)
   foreign        0.8-79     2020-04-26 [1] CRAN (R 4.0.0)
   fs             1.4.1      2020-04-04 [1] CRAN (R 4.0.0)
   generics       0.0.2      2018-11-29 [1] CRAN (R 4.0.0)
 V ggplot2      * 3.3.0      2020-05-28 [1] CRAN (R 4.0.0)
   ggpubr       * 0.3.0      2020-05-04 [1] CRAN (R 4.0.0)
   ggsci          2.9        2018-05-14 [1] CRAN (R 4.0.0)
   ggsignif       0.6.0      2019-08-08 [1] CRAN (R 4.0.0)
 V glue           1.4.0      2020-05-13 [1] CRAN (R 4.0.0)
   gridExtra      2.3        2017-09-09 [1] CRAN (R 4.0.0)
   gtable         0.3.0      2019-03-25 [1] CRAN (R 4.0.0)
   haven          2.2.0      2019-11-08 [1] CRAN (R 4.0.0)
   hms            0.5.3      2020-01-08 [1] CRAN (R 4.0.0)
   inline         0.3.15     2018-05-18 [1] CRAN (R 4.0.0)
   knitr        * 1.28       2020-02-06 [1] CRAN (R 4.0.0)
   labeling       0.3        2014-08-23 [1] CRAN (R 4.0.0)
   lattice        0.20-41    2020-04-02 [1] CRAN (R 4.0.0)
   lifecycle      0.2.0      2020-03-06 [1] CRAN (R 4.0.0)
   lme4         * 1.1-23     2020-04-07 [1] CRAN (R 4.0.0)
   lmerTest     * 3.1-2      2020-04-08 [1] CRAN (R 4.0.0)
   loo            2.2.0      2019-12-19 [1] CRAN (R 4.0.0)
   magrittr       1.5        2014-11-22 [1] CRAN (R 4.0.0)
   MASS           7.3-51.6   2020-04-26 [1] CRAN (R 4.0.0)
   Matrix       * 1.2-18     2019-11-27 [1] CRAN (R 4.0.0)
   matrixStats    0.56.0     2020-03-13 [1] CRAN (R 4.0.0)
   memoise        1.1.0      2017-04-21 [1] CRAN (R 4.0.0)
   mgcv           1.8-31     2019-11-09 [1] CRAN (R 4.0.0)
   minqa          1.2.4      2014-10-09 [1] CRAN (R 4.0.0)
   mnormt         1.5-7      2020-04-30 [1] CRAN (R 4.0.0)
   multcomp       1.4-13     2020-04-08 [1] CRAN (R 4.0.0)
   munsell        0.5.0      2018-06-12 [1] CRAN (R 4.0.0)
   mvtnorm        1.1-0      2020-02-24 [1] CRAN (R 4.0.0)
   nlme           3.1-147    2020-04-13 [1] CRAN (R 4.0.0)
   nloptr         1.2.2.1    2020-03-11 [1] CRAN (R 4.0.0)
   numDeriv       2016.8-1.1 2019-06-06 [1] CRAN (R 4.0.0)
   openxlsx       4.1.5      2020-05-06 [1] CRAN (R 4.0.0)
   pbkrtest       0.4-8.6    2020-02-20 [1] CRAN (R 4.0.0)
   pillar         1.4.4      2020-05-05 [1] CRAN (R 4.0.0)
   pkgbuild       1.0.8      2020-05-07 [1] CRAN (R 4.0.0)
   pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.0.0)
 V pkgload        1.0.2      2020-05-29 [1] CRAN (R 4.0.0)
   polynom        1.4-0      2019-03-22 [1] CRAN (R 4.0.0)
   prettyunits    1.1.1      2020-01-24 [1] CRAN (R 4.0.0)
   processx       3.4.2      2020-02-09 [1] CRAN (R 4.0.0)
   ps             1.3.3      2020-05-08 [1] CRAN (R 4.0.0)
   psych        * 1.9.12.31  2020-01-08 [1] CRAN (R 4.0.0)
   purrr          0.3.4      2020-04-17 [1] CRAN (R 4.0.0)
   R6             2.4.1      2019-11-12 [1] CRAN (R 4.0.0)
   Rcpp           1.0.4.6    2020-04-09 [1] CRAN (R 4.0.0)
   readxl         1.3.1      2019-03-13 [1] CRAN (R 4.0.0)
   remotes        2.1.1      2020-02-15 [1] CRAN (R 4.0.0)
   rio            0.5.16     2018-11-26 [1] CRAN (R 4.0.0)
   rlang          0.4.6      2020-05-02 [1] CRAN (R 4.0.0)
   rprojroot      1.3-2      2018-01-03 [1] CRAN (R 4.0.0)
   rstan          2.19.3     2020-02-11 [1] CRAN (R 4.0.0)
   rstatix        0.5.0      2020-04-28 [1] CRAN (R 4.0.0)
   rstudioapi     0.11       2020-02-07 [1] CRAN (R 4.0.0)
   sandwich       2.5-1      2019-04-06 [1] CRAN (R 4.0.0)
   scales         1.1.1      2020-05-11 [1] CRAN (R 4.0.0)
   sessioninfo    1.1.1      2018-11-05 [1] CRAN (R 4.0.0)
   StanHeaders    2.19.2     2020-02-11 [1] CRAN (R 4.0.0)
   statmod        1.4.34     2020-02-17 [1] CRAN (R 4.0.0)
   stringi        1.4.6      2020-02-17 [1] CRAN (R 4.0.0)
   survival       3.1-12     2020-04-10 [1] CRAN (R 4.0.0)
   testthat       2.3.2      2020-03-02 [1] CRAN (R 4.0.0)
   TH.data        1.0-10     2019-01-21 [1] CRAN (R 4.0.0)
   tibble         3.0.1      2020-04-20 [1] CRAN (R 4.0.0)
 V tidyr          1.0.3      2020-05-20 [1] CRAN (R 4.0.0)
   tidyselect     1.1.0      2020-05-11 [1] CRAN (R 4.0.0)
   usethis      * 1.6.1      2020-04-29 [1] CRAN (R 4.0.0)
 V vctrs          0.2.4      2020-05-11 [1] CRAN (R 4.0.0)
   withr          2.2.0      2020-04-20 [1] CRAN (R 4.0.0)
   xfun           0.13       2020-04-13 [1] CRAN (R 4.0.0)
   xtable         1.8-4      2019-04-21 [1] CRAN (R 4.0.0)
   zip            2.0.4      2019-09-01 [1] CRAN (R 4.0.0)
   zoo            1.8-8      2020-05-02 [1] CRAN (R 4.0.0)

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

 V ── Loaded and on-disk version mismatch.

**Comment by kassambara** [comment]
I can see that you have the latest CRAN version version of ggpubr. 

Please consider installing the latest dev version (on Github), which supports the p.accuracy argument. You can install as follow

```r
devtools::install_github("kassambara/rstatix", dependencies = FALSE)
devtools::install_github("kassambara/ggpubr", dependencies = FALSE)
```

**Comment by Br00ksie** [comment]
Now I receive the following:

Warning messages:
1: `mutate_()` is deprecated as of dplyr 0.7.0.
Please use `mutate()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: Computation failed in `stat_cor()`:
no applicable method for 'mutate_' applied to an object of class "function"

**Comment by kassambara** [comment]
Please provide a reproducible R script with a demo data such as `mtcars` and your session info.

**Comment by Br00ksie** [comment]
> sp <- ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line")
> sp + stat_cor(label.x = 3, p.accuracy = 0.001, r.accuracy = 0.01)

`geom_smooth()` using formula 'y ~ x'
Warning message:
Computation failed in `stat_cor()`:
no applicable method for 'mutate_' applied to an object of class "function" 

**Session Info:**

R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.0     ggpubr_0.3.0.999  ggplot2_3.3.1     knitr_1.28        psych_1.9.12.31  
 [6] apaTables_2.0.5   data.table_1.12.8 car_3.0-8         carData_3.0-4     emmeans_1.4.7    
[11] lmerTest_3.1-2    lme4_1.1-23       Matrix_1.2-18    

loaded via a namespace (and not attached):
 [1] nlme_3.1-147        fs_1.4.1            pbkrtest_0.4-8.6    usethis_1.6.1      
 [5] devtools_2.3.0      rprojroot_1.3-2     numDeriv_2016.8-1.1 tools_4.0.0        
 [9] backports_1.1.7     R6_2.4.1            mgcv_1.8-31         colorspace_1.4-1   
[13] withr_2.2.0         tidyselect_1.1.0    prettyunits_1.1.1   mnormt_1.5-7       
[17] processx_3.4.2      curl_4.3            compiler_4.0.0      cli_2.0.2          
[21] desc_1.2.0          sandwich_2.5-1      labeling_0.3        scales_1.1.1       
[25] mvtnorm_1.1-0       callr_3.4.3         digest_0.6.25       foreign_0.8-79     
[29] minqa_1.2.4         rio_0.5.16          pkgconfig_2.0.3     sessioninfo_1.1.1  
[33] rlang_0.4.6         readxl_1.3.1        rstudioapi_0.11     generics_0.0.2     
[37] farver_2.0.3        zoo_1.8-8           dplyr_1.0.0         zip_2.0.4          
[41] magrittr_1.5        Rcpp_1.0.4.6        munsell_0.5.0       fansi_0.4.1        
[45] abind_1.4-5         lifecycle_0.2.0     stringi_1.4.6       multcomp_1.4-13    
[49] MASS_7.3-51.6       pkgbuild_1.0.8      grid_4.0.0          parallel_4.0.0     
[53] crayon_1.3.4        lattice_0.20-41     haven_2.2.0         splines_4.0.0      
[57] hms_0.5.3           ps_1.3.3            pillar_1.4.4        boot_1.3-25        
[61] estimability_1.3    ggsignif_0.6.0      codetools_0.2-16    pkgload_1.1.0      
[65] glue_1.4.1          remotes_2.1.1       vctrs_0.3.0         nloptr_1.2.2.1     
[69] testthat_2.3.2      cellranger_1.1.0    gtable_0.3.0        purrr_0.3.4        
[73] tidyr_1.1.0         assertthat_0.2.1    xfun_0.13           openxlsx_4.1.5     
[77] xtable_1.8-4        broom_0.5.6         coda_0.19-3         rstatix_0.5.0.999  
[81] survival_3.1-12     tibble_3.0.1        memoise_1.1.0       statmod_1.4.34     
[85] TH.data_1.0-10      ellipsis_0.3.1

**Comment by kassambara** [comment]
Thanks! The error is not reproducible with my session below. Let's keep this issue open

``` r
suppressPackageStartupMessages(library(ggpubr))

sp <- ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line")
sp + stat_cor(label.x = 3, p.accuracy = 0.001, r.accuracy = 0.01)
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/bauBjfB.png)

<sup>Created on 2020-06-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       macOS Sierra 10.12.6        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  fr_FR.UTF-8                 
#>  ctype    fr_FR.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-06-05                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                           
#>  abind         1.4-5      2016-07-21 [1] CRAN (R 3.6.0)                   
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                   
#>  backports     1.1.7      2020-05-13 [1] CRAN (R 3.6.2)                   
#>  broom         0.5.6      2020-04-20 [1] CRAN (R 3.6.2)                   
#>  car           3.0-7      2020-03-11 [1] CRAN (R 3.6.0)                   
#>  carData       3.0-3      2019-11-16 [1] CRAN (R 3.6.0)                   
#>  cellranger    1.1.0      2016-07-27 [1] CRAN (R 3.6.0)                   
#>  cli           2.0.2      2020-02-28 [1] CRAN (R 3.6.0)                   
#>  colorspace    1.4-1      2019-03-18 [1] CRAN (R 3.6.0)                   
#>  crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                   
#>  curl          4.3        2019-12-02 [1] CRAN (R 3.6.0)                   
#>  data.table    1.12.8     2019-12-09 [1] CRAN (R 3.6.0)                   
#>  digest        0.6.25     2020-02-23 [1] CRAN (R 3.6.0)                   
#>  dplyr         1.0.0      2020-05-29 [1] CRAN (R 3.6.2)                   
#>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 3.6.2)                   
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                   
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.0)                   
#>  farver        2.0.3      2020-01-16 [1] CRAN (R 3.6.0)                   
#>  forcats       0.5.0      2020-03-01 [1] CRAN (R 3.6.0)                   
#>  foreign       0.8-75     2020-01-20 [1] CRAN (R 3.6.3)                   
#>  fs            1.4.1      2020-04-04 [1] CRAN (R 3.6.2)                   
#>  generics      0.0.2      2018-11-29 [1] CRAN (R 3.6.0)                   
#>  ggplot2     * 3.3.0      2020-03-05 [1] CRAN (R 3.6.0)                   
#>  ggpubr      * 0.3.0.999  2020-06-04 [1] local                            
#>  ggsignif      0.6.0      2019-08-08 [1] CRAN (R 3.6.0)                   
#>  glue          1.4.1      2020-05-13 [1] CRAN (R 3.6.2)                   
#>  gtable        0.3.0      2019-03-25 [1] CRAN (R 3.6.0)                   
#>  haven         2.2.0      2019-11-08 [1] CRAN (R 3.6.0)                   
#>  highr         0.8        2019-03-20 [1] CRAN (R 3.6.0)                   
#>  hms           0.5.3      2020-01-08 [1] CRAN (R 3.6.0)                   
#>  htmltools     0.4.0      2019-10-04 [1] CRAN (R 3.6.0)                   
#>  httr          1.4.1      2019-08-05 [1] CRAN (R 3.6.0)                   
#>  knitr         1.28       2020-02-06 [1] CRAN (R 3.6.0)                   
#>  labeling      0.3        2014-08-23 [1] CRAN (R 3.6.0)                   
#>  lattice       0.20-41    2020-04-02 [1] CRAN (R 3.6.2)                   
#>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 3.6.0)                   
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                   
#>  Matrix        1.2-18     2019-11-27 [1] CRAN (R 3.6.3)                   
#>  mgcv          1.8-31     2019-11-09 [1] CRAN (R 3.6.3)                   
#>  mime          0.9        2020-02-04 [1] CRAN (R 3.6.0)                   
#>  munsell       0.5.0      2018-06-12 [1] CRAN (R 3.6.0)                   
#>  nlme          3.1-147    2020-04-13 [1] CRAN (R 3.6.2)                   
#>  openxlsx      4.1.5      2020-05-06 [1] CRAN (R 3.6.2)                   
#>  pillar        1.4.4      2020-05-05 [1] CRAN (R 3.6.2)                   
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.0)                   
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 3.6.2)                   
#>  R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.0)                   
#>  Rcpp          1.0.4.6    2020-04-09 [1] CRAN (R 3.6.3)                   
#>  readxl        1.3.1      2019-03-13 [1] CRAN (R 3.6.0)                   
#>  reprex        0.3.0.9001 2020-05-16 [1] Github (tidyverse/reprex@a019cc4)
#>  rio           0.5.16     2018-11-26 [1] CRAN (R 3.6.0)                   
#>  rlang         0.4.6      2020-05-02 [1] CRAN (R 3.6.2)                   
#>  rmarkdown     2.1        2020-01-20 [1] CRAN (R 3.6.0)                   
#>  rstatix       0.5.0.999  2020-05-24 [1] local                            
#>  rstudioapi    0.11       2020-02-07 [1] CRAN (R 3.6.0)                   
#>  scales        1.1.1      2020-05-11 [1] CRAN (R 3.6.2)                   
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                   
#>  stringi       1.4.6      2020-02-17 [1] CRAN (R 3.6.0)                   
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                   
#>  styler        1.3.2      2020-02-23 [1] CRAN (R 3.6.0)                   
#>  tibble        3.0.1      2020-04-20 [1] CRAN (R 3.6.2)                   
#>  tidyr         1.0.3      2020-05-07 [1] CRAN (R 3.6.2)                   
#>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 3.6.2)                   
#>  vctrs         0.3.0      2020-05-11 [1] CRAN (R 3.6.2)                   
#>  withr         2.2.0      2020-04-20 [1] CRAN (R 3.6.2)                   
#>  xfun          0.13       2020-04-13 [1] CRAN (R 3.6.2)                   
#>  xml2          1.3.2      2020-04-23 [1] CRAN (R 3.6.2)                   
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.0)                   
#>  zip           2.0.4      2019-09-01 [1] CRAN (R 3.6.0)                   
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by Br00ksie** [comment]
I had a "stat_cor" function in my Global Environment. I have since removed that, and now receive the following:

```
> sp <- ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line")
> sp + stat_cor(label.x = 3, p.accuracy = 0.001, r.accuracy = 0.01)
```

`geom_smooth()` using formula 'y ~ x'
Warning message:
Ignoring unknown parameters: p.accuracy, r.accuracy 

![Rplot](https://user-images.githubusercontent.com/66444079/83822475-2771c600-a69f-11ea-8c0d-2163f2e1cc01.png)

**Comment by Br00ksie** [comment]
I am using RStudio to run this code, not sure if that makes any difference?

Update: I have tried to examine the stat_cor function and found the following code:

```
function (mapping = NULL, data = NULL, method = "pearson", cor.coef.name = c("R", 
  "rho", "tau"), label.sep = ", ", label.x.npc = "left", label.y.npc = "top", 
  label.x = NULL, label.y = NULL, output.type = "expression", 
  digits = 2, r.digits = digits, p.digits = digits, geom = "text", 
  position = "identity", na.rm = FALSE, show.legend = NA, 
  inherit.aes = TRUE, ...) 
{
  parse <- ifelse(output.type == "expression", TRUE, FALSE)
  cor.coef.name = cor.coef.name[1]
  layer(stat = StatCor, data = data, mapping = mapping, geom = geom, 
    position = position, show.legend = show.legend, inherit.aes = inherit.aes, 
    params = list(label.x.npc = label.x.npc, label.y.npc = label.y.npc, 
      label.x = label.x, label.y = label.y, label.sep = label.sep, 
      method = method, output.type = output.type, digits = digits, 
      r.digits = r.digits, p.digits = p.digits, cor.coef.name = cor.coef.name, 
      parse = parse, na.rm = na.rm, ...))
}
```

There does not appear to be any sign of "p.accuracy" or "r.accuracy" in the function. Is there some disconnect between the latest dev version and what is read into R Studio?

**Comment by kassambara** [comment]
Did you try this?: 

1) re-starting your R studio session; 2) Re-installing the ggpubr dev version

**Comment by Br00ksie** [comment]
Yes, it does not install as there has been no change

Skipping install of 'ggpubr' from a github remote, the SHA1 (e4e435f0) has not changed since last install.
  Use `force = TRUE` to force installation

**Comment by kassambara** [comment]
If you don't have any sign of p.accuracy argument when typing `stat_cor` , then there should be something wrong with your R session; because as you can see on [github/stat_cor](https://github.com/kassambara/ggpubr/blob/master/R/stat_cor.R), the argument p.accuracy is present in the latest dev version

**Comment by Br00ksie** [comment]
I restarted my computer and it worked! Thank you!
