### ISSUE TITLE
ggpubr:  X-axis car label names not aligned with corresponding axis ticks & columns

### ISSUE THREAD

**Issue by sfd99** [kassambara/ggpubr#301]
**ggpubr** is really easy and WONDERFUL.
Thanks Kassambara!!.

In your mtcars example: 
**Ordered Bar Plots**
https://rpkgs.datanovia.com/ggpubr/#ordered-bar-plots

the X-axis car label names _(at 90 degrees)_,
are not aligned with corresponding axis ticks & columns.
The car names are shifted _to the right_, horizontally.
So, each  car name label 
ends up _between ticks_,
not under a specific column tick-mark...

Same X-axis vs label misalignment, 
with some other plots in the post.
**---**

_On the other hand,_
the  **Lollipop Chart** is _fine_:
https://rpkgs.datanovia.com/ggpubr/#lollipop-chart

(ie: all 90 deg-rotated car names, 
are neatly under the corresponding column tick-mark) .

_Help!._
**sfd99
SF
ggpubr 0.4.0
R 3.6.3 (latest)
Rstudio version 1.3.959 (latest)
Ubuntu Linux 18.04 64bits.**

**Comment by kassambara** [comment]
fixed now, thanks!

**Comment by sfd99** [comment]
Ooops!
Updated to latest development version of ggpubr 0.4.0.999  f/ GIT ,
tried example again:
Error in ggbarplot(dfm, x = "name", y = "mpg", fill = "cyl", color = "white",  : 
  c_ould not find function "ggbarplot"_

**Comment by kassambara** [comment]
Does the following R code works `ggpubr::ggbarplot(ToothGrowth, x = "dose", y = "len", add = "mean_sd")` in a standard R terminal (outside Rstudio) ?

**Comment by sfd99** [comment]
just a sec...re-installing ggpubr f/ GIThub 
and will  try...

**Comment by sfd99** [comment]
- Re-installing latest version of ggpubr f / GIT hub...
- Re-started Rstudio on my PC,

EVERYTHING WORKS OK now! 
All examples run fine 100%...

Thanks, Kassambara!.
Have a great and safe weekend in Marseille!.

**Comment by kassambara** [comment]
great, so we can close this issue. Have a nice weekend too!
