### ISSUE TITLE
ylim & stat_compare_means don't function together

### ISSUE THREAD

**Issue by jiehuang001** [kassambara/ggpubr#305]
Hi, there 

I am using the following command to generate a plot like below:

p <- ggboxplot(dat1, x="apoe", y="cnt_min", color="same", notch=F, xlab="APOE", ylab="Reads", outlier.shape=NA, size=1.5, palette="jco", add="none") # outlier.shape=NA,
p + stat_compare_means(method="wilcox.test", aes(label=..p.format.., group=same))

![0](https://user-images.githubusercontent.com/26947455/86624158-6de77700-bff5-11ea-9c08-a30f02e57665.jpg)

The problem is that there is too much white space at the top portion. I then added ylim=c(0,50). 
As shown below, but this time the P-values at the top disappeared.

![ggboxplot1](https://user-images.githubusercontent.com/26947455/86624251-93748080-bff5-11ea-9840-0fc704c15584.jpg)

So, don't know how to remove the top portion of white space while keep the text line at the top.
Can someone please kindly let me know.

Thank you very much & best regards,
Jie

**Comment by kassambara** [comment]
Hi, please try the argument `label.y = 50` in the function `stat_compare_means()`

**Comment by jiehuang001** [comment]
Hi， I tried the following, but still the Y-axis does not change:

p <- ggboxplot(dat1, x="apoe", y="cnt_min", color="same", notch=F, xlab="APOE", ylab="Reads", outlier.shape=NA, size=1.5, palette="jco", add="none") # outlier.shape=NA,
p + stat_compare_means(method="wilcox.test", aes(y=50, label=..p.format.., group=same))

If I use the following, it gives error:
p + stat_compare_means(method="wilcox.test", y=50, aes(label=..p.format.., group=same))

Best regards,
Jie

**Comment by kassambara** [comment]
Please try the argument `label.y = 50` in the function stat_compare_means() as follow:

```r
p + stat_compare_means(aes(label=..p.format.., group=same), method="wilcox.test", label.y=50)
```

**Comment by jiehuang001** [comment]
Sorry，my bad. Yes, its label.y. I also need to use ylim=c(0,50) in the first command line. 
It now worked with the following two lines:

p <- ggboxplot(dat1, x="apoe", y="cnt_min", color="same", notch=F, ylim=c(0,50), xlab="APOE", ylab="Reads", outlier.shape=NA, size=1.5, palette="jco", add="none") # outlier.shape=NA,
p + stat_compare_means(method="wilcox.test", label.y=50, aes(label=..p.format.., group=same))

Thank you so much!

Best regards,
Jie

**Comment by alejer** [comment]
hi, I have a similar problem, the label.y is not solving it.
```
plot_parameters <- function(parameter, y.label, y.low=0, y.high=100, stat.print.y = NA, df = dataset) { 
      df %>%
          select(kat_cas, nick, parameter) %>%
          pivot_longer(cols=parameter, names_to = "parameter", values_to = "values") %>%
          ggplot(aes(x=kat_cas, y=values))  + geom_boxplot(width=0.3) + 
          stat_compare_means(comparisons = compare_to_zero, 
                             method = "wilcox.test",
                             paired = TRUE,
                             label="p.signif", hide.ns = FALSE,
                             label.y = stat.print.y) +
      coord_cartesian(ylim=c(y.low-(y.high-y.low)/10, y.high), clip = "off")
}
```
With a call `plot_parameters("IL.6", 'IL-6 (ng/L)', 0, 15000, stat.print.y = 10000, df = df.septic)` 
I get the following result:

![slika](https://user-images.githubusercontent.com/13355342/157656764-85fad42a-a0c7-48a8-90ae-ddfc8baafad3.png)

However, playing aroung with `plot_parameters("IL.6", 'IL-6 (ng/L)', 0, 50000, stat.print.y = 10000, df = df.septic)`
I get this result, which I cant explain
![slika](https://user-images.githubusercontent.com/13355342/157657627-d7a66d11-5186-4307-836f-6cb7ed7c9815.png)

Thank you!
