### ISSUE TITLE
ggbarplot add jitter does not recognize fill

### ISSUE THREAD

**Issue by rhart604** [kassambara/ggpubr#309]
Having trouble applying jitter to dots overlaid on bar plots.  This works:

`ggbarplot(d,x="Group",y="RRQ",
          fill="Target",
          color="Target",
          add=c("jitter","mean_se"),
          add.params = list(fill="black"),
          position=position_dodge(width=.7))`
Result:
![works](https://user-images.githubusercontent.com/9257143/87445714-6102ee80-c5c6-11ea-9aa0-842648420ab1.png)

But this does not:
`ggbarplot(d,x="Group",y="RRQ",
          fill="Target",
         add=c("jitter","mean_se"),
          add.params = list(fill="black"),
          position=position_dodge(width=.7))`

The error is:
Error: `position_jitterdodge()` requires at least one aesthetic to dodge by

So it recognizes color as a dodge aesthetic but not fill?  I want to use fill to distinguish "Target" but if I add color="Target" all the error bars and points are the same color as the bars, so they disappear.  How do I tell add="jitter" which aesthetic to use for dodging?

**Comment by kassambara** [comment]
Hi,

You are creating a grouped plot, where bars are grouped by fill variable.

Jitter **points** doesn't reacts to fill aesthetic, so an error is generated. You have the  choice between  shape and color for points.

``` r
suppressPackageStartupMessages(library(ggpubr))
ggbarplot(
  ToothGrowth,x="dose",y="len", fill="supp", 
  add=c("jitter","mean_se"), 
  add.params = list(shape = "supp"),
  position=position_dodge(width=.7)
)
```

![](https://i.imgur.com/7hTL3iY.png)

<sup>Created on 2020-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by rhart604** [comment]
Thanks!  That makes sense now.
