### ISSUE TITLE
R^2 as option in stat_cor()

### ISSUE THREAD

**Issue by philament** [kassambara/ggpubr#32]
I like the simplicity of quickly adding the correlation coefficient and p-value to a scatter plot produced with ggscatter(). It would be nice to be able to select the R^2 value instead of r as a method in stat_cor() .

**Comment by mlebeur** [comment]
I am totally agree !

**Comment by kassambara** [comment]
Now, R2 is supported.

```r
library("ggpubr")
# Default output
ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line") +
  stat_cor(label.x = 3)
```

![rplot39](https://user-images.githubusercontent.com/3313355/43991815-9ca44500-9d74-11e8-9479-403cf267051f.png)

```r
# Use R2 instead of R
ggscatter(mtcars, x = "wt", y = "mpg", add = "reg.line") +
  stat_cor(
    aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), 
    label.x = 3
    )
```

![rplot40](https://user-images.githubusercontent.com/3313355/43991821-afaf6094-9d74-11e8-85d6-962986c6bb11.png)

**Comment by lucygarner** [comment]
Is it possible to achieve this but with the R<sup>2</sup> and p value on separate lines?
