### ISSUE TITLE
`stat_compare_means` + change `p.label` format

### ISSUE THREAD

**Issue by bblodfon** [kassambara/ggpubr#327]
Hi! 

I want to change the p-value labels to be like this: `p = 0.0004` - so pretty much add the `p = ` in front of the values.
I tried the following but it does not seem to work and I was wondering why!

```{r}
my_comparisons = list(c("0.5", "1"), c("1", "2"), c("0.5", "2"))
ggboxplot(ToothGrowth, x = "dose", y = "len", color = "dose") + 
   stat_compare_means(comparisons = my_comparisons, aes(label = paste0("p = ", ..p.format..)))
```
Note that the simple `aes(label = ..p.signif..)` changes the format but whenever I try to `paste` something else on the label output, it fails!

**Comment by Liripo** [comment]
> Hi!
> 
> I want to change the p-value labels to be like this: `p = 0.0004` - so pretty much add the `p = ` in front of the values.
> I tried the following but it does not seem to work and I was wondering why!
> 
> ```
> my_comparisons = list(c("0.5", "1"), c("1", "2"), c("0.5", "2"))
> ggboxplot(ToothGrowth, x = "dose", y = "len", color = "dose") + 
>    stat_compare_means(comparisons = my_comparisons, aes(label = paste0("p = ", ..p.format..)))
> ```
> 
> Note that the simple `aes(label = ..p.signif..)` changes the format but whenever I try to `paste` something else on the label output, it fails!

I also encountered this situation, have you solved it？

**Comment by bblodfon** [comment]
Hi @Liripo, I have not. Thumping up the original question is I guess the only way to get attention

**Comment by kassambara** [comment]
Hi, this will be fixed in the next version. In the meantime, it's possible to add p-values manually as follow:

``` r
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(rstatix))

# Statistical tests
my_comparisons = list(c("0.5", "1"), c("1", "2"), c("0.5", "2"))
stat.test <- ToothGrowth %>% 
  wilcox_test(len ~ dose, comparisons = my_comparisons) %>%
  add_significance("p")
stat.test
#> # A tibble: 3 x 10
#>   .y.   group1 group2    n1    n2 statistic       p   p.adj p.adj.signif
#>   <chr> <chr>  <chr>  <int> <int>     <dbl>   <dbl>   <dbl> <chr>       
#> 1 len   0.5    1         20    20      33.5 7.02e-6 1.40e-5 ****        
#> 2 len   1      2         20    20      61   1.77e-4 1.77e-4 ***         
#> 3 len   0.5    2         20    20       1.5 8.41e-8 2.52e-7 ****        
#> # … with 1 more variable: p.signif <chr>

# Add p-values to a boxplot
stat.test <- stat.test %>% add_xy_position(x = "dose")
ggboxplot(ToothGrowth, x = "dose", y = "len", color = "dose") +
  stat_pvalue_manual(stat.test, label = "p = {p}{p.signif}")
```

![](https://i.imgur.com/Kwrqrdd.png)

<sup>Created on 2020-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by n-osennij** [comment]
does it fixed?

**Comment by sbbmu** [comment]
@kassambara  Does it fixed?

**Comment by kassambara** [comment]
@sbbmu  please consider using now the function `geom_pwc()` which has lot of possibilities and features compared to stat_compare_means(). See the doc: https://rpkgs.datanovia.com/ggpubr/reference/geom_pwc.html

``` r
library(ggpubr)
ggboxplot(ToothGrowth, x = "dose", y = "len", color = "dose") +
  geom_pwc(method = "wilcox_test", label = "p = {p}{p.signif}")
```

![](https://i.imgur.com/DDMsC9C.png)
