### ISSUE TITLE
t.test against control group does not graph for groups preceeding control on the plot

### ISSUE THREAD

**Issue by l-jaye** [kassambara/ggpubr#33]
Hello!

I am using the following as part of ggplot command to plot p-values on a bar-plot:
`stat_compare_means (label = "p.format", method = "t.test",
                     ref.group = "mNG") +`
My groups are set up as factors, and control ("mNG") is factor level 2. 

I am only getting p-values plotted for groups after my control "mNG" group:
![image](https://user-images.githubusercontent.com/32018129/30513477-e7396b64-9ad1-11e7-8266-9970a320e354.png)

If I change the re.group to "parental", it plots them all (but the comparison is wrong. Similarly, if I change it to "parvA", it only plots it for "parvB"
![image](https://user-images.githubusercontent.com/32018129/30513488-25c11b20-9ad2-11e7-90dd-242f947cc0fe.png)
In my opinion, it should still plot the p-values for all groups against control, no matter the factor level.

**Comment by kassambara** [comment]
This issue has been already fixed in the latest developmental version, which can be installed as follow:

```r
devtools::install_github("kassambara/github")
```

Kindly confirm that it works, thanks.

**Comment by l-jaye** [comment]
Hi Alboukadel,

Sorry for the delay.

Works great now, thank you!
