### ISSUE TITLE
stat_compare_means p values overlap with data points

### ISSUE THREAD

**Issue by atakanekiz** [kassambara/ggpubr#332]
Hi!

I'm having an issue where the p-value annotations overlap with the data points. I played with `label.y.npc` parameter, and I can plot the p-values at a lower position, but I can't position them higher than the data points without explicitly specifying a y-axis coordinate (which is difficult due to different scales in faceted plots). 

I tried using `scale_y_continuous(expand=expansion(...))` which can change the plotting area but p-values doesn't go any higher than the highest data point.

Would you consider allowing `label.y.npc` to accept values greater than `1`? I think this would solve the problem.

EDIT: I should add that this issue arises when `ref.group` is used. Pairwise comparisons appear above the data points as expected.

![image](https://user-images.githubusercontent.com/38366155/90947804-05622700-e3f6-11ea-9b10-2b2cfd446b7a.png)

**Comment by kassambara** [comment]
Does the following code helps?

``` r
suppressPackageStartupMessages(library(ggpubr))

# Basic points
df <- ToothGrowth
df$dose <- as.factor(df$dose)
p <- ggplot(df, aes(dose, len)) +
  geom_point(fill = "red", shape = 21, size = 5)

# Add significance levels
p + 
  stat_compare_means(ref.group = "0.5", label = "p.signif")
```

![](https://i.imgur.com/lyUl616.png)

``` r

# Customized plots using  vjust and expanded y-scale
p +
  stat_compare_means(ref.group = "0.5", label = "p.signif", vjust = -3) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.2)))
```

![](https://i.imgur.com/F5kc2NP.png)

<sup>Created on 2020-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by atakanekiz** [comment]
This does it! Thanks!
