### ISSUE TITLE
Support text justification for individual cells/rows/columns in ggtexttable()

### ISSUE THREAD

**Issue by winkel111** [kassambara/ggpubr#335]
Although text justification was added to ggtexttable (https://github.com/kassambara/ggpubr/issues/18), the justification setting always applies to the entire table.
It would be great if we could change the text justification for individual cells or rows/columns similar to table_cell_bg() or table_cell_font(). Having this option would be super useful. Thank you!

**Comment by tschoesi** [comment]
Also very interested in this (or a workaround that allows to change the justification of just a single column)!

**Comment by acdelre** [comment]
Can someone give an example of how to left justify the 1st column and right justify the rest? I cannot get the example above to work

**Comment by acdelre** [comment]
using this:  theme = ggpubr::ttheme(tbody.style =  ggpubr::tbody_style(hjust=as.vector(matrix(c(1, 0, 0,0),
                                                                                               ncol=4, nrow=nrow(MY_DATA),
                                                                                               byrow=TRUE)))
I can get the 1st column (sort of) left justified and the other 3 columns right justified (correctly) but the 1st column has the alignment left but flush right (so there ends up being space on the left side of the column), e.g.

 john smith
jeffe smiths
  sam smith
      j  smith

how can I get it left justified and flush left for the 1st column? thanks!

**Comment by acdelre** [comment]
I figured it out:
ggpubr::ttheme(tbody.style = ggpubr::tbody_style(hjust=as.vector(matrix(c(0, 1, 1,1),
                                                                                               ncol=4, nrow=nrow(sub),
                                                                                               byrow=TRUE)),  x = as.vector(matrix(c(.1, .9, .9,.9),
                                                                                             ncol=4, nrow=nrow(sub),
                                                                                             byrow=TRUE)))

**Comment by kassambara** [comment]
doc updated now with an example, thank you all for the contribution to the discussion
