### ISSUE TITLE
Superscripts in boxplot legend

### ISSUE THREAD

**Issue by fabio-t** [kassambara/ggpubr#337]
Hi, I made a plot with multiple boxplots side by side:

```
ggboxplot(df, x="Time", y=labels, add="point", width=0.5, merge=T, fill=".y.", palette = colours, ylab = "Proportions")
```

`df`'s rows are time points (x axis), and `df`'s columns (`labels`) contain superscripts, defined like `bquote("AA^{+/-")`. I've tried also with `expression`, but ggboxplot simply puts them as text in there, eg in the boxplot legend for that group it would show `"AA^{+/-"`.

So I'm not really sure how to force to convert the expression to unicode string with superscripts. Can you help?

**Comment by kassambara** [comment]
Would it be possible to have a reproducible script with a demo data ?

**Comment by fabio-t** [comment]
Hi, sorry for the late reply, will provide a self contained example soon.

**Comment by kassambara** [comment]
This R code works:

``` r
suppressPackageStartupMessages(library(ggpubr))

lab1 <- c(
  expression('0.5 mg.ml'^{-1}),
  expression('2 mg.ml'^{-1}),
  expression('3 mg.ml'^{-1})
)

ggboxplot(ToothGrowth, x = "dose", y = "len", color = "dose", legend = "right") +
  scale_color_discrete(labels = lab1)
```

![](https://i.imgur.com/vKZvpZg.png)

<sup>Created on 2020-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
