### ISSUE TITLE
label.y and stat_pvalue_manual for free scales facet_wrap 

### ISSUE THREAD

**Issue by pavitraviswanath** [kassambara/ggpubr#338]
I am still having the same issue despite adding p <- p + scale_y_continuous(expand = expansion(mult = c(0.1, 0.14))) before the stat_compare_means function.
In addition, when I try to add p-values computed using r-statix, I get the error saying y.position is not defined even though I do. This is my code:

stat.test <- rdf %>% add_y_position()
group_by(variable2) %>%
t_test(value~collection)
stat.test
p <- ggplot(data = rdf, mapping = aes(x = variable2, y = value, fill =collection))
p <- p + geom_violin(alpha=0.3, scale="width", position = position_dodge(width=1), size=0.5)
p <- p + geom_boxplot(alpha=0.7, outlier.shape=NA, facet.by="variable2",  position = position_dodge(1), scales="free")
p <- p + geom_point(position = position_jitterdodge(jitter.width=0.1,jitter.height=0, dodge.width = 1))
#p <- p + geom_jitter(position=position_jitter(width=0.1,height=0))
p <- p + theme_bw()
p <- p + theme(axis.text.x = element_blank())
p <- p + scale_fill_viridis_d(option = "D")
p <- p + facet_wrap(~variable2, scales="free", ncol=5)
p <- p + scale_y_continuous(expand = expansion(mult = c(0.1, 0.14)))
p <- p + stat_compare_means(method = "anova", size=3, hjust=0.7, label.y.npc = 'top', family="Arial", fontface="bold") 
#p <- p + stat_pvalue_manual(stat.test, label="p", y.position = "yloc") 
#p <- p + stat_compare_means(comparisons = my_comparisons, size=3, family= "Arial", face= "bold")
p <- p + labs(title="Extracellular Panel Analysis")
p <- p + ylab("% Live Cells") + xlab(" ")
p <- p + theme(text=element_text(family="Arial", face = "bold"))
p

![image](https://user-images.githubusercontent.com/43428054/93408900-e919a480-f852-11ea-9675-71821d53b92c.png)

_Originally posted by @pavitraviswanath in https://github.com/kassambara/ggpubr/issues/190#issuecomment-693753420_

**Comment by salix-d** [comment]
I think it might be because `label.y.npc` gets calculated before the expension?
My way around it was to do a `stat_compare_means` and use `label.y` for each facet by subsetting the data. 

For you it would be like :
```
p + 
    stat_compare_means(
        data = rdf[rdf$variable2 == "CD8+ T Cells",],
        method = "anova", 
        size=3, 
        hjust=0.7, 
        label.y = 6, 
        family="Arial", 
        fontface="bold"
     ) + 
    stat_compare_means(
        data = rdf[rdf$variable2 == "CD4+ T Cells",],
        method = "anova", 
        size=3, 
        hjust=0.7, 
        label.y = 14, 
        family="Arial", 
        fontface="bold"
    ) +
    ...etc
```

**Comment by kassambara** [comment]
@pavitraviswanath This issue may no longer be relevant; but before closing it, I would like to simply indicate that `add_y_position()` is not correctly used in your code.

It should be used like this (calling `add_y_position()` after `t_test()`) : 

```r
stat.test <- rdf %>% 
  group_by(variable2) %>%
  t_test(value~collection) %>%
  add_y_position()
```

Instead of this: 

```r
stat.test <- rdf %>% add_y_position()
group_by(variable2) %>%
t_test(value~collection)
```
