### ISSUE TITLE
Adding custom error bars to ggbarplot

### ISSUE THREAD

**Issue by bpbentley** [kassambara/ggpubr#339]
Hi,

Apologies if I've missed an obvious answer to this issue:
I'm using ggbarplot() to plot summary statistics from whole-genome data. I'm using other software to calculate means and standard deviations with single values as outputs, so I'm hoping to plot the mean as a barplot and the SD as error bars. I don't have any issues with plotting the means, but is there an easy way to add the SD as error bars without ggpubr trying to calculate these within?

i.e. can I add custom values as error bars rather than using "mean_sd"?

Thanks in advance,
Blair

**Comment by kassambara** [comment]
Does the following code help?

``` r
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggpubr))

# ccompute summary statistics
df.summary <- ToothGrowth %>%
  group_by(dose) %>%
  summarise(
    sd = sd(len, na.rm = TRUE),
    len = mean(len)
  )
#> `summarise()` ungrouping output (override with `.groups` argument)
df.summary
#> # A tibble: 3 x 3
#>    dose    sd   len
#>   <dbl> <dbl> <dbl>
#> 1   0.5  4.50  10.6
#> 2   1    4.42  19.7
#> 3   2    3.77  26.1

# Visualize
ggbarplot(df.summary, x = "dose", y = "len") +
  geom_errorbar(aes(ymin = len, ymax = len+sd), width = 0.2)
```

![](https://i.imgur.com/nB9BokJ.png)

**Comment by bpbentley** [comment]
I knew it would be something simple! Thank you, that's fixed it.
