### ISSUE TITLE
controlling order of points in ggscatter

### ISSUE THREAD

**Issue by johamunoz** [kassambara/ggpubr#340]
Dear Sir,
Thanks so much for your great package, at this moment I am doing a scatter plot with different color levels lets says levels=c("a", "b"), and  I wonder if there is a way to control which point is on top of which?  For example, what if I wanted all the "a" points to be on top of all the points labeled "b" (meaning they would sometimes partially or fully hide that point)?  Many thanks in advance for your help.

Johanna

**Comment by johamunoz** [comment]
Please you can close the issue, as I found that the plotting order is given by the order of the levels in the dataset. So for the question, it is only necessary to order the dataset with "b" levels first. Many thanks and again thanks for your great package!!!.

**Comment by kassambara** [comment]
Thank you for the positive feedback, highly appreciated!
