### ISSUE TITLE
[ggtexttable] fixing column names' position / fix column width

### ISSUE THREAD

**Issue by tschoesi** [kassambara/ggpubr#343]
I need to position a dynamic (no. of rows might change, no. of columns stays the same but the contents might be of different size) textual table in such a way that the column names stay in a certain position (because of a graphic that is above the table).

Is there any way to do this? Or alternatively a way to set some kind of spacing between columns?

Thanks!

**Comment by kassambara** [comment]
Are you trying to do something visually similar to [GGPLOT with Summary Stats Table Under the Plot](https://rpkgs.datanovia.com/ggpubr/reference/ggsummarystats.html)? If yes, then you can alternatively consider using the geom_text() function to build the table with fixed text positions under the plot.

**Comment by tschoesi** [comment]
Yes this looks pretty much like what I want to do, thank you!
Do you mean not using ggtexttable and build the table "by hand" with `geom_text`? 

Essentially what I'm trying to do is "fix column `i` to start at `(x_i,y_i)`"...

**Comment by tschoesi** [comment]
I think I will use `flextable` for this, as it seems to have excactly what I need (https://davidgohel.github.io/flextable/reference/width.html)
Thank you though!
