### ISSUE TITLE
ggarrange doesn't work in R version 4.0.2

### ISSUE THREAD

**Issue by kaatr** [kassambara/ggpubr#357]
I have been using ggarrange for a while and love the way it easily combines ggplot figures.
Recently I had to do an R update and unfortunately the ggarrange package is not compatible with the new version.
when trying to load the package I receive the following error message: 
`package ‘ggarrange’ is not available (for R version 4.0.2)`

Is there an update planned to solve this issue?
Thanks!

**Comment by apinharanda** [comment]
I am having the same issue, would love for it to be possible to use ggarrange with R 4.0.2

**Comment by llrs** [comment]
ggarrange is no longer on CRAN it was removed. If you want to combine ggplot figures I would recommend to use [patchwork](https://cran.r-project.org/package=patchwork) which is on CRAN and working for R 4.0.2.

**Comment by kassambara** [comment]
`ggarrange()` is a function available in ggpubr, you just need to load ggpubr to use it and it is available for 4.0.2.  The error message that you obtained let me think that you are trying to load `ggarrange` like a package.
