### ISSUE TITLE
Incorrect p-values postition  on ggplot facets

### ISSUE THREAD

**Issue by damianjwilliams** [kassambara/ggpubr#372]
Hi, I'm having a problem positioning the p values on a facet plot. The [example](https://www.datanovia.com/en/blog/how-to-add-p-values-to-ggplot-facets/) on the author's website works fine, but when I change the values, the positions seem wrong.

```
##Original example - works fine
#df <- ToothGrowth

##Example with changed values with incorrect p values
df <- ToothGrowth%>%
  mutate(len = if_else(dose == "0.5",len*0.1,len))%>%
  mutate(len = if_else(dose == "2",len*10,len))%>%
  as_tibble()
  
#Stats calculation
stat.test <- df %>%
  group_by(dose) %>%
  t_test(len ~ supp) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance()

# Make facet and add p-values
stat.test <- stat.test %>% add_xy_position(x = "supp", fun = "max")

#Plot
ggplot(df, aes(x = supp, y = len)) +
  geom_boxplot() +
  geom_jitter() +
  facet_wrap( ~ dose, scales = "free") +
  stat_pvalue_manual(stat.test, hide.ns = F,
                     label = "{p.adj}")
```

Original example

![Correct_position](https://user-images.githubusercontent.com/18335331/106920698-5aaaa000-66d9-11eb-9a27-5b090fae7b84.png)

Example with changed values

![Incorrect_position](https://user-images.githubusercontent.com/18335331/106920723-5e3e2700-66d9-11eb-9124-c3c85f863f73.png)

Am I missing something?

**Comment by kassambara** [comment]
Are you looking for the option `scales = "free"`  in the function `add_xy_position()`?

In your ggplot code, you used the option `scales = "free"` for facet; so don't forget to specify this option when computing also the p-value xy-position.

Here is an example:
``` r
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(rstatix))
suppressPackageStartupMessages(library(ggpubr))

# Data preparation
df <- ToothGrowth%>%
  mutate(len = if_else(dose == "0.5",len*0.1,len))%>%
  mutate(len = if_else(dose == "2",len*10,len))%>%
  as_tibble()

#Stats calculation
stat.test <- df %>%
  group_by(dose) %>%
  t_test(len ~ supp) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance()


# Make facet and add p-values
stat.test <- stat.test %>% 
  add_xy_position(x = "supp", fun = "max", scales = "free")

#Plot
ggplot(df, aes(x = supp, y = len)) +
  geom_boxplot() +
  geom_jitter() +
  facet_wrap( ~ dose, scales = "free") +
  stat_pvalue_manual(stat.test, hide.ns = F,
                     label = "{p.adj}")
```

![](https://i.imgur.com/ibhtofn.png)

<sup>Created on 2021-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by damianjwilliams** [comment]
Aaahhh. Great, works perfectly.  Thanks!
