### ISSUE TITLE
grids: space between grid lines?

### ISSUE THREAD

**Issue by AlirezaTafazzol** [kassambara/ggpubr#373]
In the following example, how can you increase the space between y-axis dashed lines to include only y-axis values (i.e., 10, 20, 30)?

![image](https://user-images.githubusercontent.com/24233022/106957288-adda1e00-66ec-11eb-80fb-a45eb45a7ea8.png)

https://rpkgs.datanovia.com/ggpubr/reference/grids.html

**Comment by brentocarrigan** [comment]
I don't think it's possible in the `ggpubr::grids` convenience wrapper function (it might well be), but it certainly is two other ways:

```
# If you want only the major axis lines, add a call to theme
p + 
  grids(linetype = 'dashed') +
  theme(panel.grid.minor.y = element_blank())

# If you want specific lines, add a call to the y scale, specifying breaks
p + 
  grids(linetype = 'dashed') + 
  scale_y_continuous(breaks = c(10,20,30))
```

**Comment by AlirezaTafazzol** [comment]
Thanks. Yeah adding the following line solved the problem.
`  + theme(panel.grid.minor.y = element_blank())
`
