### ISSUE TITLE
Package rstatix scheduled for archival on 2021-02-27

### ISSUE THREAD

**Issue by kapsner** [kassambara/ggpubr#376]
According to an email from Prof Brian Ripley of the CRAN team from Feb, 13th 2021, addressed to many package maintainers, the package `rstatix` is now scheduled for archival on 2021-02-27.

Since `ggpubr` depends on this package many reverse dependencies of `ggpubr` are scheduled as well for archival.

@kassambara would it be possible, to remove/replace `rstatix` as a strong dependency of `ggpubr`?

**Comment by kassambara** [comment]
Yes a solution is expected in due time. I will submit a new version of rstatix on CRAN on Monday 15th, so that it will not be archived

**Comment by kapsner** [comment]
Perfect thx. Did not see that you are also the maintainer of rstatix!

**Comment by kassambara** [comment]
- package rstatix_0.7.0.tar.gz is on its way to CRAN now.  
- Package check result: OK
- No changes to worse in reverse depends.

**Comment by OfekShilon** [comment]
@kassambara ggpubr depends on 96 other packages. Analysis with [pkgndep](https://cran.r-project.org/web/packages/pkgndep/vignettes/pkgndep.html) shows that most of these are through rstatix:
 
![image](https://user-images.githubusercontent.com/73080/155763370-198840c7-54e7-4494-8197-f4de9e9e1d44.png)

Is rstatix strictly necessary for ggpubr operation? Perhaps it can be moved to 'Suggests'?

(And thank you for *two* great packages!)
