### ISSUE TITLE
Cannot load ggpubr in R

### ISSUE THREAD

**Issue by muefong** [kassambara/ggpubr#384]
Hi Kassambara,
I hope you are doing well.

I get an error message trying to load ggpubr in R:
**Error: package or namespace load failed for ‘ggpubr’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘car’**

I have also tried to install the latest version from GitHub as follows:
# Install
if(!require(devtools)) install.packages("devtools")
devtools::install_github("kassambara/ggpubr")

But it still didn't get through.
Please help,
Caleb

**Comment by kassambara** [comment]
the installation of the `car` package  may have solved this problem
