### ISSUE TITLE
Column names with spaces can't be plotted.

### ISSUE THREAD

**Issue by dansmith01** [kassambara/ggpubr#388]
This is not a bug in the 0.4.0 version on CRAN; only in the current version of ggpubr on github (0.4.0.999 / ac5a01f).

```r
remotes::install_github("kassambara/ggpubr")
ToothGrowth[['spa ced']] <- ToothGrowth[['supp']]
ggpubr::ggboxplot(ToothGrowth, "supp", "len")  # works
ggpubr::ggboxplot(ToothGrowth, "spa ced", "len")  # broken
```
<img width="408" alt="spaced" src="https://user-images.githubusercontent.com/2066273/112399860-4c820480-8cc4-11eb-9b57-3c7decf09449.png">

**Comment by dansmith01** [comment]
I've submitted pull request #389 to fix this issue.

**Comment by kassambara** [comment]
Thank you for reporting this, fixed now
