### ISSUE TITLE
hide.ns not working in stat_compare_means with comparison

### ISSUE THREAD

**Issue by abletrue** [kassambara/ggpubr#40]
if (.is_p.signif_in_mapping(mapping) | !.is_empty(label %in% 
                                                      "p.signif")) {
      map_signif_level <- c(`****` = 1e-04, `***` = 0.001, 
                            `**` = 0.01, `*` = 0.05, ` ` = 1)
      if (hide.ns) 
        map_signif_level[5] <- c(` ` = 1)

Should there be a ns ? 
i.e. 
map_signif_level <- c(`****` = 1e-04, `***` = 0.001, 
                            `**` = 0.01, `*` = 0.05, `ns` = 1)

**Comment by kassambara** [comment]
Hi,

Please provide a reproducible example, thanks.

**Comment by SarenT** [comment]
I am having the same issue. When using comparisons, ns not showing up. Instead it is empty.

**Comment by kassambara** [comment]
Now, I would recommend the following approach:

1. compute p-values between groups
2. Filter out non-significant p-values
3. Add the p-values to the plots

Example:

```r
library(rstatix)  # https://github.com/kassambara/rstatix
stat.test <- ToothGrowth %>%
  group_by(dose) %>%
  t_test(len ~ supp) %>%
  adjust_pvalue() %>%
  add_significance() %>%
  filter(p.signif != "ns")
stat.test
```

<pre>
# A tibble: 2 x 9
   dose   .y. group1 group2 statistic      p method  p.adj p.signif
  <dbl> <chr>  <chr>  <chr>     <dbl>  <dbl>  <chr>  <dbl>    <chr>
1   0.5   len     OJ     VC  3.169733 0.0064 T-test 0.0128       **
2   1.0   len     OJ     VC  4.032770 0.0010 T-test 0.0030      ***
</pre>

Visualize:

```r
# Create a box plot and add the p-value
library(ggpubr)
ggboxplot(
  ToothGrowth, x = "supp", y = "len",
  color = "supp", palette = "jco",
  facet.by = "dose", ylim = c(0, 40)
) + 
  stat_pvalue_manual(stat.test, label = "p.signif", y.position = 35)
```

![rplot38](https://user-images.githubusercontent.com/3313355/43972598-30271d16-9cd5-11e8-9f11-c02bbf112c16.png)

**Comment by natjoh** [comment]
Hi, I have followed the instructions above, see as below, however, in the graph brackets are overlapping and it is difficult to determine the comparisons and values, is there a way to fix this? Secondly, is there a y_scale = free options for use with this package? I can't get scales =  "free" to work. 

dat2<-data.frame(R_Full_simple)
R_Full_simple

dat2$grp.fac <- factor(dat2$spacer_type,levels=c("1","2","0","3","4"),
                       labels = c("a) non-valved \n spacer", 
                      "b) valved \n spacer", "c) direct", "d) adapter", "e) syringe") ) 
dat2$grp.size <- factor(dat2$ett_size,levels=c("1","2","3","4"),labels = c("3 mm", "5 mm", "7 mm", "9 mm"))

#copy and paste https://github.com/kassambara/ggpubr/issues/40
stat.test <- dat2 %>%
  group_by(ett_size) %>%
  t_test(ett_pct ~ grp.fac, conf.level = 0.95) %>%
  adjust_pvalue() %>%
  add_significance("p.adj") %>%
  filter(p.adj.signif != "ns")
stat.test


#now create the graph, copy and paste, https://github.com/kassambara/ggpubr/issues/40
ggboxplot(dat2, x = "grp.fac", y = "ett_pct",
  color = "grp.fac", palette = "jco",
  facet.by = "grp.size") + 
  stat_pvalue_manual(stat.test, label = "p.adj.signif", y.position = 50)

![Rplot_Rstatix_github](https://user-images.githubusercontent.com/48945604/55943095-775e2400-5c78-11e9-96b6-fbaee1df7571.png)

Thanks in advance

**Comment by Zhuang-WUR** [comment]
> stat_pvalue_manual(stat.test, label = "p.adj.signif", y.position = 50)

first problem solved
stat_pvalue_manual(stat.test, label = "p.adj.signif", y.position = 50, step.increase = 0.1)

**Comment by Zhuang-WUR** [comment]
> Now, I would recommend the following approach:
> 
> 1. compute p-values between groups
> 2. Filter out non-significant p-values
> 3. Add the p-values to the plots
> 
> Example:
> 
> ```r
> library(rstatix)  # https://github.com/kassambara/rstatix
> stat.test <- ToothGrowth %>%
>   group_by(dose) %>%
>   t_test(len ~ supp) %>%
>   adjust_pvalue() %>%
>   add_significance() %>%
>   filter(p.signif != "ns")
> stat.test
> ```
> 
> # A tibble: 2 x 9
>    dose   .y. group1 group2 statistic      p method  p.adj p.signif
>                       
> 1   0.5   len     OJ     VC  3.169733 0.0064 T-test 0.0128       **
> 2   1.0   len     OJ     VC  4.032770 0.0010 T-test 0.0030      ***
> Visualize:
> 
> ```r
> # Create a box plot and add the p-value
> library(ggpubr)
> ggboxplot(
>   ToothGrowth, x = "supp", y = "len",
>   color = "supp", palette = "jco",
>   facet.by = "dose", ylim = c(0, 40)
> ) + 
>   stat_pvalue_manual(stat.test, label = "p.signif", y.position = 35)
> ```
> 
> ![rplot38](https://user-images.githubusercontent.com/3313355/43972598-30271d16-9cd5-11e8-9f11-c02bbf112c16.png)

Hi I keep receive this following error:

Error: Problem with `filter()` input `..1`.
x object 'p.signif' not found
i Input `..1` is `p.signif != "ns"`.

my code:

stat.test <- met.dat.24 %>%
  group_by(Bac.lev) %>%
  t_test(acetate~prototype) %>%
  adjust_pvalue() %>%
  add_significance() %>%
  filter(p.signif != "ns")
stat.test

could you have a look? thank you so much!

**Comment by Zhuang-WUR** [comment]
> Now, I would recommend the following approach:
> 
> 1. compute p-values between groups
> 2. Filter out non-significant p-values
> 3. Add the p-values to the plots
> 
> Example:
> 
> ```r
> library(rstatix)  # https://github.com/kassambara/rstatix
> stat.test <- ToothGrowth %>%
>   group_by(dose) %>%
>   t_test(len ~ supp) %>%
>   adjust_pvalue() %>%
>   add_significance() %>%
>   filter(p.signif != "ns")
> stat.test
> ```
> 
> # A tibble: 2 x 9
>    dose   .y. group1 group2 statistic      p method  p.adj p.signif
>                       
> 1   0.5   len     OJ     VC  3.169733 0.0064 T-test 0.0128       **
> 2   1.0   len     OJ     VC  4.032770 0.0010 T-test 0.0030      ***
> Visualize:
> 
> ```r
> # Create a box plot and add the p-value
> library(ggpubr)
> ggboxplot(
>   ToothGrowth, x = "supp", y = "len",
>   color = "supp", palette = "jco",
>   facet.by = "dose", ylim = c(0, 40)
> ) + 
>   stat_pvalue_manual(stat.test, label = "p.signif", y.position = 35)
> ```
> 
> ![rplot38](https://user-images.githubusercontent.com/3313355/43972598-30271d16-9cd5-11e8-9f11-c02bbf112c16.png)

hi, is there a spectacular reason to add the adjust pvalue?

**Comment by yzhong005** [comment]
Have written something to get a good y position for facet plot. hope this can help someone who needs it.


# stat test with t.test.
stat.test2<-compare_means(
  value ~ Group1, data = data, group.by = "variable",
  method = "t.test")
# remove the ns value
stat.test2<-stat.test2 %>%
  filter(p.signif !="ns") 
# get y position from your original data
stat.test2$y.position<-0 # add the y.position column

for (i in 1:length(stat.test2))                                                                               # get the y.position one by one
{data1<-data[data$variable==stat.test2$variable[i],]   # variable is the data I use to facet. the idea is for each facet it will call 
                                                                                       #different y position
level<-max(data1$value[data1$Group1 %in% c(stat.test2[i,]$group1,stat.test2[i,]$group2)]) #check the highest value in these 
                                                                                                                                                   #two group I want to draw bracket 
                                                                                                                                                   #for p value in this facet
level<-level*1.03  # make the bracket a little bit higher than the highest value
while (level %in% stat.test2$y.position[stat.test2$variable==stat.test2$variable[i]])    # In case the bracket overlap, make it 
{level<-level*1.05}                                                                                                          # higher until no overlap with previous
stat.test2$y.position[i]<-level}

#now you can plot it and add it to your plot
p+stat_pvalue_manual(stat.test2,label = "p.signif")
