### ISSUE TITLE
Specifying Alternative for stat_compare_means

### ISSUE THREAD

**Issue by Nicktz** [kassambara/ggpubr#41]
Hi, 

Great package.

When using stat_compare_means , I cannot find a way of specifying the alternative for the wilcox.test (e.g. setting alternative = "less").

Is this possible using the function? It seems like a core parameter for a graphical function of this sort to be used extensively.

Thanks and regards

Nico

**Comment by kassambara** [comment]
New argument `method.args` added to `stat_compare_means()`. A list of additional arguments used for the test method. For example one might use method.args = list(alternative = "greater") for wilcoxon test

```r
library("ggpubr")
data(ToothGrowth)

df3 <- ToothGrowth
ggboxplot(df3, x = "dose", y = "len")+
  stat_compare_means(ref.group = "0.5", 
                     method = "wilcox.test",
                     method.args = list(alternative = "less"))
```

![rplot18](https://user-images.githubusercontent.com/3313355/31347574-0f2d897c-ad1d-11e7-9919-6fbff410d4f6.png)
