### ISSUE TITLE
Adjust significance brackets for grouped boxplots

### ISSUE THREAD

**Issue by RainmanMathers** [kassambara/ggpubr#421]
Dear kassambara, 

first of all, thank you for your great packages and all of the work you put in, it's really helped me a lot for my projects. 
However, I have a minor aesthetic issue / question: 
Using your guide on how to add p values to grouped ggplot objects I have created multiple great plots similar to your examples. 
https://www.datanovia.com/en/blog/how-to-add-p-values-onto-a-grouped-ggplot-using-the-ggpubr-r-package/

I am particularly interested in a layout similar to this one:

![image](https://user-images.githubusercontent.com/45274761/124610883-2ea26f00-de71-11eb-8e5c-e3684a9db71e.png)

However, going through your guide(s) and attempting various things I've been unable to nudge the brackets so they start and end above the corresponding pair of boxplots (i.e. blue bar spans between the two blue boxplots (like the red exemplary bar) and not centered with the same range as the yellow one). 
Obviously this is only a minute detail, however when it comes down to publication journals (or PIs for that matter) can be pretty picky. 
I've managed to achieve this by manually changing the xmin and xmax values, but I was wondering if there was a more elegant way of doing this especially for larger scaled analysis.

I hope you can help me with this, 
Best!

**Comment by ncro0005** [comment]
Hi there!
I know you had this drama over a year ago however I am encountering the same thing at the moment and cannot find a solution on other forums. 
I think I too will resort to using manual entry, how did you enter the xmin and xmax values for your manual solution? 
Cheers!

**Comment by RainmanMathers** [comment]
Hi!

So basically I used the stat_pvalue_manual function from the ggpubr package and a manually built tibble with the data: 
- I ran the desired test
- added xy position using the add_xy_position from the rstatix package

`statGroup <- MonosLong %>% filter(cell == "ClassMonosPer" & Group %in% c("RI+", "Remission")) %>% 
  group_by(specimen) %>% 
  pairwise_wilcox_test(value ~ Group, p.adjust.method = "holm") %>% 
  add_significance() %>% 
  add_xy_position(x = "Group", dodge = 1)`

- manually edited the xmin and xmax values in crude trial and error fashion trying to see what looked ok:
`statGroup[1, 13] = 0.8
statGroup[1, 14] = 1.8

statGroup[2, 13] = 1.2
statGroup[2, 14] = 2.2`

- then built the plot with manual p-values: 
`CMonosplot <- MonosLong %>% 
  filter(cell == "ClassMonosPer" & Group %in% c("RI+", "Remission")) %>% 
  ggplot(data = ., aes(x = Group, y = value))+
    geom_boxplot(width = .5, outlier.shape = NA, aes(color = specimen, fill = specimen), position = position_dodge(width = 0.8), alpha = 0.5)+
    geom_dotplot(binaxis = "y", stackdir = "center", stackratio = 1, dotsize = .5, alpha = 0.5, aes(fill = specimen), 
                 position = position_dodge(width = .8))+
    stat_pvalue_manual(data = statPaired, tip.length = 0.01, label.size = 2.5, label = "p.adj")+
    stat_pvalue_manual(data = statGroup, step.increase = .05, tip.length = 0.01, label.size = 2.5, label = "p")`

It was quite a bit of work doing it manually, but I guess for a single figure it's doable.

**Comment by kassambara** [comment]
Now, the function `geom_pwc()` is available for automatically computing and adding pairwise comparison p-values on ggplot. It has more possibilities compared to the manual way using rstatix + ggpubr::stat_pvalue_manual().   Read more at: http://rpkgs.datanovia.com/ggpubr/reference/geom_pwc.html

See examples below:

``` r
suppressPackageStartupMessages(library(ggpubr))

# Data preparation
# Transform `dose` into factor variable
df <- ToothGrowth
df$dose <- as.factor(df$dose)
head(df, 3)
#>    len supp dose
#> 1  4.2   VC  0.5
#> 2 11.5   VC  0.5
#> 3  7.3   VC  0.5


# Create a box plot
# Add 10% spaces between the p-value labels and the plot border
bxp <- ggboxplot(
  df, x = "dose", y = "len", 
  color = "supp", palette = c("#00AFBB", "#E7B800")
) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.10)))

# Box plot
# Group by legend var (`supp`) and perform test between x-groups
# dodge = 0.8 default
bxp + geom_pwc(
  aes(group = supp, color = supp), 
  method = "t_test", label = "p.adj.signif",
  p.adjust.method = "bonferroni", p.adjust.by = "group",
  tip.length = 0, group.by = "legend.var"
)
```

![](https://i.imgur.com/6leykmo.png)

``` r


# Group brackets by legend var
bxp + geom_pwc(
  aes(group = supp, color = supp), 
  method = "t_test", label = "p.adj.signif",
  p.adjust.method = "bonferroni", p.adjust.by = "group",
  tip.length = 0, group.by = "legend.var",
  bracket.group.by = "legend.var"
)
```

![](https://i.imgur.com/Kmv6E3N.png)

``` r


# Using dodge = 0
bxp + geom_pwc(
  aes(group = supp, color = supp), 
  method = "t_test", label = "p.adj.signif",
  p.adjust.method = "bonferroni", p.adjust.by = "group",
  tip.length = 0, group.by = "legend.var",
  bracket.group.by = "legend.var",
  dodge = 0
)
```

![](https://i.imgur.com/JaALZe4.png)

**Comment by kassambara** [comment]
Of course, if you still would like to continue using stat_pvalue_manual(), you can, but make sure to specify the grouping variable ( legend variable) when calling `add_xy_position()`  if you would like to adjust the bracket position of grouped plot. See example below

``` r
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(rstatix))

# Data preparation
# Transform `dose` into factor variable
df <- ToothGrowth
df$dose <- as.factor(df$dose)
head(df, 3)
#>    len supp dose
#> 1  4.2   VC  0.5
#> 2 11.5   VC  0.5
#> 3  7.3   VC  0.5

# statistical tests
pwc <- df %>%
  group_by(supp) %>%
  t_test(len ~ dose, p.adjust.method = "bonferroni")
pwc
#> # A tibble: 6 × 11
#>   supp  .y.   group1 group2    n1    n2 statistic    df        p   p.adj p.adj…¹
#> * <fct> <chr> <chr>  <chr>  <int> <int>     <dbl> <dbl>    <dbl>   <dbl> <chr>  
#> 1 OJ    len   0.5    1         10    10     -5.05  17.7  8.78e-5 2.63e-4 ***    
#> 2 OJ    len   0.5    2         10    10     -7.82  14.7  1.32e-6 3.96e-6 ****   
#> 3 OJ    len   1      2         10    10     -2.25  15.8  3.9 e-2 1.18e-1 ns     
#> 4 VC    len   0.5    1         10    10     -7.46  17.9  6.81e-7 2.04e-6 ****   
#> 5 VC    len   0.5    2         10    10    -10.4   14.3  4.68e-8 1.4 e-7 ****   
#> 6 VC    len   1      2         10    10     -5.47  13.6  9.16e-5 2.75e-4 ***    
#> # … with abbreviated variable name ¹​p.adj.signif


# Create a box plot
# Add 10% spaces between the p-value labels and the plot border
bxp <- ggboxplot(
  df, x = "dose", y = "len", 
  color = "supp", palette = c("#00AFBB", "#E7B800")
) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.10)))


# Add p-values to the plot
pwc <- pwc %>% add_xy_position(x = "dose", group = "supp")
bxp +
  stat_pvalue_manual(
    pwc, color = "supp", step.group.by = "supp",
    tip.length = 0, step.increase = 0.1
  )
```

![](https://i.imgur.com/2x465xr.png)

**Comment by RainmanMathers** [comment]
Awesome! That’s exactly what I was looking for. Thank you so much!!
