### ISSUE TITLE
ggpie cutting off labels

### ISSUE THREAD

**Issue by vertesy** [kassambara/ggpubr#429]
Dear Alboukadel,

thanks for this awesome package, really useful! 
(I even built on top of it for further lazyfication [ggExpress](https://github.com/vertesy/ggExpressDev))

With `ggpie` I noticed that if slices have long names 
(and not using legend, directly labeling the sectiions),  they are often cropped.

I was trying to fix it with margin, but that does not help with cropping.

I guess I am lacking terminology here, maybe I need to adjust: axis-range? canvas size?

Example
```r

df <- data.frame(
  group = c("Male", "Female", "Children but not teenager"),
  value = c(25, 25, 50))

ggpie(df, "value", label = "group")
```
![image](https://user-images.githubusercontent.com/5101911/134222162-51d7fe97-d8b7-4db2-becc-f067f3485f5c.png)

Appreciate your help!

**Comment by caldwellst** [comment]
Referenced in an [SO post I responded to](https://stackoverflow.com/questions/70353459/how-can-i-increase-canvas-size-or-plot-area-so-that-it-does-not-crop-labels-in-g/70353670#70353670). Would recommend amending `ggpie()` to add `clip = "off"` to the call to `coord_polar()` on line 26 as default, or allow passing the argument explicitly in `ggpie()`.

**Comment by kassambara** [comment]
fixed now, thanks
