### ISSUE TITLE
Change axis, error bar and comparison brackets linewidth

### ISSUE THREAD

**Issue by mtmatter** [kassambara/ggpubr#43]
Hey,
Is there any way to change the thickness of axis, error bar and comparison brackets?
Thanks

Edit: I just realized you can overwrite the axis with ggplot2 code (+theme(axis.line.x=...))
Haven't found a way to change the error bars or comparison brackets though

**Comment by kassambara** [comment]
You can do this:


```r
library(ggpubr)
ggbarplot(
  ToothGrowth, x = "dose", y = "len",
  add = "mean_sd", add.params = list(size = 4)
  )+
  stat_compare_means(
    comparisons = list(c("1", "2")),
    bracket.size = 2
  )
```

![rplot42](https://user-images.githubusercontent.com/3313355/44001107-e52cbf84-9e2b-11e8-8e5c-4f7e6ed009a9.png)
