### ISSUE TITLE
A question about the argument align in the function ggarrange()

### ISSUE THREAD

**Issue by JackTsaoo** [kassambara/ggpubr#430]
Dear Alboukadel,

Thanks for your great work!
I have a question about the argument align in the function ggarrange().
I try to combine two plots with different ranges of x-axis into a 2*1 plot using the ggarrange(). 
I hope the two plots can be aligned vertically (i.e., having the same ranges and scales of x-axis). 
So I set align = 'v'. However, it doesn't work. 
I give a simple example here:
g1 = ggplot() + geom_line(aes(x = 1:5, y = 5:9)) 
g2 = ggplot() + geom_line(aes(x = 3:7, y = 1:5))
ggarrange( g1, g2, nrow = 2, align = 'v') 

What's wrong with these scripts? Or I misunderstand the use of align?
Many Thanks.

**Comment by nd283** [comment]
I am having the same issue.

**Comment by kassambara** [comment]
It should workwith the latest version of ggpubr, like below:


``` r
suppressPackageStartupMessages(library(ggpubr))

g1 = ggplot() + geom_line(aes(x = 1:5, y = 5:9))
g2 = ggplot() + geom_line(aes(x = 3:7, y = 1:5))
ggarrange( g1, g2, nrow = 2, align = 'v')
```

![](https://i.imgur.com/oANCmEv.png)

**Comment by hwouters-argenx** [comment]
I still have the same problem with the newest version of ggpubr?
