### ISSUE TITLE
Error in library(ggscatter) : there is no package called ‘ggscatter’

### ISSUE THREAD

**Issue by xiranhui** [kassambara/ggpubr#431]
After I updated R I  cannot use ggscatter
Warning in install.packages :
  package ‘ggscatter’ is not available (for R version 4.1.0)

Then I changed R to 3.6.1
Still cannot use ggscatter after I installed ggplot2 and ggpubr
> library(ggpubr)
> library(ggplot2)
> library(ggscatter)
Error in library(ggscatter) : there is no package called ‘ggscatter’

> devtools::session_info()
- Session info ---------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2021-09-28                  

- Packages -------------------------------------------------------------------------------------------------------------
 ! package        * version date       lib source        
   abind            1.4-5   2016-07-21 [1] CRAN (R 4.0.0)
   assertthat       0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
   backports        1.2.1   2020-12-09 [1] CRAN (R 3.6.3)
   BiocManager      1.30.16 2021-06-15 [1] CRAN (R 3.6.1)
   broom            0.7.9   2021-07-27 [1] CRAN (R 3.6.1)
   cachem           1.0.4   2021-02-13 [1] CRAN (R 3.6.3)
   callr            3.7.0   2021-04-20 [1] CRAN (R 3.6.3)
   car              3.0-11  2021-06-27 [1] CRAN (R 3.6.1)
   carData          3.0-4   2020-05-22 [1] CRAN (R 4.0.0)
   cellranger       1.1.0   2016-07-27 [1] CRAN (R 4.0.2)
   cli              3.0.1   2021-07-17 [1] CRAN (R 3.6.1)
   colorspace       2.0-1   2021-05-04 [1] CRAN (R 3.6.3)
   crayon           1.4.1   2021-02-08 [1] CRAN (R 3.6.3)
   curl             4.3.1   2021-04-30 [1] CRAN (R 3.6.3)
   data.table       1.14.0  2021-02-21 [1] CRAN (R 3.6.3)
   DBI              1.1.1   2021-01-15 [1] CRAN (R 3.6.3)
   desc             1.4.0   2021-09-28 [1] CRAN (R 3.6.1)
   devtools       * 2.4.2   2021-06-07 [1] CRAN (R 3.6.1)
   digest           0.6.27  2020-10-24 [1] CRAN (R 3.6.3)
   dplyr            1.0.6   2021-05-05 [1] CRAN (R 3.6.3)
   ellipsis         0.3.2   2021-04-29 [1] CRAN (R 3.6.3)
   fansi            0.4.2   2021-01-15 [1] CRAN (R 3.6.3)
   farver           2.1.0   2021-02-28 [1] CRAN (R 3.6.3)
   fastmap          1.1.0   2021-01-25 [1] CRAN (R 3.6.3)
   forcats          0.5.1   2021-01-27 [1] CRAN (R 3.6.3)
 D foreign          0.8-71  2018-07-20 [2] CRAN (R 3.6.1)
   fs               1.5.0   2020-07-31 [1] CRAN (R 3.6.3)
   generics         0.1.0   2020-10-31 [1] CRAN (R 3.6.3)
   ggplot2        * 3.3.5   2021-06-25 [1] CRAN (R 3.6.1)
   ggpubr         * 0.4.0   2020-06-27 [1] CRAN (R 3.6.3)
   ggsignif         0.6.3   2021-09-09 [1] CRAN (R 3.6.1)
   glue             1.4.2   2020-08-27 [1] CRAN (R 3.6.3)
   gtable           0.3.0   2019-03-25 [1] CRAN (R 4.0.2)
   haven            2.4.1   2021-04-23 [1] CRAN (R 3.6.3)
   hms              1.1.1   2021-09-26 [1] CRAN (R 3.6.1)
   labeling         0.4.2   2020-10-20 [1] CRAN (R 3.6.3)
   lifecycle        1.0.1   2021-09-24 [1] CRAN (R 3.6.1)
   limma          * 3.42.2  2020-02-03 [1] Bioconductor  
   magrittr         2.0.1   2020-11-17 [1] CRAN (R 3.6.3)
   memoise          2.0.0   2021-01-26 [1] CRAN (R 3.6.3)
   munsell          0.5.0   2018-06-12 [1] CRAN (R 4.0.2)
   openxlsx         4.2.3   2020-10-27 [1] CRAN (R 3.6.3)
   pheatmap       * 1.0.12  2019-01-04 [1] CRAN (R 4.0.2)
   pillar           1.6.3   2021-09-26 [1] CRAN (R 3.6.1)
   pkgbuild         1.2.0   2020-12-15 [1] CRAN (R 3.6.3)
   pkgconfig        2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
   pkgload          1.2.2   2021-09-11 [1] CRAN (R 3.6.1)
   preprocessCore * 1.48.0  2019-10-29 [1] Bioconductor  
   prettyunits      1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
   processx         3.5.2   2021-04-30 [1] CRAN (R 3.6.3)
   ps               1.6.0   2021-02-28 [1] CRAN (R 3.6.3)
   purrr            0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
   R6               2.5.1   2021-08-19 [1] CRAN (R 3.6.1)
   RColorBrewer     1.1-2   2014-12-07 [1] CRAN (R 4.0.0)
   Rcpp             1.0.6   2021-01-15 [1] CRAN (R 3.6.3)
   readxl           1.3.1   2019-03-13 [1] CRAN (R 4.0.2)
   remotes          2.4.0   2021-06-02 [1] CRAN (R 3.6.1)
   rio              0.5.27  2021-06-21 [1] CRAN (R 3.6.1)
   rlang            0.4.11  2021-04-30 [1] CRAN (R 3.6.3)
   rprojroot        2.0.2   2020-11-15 [1] CRAN (R 3.6.3)
   rstatix          0.7.0   2021-02-13 [1] CRAN (R 3.6.3)
   scales           1.1.1   2020-05-11 [1] CRAN (R 4.0.2)
   sessioninfo      1.1.1   2018-11-05 [1] CRAN (R 3.6.3)
   stringi          1.6.1   2021-05-10 [1] CRAN (R 3.6.3)
   testthat         3.0.2   2021-02-14 [1] CRAN (R 3.6.3)
   tibble           3.1.1   2021-04-18 [1] CRAN (R 3.6.3)
   tidyr            1.1.3   2021-03-03 [1] CRAN (R 3.6.3)
   tidyselect       1.1.1   2021-04-30 [1] CRAN (R 3.6.3)
   usethis        * 2.0.1   2021-02-10 [1] CRAN (R 3.6.3)
   utf8             1.2.1   2021-03-12 [1] CRAN (R 3.6.3)
   vctrs            0.3.8   2021-04-29 [1] CRAN (R 3.6.3)
   withr            2.4.2   2021-04-18 [1] CRAN (R 3.6.3)
   zip              2.1.1   2020-08-27 [1] CRAN (R 3.6.3)

 D -- DLL MD5 mismatch, broken installation.

**Comment by kassambara** [comment]
`ggscatter()` is not a package, it is a function available in `ggpubr`. After loading ggpubr, you just need to use it. You don't have to execute `library(ggscatter)`
