### ISSUE TITLE
Remove whitespace around pie chart

### ISSUE THREAD

**Issue by wenbostar** [kassambara/ggpubr#443]
Is that possible to add a parameter in ggpie to control removing whitespace around pie chart?

```R
df <- data.frame(
    group = c("Male", "Female", "Child"),
    value = c(25, 25, 50))

head(df)


# Basic pie charts
# ++++++++++++++++++++++++++++++++

ggpie(df, "value", label = "group")
```

![image](https://user-images.githubusercontent.com/5302110/145447443-87150907-16f4-4dc1-917e-e74c6812a989.png)

**Comment by kassambara** [comment]
Something like the following code can be used to reduce the plot margin:

```r
ggpie(df, "value", label = "group") +
  theme( plot.margin = unit(c(-.75,-.75,-.75,-.75),"cm"))
```
