### ISSUE TITLE
ylim & stat_compare_means

### ISSUE THREAD

**Issue by xiangrong7** [kassambara/ggpubr#451]
Hello
dear,I have a problem. I checked this #305 ,but it did not work .
```r
my_comparisons <- list(c("1","2"), c("1", "3"),c("1", "4"),
                       c("2","3"),c("2", "4"),
                       c("3", "4")
                       )

ggboxplot(df, x = "Patient",y="Value",outlier.shape=NA,fill = "Patient")+
  #ylim(0,20)+
  stat_compare_means(method = "wilcox.test", comparisons = my_comparisons, 
                    # label.y=c( 20)
                     )
```
This will output following:
![image](https://user-images.githubusercontent.com/24288935/154233128-628b519c-cd43-40dd-8596-a69504e082a8.png)
add ylim
```r
ggboxplot(df, x = "Patient",y="Value",outlier.shape=NA,fill = "Patient")+
  ylim(0,20)+
  stat_compare_means(method = "wilcox.test", comparisons = my_comparisons, 
                     label.y=c( 20)
                     )
```
This will output following:
![image](https://user-images.githubusercontent.com/24288935/154233317-dc3111f2-d35f-4596-bb4f-274f71ea905e.png)

There is not have p value in graph. Could you help me ?

**Comment by alejer** [comment]
hi, I have a similar problem, the label.y is not solving it.
```
plot_parameters <- function(parameter, y.label, y.low=0, y.high=100, stat.print.y = NA, df = dataset) { 
      df %>%
          select(kat_cas, nick, parameter) %>%
          pivot_longer(cols=parameter, names_to = "parameter", values_to = "values") %>%
          ggplot(aes(x=kat_cas, y=values))  + geom_boxplot(width=0.3) + 
          stat_compare_means(comparisons = compare_to_zero, 
                             method = "wilcox.test",
                             paired = TRUE,
                             label="p.signif", hide.ns = FALSE,
                             label.y = stat.print.y) +
      coord_cartesian(ylim=c(y.low-(y.high-y.low)/10, y.high), clip = "off")
}
```
With a call `plot_parameters("IL.6", 'IL-6 (ng/L)', 0, 15000, stat.print.y = 10000, df = df.septic)` 
I get the following result:

![slika](https://user-images.githubusercontent.com/13355342/157656764-85fad42a-a0c7-48a8-90ae-ddfc8baafad3.png)

However, playing aroung with `plot_parameters("IL.6", 'IL-6 (ng/L)', 0, 50000, stat.print.y = 10000, df = df.septic)`
I get this result, which I cant explain
![slika](https://user-images.githubusercontent.com/13355342/157657627-d7a66d11-5186-4307-836f-6cb7ed7c9815.png)

Thank you!

**Comment by kassambara** [comment]
The length of `label.y` should be the same as the number of brackets. If you have 5 brackets then `label.y` should contain 5 values, one position for each bracket. See examples below: 

``` r
suppressPackageStartupMessages(library(ggpubr))

# Load data
data("ToothGrowth")
head(ToothGrowth)
#>    len supp dose
#> 1  4.2   VC  0.5
#> 2 11.5   VC  0.5
#> 3  7.3   VC  0.5
#> 4  5.8   VC  0.5
#> 5  6.4   VC  0.5
#> 6 10.0   VC  0.5

# Pairwise comparisons: Specify the comparisons you want
my_comparisons <- list( c("0.5", "1"), c("1", "2"), c("0.5", "2") )
p <- ggboxplot(ToothGrowth, x = "dose", y = "len",
          color = "dose", palette = "npg")

  # Add pairwise comparisons p-value
p + stat_compare_means(comparisons = my_comparisons)
```

![](https://i.imgur.com/5ahi1XO.png)

``` r

# Changing bracket y position
# you should specify position for each bracket
# We have 3 brackets so label.y should contain 3 values
p + stat_compare_means(comparisons = my_comparisons, label.y = c(29, 35, 40))
```

![](https://i.imgur.com/qPQXY27.png)


See also https://rpkgs.datanovia.com/ggpubr/reference/geom_pwc.html
