### ISSUE TITLE
compare_means() and pairwise_wilcox_test() different results?

### ISSUE THREAD

**Issue by marwa38** [kassambara/ggpubr#478]
Hello amazing guys 

Now I found there is a difference that I can't grasp between compare_means() and pairwise_wilcox_test() looking in to stat difference between intes.dsChall**MMV**  and intes.dsChall**VMV**

my codes 
```
devtools::install_github("kassambara/rstatix", dependencies = FALSE)
devtools::install_github("kassambara/ggpubr", dependencies = FALSE)
library("ggpubr") # for stat_compare_means function 
library("rstatix")
.rs.restartR()
test1 <- compare_means(Shannon ~ CONDITION,
              ps.prev.np.rich,
              p.adjust.method = "BH")
```
selected one from the table 
          .y.     group1                   group2                 p                     p.adj     p.format p.signif method  
Shannon  intes.dsChallMMV  intes.dsChallVMV  3.441769e-02  6.2e-02  0.03442  *         Wilcoxon
```
test2 <- pairwise_wilcox_test(ps.prev.np.rich,
            Shannon ~ CONDITION,
            p.adjust.method = "BH")
```
selected same two groups from from the table 
          .y.     group1                     group2              n1    n2      statistic      p p.adj   p.adj.signif
Shannon intes.dsChallMMV intes.dsChallVMV    13    11      108. 0.034  0.062     ns 

Kindly find attached the results of both (test 1 and test 2 tables) in addition to the dataframe used (ps.prev.np.rich.rds) in a zipped folder.
[trail.zip](https://github.com/kassambara/ggpubr/files/9030600/trail.zip)

```
sessionInfo()
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] rstatix_0.7.0.999 microbiome_1.14.0 phyloseq_1.38.0   forcats_0.5.1     stringr_1.4.0     dplyr_1.0.7       purrr_0.3.4       readr_2.1.1      
 [9] tidyr_1.1.4       tibble_3.1.6      tidyverse_1.3.1   ggpubr_0.4.0.999  ggplot2_3.3.5     agricolae_1.3-5  
```

**Comment by marwa38** [comment]
@kassambara Any updates please on this?

**Comment by kassambara** [comment]
related to #256

**Comment by kassambara** [comment]
Hello, I can see that the two functions returns similar results in term of adjusted p-value (see attached image). The only minor difference is that compare_means() is rounding the adjusted p value using `signif(p.adj, digits = 2)`.

![Capture d’écran 2022-11-23 à 22 36 12](https://user-images.githubusercontent.com/3313355/203650415-056fe6d2-3c98-4956-9023-32b35a1a7939.png)
