### ISSUE TITLE
Follow up for issue #60

### ISSUE THREAD

**Issue by Shari51** [kassambara/ggpubr#483]
It would be so helpful to please add in an option to hide the line of comparisons with non-significant p-values. I want to remove the value (done with hide.ns=T) but I also want the line gone. (Another issue for another time is hiding non-significant value when using the p.format, but again, for another time) I know there are workarounds for only including significant comparisons in the comparisons list but none of them work with facetting of boxplot with 4 samples if the comparisons are different in each facet.
Any help on this would be greatly appreciated!

**Comment by yzhong005** [comment]
You can consider calculating the p-value and add it manually with this code
# calculate the p-value
stat.test2<-compare_means(
  value ~ Group1, data = data, group.by = "variable",
  method = "t.test")
#remove the ns
stat.test2<-stat.test2 %>%
  filter(p.signif !="ns")
# or if you don't want to use the filter function.
stat.test2<-stat.test2[stat.test2$p.signif !="ns",]
#now get the y.position for them to plot
# add the y.position column
stat.test2$y.position<-0 

for (i in 1:length(stat.test2)) # get the y.position one by one
{data1<-data[data$variable==stat.test2$variable[i],] # variable is the data I use to facet. the idea is for each facet it will call 
                                                                                     #different y position
level<-max(data1$value[data1$Group1 %in% c(stat.test2[i,]$group1,stat.test2[i,]$group2)]) #check the highest value in these
                                                                                                                                                  #two group I want to draw bracket
                                                                                                                                                  #for p value in this facet
level<-level1.03 # make the bracket a little bit higher than the highest value
while (level %in% stat.test2$y.position[stat.test2$variable==stat.test2$variable[i]]) # In case the bracket overlap, make it
{level<-level1.05}                                                                                                         # higher until no overlap with previous
stat.test2$y.position[i]<-level}

#now you can plot it and add it to your plot
p+stat_pvalue_manual(stat.test2,label = "p.signif")

**Comment by kassambara** [comment]
Please consider using the latest (dev) version of `ggpubr`  which contains now the function [geom_pwc()](https://rpkgs.datanovia.com/ggpubr/reference/geom_pwc.html) with lot of possibilities compared `stat_compare_means()`. stat_compare_means() will be progressively updated to be a wrapper around `geom_pwc()`.

## Examples using `geom_pwc()`: 

``` r
suppressPackageStartupMessages(library("ggpubr"))

df <- ToothGrowth
df$dose <- as.factor(df$dose)

# Create a basic box plot
#:::::::::::::::::::::::::::::::::::::::
# Add p-values. The default method is the Wilcoxon test
bxp <- ggboxplot(df, x = "supp", y = "len") +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.10)))
bxp + geom_pwc(method = "t_test")
```

![](https://i.imgur.com/ZVd5wjq.png)

``` r

# Hide NS
bxp + geom_pwc(method = "t_test", hide.ns = TRUE)
```

![](https://i.imgur.com/fIl6xsz.png)

``` r


# Facet
#:::::::::::::::::::::::::::::::::::::::
# Change the label
# Create a ggplot facet
bxp + 
  geom_pwc(method = "t_test", label = "p.signif") +
  facet_wrap(~dose)
```

![](https://i.imgur.com/0lW1Fet.png)

``` r


# Hide NS
bxp + 
  geom_pwc(method = "t_test", label = "p.signif", hide.ns = TRUE) +
  facet_wrap(~dose)
```

![](https://i.imgur.com/lOk8JQC.png)

``` r

# Show p-values and significance
# and hide.ns
bxp + 
  geom_pwc(method = "t_test", label = "{p.format}{p.signif}",
           hide.ns = TRUE) +
  facet_wrap(~dose)
```

![](https://i.imgur.com/TsGbccy.png)

``` r


# More examples
#:::::::::::::::::::::::::::::::::::::::
ggboxplot(df, x = "dose", y = "len")  +
  geom_pwc(label = "{p.format}{p.signif}") +
  facet_wrap(~supp)
```

![](https://i.imgur.com/ikUb1bO.png)

``` r

# Hide NS
ggboxplot(df, x = "dose", y = "len")  +
  geom_pwc(label = "{p.format}{p.signif}", hide.ns = TRUE) +
  facet_wrap(~supp)
```

![](https://i.imgur.com/sjhAPfE.png)


## Read more

- [geom_pwc(): Add Pairwise Comparisons P-values to a GGPlot](https://rpkgs.datanovia.com/ggpubr/reference/geom_pwc.html)
- [Add manually p-values to ggplots using rstatix and ggpubr](https://www.datanovia.com/en/?s=rstatix&search-type=default)
