### ISSUE TITLE
Add dunn_test for stat_compare_means

### ISSUE THREAD

**Issue by Minh-AnhHuynh** [kassambara/ggpubr#487]
Hello,

Currently it is only possible to perform multiple pairwise comparison on non parametric data using wilcoxon. It would be great to add the possibility to do dunn tests. Currently we have to add them one by one instead of looping over a list of plot through `stat_compare_means`, which would be very practical. Thankfully it is possible to perform the initial Kruskal Wallis test.

Thanks,
Minh-Anh

**Comment by aphalo** [comment]
There is an R package called 'dunn.test' that provides `dunn.test()`. It could work possibly directly or if not by defining a wrapper function, together with with the statistic from package 'ggsignif'.

**Comment by kassambara** [comment]
@Minh-AnhHuynh are you looking for something like this:

``` r
library(ggpubr)
ggboxplot(PlantGrowth, x = "group", y = "weight") +
  geom_pwc(method = "dunn_test")
```

![](https://i.imgur.com/mbQVPAq.png)

Note that `ggpubr::geom_pwc()` calls the function `rstatix::dunn_test()` to perform the dunn test.  The default of the `rstatix::dunn_test()` function is to perform a two-sided Dunn test like the well known commercial softwares, such as SPSS and GraphPad. This is not the case for some other R packages (dunn.test and jamovi), where the default is to perform one-sided test. This discrepancy is documented at https://github.com/kassambara/rstatix/issues/50.

You can also add p-value computed from other packages using `stat_pvalue_manual()`. This blog post might help: https://www.datanovia.com/en/lessons/kruskal-wallis-test-in-r/#report

**Comment by Minh-AnhHuynh** [comment]
Thank you, I think this is what I'm looking for. I was doing the `dunn_test()` separately and putting the values with `stat_pvalue_manual()`.

However, this is slightly unintuitive since I was not aware of the existence of this function, and I was thinking along adding a dunn test argument inside the `stat_compare_means()` function. But next time I know the option is available through `geom_pwc()`
