### ISSUE TITLE
Put the jitter behind the boxplot using ggboxplot

### ISSUE THREAD

**Issue by SongchaoChen** [kassambara/ggpubr#489]
Dear all,

By  default, when `add="jitter"` is used in the ggboxplot, the jitter points are over the boxplot (please see the figure attached). Is it possible to put boxplot over jitter points? Many thanks for your help in advance.

With best regards,

![ggboxplot](https://user-images.githubusercontent.com/31031140/188074467-8f76cbb2-7184-4185-b314-2dae8f31b69d.jpg)

**Comment by kassambara** [comment]
too late but this can be achieved as follow:

``` r
suppressPackageStartupMessages(library("ggpubr"))

# Generate demo data
set.seed(123)
x <- rnorm(2000)

# Using ggboxplot, but here points are over the boxplot
ggboxplot(x, add ="jitter", add.params = list(alpha = 0.5))
```

![](https://i.imgur.com/ofBSUEm.png)

``` r

# Put the boxplot over stripchart or jittered points
ggstripchart(x) %>%
  ggadd("boxplot", size = 2, color = "red")
```

![](https://i.imgur.com/SJhG2w3.png)

``` r

# Change the boxplot fill to NA (transparent)
ggstripchart(x) %>%
  ggadd("boxplot",  size = 2, color = "red", fill = NA)
```

![](https://i.imgur.com/s7pQVDJ.png)

<sup>Created on 2022-11-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
