### ISSUE TITLE
desc_statby {ggpubr} sd and se with wrong explanation

### ISSUE THREAD

**Issue by trustindata** [kassambara/ggpubr#492]
When you use e.g. ggerrorplot you can choose desc_statby=sd or desc_statby= se. Where sd = standard deviation of the mean
and se= standard error of the mean. That makes no sense at all all because  the standard error of the mean is defined as standard deviation of the mean.
So the standard error of the mean or the standard deviation of the mean (sem) = sample standard deviation devided by the root of the sample size : sem= sigma/root(n)
Whereas sd is normally used as the term for the standard deviation of the sample.
In errorplots it is usual to plot the mean with the sample standard deviation (sd) or the standard error of the mean (sem).
I thing it is import to get the difference betwenn sem and sd straight concerning desc_statby because they often get mixed up by students and scientiest alike.

**Comment by kassambara** [comment]
fixed in this commit: [#c25039db0ff61ba3be0d5c7974c57a700a27896d](https://github.com/kassambara/ggpubr/commit/c25039db0ff61ba3be0d5c7974c57a700a27896d)
