### ISSUE TITLE
Backports as dependency?

### ISSUE THREAD

**Issue by thomaszwagerman** [kassambara/ggpubr#493]
Hi there,

Thank you for this package.

I get the following error after using installing ggpubr for the first time:

```r
> plot_grid <- ggpubr::ggarrange(ppd_plot, footer,
+                                  ncol = 1, nrow = 2,
+                                  heights = c(1, 0.045/(height_pixels/450)))
Error: .onLoad failed in loadNamespace() for 'broom', details:
  call: loadNamespace(x)
  error: there is no package called 'backports'
```

Does backports need to be added as a dependency?

**Comment by kassambara** [comment]
There is no direct dependency between ggpubr and backports. However ggpubr indirectly depends on the broom package, which requires backports.
