### ISSUE TITLE
Error in plot.xy(xy.coords(x, y), type = type, ...) :    invalid RGB specification 

### ISSUE THREAD

**Issue by NkcubekoBara** [kassambara/ggpubr#495]
Hi there I am experiencing the error in shown in the above screen shot when I run line 84, could anyone help me solve it?

Thanks
![invalid RGB specification](https://user-images.githubusercontent.com/104196412/192472594-432f3a7b-b8bc-437c-95a8-127d9bfa441e.PNG)

**Comment by kassambara** [comment]
closing this issue, because it doesn't seem to be related to ggpubr
