### ISSUE TITLE
Specify label.y positions in facets

### ISSUE THREAD

**Issue by miguelroboso** [kassambara/ggpubr#50]
Hello,

I am having an issue with faceted plots, and in particular I cannot place labels of `stat_compare_means` in a specific place for each faceted plot. 
No matter what I try, it always ends up being at the top.

This is a reproducible example, any idea of what I am doing wrong?

In this example I am leaving some space at the top because I would like to put some other annotations there.

```library(ggplot2)
library(ggpubr)
library(data.table)
library(magrittr)

group = c('A', 'B')
vars = c('X', 'Y', 'K', 'J')
test = data.table(vars = rep(vars, each = 10))

test[,values:=rnorm(length(vars))*rep(1:4,each = 10)]
test[,values:= values - min(values), by = vars]

test[, ymin:=min(values)*0.5, by = .(vars)]
test[, ymax:=max(values)*1.3, by = .(vars)]
test[, ylab_pos:=max(values)*1, by = .(vars)]

# ylab_vec = unique(test$ylab)

test$group = rep(group, each = 20) %>% sample

ggplot(test, aes(x=group, y = values, fill=group)) + 
  geom_boxplot() +
  geom_blank(aes(y=ymax*3))+
  facet_wrap(~vars, scales = 'free') + 
  stat_compare_means(comparisons=list(c("A","B")), aes(label.y=ylab_pos))```

**Comment by kassambara** [comment]
Hi,

specifying `label.y` in aes() is not supported.

You can do this:

```r
ggplot(test, aes(x=group, y = values, fill=group)) + 
  geom_boxplot() +
  geom_blank(aes(y=ymax*3))+
  facet_wrap(~vars, scales = 'free') + 
  stat_compare_means(comparisons=list(c("A","B")), label.y = 20)
```

When scales = 'free', it's even better to use `label.y.npc`:

```r
ggplot(test, aes(x=group, y = values, fill=group)) + 
  geom_boxplot() +
  geom_blank(aes(y=ymax*3))+
  facet_wrap(~vars, scales = 'free') + 
  stat_compare_means(label.y.npc = 0.4)
````

![rplot](https://user-images.githubusercontent.com/3313355/32930720-9b826c92-cb60-11e7-85ca-1be16bb866e7.png)

Let's keep this issue open, I need to improve annotation of the different facet panels

**Comment by miguelroboso** [comment]
Thanks @kassambara .
Surprisingly enough,  `label.y.npc` does not work when I specify the comparisons.

This code

```ggplot(test, aes(x=group, y = values, fill=group)) + 
  geom_boxplot() +
  geom_blank(aes(y=ymax*3))+
  facet_wrap(~vars, scales = 'free') + 
  stat_compare_means(comparisons=list(c("A","B")),label.y.npc = 0.4)
```

actually still returns the labels at the top:

![plot_zoom_png](https://user-images.githubusercontent.com/17713880/32962979-4e35c916-cb83-11e7-9d44-03f6d1bdf984.png)

**Comment by kassambara** [comment]
now, you can compute p-value and add it manually at any position.

In the following example, we'll use the ToothGrowth data.  We'll compare `supp` levels after grouping the data by `dose`.

```r
# Statistical test
library("rstatix")  # https://github.com/kassambara/rstatix
stat.test <-  ToothGrowth %>%
  group_by(dose) %>%
  t_test(len ~ supp) %>%
  adjust_pvalue() %>%
  add_significance("p.adj")
stat.test
```

<pre>
# A tibble: 3 x 9
   dose   .y. group1 group2  statistic      p method  p.adj p.adj.signif
  <dbl> <chr>  <chr>  <chr>      <dbl>  <dbl>  <chr>  <dbl>        <chr>
1   0.5   len     OJ     VC  3.1697328 0.0064 T-test 0.0128            *
2   1.0   len     OJ     VC  4.0327696 0.0010 T-test 0.0030           **
3   2.0   len     OJ     VC -0.0461361 0.9600 T-test 0.9600           ns
</pre>


```r
# Visualization
library(ggpubr)
ggboxplot(
  ToothGrowth, x = "supp", y = "len",
  color = "supp", palette = "jco",
  ylim = c(0, 40)
) +
  facet_wrap(~dose) +
  stat_pvalue_manual(stat.test, label = "p.adj", y.position = 35)
```

![rplot](https://user-images.githubusercontent.com/3313355/43940309-57b8c85e-9c6f-11e8-9f17-b781e28f9492.png)

Note that, the option `y.position` can be a numeric vector with length = the nombre of p-values to add. It can be also a column name in the stat.test data frame.
