### ISSUE TITLE
LAB.FONT issues

### ISSUE THREAD

**Issue by Cami1992** [kassambara/ggpubr#502]
country <- c( "salvador", "honduras", "guatemala")
  
data_2022ago <- data.frame(
  number = c(10399, 66763,68663), 
  country = factor(country, levels = country),
  y = seq(length(country)) * 0.9
)%>%
  dplyr::mutate(total = sum(number))%>%
  mutate(prop = number/total)%>%
  dplyr::mutate(percent = paste0(round(prop*100), "%"))%>%
  mutate(label = paste(percent, "\n","(", scales::comma (number), ")", sep = ""))
CHART

ggpubr::ggdonutchart(data = data_2022ago, x = "number",  color = "white",
                     fill = "country",lab.pos = "out", 
                     orientation = "horizontal",
                     lab.font =  c(12, "bold", "blue"))
PROBLEM: It does not give me the right font in terms of colour  and size

**Comment by kassambara** [comment]
Now, `ggpie()` and `ggdonutchart()` now fully reacts to the option `lab.font`

``` r
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(dplyr))

country <- c( "salvador", "honduras", "guatemala")

data_2022ago <- data.frame(
  number = c(10399, 66763,68663),
  country = factor(country, levels = country),
  y = seq(length(country)) * 0.9
)%>%
  dplyr::mutate(total = sum(number))%>%
  mutate(prop = number/total)%>%
  dplyr::mutate(percent = paste0(round(prop*100), "%"))%>%
  mutate(label = paste(percent, "\n","(", scales::comma (number), ")", sep = ""))

ggpubr::ggdonutchart(data = data_2022ago, x = "number", color = "white",
                     fill = "country",lab.pos = "out",
                     orientation = "horizontal",
                     lab.font = c(4, "bold", "blue"))
#> Coordinate system already present. Adding new coordinate system, which will
#> replace the existing one.
```

![](https://i.imgur.com/YeDSLuA.png)
