### ISSUE TITLE
stat_compare_means - all comparisons dissappear when one comparison has missings

### ISSUE THREAD

**Issue by MPietzke** [kassambara/ggpubr#503]
When using stat_compare_means to make multiple comparisons it works fine, until one of the comparisons cannot be performed (e.g. due to too many missings). In this case also all the possible comparisons dissappear! 
Please see this example:

```
library(tidyverse)
library(ggpubr)

dataset = tibble(
  "Sample" = rep(c("Sample1", "Sample2"), each = 15),
  "Cond"   = rep(c("A", "B", "C",
                   "A", "B", "C"), each = 5),
  "Rep"    = rep(1:5, 6),
  "Value"  = c(runif(5, 10, 12),  #A1
               runif(5, 11, 14),  #B1
               runif(5, 10, 13),  #C1
               runif(5, 10, 12),  #A2
               runif(5, 11, 14),  #B2
               c(runif(2, 10, 13), NA, NA, NA) #C2
               ))

# With min 2 datapoints we see all the comparisons we want to have!
ggplot(dataset, 
       aes(x = Cond, y = Value, 
           colour = as.factor(Cond),
           fill = as.factor(Cond) )) + 
  geom_jitter(size = 5, width = 0.2, alpha = 0.3, stroke = 1.5,
              shape = 21) + 
  stat_summary(fun.min = mean, fun.max = mean, size = 1.5,                
               geom='errorbar') + 
  facet_wrap( ~ Sample) +
  theme_bw()  + scale_y_continuous(limits = c(0, 16)) +
  stat_compare_means(comparisons = list(c("A", "B"),
                                        c("B", "C") )) + 
  theme(legend.position = "none")
```
![image](https://user-images.githubusercontent.com/70321724/197729365-e12e8119-76f8-48f8-b8ad-9063570ef8a5.png)
```

# with only NAs in one of the conditions (C), the other comparisons (A-B) dissappers as well!
ggplot(data = filter(dataset, Rep >= 3), 
       aes(x = Cond, y = Value, 
           colour = as.factor(Cond),
           fill = as.factor(Cond) )) + 
  geom_jitter(size = 5, width = 0.2, alpha = 0.3, stroke = 1.5,
              shape = 21) + 
  stat_summary(fun.min = mean, fun.max = mean, size = 1,                
               geom='errorbar') + 
  facet_wrap( ~ Sample) +
  theme_bw()  + scale_y_continuous(limits = c(0, 16)) +
  stat_compare_means(comparisons = list(c("A", "B"),
                                        c("B", "C") )) + 
  theme(legend.position = "none")
```

![image](https://user-images.githubusercontent.com/70321724/197729463-ca0bf4e1-39ad-4893-838f-d24754fd9b14.png)

Here also the comparison A-B get lost, even though this can still be calculated. 
I could adapt the comparisons made, but in general I want to have a consistent picture over multiple (usually more than just 2) Samples . 

However, it throws a warning, so it knows something fails:
1: Removed 3 rows containing non-finite values (stat_summary). 
2: Removed 3 rows containing non-finite values (stat_signif). 
3: Computation failed in `stat_signif()`:
not enough 'y' observations.

Would it be possible to: 
- check (e.g. after the warning) which of the comparisons cannot be made, 
- remove the impossible one, 
- still show the working ones and maybe either just drop the failed comparison 
- or (better) add something as "n.d.", therefor maintaining the original structure?

This would be great!

**Comment by schelhorn** [comment]
I have the same issue - a fix would be appreciated!

**Comment by kassambara** [comment]
Please, consider using `geom_pwc()` . See example below: 


``` r
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(tidyverse))


dataset = tibble::tibble(
  "Sample" = rep(c("Sample1", "Sample2"), each = 15),
  "Cond"   = rep(c("A", "B", "C",
                   "A", "B", "C"), each = 5),
  "Rep"    = rep(1:5, 6),
  "Value"  = c(runif(5, 10, 12),  #A1
               runif(5, 11, 14),  #B1
               runif(5, 10, 13),  #C1
               runif(5, 10, 12),  #A2
               runif(5, 11, 14),  #B2
               c(runif(2, 10, 13), NA, NA, NA) #C2
  ))


ggplot(data = filter(dataset, Rep >= 3), 
       aes(x = Cond, y = Value, 
           colour = as.factor(Cond),
           fill = as.factor(Cond) )) + 
  geom_jitter(size = 5, width = 0.2, alpha = 0.3, stroke = 1.5,
              shape = 21) + 
  stat_summary(fun.min = mean, fun.max = mean, size = 1,                
               geom='errorbar') + 
  facet_wrap( ~ Sample) +
  theme_bw()  + scale_y_continuous(limits = c(0, 16)) +
  geom_pwc(step.increase = 0.2)+
  theme(legend.position = "none")
```

![](https://i.imgur.com/e8qzgSN.png)

**Comment by MPietzke** [comment]
geom_pwc() is clearly an interesting workaround. 
However, it seems it's not possible to define the list of planned comparisons. This isn't a big deal for just 3 conditions, but with a higher number of conditions also the number of pairwise comparisons increase dramatically - not all the comparisons are needed or scientifically relevant. 

![grafik](https://user-images.githubusercontent.com/70321724/208692260-7b9385f4-16da-4681-873e-59ba4e93bbda.png)

Obviously geom_pwc() has the check implemented somewhere. 
If I am allowed to make a wish it would be to add the check for validity from geom_pwc() to stat_compare_means() or to add the list of allowed comparisons to geom_pwc().

**Comment by kassambara** [comment]
Comparisons of interest can be specified as described in #529
