### ISSUE TITLE
Deprecated arguments of stat_summary()

### ISSUE THREAD

**Issue by fgillet3** [kassambara/ggpubr#510]
The `fun.y` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
Please use the `fun` argument instead.

The `fun.ymin` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
Please use the `fun.min` argument instead.

The `fun.ymax` argument of `stat_summary()` is deprecated as of ggplot2 3.3.0.
Please use the `fun.max` argument instead.

**Comment by kassambara** [comment]
Would you please provide a [reproducible example](https://reprex.tidyverse.org/) leading to these warnings? so that I can quickly fix it

**Comment by fgillet3** [comment]
These warnings appeared in the version 0.4.0 of ggpubr installed from CRAN. I installed the last version 0.5.0 from GitHub and the warnings are no longer displayed. I suppose the issue was resolved? Thank you for this great package!

**Comment by kassambara** [comment]
Thank you for your feedback! So let's close this issue for now
