### ISSUE TITLE
Error trying to use stat_conf_ellipse()

### ISSUE THREAD

**Issue by jehaab** [kassambara/ggpubr#514]
Hi,

I've been using ggpubr for a while, and a week ago I started to get the following error message when I try to use stat_conf_ellipse the same way I have been for years and cannot understand why.

New names:
• `x` -> `x...1`
• `y` -> `y...2`
• `x` -> `x...4`
• `y` -> `y...5`
New names:
• `x` -> `x...1`
• `y` -> `y...2`
• `x` -> `x...4`
• `y` -> `y...5`
New names:
• `x` -> `x...1`
• `y` -> `y...2`
• `x` -> `x...4`
• `y` -> `y...5`
Error in `stat_conf_ellipse()`:
! Problem while setting up geom.
ℹ Error occurred in the 2nd layer.
Caused by error in `compute_geom_1()`:
! `geom_path()` requires the following missing aesthetics: x and y
Run `rlang::last_error()` to see where the error occurred.
Warning message:
The following aesthetics were dropped during statistical transformation: x, y
ℹ This can happen when ggplot fails to infer the correct grouping structure in the data.
ℹ Did you forget to specify a `group` aesthetic or to convert a numerical variable into a factor?

I usually just use it like so:

`
ggplot(mds.data.RF, aes(x=X, y=Y, color=Lifestyle) +
  theme_gray() +
  geom_point() +
  theme(text = element_text(size=10))+
  labs(colour = "")+
  xlab(paste("PCoA1 - ", mds.var.per.RF[1], "%", sep="")) +
  ylab(paste("PCoA2 - ", mds.var.per.RF[2], "%", sep="")) +
  ggtitle("") +
  scale_color_manual(breaks=c("group1","group2",
                              "group3"), values=c( "#E69F00","#CC79A7", "#56B4E9" )) +
 
 stat_conf_ellipse(
  geom = "path",
    position = "identity",
    show.legend = NA,
    inherit.aes = TRUE,
   level = 0.95,
    npoint = 100,
    bary = TRUE
  )`

But I also tried: 
` stat_conf_ellipse(aes( color=Lifestyle))`

I really don't understand this error, can someone help.

Thank you

**Comment by kassambara** [comment]
This issue is due to the recent changes in ggplot2 v3.4.0. 

Please consider installing the latest dev version of ggpubr using `devtools::install_github("kassambara/ggpubr")`, where the issue is already fixed. Please let me know if it works on your computer after installation.

**Comment by jehaab** [comment]
Thank you, it works ! Have a good day
