### ISSUE TITLE
gghistogram error message

### ISSUE THREAD

**Issue by brontosorus32** [kassambara/ggpubr#515]
In the newest ggplot2 update (3.4.0), the `..count..` notation was deprecated in favor of `after_stat(count)`. 
When you're able, could you update ggpubr to match? Thanks!

**Comment by kassambara** [comment]
This is issue is normally already fixed in the latest dev version, which was submitted to CRAN this week. 

Installing the latest dev version, using devtools:install_github(), should remove the warning

**Comment by brontosorus32** [comment]
Awesome, thank you so much!
