### ISSUE TITLE
Issue with stat_regline_equation when specifying formula

### ISSUE THREAD

**Issue by eemilybrown1** [kassambara/ggpubr#518]
Hello!
I am having an issue with stat_regline_equation where if I specify the formula to 
stat_regline_equation(formula=y~(0+x))
the x disappears in the regression equation. See the attached figure. 
![Rplot](https://user-images.githubusercontent.com/113129562/204070918-8ddb8522-95fc-4364-a81b-b8144d9e8567.png)
Thanks for your help!

**Comment by aphalo** [comment]
Try using `stat_poly_eq()` from 'ggpmisc'. It is very similar, but this bug was fixed after the code was copied long ago from `stat_poly_eq()` in my package 'ggpmisc' into 'ggpubr' and renamed stat_regline_equation(). I have also improved `stat_poly_eq()` in other respects.

**Comment by eemilybrown1** [comment]
Thank you! stat_poly_eq() works.
