### ISSUE TITLE
 Cannot convert object of class ggscatterhistlist into a grob.

### ISSUE THREAD

**Issue by B-1991-ing** [kassambara/ggpubr#527]
Hi Kassambara,

I am using "**ggarrange**" to combine my **ggscatterhist(p)**  and **ggbarplot(p1)** into one page as below. 
<img width="840" alt="image" src="https://user-images.githubusercontent.com/54441633/206024118-f24c64f7-ee2f-4a7e-a4c2-0c8d0f46f75c.png">

But error --- **Warning message: In as_grob.default(plot) : Cannot convert object of class ggscatterhistlist into a grob.** happened. 

What should I do to avoid the error?

**Code**
[Rcode.txt](https://github.com/kassambara/ggpubr/files/10170381/Rcode.txt)

**Tsvfile**
[tsvfile.zip](https://github.com/kassambara/ggpubr/files/10170424/tsvfile.zip)

Best,

Bing

**Comment by kassambara** [comment]
`ggscatterhist()` is already an arranged plot with a specific printing method. To arrange it again with orther plots, one can follow these steps:

1. create ggscatterhist using the option `print = FALSE`  (see example below)
2. print ggscatter hist
3. arrange the printed plot with other plots


Please see a reproducible example below: 

``` r
suppressPackageStartupMessages(library(ggpubr))

# Basic scatter plot with marginal density plot
scatter_hist <- ggscatterhist(iris, x = "Sepal.Length", y = "Sepal.Width",
              color = "#00AFBB", margin.params = list(fill = "lightgray"),
              print = FALSE)

# Barplot
# Create some data
df2 <- data.frame(supp=rep(c("VC", "OJ"), each=3),
                  dose=rep(c("D0.5", "D1", "D2"),2),
                  len=c(6.8, 15, 33, 4.2, 10, 29.5))
p1 <- ggbarplot(df2, "dose", "len",
          fill = "supp", color = "supp", palette = "Paired",
          label = TRUE, lab.col = "white", lab.pos = "in")

# Print the scatter hist and then arrange with other plots
printed_scatter_hist <- print(scatter_hist)
ggarrange(
  printed_scatter_hist, p1, p1, 
  nrow = 2,ncol = 2, labels = c("A", "B", "C")
  )
```

![](https://i.imgur.com/e5tOD3e.png)

**Comment by kassambara** [comment]
Yes, it is possible, here is an example:

``` r
suppressPackageStartupMessages(library(ggpubr))

# Basic scatter plot with marginal density plot
scatter_hist <- ggscatterhist(iris, x = "Sepal.Length", y = "Sepal.Width",
              color = "#00AFBB",
              margin.params = list(fill = "lightgray"),
              print = FALSE)

# Barplot
# Create some data
df2 <- data.frame(supp=rep(c("VC", "OJ"), each=3),
                  dose=rep(c("D0.5", "D1", "D2"),2),
                  len=c(6.8, 15, 33, 4.2, 10, 29.5))
p1 <- ggbarplot(df2, "dose", "len",
          fill = "supp", color = "supp", palette = "Paired",
          label = TRUE, lab.col = "white", lab.pos = "in")



# Arrange B and C first
b_and_c <- ggarrange(p1, p1, nrow = 2,ncol = 1, labels = c( "B", "C"))

# Then Arrange A + b_and_c
# Print the scatter hist and then arrange with other plots
a <- print(scatter_hist)

ggarrange(a, b_and_c, nrow = 1, ncol = 2, labels = c("A"))
```

![](https://i.imgur.com/iD73bfm.png)

<sup>Created on 2022-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by B-1991-ing** [comment]
Ok, get it. Thank you very much.
