### ISSUE TITLE
Ylim change significativity of data

### ISSUE THREAD

**Issue by hedjour** [kassambara/ggpubr#528]
I try to make a more lisible graph by changing the ylim and I get this :

![image](https://user-images.githubusercontent.com/11226410/206699331-903f90ab-d8d1-463d-ab7f-837a52ec642e.png)
![image](https://user-images.githubusercontent.com/11226410/206699350-e8a5e01a-8f46-4eed-a89f-f3108e219bcb.png)

The unique difference between the two graph :
  ylim(0,10) + (First graph)
  ylim(0,3) + (Second graph)

Sorry I can't publish a ECM

**Comment by kassambara** [comment]
Did you see #36 and #505? 

Please consider using `coord_cartesian(ylim = c(0, 3))` instead of `ylim()`
