### ISSUE TITLE
Error in grDevices::col2rgb(colour, TRUE) : invalid RGB specification

### ISSUE THREAD

**Issue by tonydurst** [kassambara/ggpubr#55]
I'm working through the example in Chapter six on Kmeans clustering. Here is the code I'm trying to run to create the graph:

fviz_cluster(km.res, data = df, palette = c("# 2E9FDF", "# 00AFBB", "# E7B800", "# FC4E07"), ellipse.type = "euclid", 
              
              # Concentration ellipse 
              
              star.plot = TRUE, 
              
              # Add segments from centroids to items 
              
              repel = TRUE, 
              
              # Avoid label overplotting (slow) 
              
              ggtheme = theme_minimal())

When I try to execute, I get the error below:

Error in grDevices::col2rgb(colour, TRUE) : invalid RGB specification

**Comment by kassambara** [comment]
hi,

You are adding extra space between "#" and color names. This doesn't work.

Use this:

```r
palette = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07")
```

Instead of this:

```r
palette = c("# 2E9FDF", "# 00AFBB", "# E7B800", "# FC4E07")
```

**Comment by tonydurst** [comment]
Ah! Should have noticed that. Thank you for the quick response. I am enjoying your work!

**Comment by NkcubekoBara** [comment]
![invalid RGB specification](https://user-images.githubusercontent.com/104196412/192471763-f80d8447-a003-4e84-bf49-0f85fa19c304.PNG)
Hi there, could you please help solve that error shown in the image above. I get it when I run line 85.
Thanks
