### ISSUE TITLE
Need help generating comparisons as shown in plot!

### ISSUE THREAD

**Issue by jaydoc** [kassambara/ggpubr#551]
I need to generate comparisons in a grouped plot like this. 

![Picture4](https://user-images.githubusercontent.com/7351352/219582778-daf0049d-ce91-4734-a597-321266ea10a5.png)

I have tried using ggpubr function such as stat_pvalue_manual as well as newer function such as geom_pwc. With both I am able to generate either the intra-group comparisons or the inter subgroup comparisons, but not both in the same plot. 

Is there any way I can do this using ggpubr functions? Any help would be greatly appreciated as I have a script that relies on ggpubr functions that automates a lot of what I need to plot and this would greatly simplify my workflow!

Thanks.

**Comment by kassambara** [comment]
Are you looking for something like below?

``` r
suppressPackageStartupMessages(library("ggpubr"))

# Data preparation
# Transform `dose` into factor variable
df <- ToothGrowth %>%
  dplyr::filter(dose %in% c("0.5", "2"))
df$dose <- as.factor(df$dose)


# Create a box plot
# Add 10% spaces between the p-value labels and the plot border
bxp <- ggboxplot(
  df, x = "dose", y = "len", 
  color = "supp", palette = c("#00AFBB", "#E7B800")
) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.10)))


# Add intra-group comparison p-values onto the box plots
bxp2 <- bxp + geom_pwc(
  aes(group = supp), tip.length = 0,
  method = "t_test", label = "p.format"
)
bxp2 
```

![](https://i.imgur.com/gTETmZQ.png)

``` r


# Add inter-group comparisons p-values
# Group by legend var (`supp`) and perform test between x-groups
# dodge = 0.8 default
bxp2 + geom_pwc(
  aes(group = supp, color = supp), 
  method = "t_test", label = "p.format",
  tip.length = 0, group.by = "legend.var",
  bracket.nudge.y = 0.2
)
```

![](https://i.imgur.com/tTsx7JR.png)

**Comment by jaydoc** [comment]
Exactly what I was looking for. Thank you so much.
