### ISSUE TITLE
Modify spacing between panels in ggpubr?

### ISSUE THREAD

**Issue by sydneyg** [kassambara/ggpubr#58]
Thank you so much for your excellent package! I am wondering, is there a way to modify spacing between plots when using ggarrange? I would like to remove the space between the rows in these panels that I made with ggarrange(p1,p2,p3,p4, ncol = 2, nrow = 2, common.legend = TRUE, legend="bottom" ). Is there a way to remove the space between the top 2 panels and the bottom 2 panels?

Thanks!

[Meanrichnessbysite_3timepoints_fungiandbac_zotuvotu.pdf](https://github.com/kassambara/ggpubr/files/1557198/Meanrichnessbysite_3timepoints_fungiandbac_zotuvotu.pdf)

**Comment by kassambara** [comment]
Hi,

The following R code seems to work:

```r
library(ggpubr)

data("ToothGrowth")
df <- ToothGrowth
df$dose <- as.factor(df$dose)

# Create some plots
# ::::::::::::::::::::::::::::::::::::::::::::::::::
# Box plot
bxp <- ggplot(df, aes(dose, len))+
  geom_boxplot(aes(color = dose))+
  theme_bw()

# Dot plot
dp <- ggdotplot(df, x = "dose", y = "len",
                color = "dose", palette = "jco",
                ggtheme = theme_bw())

# Cleaning the box plot
bxp <- bxp + theme(
  axis.title.x = element_blank(),
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank()
)

# Arrange
# ::::::::::::::::::::::::::::::::::::::::::::::::::
ggarrange(bxp, dp, nrow = 2,
          common.legend = TRUE, legend="bottom")
```

![rplot](https://user-images.githubusercontent.com/3313355/33964984-a0c935be-e05a-11e7-8e11-2238356a160f.png)


You might want to reduce the plot margins before combining them:

```r
ggplot(...) + theme(plot.margin = unit(c(3,3,3,3), "lines"))
```

**Comment by jschito** [comment]
The option proposed by @kassambara  works well however, pay attention to set the margins 
`ggplot(...) + theme(plot.margin = unit(c(0,0.1,3,0), "lines"))` properly so that the label is aligned with the upper edge of the chart. Thus, set the margin on the top to zero (first argument of c(...)

Another option would be to add an empty ggparagraph( ) between the plots: 
`ggarrange(p1,
ggparagraph(text="   ", face = "italic", size = 16, color = "black"),
          p2, 
          ggparagraph(text="   ", face = "italic", size = 16, color = "black"),
          p3, 
          ncol = 1, 
          nrow = 5,
          labels=c("A", "", "B", "", "C"),
          heights=c(1,0.15,1,0.15,1),
          widths=c(1, 1, 1, 1, 1),
          common.legend = TRUE, 
          legend="bottom"
)` 
while p1, p2, and p3 represent plots.

**Comment by BrittanyHBrown** [comment]
Hi everyone - I've been following along here trying all the different options to remove white space between plots but no option seems to work for me.

I have 2 x 2 plot panel I am trying to set up. 
The top right & bottom right plots do not have y-axis tick labels as they are the same as the top left & bottom left labels, so I wanted to reduce the amount of unnecessary text in the figure. 

 I have tried;
- changing the margins on the plots without the y-axis (plot.margin = unit(c(3,3,3,-5), "mm")) (PAE_est and PE_est)
- adding in a NULL plot in the list, a ggparagraph (as per jschito above) or adding in ggplot + theme_void() as another solution suggested & then changing the widths 

Code for plot as is;
Fig1 <- ggarrange(PAE_pred + rremove('ylab'),
                  PAE_est + rremove('ylab'), <- I want to remove the space between this plot and PAE_pred
                  PE_pred + rremove ('ylab'),
                  PE_est + rremove('ylab'), <- and here and the one before it
                  ncol = 2, nrow = 2,
                  widths = c(1, 1.25, 1,1.25),
                  labels = c("(a)", "(b)","(c)","(d)"),
                  align = "hv",
                 legend = "none")

Thanks in advance! Please let me know if additional information is needed

**Comment by liamfitzstevens** [comment]
Hi @BrittanyHBrown , I'm having the same problem (as have, it seems, many others). Did you find a solution? ChatGPT is also of no help here.
