### ISSUE TITLE
Does not plot adjusted p-values

### ISSUE THREAD

**Issue by mathykathy26** [kassambara/ggpubr#59]
When using stat_compare_means() for multiple comparisons, the plot will not reflect the adjusted p-values. I imagine that any asterisks for significance are also based on the original p-value, not the adjusted. How can I specify which p-value I'd like to use to denote significance?

```r
library(ggpubr)

data("ToothGrowth")
head(ToothGrowth)

my_comparisons <- list( c("0.5", "1"), c("1", "2"), c("0.5", "2") )
ggboxplot(ToothGrowth, x = "dose", y = "len",
          color = "dose", palette = "npg")+
  stat_compare_means(comparisons = my_comparisons, label.y = c(29, 35, 40))+
  stat_compare_means(label.y = 45)     # Add global Anova p-value

# The plot only prints what p.format says, which does not reflect p.adj
compare_means(len~dose,comparisons = my_comparisons,p.adjust.method = "bonferroni",data = ToothGrowth)
```

**Comment by grst** [comment]
same issue here!
You can use
```r
stat_compare_means(aes(label=..p.adj..))
```
to display the adjusted p-value. 

However I could not figure out how to use that value for the asterisk-representation.

**Comment by bandrasmedik** [comment]
Hi there, 
I'm facing the same issue, and to the stat_compare_means(aes(label="..p.adj..")) I got an error message:

"Error in .update_mapping(mapping, label): Allowed values for label are: p.signif, ..p.signif.., p.format, ..p.format.., p, ..p.."

Is there a solution to that?

**Comment by atakanekiz** [comment]
Has there been a development in this issue? Any insights on how we can plot adjusted p values for plots involving multiple comparisons?

Thanks!

**Comment by kassambara** [comment]
issue fixed at https://github.com/kassambara/ggpubr/issues/65#issuecomment-407211245

**Comment by roni-fultheim** [comment]
I am currently using this command: 
stat_compare_means(comparisons = comparisons_todo , method = "wilcox.test", p.adjust.methods = "fdr")
but to no avail.
Please help

**Comment by Cecilia-Wang** [comment]
I am having the same issue.
Due to large number of groups, use asterisks for significance based on p.adj is the only option. If I use the adjusted p-value, it will be just a mess on the figure. I thought about change the font size of p-value to avoid overlapping but would be too small to read.
Just wondering if there is any update on this?
