### ISSUE TITLE
doubling of outlier points in boxplots with jitter

### ISSUE THREAD

**Issue by jgoldmann** [kassambara/ggpubr#6]
Hi, 

When plotting boxplots with outlier points, these outliers are plotted twice when the `add="jitter"` option is set:

```r
someData <- 
  data.frame(values=c(1:10, c(1:9, 25)), 
             set=c(rep("no outliers",10), rep("outliers", 10)))

ggboxplot(data=someData,
          x="set",
          y="values",
          add="jitter")
```
The outlying point (with the value 25) is present twice in the picture:
![afbeelding](https://user-images.githubusercontent.com/8589127/27032332-ac858f28-4f74-11e7-9df6-20fd6ad69761.png)

**Comment by jgoldmann** [comment]
A workaround is to give the additional option `outlier.shape=NA`, which suppresses the standard plotting of outlier points by `geom_boxplot()`.

**Comment by kassambara** [comment]
Hi,

The `ggboxplot()` function accepts further arguments to be passed to the `geom_boxplot()` function. 

For example,  if you want to remove outliers, type this:

```r
ggboxplot(data=someData,
          x="set",
          y="values",
          add="jitter", 
         outlier.shape = NA)
```

Kindly confirm that it works, so that we can close this issue.

**Comment by jgoldmann** [comment]
Works :)
