### ISSUE TITLE
Edit the size of the pdf sheet using ggexport

### ISSUE THREAD

**Issue by JauntyJJS** [kassambara/ggpubr#63]
Hi, 

I was trying to plot 2 by 2 density plot showing the difference in log transforming the data as well as to compare different sets.

```{r}
plotlist <- list()
i=1
for (set_id in Celegan_data_set_ids) {
    Celegan_data_replicate <- Celegan_data[which(Celegan_data$Set == set_id),]
    peak_transform_list <- c("Peak_Intensity","Log10_Peak_Intensity")
    for (peak_transform in peak_transform_list) {
        p <- ggdensity(Celegan_data_replicate, x = peak_transform, add = "mean", rug = TRUE, title = paste0("Set ", set_id),
             color = "Time_Group", fill = NA, palette = c("#00AFBB", "#E7B800", "#FC4E07", "#7570B3"))
        plotlist[[i]] <- p
        i <- i+1
    }
}
multi.page <- ggarrange(plotlist = plotlist, nrow = 2, ncol = 2)
ggexport(multi.page, filename = 'Celegan_Density_Plot.pdf', width = 2000, height = 480, verbose = FALSE)
dev.off()

```
I thought changing the width default value from 480 to 2000 may help but I still could not change the paper size in the pdf file and the legend 121 which stands for the purple line got cut off

![image](https://user-images.githubusercontent.com/9066508/35202160-e5668efe-ff5b-11e7-9ef6-16010ccdaa32.png)

Is there a way to increase the width of the pdf file ?

Thank you.

Regards,
Jeremy

**Comment by kassambara** [comment]
fixed now, thanks
