### ISSUE TITLE
Reduce/Fixed the number of decimal places to display in a ggtextable

### ISSUE THREAD

**Issue by JauntyJJS** [kassambara/ggpubr#64]
Hi,

I apologize in advance if I were to ask a very simple question

I was trying to output a ggtexttable to a pdf file
```{r}
p <- ggtexttable(as.data.frame(summary(res.aov)[[1]]), theme = ttheme("mOrange"))
ggexport(p, filename = "data_output.pdf", width = 480, height = 480, verbose = FALSE)
```
Unfortunately, I got this instead

![image](https://user-images.githubusercontent.com/9066508/35204777-47bfdc86-ff6b-11e7-8932-7c7e3f828c6f.png)

Is there an option in the ggtexttable function to control the amount of decimal places required ?

Thank you.

Regards,
Jeremy

**Comment by JauntyJJS** [comment]
So far this works for me

```{r}
ggtexttable(format(res.aov.df, digits = 4 ,scientific = FALSE), theme = ttheme("mOrange"))
ggexport(p, filename = "data_output.pdf", width = 480, height = 480, verbose = FALSE)
```

**Comment by JauntyJJS** [comment]
May I ask if it is possible to add a title to this table using ggtexttable ?

**Comment by kassambara** [comment]
Hi,

Try the following R code:

```r

library(ggpubr)
p <- ggtexttable(head(iris))
p + theme_void() + labs(
  title = "A table Created Using ggpubr",
  subtitle = "It contains a sample of iris data set",
  caption = "The famous iris data set"
  )
```

![rplot](https://user-images.githubusercontent.com/3313355/35233499-9ef2ff8c-ff9e-11e7-92c0-3634d0489597.png)
