### ISSUE TITLE
Hard-coded adj Pvalue in ggmaplot for labeling top genes!!

### ISSUE THREAD

**Issue by ash-lji** [kassambara/ggpubr#66]
I was trying to add a few gene labels to the MA plot with an adjusted p value < 0.1 but was unable to do so. I figured from the R script that you guys have for ggmaplot - https://github.com/kassambara/ggpubr/blob/d6e249e055d8be3ee73229a19ba4dec07bbd18c2/R/ggmaplot.R#L119
that the adjusted p value is hard coded to a cut off of 0.05. Is that something that may be made more flexible?

**Comment by kassambara** [comment]
Now you can specify the option `fdr` when using ggmaplot(), for example fdr = 0.1
