### ISSUE TITLE
ggarrange features

### ISSUE THREAD

**Issue by Gian77** [kassambara/ggpubr#67]
Hello folks,
I love the ggarrange function. I was, therefore, looking for the possibility to add common x and y labels when you are plotting multiple plots together (e.g. 4) to generate a single Figure. It would be useful. Are you planning to integrate something like that soon?
Thank you,
G.

**Comment by oofd** [comment]
Hi Gian77,  I've figured out how to do it with ggpubr.

`
ylab <-  as_ggplot(text_grob("ylab_text", rot=90))
a <- ggarrange(plotlist = plots[1:6], ncol = 1, nrow = 6, align = 'v')
ggarrange(ylab,a,ncol = 2, widths = c(1,20))
`

**Comment by kassambara** [comment]
I would go as follow:

1. Create multiple plots without x/y axis labels
2. Arrange them
3. Annotate as described at: [ggubr page](http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/81-ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page/#annotate-the-arranged-figure)
