### ISSUE TITLE
add another 'color' condition with ggboxplot

### ISSUE THREAD

**Issue by qalid7** [kassambara/ggpubr#68]
Suppose I've one of these high-end boxplots:

ggboxplot(ToothGrowth, x = "dose", y = "len",
          color = "dose", palette = "jco")+ 
  stat_compare_means(comparisons = my_comparisons, label.y = c(29, 35, 40))+
  stat_compare_means(label.y = 45)
https://i2.wp.com/www.sthda.com/sthda/RDoc/figure/ggpubr/add-p-values-to-ggplots-pairwise-comparisons-bar-location-1.png?zoom=2&w=450

Now if I do 'add = "jitter"', I want to color some of the points based on a new condition that is not related to the actual boxes e.g. certain p-value... 

If I play with fill/color/palette, it will just split each group's box into two based on this new condition.. 

Any idea how to color the jitter based on a new column without touching the groups at all.... 

Thanks!

**Comment by kassambara** [comment]
Specify the `add.params`  argument to customize the jitter points:


```r
ggboxplot(ToothGrowth, x = "dose", y = "len",
          color = "lightgray", palette = "jco",
          add = "jitter",
          add.params = list(color = "supp")
          )
```

![rplot29](https://user-images.githubusercontent.com/3313355/42075713-808cca82-7b72-11e8-9acc-6eba6f80c71b.png)

**Comment by yliueagle** [comment]
A question, in the above figure, why in the dose category of 0.5 there is still a point with color lightgray there? How to avoid this?

**Comment by snashraf** [comment]
yes any idea about this ?

**Comment by kassambara** [comment]
This is a boxplot outlier. To remove it, Please consider specifying the argument:  outlier.shape = NA

**Comment by snashraf** [comment]
Thanks !!
