### ISSUE TITLE
Is possible to add facet/ subgraphs?

### ISSUE THREAD

**Issue by zhouyisu** [kassambara/ggpubr#7]
Hi, I really love the aesthetics of ggpubr. Great work. I have been playing around with some of my own data. Wondering if it's possible to do subgraphs looping over factor variable just as using `facet_grid` in ggplot2?

**Comment by kassambara** [comment]
Yes, faceting is supported.

Try this:

```r
library("ggpubr")
# Facet by "supp"
ggboxplot(ToothGrowth, x = "dose", y = "len",
          color = "supp", facet.by = "supp")
```

![rplot](https://user-images.githubusercontent.com/3313355/27458670-88692b52-57aa-11e7-979b-21a400b30331.png)

```r
# Facet by supp and dose
ggboxplot(ToothGrowth, x = "dose", y = "len",
          color = "supp", facet.by = c("supp", "dose"))
```
![rplot03](https://user-images.githubusercontent.com/3313355/27458708-a8727c00-57aa-11e7-90ff-722d8f585bf2.png)

```r
# Extra arguments 
ggboxplot(ToothGrowth, x = "dose", y = "len",
          color = "supp", facet.by = c("supp", "dose"),
          short.panel.labs = FALSE
          )
```

![rplot04](https://user-images.githubusercontent.com/3313355/27458731-c97cf6b4-57aa-11e7-881a-259eecbafa2b.png)

```r
# Extra arguments: panel labels font
ggboxplot(ToothGrowth, x = "dose", y = "len",
          color = "supp", facet.by = c("supp", "dose"),
          short.panel.labs = FALSE,
          panel.labs.font = list(color = "red", size = 12)
)
```

![rplot05](https://user-images.githubusercontent.com/3313355/27458798-165bd810-57ab-11e7-8ea9-87dca3228292.png)

see also the function [facet() in ggpubr](http://www.sthda.com/english/rpkgs/ggpubr/reference/facet.html)

**Comment by zhouyisu** [comment]
Thanks! Really helpful.
