### ISSUE TITLE
ggmaplot label specific genes

### ISSUE THREAD

**Issue by apastore** [kassambara/ggpubr#70]
Hi I really like this package and the Nice MA plots. I was wondering if is possible to label specific genes instead of the top xx only.

Thanks a lot for this!
Alessandro

**Comment by amaurypm** [comment]
Hi, @apastore 
I have the same issue. For know what I am doing is setting top = 0 in the function and adding `geom_label_repel` or `geom_text_repel` function. Something like this:
```R
ggmaplot(...) + geom_label_repel(data = subset(your_data_frame, gene %in% your_vector_of_specific_gene_names), 
                mapping = aes(label = as.vector(gene),
                             x = log2(baseMean),
                             y = log2FoldChange),
                box.padding = unit(0.35, "lines"),
                point.padding = unit(0.3, "lines"),
                force = 1, 
                fontface = "bold",
                size = 10/3)
```
Here I am assuming you have a `gene` column in your data frame with the gene names. Use the same font face and size you used inside ggmaplot (bold and 10 in this example).
I hope this could be useful for you.
Regards,
Amaury

**Comment by kassambara** [comment]
fixed now, thanks!

New argument `label.select` added

``` r
library(ggpubr)
data(diff_express)

# Default plot
ggmaplot(diff_express, main = expression("Group 1" %->% "Group 2"),
         fdr = 0.05, fc = 2, size = 0.4, 
         genenames = as.vector(diff_express$name),
         ggtheme = ggplot2::theme_minimal(),
         top = 15
)
```

![](https://i.imgur.com/b3IyXD6.png)

``` r

# Select specific genes to show
# set top = 0, then specify genes using label.select argument
ggmaplot(diff_express, main = expression("Group 1" %->% "Group 2"),
         fdr = 0.05, fc = 2, size = 0.4, 
         genenames = as.vector(diff_express$name),
         ggtheme = ggplot2::theme_minimal(),
         top = 0, label.select = c("BUB1", "CD83")
         )
```

![](https://i.imgur.com/etAtTYk.png)

<sup>Created on 2020-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
