### ISSUE TITLE
ggbarplot: Multiple groups with error bars only work with color argument

### ISSUE THREAD

**Issue by j3ypi** [kassambara/ggpubr#71]
If one uses **fill** instead of **color**, one wouldn't get an error bar within the categories, but a centered error bar for each category on the x-axis. The combination of both arguments is possible though, but it's useless, since one can't see the bottom half of the error bar. 

Here's a short reproducable example:

    library(tidyverse)
    library(ggpubr)

    df <- tibble(
      iq = rnorm(100, 100, 15),
      condition = rep(c("A", "B"), each = 50),
      time = rep(c("t1", "t2", "t1", "t2"), each = 25)
    )
    ggbarplot(df,
          x = "condition",
          y = "iq",
          fill = "time",
          palette = "grey",
          add = "mean_se", 
          position = position_dodge(0.8))

**Comment by yfangumich** [comment]
I've had the same problem.

**Comment by kassambara** [comment]
For customizing the error bar, you should specify the argument `add.params`:

```r
ggbarplot(df,
          x = "condition",
          y = "iq",
          fill = "time",
          palette = "grey",
          add = "mean_se",  add.params = list(color = "time"),
          position = position_dodge(0.8))
```

**Comment by j3ypi** [comment]
Your code doesn't work like its supposed to. It still produces error bars in the same color as the barplot, which makes it impossible to see the lower half. 

What I want is this:
     
    df %>% 
      group_by(condition, time) %>% 
      summarise(IQ = mean(iq),
                se = sd(iq) / sqrt(n())) %>% 
      ggplot(aes(x = condition, y = IQ, fill = time)) +
      geom_bar(width = 0.85, position = position_dodge(width = 0.9), stat = "identity") +
      geom_errorbar(aes(ymin = IQ - se, ymax = IQ + se),
                    width = .2,                   
                    position = position_dodge(0.9)) + 
      scale_fill_grey() +
      theme_pubr()

The problem wouldn't exist, if the `color` argument would work intuitivly like `fill`.

**Comment by cnnmat** [comment]
Same problem here.

**Comment by kassambara** [comment]
With the latest developmental version of ggpubr, you can do this:


```r

# Required packages and demo data
library(tidyverse)
library(ggpubr)
df <- tibble(
  iq = rnorm(100, 100, 15),
  condition = rep(c("A", "B"), each = 50),
  time = rep(c("t1", "t2", "t1", "t2"), each = 25)
)


# Visualization
ggbarplot(df, x = "condition", y = "iq", 
          fill = "time", palette = "grey",
          add = "mean_se",  add.params = list(group = "time"),
          position = position_dodge(0.8))

```

![rplot45](https://user-images.githubusercontent.com/3313355/44002548-b167ab1e-9e44-11e8-8ca4-9bae9dbc5951.png)

**Comment by j3ypi** [comment]
Works like a charm - thanks!

**Comment by kassambara** [comment]
so we can close the issue

**Comment by sophiahng** [comment]
It does not work for me.
It produces error codes 
Error in (function (p, add = NULL, color = "black", fill = "white", width = 1,  : 
  unused argument (group = "time")
What is the problem?

**Comment by j3ypi** [comment]
You have to install the current development version via

    devtools::install_github("kassambara/ggpubr")

**Comment by sophiahng** [comment]
Problem solved. Thanks!

**Comment by cnnmat** [comment]
Merci beaucoup !

**Comment by dkagro1991** [comment]
[Yielddata.xlsx](https://github.com/kassambara/ggpubr/files/2848018/Yielddata.xlsx)
i want to create a barplot on data yld and yld2 (sheet2) in r studio after importing my excel sheet into r studio. I am foloowing the step provided by you but not able to creat one. plz help me with the steps and codes. Thankyou

**Comment by kassambara** [comment]
grps column should be organized as highlighted in red.

![groups](https://user-images.githubusercontent.com/3313355/52524452-72dbb600-2c9d-11e9-9766-f3d981ae4977.png)

**Comment by elenichri** [comment]
Hello,
I have a similar issue but with adding points after doing the barplot: The points are added in the middle of the group. I want however to add them at each bar of the group. So the x for the points should be different from the x for the x for the barplot. How can I do that? Here is my code:

`ggbarplot(melted_fig4a.dmso, x = 'drug', y = 'value', width=0.8,
          add = c("mean_sd"), 
          add.params = list(color='black', group='compound_concentration'),
          font.xtickslab = 20,
          font.x=22,
          font.ytickslab = 20,
          font.y=22,
          ylim=c(0,15),
          color='compound_concentration',  #no, group by concentration
          fill='compound_concentration',
          position=position_dodge(0.8),
          palette='grey',
          x.text.angle=90) + 
          geom_point(size=2, data= melted_fig4a.dmso, aes(x=treatment, y=value)) `

This adds the points in different columns AFTER the bars of each group

Here are the top 15 lines of the melted_fig4a.dmso
     treatment compound_concentration replicate value drug
       None                      1      rep1  0.33    None
       Dima 1                      1      rep1  0.73 Dima
      Dima 10                      2      rep1  1.03 Dima
     Dima 100                      3      rep1  2.49 Dima
       Quin 1                      1      rep1  0.74 Quin
      Quin 10                      2      rep1  0.46 Quin
     Quin 100                      3      rep1  0.53 Quin
  Colc 0.0025                      1      rep1  1.35 Colc
   Colc 0.005                      2      rep1  2.41 Colc
   Colc 0.01                      3      rep1  1.53 Colc
    Meb 0.05                      1      rep1  0.38  Meb
     Meb 0.1                      2      rep1  1.11  Meb
  Podo 0.005                      1      rep1  0.68 Podo
   Podo 0.01                      2      rep1  1.02 Podo
      Dino 1                      1      rep1  0.74 Dino


I would very much appreciate your help

Eleni

**Comment by Pengdbamba-ZONGO** [comment]
Hello,

I am a beginner in R programming and I want to create multiple Barchart and adding significative p-value on it. I wrote my code but when I run it to add p-value it does error; I need your help please.

The following is my data "head", and I want to plot for each strain the inhibition diameter (3 independent experiments) : 






IPM | FOX | CAZ | CTX | MEM | ETP | Souches
-- | -- | -- | -- | -- | -- | --
27,7 | 28,6 | 34,3 | 30,8 | 28,3 | 28,3 | W3110-pOXA232
27,4 | 28,4 | 33,9 | 29,9 | 28,1 | 28,1 | W3110-pOXA232
28 | 28,1 | 36,1 | 30,3 | 25,8 | 28,1 | W3110-pOXA232
14,7 | 16,3 | 31,1 | 22,8 | 0 | 9,7 | W3110-dlompF/C-pOXA232
16,3 | 15,1 | 31,1 | 23,3 | 0 | 9,2 | W3110-dlompF/C-pOXA232
16,5 | 14,6 | 33,4 | 23,8 | 0 | 9,1 | W3110-dlompF/C-pOXA232
28,8 | 29,5 | 34,2 | 34,2 | 28,6 | 28,3 | RH1-pompC-yedSA6
28,8 | 28,8 | 34,7 | 34,2 | 28,8 | 28 | RH1-pompC-yedSA6
29,5 | 29,5 | 36,4 | 35,3 | 27,6 | 29,2 | RH1-pompC-yedSA6
28,6 | 36,4 | 35 | 35 | 28 | 28,1 | RH3-pompC-yedSB2
27,7 | 30,8 | 36,4 | 36,1 | 28,4 | 27,7 | RH3-pompC-yedSB2
29,4 | 31,2 | 37,8 | 35,9 | 27 | 27,7 | RH3-pompC-yedSB2
29 | 28,1 | 34,2 | 29,8 | 28 | 28,1 | RH9-pompC-ompFMG
28,8 | 27,1 | 33,6 | 30,3 | 29,2 | 28 | RH9-pompC-ompFMG
29,5 | 28,3 | 35,4 | 30,2 | 27 | 28,3 | RH9-pompC-ompFMG
27,4 | 25,3 | 33,1 | 28,8 | 28,1 | 26,6 | RH11.2-pompC-ompFST38
28,6 | 25,5 | 33,4 | 28,6 | 27,4 | 26,6 | RH11.2-pompC-ompFST38
28 | 25,8 | 35,4 | 29,2 | 26 | 26 | RH11.2-pompC-ompFST38
29,5 | 28,3 | 31,7 | 30,5 | 28,1 | 25,5 | RH2-pompF-yedSA6
29 | 27,6 | 33,3 | 30,9 | 28,3 | 26 | RH2-pompF-yedSA6
29,6 | 27,8 | 33,4 | 31,2 | 26,8 | 26,1 | RH2-pompF-yedSA6
27,5 | 29,4 | 35,6 | 31,7 | 27,3 | 24,7 | RH4-pompF-yedSB2
28 | 29,7 | 36,7 | 33,1 | 27,2 | 25 | RH4-pompF-yedSB2
28,8 | 29,6 | 36,7 | 32,8 | 26,3 | 25,2 | RH4-pompF-yedSB2
29,5 | 28,1 | 34,3 | 29,8 | 28 | 26,6 | RH10-pompF-ompFMG
28,8 | 27,6 | 34,7 | 29 | 28,1 | 26,7 | RH10-pompF-ompFMG
29,2 | 27,2 | 36,1 | 29,6 | 26 | 26,9 | RH10-pompF-ompFMG
28 | 25,2 | 31,9 | 26,3 | 26,4 | 23,9 | RH12-pompF-ompFST38
28,1 | 25,6 | 33,3 | 27,6 | 27,7 | 24,4 | RH12-pompF-ompFST38
28,9 | 25,5 | 34,6 | 27,7 | 24,9 | 25,6 | RH12-pompF-ompFST38

and this is my code : 

# Statiscal analysis of inhibition diameter of antibiogram
# Loading the data
atb_data = read.csv2("/Users/dieudonne/Documents/M2_suite/ATBg/analyse/statistical_analysis_atb2.csv")
View(atb_data)

atb_data1 = melt(atb_data)
colnames(atb_data1) = c("Souches", "Antibiotiques", "inhibition_diameter")
atb_data1
# subsetting RH1-4/1134 and 1136
yed_comp = subset(atb_data1, atb_data1[[1]] %in% c("RH1-pompC-yedSA6", "RH3-pompC-yedSB2", "RH2-pompF-yedSA6",
                                                           "RH4-pompF-yedSB2", "W3110-pOXA232", "W3110-dlompF/C-pOXA232"), drop = TRUE) 

yed_comp$Souches = as.factor(yed_comp$Souches)

# packages 
# multiple student test
install.packages("tidyverse")
install.packages("rstatix")
install.packages("ggpubr")
library(tidyverse)
library(rstatix)
library(ggpubr)

# Inversez l'ordre comme suit
yed_comp$Souches <- factor(yed_comp$Souches, levels = rev(levels(yed_comp$Souches)))
# Ou spécifiez les niveaux de facteur dans l'ordre que vous voulez
yed_comp$Souches <- factor(yed_comp$Souches, levels = c("W3110-pOXA232", "W3110-dlompF/C-pOXA232", "RH1-pompC-yedSA6", 
                                                        "RH3-pompC-yedSB2", "RH2-pompF-yedSA6", "RH4-pompF-yedSB2"))

yd = ggplot(yed_comp,  aes(x= Souches, y =  inhibition_diameter, fill = Souches, add = "mean_sd"))+
  geom_bar(stat = "identity", position = position_dodge(0.8)) +
  scale_fill_manual(values = c("dark green", "dark red", "navy", "grey", "blue", "sky blue"))+
  theme_classic()+
  ylab("inhibition_diameter") + ylim(0, 40) +
  ggtitle(label = "Antibiotic susceptibility test") +
  theme(plot.title = element_text(hjust = 0.5)) + facet_grid(~Antibiotiques) +
  rotate_x_text(angle = 60)

# multiple student test
tRH13 = t.test(atb_data$CAZ[atb_data$Souches=="RH1-pompC-yedSA6"], atb_data$IPM[atb_data$Souches=="RH3-pompC-yedSB2"])
tRH13


RHall = atb_data[c(1:6, 7:12, 19:24),]
View(RHall);
RHall.long <-RHall %>% #transpose les variables en colonne  
  pivot_longer(-"Souches", names_to = "Antibiotiques", values_to = "inhibition_diameter")
View(RHall.long);

stat.test_RHall <- RHall.long %>%
  group_by(Antibiotiques) %>% # grouper les antibiotiques de même variable ensemble
  t_test(inhibition_diameter ~ Souches) %>% # t.test des variables
  adjust_pvalue(method = "BH") %>% # Method BH for p-value adjustment
  add_significance()

stat.test_RHall
View(stat.test_RHall);
stat.test_RHall <- stat.test_RHall %>%
  add_xy_position(fun = "mean_sd", x = "Souches" , dodge = 0.8) 
View(stat.test_RHall)

pv = stat.test_RHall[stat.test_RHall$p.adj.signif != "ns",]
view(pv)
pv1 = pv[-c(3:4, 7:8, 10, 12:15, 19, 22:23, 25:27, 30, 32:35, 37:42, 44:47),]
View(pv1)

yd + stat_pvalue_manual(pv1, label = "p.adj.signif", tip.length = 0.01)

**Comment by dkagro1991** [comment]
Try this

plot<- ggbarplot(datamay, x = "Treatment",
y = "Corg", add = "mean_se", add.params=list(group = "Fraction", *color =
"black"* ),
color ="Fraction", fill= "Fraction",
palette=c("darkgoldenrod4", "darkolivegreen4"),
ylim=c(0,60))

Thanks & Regards,

डॉ दिनेश कुमार (पीएचडी) / Dr. DINESH KUMAR (PhD)
वैज्ञानिक (सस्य विज्ञान) / Scientist (Agronomy)
भा॰कृ॰अनु॰प॰ - भारतीय मृदा एवं जल संरक्षण संस्थान, अनुसंधान केंद्र, दतिया,
मध्य प्रदेश, भारत, 475661 / ICAR-Indian Institute of Soil and Water
Conservation, Research Centre Datia, Madhya Pradesh, India, 475661
मोबाइल / Mob: 7877172907, 8140486460
ई मेल / Email: ***@***.*** ***@***.***>com* |
***@***.***
***@***.***>*
ResearchGate <https://www.researchgate.net/profile/Dinesh_Kumar520> | ORCID
<https://orcid.org/0000-0002-0505-9023> | GoogleScholar
<https://scholar.google.com/citations?hl=en&user=KX59L-oAAAAJ> |
Pubslon/WebOfScience <https://publons.com/researcher/1323156/dinesh-kumar/>
| SciProfiles <https://sciprofiles.com/profile/dkagro1991>

**Comment by marinaaa118** [comment]
Thanks a lot!

I already had made it work, hence I deleted the comment.

Is it possible to customize the error bars? I tried using size in
add.params but nothing happens.

Thanks and regards,

**Comment by dkagro1991** [comment]
What kind of customization do you want to do?
Do you want to change the position? or is it about the width of the error
bar?


Thanks & Regards,

डॉ दिनेश कुमार (पीएचडी) / Dr. DINESH KUMAR (PhD)
वैज्ञानिक (सस्य विज्ञान) / Scientist (Agronomy)
भा॰कृ॰अनु॰प॰ - भारतीय मृदा एवं जल संरक्षण संस्थान, अनुसंधान केंद्र, दतिया,
मध्य प्रदेश, भारत, 475661 / ICAR-Indian Institute of Soil and Water
Conservation, Research Centre Datia, Madhya Pradesh, India, 475661
मोबाइल / Mob: 7877172907, 8140486460
ई मेल / Email: ***@***.*** ***@***.***>com* |
***@***.***
***@***.***>*
ResearchGate <https://www.researchgate.net/profile/Dinesh_Kumar520> | ORCID
<https://orcid.org/0000-0002-0505-9023> | GoogleScholar
<https://scholar.google.com/citations?hl=en&user=KX59L-oAAAAJ> |
Pubslon/WebOfScience <https://publons.com/researcher/1323156/dinesh-kumar/>
| SciProfiles <https://sciprofiles.com/profile/dkagro1991>

**Comment by marinaaa118** [comment]
The width of the error bar. I've tried with "width=.2" inside add.params
but it won't work.

Thanks!!!

Marina.
