### ISSUE TITLE
Plotter not found

### ISSUE THREAD

**Issue by HannaHippo** [kassambara/ggpubr#72]
Hello there. I am trying to use ggpubr but when I do I get the following error:

> Error in do.call(.plotter, .opts) : object '.plotter' not found

This is what i try to run:

> 
> > ggline(Accuracy, x = "Day", y = "Pcorrect", color = "Condition",
> +        add = c("Pcorrect", "dotplot"),
> +        palette = c("#00AFBB", "#E7B800"))

Many thanks

**Comment by kassambara** [comment]
This error is not reproducible with latest developmental version of ggpubr
