### ISSUE TITLE
ggarrange and creating common axis titles

### ISSUE THREAD

**Issue by zShores** [kassambara/ggpubr#78]
Hi kassandra,
Just started out using the ggpubr package today, and it's great! However I am having issues with making a common x-axis label or y-axis label for a grid of graphs. I have attempted a few things however to no avail, including annotate_figure() and ggpar().

ggpar() brought up the following despite several attempts to adjust:
```
Error in element_grob.element_text(el, ...) : 
Text element requires non-NULL value for 'angle'.
```

So my question is, is there an inbuilt function somewhere in ggpubr to apply common labels? If not, any advice on how to do so?
 
I have created 7 graphs of selected genes as follows:
```
Cdkn2b <- ggplot() +
  geom_line(data=df1, aes(x=day, y=Cdkn2b, group=1, color="HS"))+
  geom_line(data=df2, aes(x=day, y=Cdkn2b, group=2, color="TCPS"))
```
Which includes a legend, however I am using the `common.legend=` in the ggarrange().
My ggarrange is as follows:
```
plot <- ggarrange(Snai1, Alpl, Ccnb1, Cdh1, Fbxo15, Sox2, Cdkn2b,
          labels = c("Snai1","Alpl",'Ccnb1', 'Cdh1', 'Fbxo15', 'Sox2', 'Cdkn2b'),
          ncol = 4, nrow = 2, label.x = 0.33, align = "v",
          common.legend = TRUE, legend = "right")
```
I have used the following to label one of the axes:
```
  labs(color = "Substrate") + ylab("Expression") + xlab("Day") +
  scale_color_discrete("Substrate")
```
Any help with actually getting the axis titles matching and having the abilty to modify the graph labels would be awesome!.

**Comment by kassambara** [comment]
For annotating arranged plots, read this blog post: [Annotate the arranged figure](http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/81-ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page/#annotate-the-arranged-figure)

Example of R code:

```r
library(ggpubr)
df <- data.frame(dose=c("D0.5", "D1", "D2"),
                 len=c(4.2, 10, 29.5))

# Create multiple plots without y axis labels
plot1 <- ggline(df, x = "dose", y = "len", color = "black", ylab = " ")
plot2 <- ggline(df, x = "dose", y = "len", color = "red", ylab = " ")
plot3 <- ggline(df, x = "dose", y = "len", color = "blue", ylab = " ")

# Create a figure by combining the different plots
figure <- ggarrange(plot1, plot2, plot3, labels = c("A", "B", "C"))

# Annotate the figure by adding a common labels
annotate_figure(figure,
                top = text_grob("Visualizing len", color = "red", face = "bold", size = 14),
                bottom = text_grob("Data source: \n ToothGrowth data set", color = "blue",
                                   hjust = 1, x = 1, face = "italic", size = 10),
                left = text_grob("Tooth length", color = "green", rot = 90),
                right = "I'm done, thanks :-)!",
                fig.lab = "Figure 1", fig.lab.face = "bold"
)
```


![annotate-arranged-plots](https://user-images.githubusercontent.com/3313355/41507330-05a785ae-7231-11e8-95b7-1f37816e0421.png)
