### ISSUE TITLE
stat_compare_means and one-sample tests

### ISSUE THREAD

**Issue by sjmgarnier** [kassambara/ggpubr#79]
Both `t.test` and `wilcox.test` offer the possibility to do one-sample tests against a known value. I could not figure out a way to do this with stat_compare_means (i.e. compare each group to a known value).

**Comment by kassambara** [comment]
Try this:

```r
library(ggpubr)
library(rstatix)

# Prepare data
df <- ToothGrowth
df$dose <- as.factor(df$dose)

# One sample t-test
stat.test <- df %>%
  group_by(dose) %>%
  t_test(len ~ 1, mu = 2) %>%
  adjust_pvalue() %>%
  mutate(y.position = 35)

stat.test
```

<pre>
# A tibble: 3 x 9
    dose   .y. group1     group2 statistic       p method    p.adj y.position
  <fctr> <chr>  <chr>      <chr>     <dbl>   <dbl>  <chr>    <dbl>      <dbl>
1    0.5   len      1 null model  8.552168 6.1e-08 T-test 6.10e-08         35
2      1   len      1 null model 17.962739 2.2e-13 T-test 4.40e-13         35
3      2   len      1 null model 28.557018 4.5e-17 T-test 1.35e-16         35
</pre>


```r

# Add p-values to a ggplot
ggboxplot(df, x = "dose", y = "len") +
  stat_pvalue_manual(stat.test, label = "p.adj", xmin = "dose", xmax = NULL)
```

![rplot](https://user-images.githubusercontent.com/3313355/43105237-76795626-8ed4-11e8-8e94-bc36023f1eb0.png)
