### ISSUE TITLE
Error: No stat called StatSignif.

### ISSUE THREAD

**Issue by zhouyisu** [kassambara/ggpubr#8]
I tried replicating the example:

```
data("ToothGrowth")
df <- ToothGrowth

p <- ggboxplot(df, x = "dose", y = "len",
               color = "dose", palette =c("#00AFBB", "#E7B800", "#FC4E07"),
               add = "jitter", shape = "dose")

my_comparisons <- list( c("0.5", "1"), c("1", "2"), c("0.5", "2") )
p + stat_compare_means(comparisons = my_comparisons)+ stat_compare_means(label.y = 50) 
```

but returned an error message: Error: No stat called StatSignif. Any advice? I am on ggplot2_2.2.1.

**Comment by kassambara** [comment]
I'm also on ggplot2_2.2.1 and it works.

generally, re-installing ggplot2 solves this type of issues.

If it still fails, please, post the output of:

```r
devtools::session_info()
```

**Comment by zhouyisu** [comment]
You are right. I updated to the latest R (3.4.0) along with other packages and was able to reproduce the results.
