### ISSUE TITLE
ggbarplot + geom_rect - Alpha parameter for geom_rect does not work

### ISSUE THREAD

**Issue by pea475** [kassambara/ggpubr#80]
When combining ggbarplot with geom_rect, the alpha parameter for geom_rect is not working. Any reasons or ideas on how to fix this problem?

**Comment by kassambara** [comment]
Would you, please, provide a reproducible example?

It works on my computer with the following example:

```r
library(ggpubr)
df <- data.frame(dose=c("D0.5", "D1", "D2"),
                 len=c(4.2, 10, 29.5))
ggbarplot(df, x = "dose", y = "len",
          label = TRUE, label.pos = "out")+
  geom_rect(xmin=2, xmax=3, ymin=0, ymax=10, alpha = 0.2)
```
![barplot-with-rectangle](https://user-images.githubusercontent.com/3313355/41507235-e18e8188-722e-11e8-832a-f555dec4609b.png)


<pre>
Session info ----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.1.423)           
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2018-06-17                  

Packages --------------------------------------------------------------------------------------------------------------
 package    * version    date       source                                
 assertthat   0.2.0.9000 2017-11-08 Github (hadley/assertthat@37f0a56)    
 backports    1.1.2      2017-12-13 cran (@1.1.2)                         
 base       * 3.3.2      2016-10-31 local                                 
 bindr        0.1        2016-11-13 cran (@0.1)                           
 bindrcpp     0.2        2017-06-17 cran (@0.2)                           
 colorspace   1.4-0      2017-10-23 url                                   
 commonmark   1.2        2017-03-01 CRAN (R 3.3.2)                        
 cowplot      0.9.2      2017-12-17 CRAN (R 3.3.2)                        
 crayon       1.3.4      2017-09-16 CRAN (R 3.3.2)                        
 curl         3.0        2017-10-06 cran (@3.0)                           
 datasets   * 3.3.2      2016-10-31 local                                 
 desc         1.1.0      2017-01-27 CRAN (R 3.3.2)                        
 devtools   * 1.13.1     2017-05-13 CRAN (R 3.3.2)                        
 digest       0.6.15     2018-01-28 cran (@0.6.15)                        
 dplyr        0.7.4      2017-09-28 cran (@0.7.4)                         
 ggplot2    * 2.2.1.9000 2018-06-17 Github (tidyverse/ggplot2@ff41bc8)    
 ggpubr     * 0.1.6.999  <NA>       local                                 
 ggrepel      0.7.0      2017-09-29 cran (@0.7.0)                         
 ggsci        2.9        2018-05-14 cran (@2.9)                           
 ggsignif     0.4.0      2018-06-17 Github (Artjom-Metro/ggsignif@aadd9d4)
 git2r        0.18.0     2017-01-01 CRAN (R 3.3.2)                        
 glue         1.2.0      2017-10-29 cran (@1.2.0)                         
 graphics   * 3.3.2      2016-10-31 local                                 
 grDevices  * 3.3.2      2016-10-31 local                                 
 grid         3.3.2      2016-10-31 local                                 
 gridExtra    2.3        2017-09-09 cran (@2.3)                           
 gtable       0.2.0      2016-02-26 CRAN (R 3.3.0)                        
 httr         1.2.1.9000 2017-03-14 Github (gaborcsardi/httr@30001d4)     
 knitr        1.18       2017-12-27 cran (@1.18)                          
 labeling     0.3        2014-08-23 CRAN (R 3.3.0)                        
 lazyeval     0.2.1      2017-10-29 cran (@0.2.1)                         
 magrittr   * 1.5        2014-11-22 CRAN (R 3.3.0)                        
 memoise      1.1.0      2017-04-21 cran (@1.1.0)                         
 methods    * 3.3.2      2016-10-31 local                                 
 munsell      0.4.3      2016-02-13 CRAN (R 3.3.0)                        
 pkgconfig    2.0.1      2017-03-21 cran (@2.0.1)                         
 plyr         1.8.4      2016-06-08 CRAN (R 3.3.0)                        
 purrr        0.2.4      2017-10-18 cran (@0.2.4)                         
 R6           2.2.2      2017-06-17 cran (@2.2.2)                         
 Rcpp         0.12.14    2017-11-23 cran (@0.12.14)                       
 rlang        0.2.0.9001 2018-06-17 Github (tidyverse/rlang@ba4fb06)      
 roxygen2     6.0.1      2017-02-06 CRAN (R 3.3.2)                        
 rprojroot    1.3-2      2018-01-03 cran (@1.3-2)                         
 rstudioapi   0.6        2016-06-27 CRAN (R 3.3.0)                        
 scales       0.5.0.9000 2018-06-17 Github (hadley/scales@4056ec3)        
 stats      * 3.3.2      2016-10-31 local                                 
 stringi      1.1.6      2017-11-17 cran (@1.1.6)                         
 stringr      1.3.0      2018-02-19 cran (@1.3.0)                         
 tibble       1.3.4      2017-08-22 cran (@1.3.4)                         
 tidyr        0.8.1.9000 2018-06-17 Github (tidyverse/tidyr@cbdd14e)      
 tools        3.3.2      2016-10-31 local                                 
 utils      * 3.3.2      2016-10-31 local                                 
 withr        2.1.2      2018-06-17 Github (jimhester/withr@dbcd7cd)      
 xml2         1.1.1      2017-03-31 Github (hadley/xml2@268387b)          
 yaml         2.1.16     2017-12-12 cran (@2.1.16)  
</pre>
