### ISSUE TITLE
Change order of box plot

### ISSUE THREAD

**Issue by stangedal** [kassambara/ggpubr#84]
I have found ggpubr great to use, but I have two issues I simply cannot solve myself. I hope you can guide me to a solution if there is one:

I have paired measurements from two different disease states - steady state and exacerbations. I am visualizing this as box plots with ggpaired and I have 8 measurements at each situation. I get 8 box plots that I combine in a final plot with ggarrange. 
Issue 1: R order the groups alphabetically and I am not getting anywhere when trying to rearrange the order. Is there anyway I can tell R to arrange the box plots with Stable state first and Exacerbation last? Here is the command for one of the eight measurements

P1 <-ggpaired(Inflam, x="Diseasestate", y="IL6", ylab="IL6 pg/ml", xlab="", id = "idnr", color="Diseasestate", line.color = "gray", line.size = 0.4, palette = c("red", "skyblue3"))+
  stat_compare_means(paired=TRUE, hide.ns = TRUE, label = "p.format", label.x.npc = "center", label.y.npc = "top")+
  theme(legend.position="none")+
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

The values for Diseasestate is simply Stable state or Exacerbation

And the ggarrange:
Inflam1 <- ggarrange(P1,P2,P3,P4,P5,P6,P7,P8, ncol = 2, nrow = 4, common.legend = TRUE, legend = "right" )

Issue 2. I saw this issue already been raised: Is there a way to get a common title and common captions in Inflam1 - the plot created by ggarrange?

Best wishes, Solveig

**Comment by kassambara** [comment]
## Answer to issue 1

- Default R behavior:

```r
library(ggpubr)
ggboxplot(iris, x = "Species", y = "Sepal.Length")
```

![default-box-plot](https://user-images.githubusercontent.com/3313355/41507156-2f64db3e-722d-11e8-827c-4bc0394d9f61.png)


- Decide the order of groups:

```r
# Decide the order of groups in the argument levels
iris$Species <- factor(iris$Species, levels = c("virginica", "versicolor", "setosa"))
ggboxplot(iris, x = "Species", y = "Sepal.Length")
```

![box-plot-change-group-order](https://user-images.githubusercontent.com/3313355/41507164-48b5ac6c-722d-11e8-864e-a78b17023d28.png)

## Answer to issue 2:

To annotate the arranged figure, the function annotate_figure() [in ggpubr] might help. See this blog post: [Annotate arranged figure](http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/81-ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page/#annotate-the-arranged-figure)

**Comment by Rainjie-afk** [comment]
> ## Answer to issue 1
> * Default R behavior:
> 
> ```r
> library(ggpubr)
> ggboxplot(iris, x = "Species", y = "Sepal.Length")
> ```
> 
> ![default-box-plot](https://user-images.githubusercontent.com/3313355/41507156-2f64db3e-722d-11e8-827c-4bc0394d9f61.png)
> 
> * Decide the order of groups:
> 
> ```r
> # Decide the order of groups in the argument levels
> iris$Species <- factor(iris$Species, levels = c("virginica", "versicolor", "setosa"))
> ggboxplot(iris, x = "Species", y = "Sepal.Length")
> ```
> 
> ![box-plot-change-group-order](https://user-images.githubusercontent.com/3313355/41507164-48b5ac6c-722d-11e8-864e-a78b17023d28.png)
> 
> ## Answer to issue 2:
> To annotate the arranged figure, the function annotate_figure() [in ggpubr] might help. See this blog post: [Annotate arranged figure](http://www.sthda.com/english/articles/24-ggpubr-publication-ready-plots/81-ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page/#annotate-the-arranged-figure)

Very nice, so many thanks!

**Comment by chabld** [comment]
Hi,

In case anybody like me could not solve Issue 1 simply that way when using stat_pvalue_manual: it turns out those same levels need to be given to the statistical data argument too, _even_ if not all levels are being compared and are present in the test. 

So to take back the example above and the "stat.test" example variable from [the manual](https://rpkgs.datanovia.com/ggpubr/reference/stat_pvalue_manual.html), this should be added too:  
stat.test$supp  <- factor(stat.test$supp, levels = c("VC", "OJ"))
