### ISSUE TITLE
ggscatterhist: y-axis marginal histogram has x-axis data.

### ISSUE THREAD

**Issue by J0PR** [kassambara/ggpubr#85]
In ggscatterhist, the marginal histogram for the y-axis is the same as the x-axis; it has the x-axis data in fact. It can be easily fixed by replacing "**xplot**" with "**yplot**" on line 55.

yplot <- ggplot() + margin.params %>% .add_item(geomfunc = geomfunc, 
    data = data, x = **xplot**.x, y = **xplot**.y, alpha = 0.7) %>%

Best,
J

**Comment by kassambara** [comment]
This has been already fixed in the developmental version: https://github.com/kassambara/ggpubr/commit/998f06c9bb414409bb05f579134deb4662bb6804
