### ISSUE TITLE
Keep plot-specific legend when using common legend (common.legend)

### ISSUE THREAD

**Issue by DiogoFerrari** [kassambara/ggpubr#88]
Hi,
Is it possible to keep all legends if they are different? I would like to group those that are similar but keep the ones that are different and display it either at the top of the figure of the panel.

Example:
dsamp <- diamonds[sample(nrow(diamonds), 1000), ]
p1 <- ggplot(data = dsamp, aes(carat, price,  colour = clarity)) + geom_point()
p2 <- ggplot(data = dsamp, aes(carat, price,  colour = clarity)) + geom_point()
p3 <- ggplot(data = dsamp, aes(carat, price,  colour = clarity)) + geom_point()
p4 <- ggplot(dsamp, aes(cut, price, group = clarity, fill=clarity)) + geom_smooth() 
ggarrange(p1, p2, p3, p4,  common.legend = TRUE)

**Comment by kassambara** [comment]
I'm sorry that this is not possible.
