### ISSUE TITLE
Lollipop chart sorted within groups even with group=NULL

### ISSUE THREAD

**Issue by sfeds** [kassambara/ggpubr#90]
Hi,
I'm greatly enjoying your different package(s), thanks for sharing.

I'm having a small hiccup trying to plot my data.frame with a lollipop chart.
Even though I don't use the "group" option within the function, it still sorts by group.
This only happens when I use color= "my variable", even if I set group= NULL

This would be my full code:
> ggdotchart(sub_imp, x = "variables", y = "value",
           color = "cat",                                
           palette = c("#E7B800", "#FC4E07"), 
           sorting = "descending",                       
           rotate = TRUE,                                
           dot.size = 2,                                 
           y.text.col = TRUE,                            
           ggtheme = theme_pubr() ,
           group = NULL
) + theme_cleveland() +
  geom_hline(yintercept = 15, linetype = 2, color = "lightgray") 

And the output is still sorted descending per group.

Any tips?
thanks!

**Comment by kassambara** [comment]
pied now, thanks
