### ISSUE TITLE
annotate_figure: Changing the font family of plot annotations?

### ISSUE THREAD

**Issue by yiqinfu** [kassambara/ggpubr#97]
Hi! I'm just wondering if it's possible to change the font family to the top/left/bottom/right annotations created by `annotate_figure`? I don'ts see a `family` parameter in the function.

Thanks so much for creating and maintaining the package!

**Comment by kassambara** [comment]
Use the argument family:

```r
library(ggpubr)
# Create some plots
# ::::::::::::::::::::::::::::::::::::::::::::::::::
# Box plot
bxp <- ggboxplot(ToothGrowth, x = "dose", y = "len",
                 color = "dose", palette = "jco")
# Dot plot
dp <- ggdotplot(ToothGrowth, x = "dose", y = "len",
                color = "dose", palette = "jco")

# Arrange and annotate
# ::::::::::::::::::::::::::::::::::::::::::::::::::
figure <- ggarrange(bxp, dp, ncol = 2, nrow = 1)
annotate_figure(figure,
                top = text_grob("Visualizing Tooth Growth",  size = 14, family = "Arial"),
                bottom = text_grob("ToothGrowth data set", size = 14, family = "Times")
)
```

![rplot36](https://user-images.githubusercontent.com/3313355/42536786-4cf9ec98-8493-11e8-8f10-244378a0c1bd.png)

**Comment by mundreramesha** [comment]
Hi! excellent package, I have small query- is it possible to use superscript/subscript text/values/symbols/etc in shared axis label? If yes, let me know.

Thanks in advance!

**Comment by willright28** [comment]
Hi all,
Could I ask how to change the font family of fig.lab?

Thanks in advance!
