### ISSUE TITLE
left alignment of label and change the font of 'r' and 'p'

### ISSUE THREAD

**Issue by zhan6073** [kassambara/ggpubr#98]
I have make a scatter plot adding correlation coefficients using stat_cor().
When set stat_cor(aes(color = Group), label.x.npc = 'left', label.y.npc = 0.3), the labela are left aligned in the bottom left corner ,
![cor1](https://user-images.githubusercontent.com/34253682/42229921-42c9f01a-7ead-11e8-9523-ccf2a73adc57.png)
When set stat_cor(aes(color = Group), label.x.npc = 0.53,label.y.npc = 0.33), the labels are nearly central aligned on the X axis, but not left aligned at this position. How can I make all the labels left alignment at this position? Thank you for your response!!! 
![cor2](https://user-images.githubusercontent.com/34253682/42229922-42e81018-7ead-11e8-85de-9415346e3000.jpg)

**Comment by zhan6073** [comment]
How to change the font of 'r' and 'p' in the correlation labels. eg. 'r' to 'R', 'p' to italic '_P_' ?

**Comment by kassambara** [comment]
For the left alignment, play with the argument `hjust`, which value should be in [-1, 1].

Install the latest developmental version and try this:

```r
library(ggpubr)
ggscatter(
  iris, x = "Sepal.Length", y = "Petal.Width", 
  color = "Species"
  ) +
  stat_smooth(
    aes(color = Species), method = "lm",
    se = FALSE, fullrange = TRUE
    ) +
  stat_cor(
    aes(color = Species, label = paste0("R = ", ..r.., ", P = ", ..p..)), 
    label.x.npc = 0.5, 
    label.y.npc = 0.3, hjust = 0
    )
```

![rplot35](https://user-images.githubusercontent.com/3313355/42535985-488fafe6-8491-11e8-81a3-1f8f49dd648b.png)

**Comment by samuelcharberet** [comment]
Is there a way to put the whole legend inside a label box so that it does not appear above points which is what happens in the first plot of [zhan6073](https://github.com/zhan6073) ?
